### ISSUE TITLE
OnClock if use atcommand Map-Server has crashed!

### ISSUE THREAD

**Issue by Beginerxxxxx** [rathena/rathena#8886] opened 2024-12-20 17:48 UTC
### rAthena Hash

https://github.com/rathena/rathena/commits/master

### Client Date

20230906

### Server Mode

Renewal

### Result

Hello everyone, how are you doing?
I encountered a problem after updating the server from the master branch, but I’m not sure which part caused it because the script I was using before the update was working fine.

```
OnClock0100:
atcommand "@broadcast Test Test Test";
end;
```

![Screenshot 2024-12-21 003024](https://github.com/user-attachments/assets/22d07daf-6b6a-4e6e-8595-62da0abfc359)

Or just using this command "atcommand", it encounters the same issue.

Please help test it. Thank you in advance.

### Relevant Log Output

```Shell
none
```

### Expected Result

none

### How to Reproduce

none

### Official Information

none

### Modifications that may affect results

none

**Comment by Beginerxxxxx** [comment] 2024-12-21 06:33
Before Update

https://github.com/user-attachments/assets/a7ced93c-c0c9-4819-9edb-cb71c4c76064

**Comment by Beginerxxxxx** [comment] 2024-12-21 06:57
On Dec 15, 2024 Works fine.
After update to on Dec 17, 2024 bug.

![Screenshot 2024-12-21 135522](https://github.com/user-attachments/assets/c4d4f123-b935-482d-a6dd-1997b5579943)

**Comment by Beginerxxxxx** [comment] 2024-12-21 07:00
![Screenshot 2024-12-21 135908](https://github.com/user-attachments/assets/3279c027-fa36-44ba-a169-2d293284c631)

**Comment by Daegaladh** [comment] 2024-12-21 11:51
Your screenshots and videos doesn't help us at all. Have you tested on a clean rAthena?

**Comment by Beginerxxxxx** [comment] 2024-12-21 13:48
> Your screenshots and videos doesn't help us at all. Have you tested on a clean rAthena?

Clean Master it's same problem i told you before update it's works fine after update 15/12 it's bug.

![Screenshot 2024-12-21 204544](https://github.com/user-attachments/assets/1f7b0d1e-1ba3-40cd-9576-d6d0eebc266c)

**Comment by Beginerxxxxx** [comment] 2024-12-21 13:50
> Before Update
> 
>  2024_12_21_13_31_59_994.mp4

Before Update it's works fine.

https://github.com/user-attachments/assets/ee675c4e-909d-4047-ac01-37f92496d844

**Comment by Daegaladh** [comment] 2024-12-21 13:51
Stop with the videos, that doesn't help. Learn how to use VS studio debug instead.

**Comment by Daegaladh** [comment] 2024-12-21 13:51
Stop with the videos, that doesn't help. Learn how to use VS studio debug instead.

**Comment by Beginerxxxxx** [comment] 2024-12-21 13:55
> Stop with the videos, that doesn't help. Learn how to use VS studio debug instead.

It’s up to you. I’ve already identified the issue, specifying when it worked fine and when the update caused the problem. If this issue isn’t fixed, it will persist. Even with the latest master branch, the same problem occurs. All I can do is report the issue I’ve encountered. Whether you’re interested in addressing and fixing it is up to you.

**Comment by Daegaladh** [comment] 2024-12-21 14:02
Ok, I'm looking into it. But next time, instead of posting videos and stuff that shows absolutely nothing, do the following:
1. Try on a clean rathena first, before opening a new issue because most likely is caused by your weird way of updating your server
2. Use the proper rathena hash it happens instead of random dates.
3. Post only relevant information.

**Comment by Beginerxxxxx** [comment] 2024-12-21 14:05
> Ok, I'm looking into it. But next time, instead of posting videos and stuff that shows absolutely nothing, do the following:
> 
> 1. Try on a clean rathena first, before opening a new issue because most likely is caused by your weird way of updating your server
> 2. Use the proper rathena hash it happens instead of random dates.
> 3. Post only relevant information.

I’m just a player and someone who updates the server. I don’t have the ability or much knowledge in this area. I don’t know where the problem is. All I can do is point out approximately when the issue started.

**Comment by Daegaladh** [comment] 2024-12-21 14:09
Ok, but understand that in order to fix the bugs we need to know which hash they occur on, and if it happens on a clean rathena or is due to your modifications. Because if you open an issue about a bug that doesn't occur on a clean rathena, we won't fix it and you'll waste our time.

**Comment by Beginerxxxxx** [comment] 2024-12-21 14:17
> Ok, but understand that in order to fix the bugs we need to know which hash they occur on, and if it happens on a clean rathena or is due to your modifications. Because if you open an issue about a bug that doesn't occur on a clean rathena, we won't fix it and you'll waste our time.

Okay, I understand. Actually, I’ve encountered other issues, but I didn’t report them because I assumed they might be caused by my own server code. For example, the change from CHANGE_CHATROOM to struct or anything related to CHATROOM. I couldn’t update the code to match it, and it caused everything to error, so I had to skip that part.

However, for other issues, I believe they are real problems, which is why I reported them. I can’t pinpoint the exact hash date of the problem, but what I can do is take a previous backup, compile it, and test if the issue existed before. If it didn’t, then it must have occurred after the last successful test.

I also try not to report issues caused by my own code. If I’ve made any mistakes, I apologize.

**Comment by Lemongrass3110** [comment] 2024-12-21 14:42
If you have a (full) sample script it would be better to provide the (full) sample script, rather than a video.
A video is just helpful to show steps on how to reproduce a issue, where you can only describe the scenario in words.

**Comment by Beginerxxxxx** [comment] 2024-12-22 06:39
> If you have a (full) sample script it would be better to provide the (full) sample script, rather than a video. A video is just helpful to show steps on how to reproduce a issue, where you can only describe the scenario in words.

Thank you [Lemongrass3110](https://github.com/Lemongrass3110). 
The script I’m using is only this simple. The working process is that, at the specified time, it uses the "atcommand." Before the update, the script worked perfectly fine, which is why I’m reporting this issue.

I’m just a player and someone who updates the server. I don’t have expertise in this area. If I receive reports from players, I’ll check again. If the issue is confirmed, I’ll provide details about the problem. Also, I apologize if my English isn’t good, as I’m using a translation program to assist me. Thank you once again.

**Comment by Beginerxxxxx** [comment] 2024-12-22 07:13
Compile Error
![Screenshot 2024-12-22 135624](https://github.com/user-attachments/assets/3bbafbd5-ef0f-424a-88d0-6ddbdfc57411)

![Screenshot 2024-12-22 141252](https://github.com/user-attachments/assets/c1242206-6eef-4ebd-aa05-20b21d844fc1)

**Comment by Lemongrass3110** [comment] 2024-12-22 11:51
Sorry, but you can see here, that there is no compilation error on our side:

![grafik](https://github.com/user-attachments/assets/092a49c6-80f1-4121-98dd-16960e869521)

This has to be a problem in your codebase.

**Comment by Beginerxxxxx** [comment] 2024-12-22 12:13
> Sorry, but you can see here, that there is no compilation error on our side:
> 
> ![grafik](https://private-user-images.githubusercontent.com/3517879/397983081-092a49c6-80f1-4121-98dd-16960e869521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4Njk3MzYsIm5iZiI6MTczNDg2OTQzNiwicGF0aCI6Ii8zNTE3ODc5LzM5Nzk4MzA4MS0wOTJhNDljNi04MGYxLTQxMjEtOThkZC0xNjk2MGU4Njk1MjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjJUMTIxMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ4ZDBmNGVjZTdmMzcyZWY3YmY1MTM4NjRjMzc1MzI5ODBhZDZkNTk5ODA3MmQyOWE2OTcyZTBiNDQ2MDMzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._YthmbkcyMKWbxhuevik_v5ahISp5eVe_TcaRXBxS24)
> 
> This has to be a problem in your codebase.

Thank you [Lemongrass3110](https://github.com/Lemongrass3110)

I fixed it by disabling that line. Does it affect anything else?
However, after testing, the issue seems to be resolved.

**Comment by Lemongrass3110** [comment] 2024-12-22 12:24
That means you already miss a really old update from 2022:
51ddc63a025a962dccb8d7a40996131c950a8677

This can cause a lot of problems with your emulator.

**Comment by Beginerxxxxx** [comment] 2024-12-22 12:34
> That means you already miss a really old update from 2022: [51ddc63](https://github.com/rathena/rathena/commit/51ddc63a025a962dccb8d7a40996131c950a8677)
> 
> This can cause a lot of problems with your emulator.

Thank you i'll try update.

**Comment by Beginerxxxxx** [comment] 2024-12-22 13:07
> Compile Error ![Screenshot 2024-12-22 135624](https://private-user-images.githubusercontent.com/182538630/397969699-3bbafbd5-ef0f-424a-88d0-6ddbdfc57411.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzMwODQsIm5iZiI6MTczNDg3Mjc4NCwicGF0aCI6Ii8xODI1Mzg2MzAvMzk3OTY5Njk5LTNiYmFmYmQ1LWVmMGYtNDI0YS04OGQwLTZkZGJkZmM1NzQxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQxMzA2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2Q0MmNkYjdlNzY0ZDUxN2M5NmMzZWFiMDBjNjE5OWE3ZTJiNzYzOGRkNjBiODI0OWIxODU1MmIwNDI1ZDExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CdUk9U-P60Eq-Tw3Xxojq_kt5kJGblzt0gemacqVLP4)
> 
> ![Screenshot 2024-12-22 141252](https://private-user-images.githubusercontent.com/182538630/397969706-c1242206-6eef-4ebd-aa05-20b21d844fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NzMwODQsIm5iZiI6MTczNDg3Mjc4NCwicGF0aCI6Ii8xODI1Mzg2MzAvMzk3OTY5NzA2LWMxMjQyMjA2LTZlZWYtNGViZC1hYTA1LTIwYjIxZDg0NGZjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQxMzA2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmMxMTEzYjcwODc2MmRkZDE0YTA0YmYzMmZkYjBmYzkzY2NjNWViZWI3MDI4OWI1YWM1YzAwMzhjZWU5OWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k5ZEA8wUtkdycN0uvgdmFwOoN2yljTzoQiqf454p5z0)


Solved Thank you [Lemongrass3110](https://github.com/Lemongrass3110)

**Closed** 2024-12-22 13:07 UTC
Labels: component:core, mode:renewal, mode:prerenewal, type:bug
