### ISSUE TITLE
Cash Log Issue

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2603] opened 2017-11-13 19:31 UTC
* **rAthena Hash**: c6fe9e9

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Server Operating System**: CentOS 7 Minimal 64bit

* **GCC Version**: 5.3.1

* **Description of Issue**: Cash Log Issue
  * Result: Cash Log not log NPC Script set #KAFRAPOINTS
  * Expected Result: Cash Log log NPC Script set #KAFRAPOINTS
  * How to Reproduce:
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2017-11-14 00:38
Technically a duplicate of #2169.

**Closed** 2017-11-14 14:45 UTC
Labels: status:duplicate
