### ISSUE TITLE
@auction

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#796] opened 2015-12-02 03:46 UTC
Hello .. good evening.

The auction system also is not working, you use the command @auction, but nothing happens.

Client: 2015-05-13
Renewal, last version.

**Comment by Lemongrass3110** [comment] 2015-12-02 12:22
@icxbb-xx was auction readded? I think that was dropped on the officials?

**Comment by icxbb-xx** [comment] 2015-12-02 12:39
@Lemongrass3110  yes, maybe gravity dropped packets for this

**Comment by Lemongrass3110** [comment] 2015-12-02 13:04
we should find the packet version where it was dropped and ifdef the support for auction out after that. So it's not really a 2015 client target.

**Comment by aleos89** [comment] 2015-12-02 14:09
This is a duplicate of #704.

**Comment by Lemongrass3110** [comment] 2015-12-17 17:04
@aleos89 not a duplicate I guess. @icxbb-xx and I think it was removed when RODEX was added in.

**Closed** 2015-12-17 17:05 UTC
Labels: bug:core, mode:prerenewal, mode:renewal, server:map, status:confirmed, status:git hash missing, status:needs official info
