### ISSUE TITLE
Wanderer bonus skill when received soul linker buff

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#4909] opened 2020-05-07 14:39 UTC
![local wanderer](https://user-images.githubusercontent.com/62187272/81309262-55221a00-90b5-11ea-9b72-b82b459be303.png)
![liver wanderer](https://user-images.githubusercontent.com/62187272/81309704-d11c6200-90b5-11ea-9210-a3c7140ae229.png)

* **rAthena Hash**: Latest

* **Client Date**: 20151104

* **Server Mode**: Pre Renewal / Renewal

* **Description of Issue**: Well for starter. This issue is really weird. If you are a wanderer and you received soul linker buff you should have poem of bragi and other bard skill right? Well its working on my local server which uses Windows OS. But in my live server which uses centOS it doesnt.

  * Result:  in linux based vps it doesnt work. Im not really sure whats happening but i know someone who test this for me. It shows same result. So maybe the problem lies in rathena itself. (by the way, he does have a live test server running on linux based OS)

  * Expected Result:  I have updated the compiler of my vps which is CentOS by following what's on wiki. Still the same result. (im not sure if i do it right) But when i try to redo it it says nothing to do. Assuming that my vps compiler is now up to date

  * How to Reproduce:  to reproduce this. You have to set up your server in linux based OS. Cent OS for instance. Because you cannot test this on windows OS.

* Additional Information: Okay ive edit this post many times. But what i did was git clone a fresh rathena copy from my VPS. I have set it to PRE RE MODE leave everything as is. For me to try the Wanderer extra skills when have soul linker buff. But still the same. I even tried is using RENEWAL settings. The problem really lies in the current git. But like i said. Its perfectly working on my local server which uses windows OS.

**Comment by aleos89** [comment] 2020-05-09 15:05
Duplicate of #4801.

**Closed by aleos89** 2020-05-09 15:05 UTC
Labels: status:duplicate
