### ISSUE TITLE
List of bugs and Issue's found.

### ISSUE THREAD

**Issue by DrNebula** [rathena/rathena#207] opened 2015-01-06 23:48 UTC
I don't know if rAthena is trying to aim for kRO As a base but if we are these are a few bugs reported from the server I currently work on.
Mora Equipment are not to the way kRO has them, Half the set being droped the other half tradable with Mora Coins Here are links from divine pride with the drop rate + Monster drop:

http://www.divine-pride.net/database/item/15043/black-wing-suits-1
http://www.divine-pride.net/database/item/2891/black-wing-brooch
http://www.divine-pride.net/database/item/15042/white-wing-suits-1
http://www.divine-pride.net/database/item/2890/white-wing-brooch
http://www.divine-pride.net/database/item/15037/peuzs-plate
http://www.divine-pride.net/database/item/2884/peuzs-seal-1
http://www.divine-pride.net/database/item/15036/urs-plate
http://www.divine-pride.net/database/item/2883/urs-seal-1
http://www.divine-pride.net/database/item/15039/nabs-cloth-1
http://www.divine-pride.net/database/item/2887/nab-ring
http://www.divine-pride.net/database/item/15038/saphas-cloth-1
http://www.divine-pride.net/database/item/2886/sapha-ring

The Malaya Port Quest "Extermination of Bakonawa" is Bugged doesn't drop the request item when doing the quest. (Lost Belongings) 

Sprites for Rebellion weapons and Ammo needs to be added.
New Rebellion Ammo needs to be added.
The Slotter Leablem don't have Special Ninja Suit in its slot list.
Some NPC's that work for Gunslinger don't work for rebellion.
Reproduce is not coping Skills that are ground target. Example: Severe RainStorm
King's Grace suppose to have a 90 Second Cool Down
Full Throttle Cool Down suppose to be 1 Hour and is not draining the % of HP/SP per second during the said period of time under its effect.
Sorcerers Skill “Elemental Shield” Suppose to Cast Both Pneuma and Safetywall on all party Members cell that isn’t within a land protector, (Including player) and can’t cast without Having a summon, + Bluegemstone. Consumes a Blue Gemstones but no summon is killed.
Shadow Chaser Bloody Lust Skill doesn’t do anything. iRO Has it to Level 10 Provoke buff on everyone whos is in the 7x7 Radius, kRO has Berserk cast on the 7x7 Radius.
Amplified Magic Power has to have a cast-time.
Warg Strike/Bite is being reconized as ranged. Anything that increase Long Range Damage increases Warg Strike/Bite Damage. The way it is suppose to be is based on is your ATK + Tooth Of Warg + Warg Strike/Bite Lv/% Only.

Axe Training (mechanic skill) Suppose to add weapon attack. (Needs Research)
Fire Earth Research (Mechanic skill) Is suppose to add on weapon attack.  (Needs Research)

King's Grace is missing the animation, Effect ID: 1051
Rune Stone creation has the wrong animation, Effect ID: 1015 (Success) 1016 (Failed)
Mix Cooking has the wrong animation, Effect ID: 1017 (Success) 1018 (Failed)

One thing in need of research:
King's Grace also suppose to have all the party restricted to  attack and be attacked.
No skills allowed, No Physical damage allowed during the time it is casted, During WoE Only effects allies.

**Comment by MrAntares** [comment] 2015-01-08 09:30
2 things I think invalid:
- Rebellion weapons and ammo is a client-sided todo, because it's missing from the luas/txts, am I right?
- Last time I checked with my 2014.12.07 ver, Bloody Lust did give the Berserk status in PVP enabled areas.

Amplified Magic Power's missing casttime is confirmed on my server.

About axe training and fire earth research can you provide some source? Afaik, every skill/item atk bonus is equipment attack unless it is mastery.

**Comment by DrNebula** [comment] 2015-01-09 03:14
Sorry My mistake I am or can be wrong about that, but here's some information : on iRO Str or Dex (Depending on what weapon) Gives 0.5% Weapon ATK While On kRO it doesn't if that was the case in this video 
https://www.youtube.com/watch?v=CL8LCZvbkPQ 
The Mechanic would've reached a lot more higher ATK.
The Axe gives 383 ATK when refined to +9, + 40 With the Headgear, +57 With the shoes, + 24 (Fightspirit Lv.7), +15 (White Knight Card), (Idk what shadow weapon he is wearing), +fighting Spirit 30 ATK or Box of Resentment 20 ATK,  I can't find out about the other numbers to have it in total of 575 missing out 26-36 ATK.

**Comment by cydh** [comment] 2015-01-11 03:18
@euphyy @nanakiwurtz @Atemo

**Comment by cydh** [comment] 2015-01-11 03:18
@euphyy @nanakiwurtz @Atemo @Luciar

**Comment by Atemo** [comment] 2015-01-13 23:35
About Malaya Port quest
https://rathena.org/board/tracker/issue-9376-renewal-instances-bug/

**Comment by DrNebula** [comment] 2015-01-14 03:56
What I read from what you posted Atemo, is that the quest with bakonawa is bugged because it was a customized quest based on another player in kRO report and you can't put much further effort on it due to lack of information. 
http://irowiki.org/wiki/Bakonawa_Extermination
If the way Ziu explained it is similar to this information then iRO and kRO Have the same quest with it. 
If I am wrong that that is the reason then the other reason is that it was custom made so it will come with bugs, but isn't debugging what this thread is about? Making a better Ragnarok Emulator/rAthena?

I checked the logs they have/wiki in the korean ragnarok website and the quest has no futher information besides the rewards but I believe it to be the same.

If there is need of any further information I'll get it for you guys. I do research a lot especially for the server I am currently working for and I am just trying to organize things to be running as smooth as possible and as professional as it can be.

**Comment by nanakiwurtz** [comment] 2015-01-14 10:52
I'm sorry for my late reply, I'll see what I can do...

**Comment by DrNebula** [comment] 2015-01-22 00:18
Hi, just wondering what is the process that is going on at the moment to this bug report.
I am frequently checking if anything is being done.

P.S. Thank you for your replies.

**Comment by Luciar** [comment] 2015-02-05 10:58
Are you still working on this Nanakiwurtz?

**Comment by nanakiwurtz** [comment] 2015-02-05 17:16
@Luciar: I have finished submitting my commits regarding the missing items since 16 days ago (https://github.com/rathena/rathena/commit/a60e41e8cbb978576e8790267e4d2ecb069caecf)

**Comment by Luciar** [comment] 2015-02-05 17:23
Fixed a60e41e8cbb978576e8790267e4d2ecb069caecf by @nanakiwurtz

**Comment by DrNebula** [comment] 2015-02-22 02:33
"Also the axe training and all I'm Sorry My mistake I am or can be wrong about that, but here's some information : on iRO Str or Dex (Depending on what weapon) Gives 0.5% Weapon ATK While On kRO it doesn't if that was the case in this video : 
https://www.youtube.com/watch?v=CL8LCZvbkPQ 
The Mechanic would've reached a lot more higher ATK.
The Axe gives 383 ATK when refined to +9, + 40 With the Headgear, +57 With the shoes, + 24 (Fightspirit Lv.7), +15 (White Knight Card), (Idk what shadow weapon he is wearing), +Distilled fighting Spirit 30 ATK or Box of Resentment 20 ATK, I can't find out about the other numbers to have it in total of 575 missing out 26-36 ATK, but most definitely the weapon attack is off." 

What about this that I stated? and the other bug reports?

**Comment by nanakiwurtz** [comment] 2015-02-26 06:32
@DrNebula: Sorry, but where do you get this one? "The Slotter Leablem don't have Special Ninja Suit in its slot list"

**Comment by cydh** [comment] 2015-02-27 14:15
can someone
- [x] make
- [x] it
- [ ] clear
- [ ] with
- [x] task
- [ ] list

**Comment by anacondaqq** [comment] 2015-02-27 14:44
- [x] sorry 
- [ ] offtop
- [x] nice 
- [x] feature

**Comment by nanakiwurtz** [comment] 2015-02-27 16:28
This is what will happened if there's so much report in a single Issue

**Comment by nanakiwurtz** [comment] 2015-02-27 16:35
- [x] http://www.divine-pride.net/database/item/15043/black-wing-suits-1
- [x] http://www.divine-pride.net/database/item/2891/black-wing-brooch
- [x] http://www.divine-pride.net/database/item/15042/white-wing-suits-1
- [x] http://www.divine-pride.net/database/item/2890/white-wing-brooch
- [x] http://www.divine-pride.net/database/item/15037/peuzs-plate
- [x] http://www.divine-pride.net/database/item/2884/peuzs-seal-1
- [x] http://www.divine-pride.net/database/item/15036/urs-plate
- [x] http://www.divine-pride.net/database/item/2883/urs-seal-1
- [x] http://www.divine-pride.net/database/item/15039/nabs-cloth-1
- [x] http://www.divine-pride.net/database/item/2887/nab-ring
- [x] http://www.divine-pride.net/database/item/15038/saphas-cloth-1
- [x] http://www.divine-pride.net/database/item/2886/sapha-ring
- [ ] The Malaya Port Quest "Extermination of Bakonawa" is Bugged doesn't drop the request item when doing the quest. (Lost Belongings)
- [x] ~~Sprites for Rebellion weapons and Ammo needs to be added.~~
- [ ] New Rebellion Ammo needs to be added.
- [ ] The Slotter Leablem don't have Special Ninja Suit in its slot list.
- [ ] Some NPC's that work for Gunslinger don't work for rebellion.
- [ ] Reproduce is not coping Skills that are ground target. Example: Severe RainStorm
- [ ] King's Grace suppose to have a 90 Second Cool Down
- [ ] Full Throttle Cool Down suppose to be 1 Hour and is not draining the % of HP/SP per second during the said period of time under its effect.
- [ ] Sorcerers Skill “Elemental Shield” Suppose to Cast Both Pneuma and Safetywall on all party Members cell that isn’t within a land protector, (Including player) and can’t cast without Having a summon, + Bluegemstone. Consumes a Blue Gemstones but no summon is killed.
- [ ] Shadow Chaser Bloody Lust Skill doesn’t do anything. iRO Has it to Level 10 Provoke buff on everyone whos is in the 7x7 Radius, kRO has Berserk cast on the 7x7 Radius.
- [ ] Amplified Magic Power has to have a cast-time.
- [ ] Warg Strike/Bite is being reconized as ranged. Anything that increase Long Range Damage increases Warg Strike/Bite Damage. The way it is suppose to be is based on is your ATK + Tooth Of Warg + Warg Strike/Bite Lv/% Only.
- [ ] Axe Training (mechanic skill) Suppose to add weapon attack. (Needs Research)
- [ ] Fire Earth Research (Mechanic skill) Is suppose to add on weapon attack. (Needs Research)
- [ ] King's Grace is missing the animation, Effect ID: 1051
- [ ] Rune Stone creation has the wrong animation, Effect ID: 1015 (Success) 1016 (Failed)
- [ ] Mix Cooking has the wrong animation, Effect ID: 1017 (Success) 1018 (Failed)
- [ ] King's Grace also suppose to have all the party restricted to attack and be attacked. No skills allowed, No Physical damage allowed during the time it is casted, During WoE Only effects allies.

**Comment by nanakiwurtz** [comment] 2015-04-06 18:06
> @DrNebula said:
> The Malaya Port Quest "Extermination of Bakonawa" is Bugged doesn't drop the request item when doing the quest. (Lost Belongings)

Confirmed, the 'Lost Belongings' (ID: 6520) currently can't be retrieved by any means.
It should be dropped by Tiyanak (ID: 2314) on map 'ma_fild01'.
The monster Tiyanak itself doesn't drop 'Lost Belongings' by default.
I guess the possible temp fix is to use OnNPCKillEvent + check for malaya_bakona2 > 0 + killedrid==2314 + rand.

**Comment by nanakiwurtz** [comment] 2015-04-11 05:13
> @DrNebula said:
> Some NPC's that work for Gunslinger don't work for rebellion

Could you post the NPC coordinates here to make us easier to locate it?

**Comment by nanakiwurtz** [comment] 2015-05-05 19:21
Summoning @euphyy or @Atemo :wink:

**Comment by nanakiwurtz** [comment] 2015-06-02 17:53
Hello..... :banana:

**Comment by Akkarinage** [comment] 2015-06-03 12:40
It may well be easier if we just created each item on that list as separate issues.

**Comment by Lemongrass3110** [comment] 2015-11-05 12:17
@nanakiwurtz could you create issues for the things that are still left and close this one?

**Comment by nanakiwurtz** [comment] 2015-11-08 15:47
I guess the only valid issue is:
> The Malaya Port Quest "Extermination of Bakonawa" is Bugged doesn't drop the request item when doing the quest. (Lost Belongings)

The others are mostly done

**Comment by nanakiwurtz** [comment] 2015-11-08 17:17
@Atemo said that the Bakonawa quest has been fixed on 230811c8
So I'm closing this issue now :banana:

**Closed by nanakiwurtz** 2015-11-08 17:17 UTC
Labels: bug:database
