### ISSUE TITLE
warning: passing NULL to non-pointer argument 4

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#7574] opened 2023-02-01 05:54 UTC
### rAthena Hash

d93d4144eb599bf1656ab0e7fbdb7cb8edf0decf

### Client Date

20211103

### Server Mode

Pre-Renewal, Renewal

### Result

i always get this compile warning

`        CXX     npc.cpp (custom rule)
npc.cpp: In function ??int npc_dynamicnpc_removal_timer(int, t_tick, int, intptr_t)??:
npc.cpp:5813:161: warning: passing NULL to non-pointer argument 4 of ??int add_timer(t_tick, TimerFunc, int, intptr_t)?? [-Wconversion-null]
 5813 |    nd->dynamicnpc.removal_tid = add_timer( nd->dynamicnpc.last_interaction + battle_config.feature_dynamicnpc_timeout, npc_dynamicnpc_removal_timer, nd->bl.id, NULL );
      |                                                                                                                                                                 ^~~~
In file included from ../common/core.hpp:10,
                 from ../common/database.hpp:16,
                 from npc.hpp:10,
                 from npc.cpp:4:
../common/timer.hpp:54:61: note:   declared here
   54 | int add_timer(t_tick tick, TimerFunc func, int id, intptr_t data);
      |                                                    ~~~~~~~~~^~~~
npc.cpp:5819:176: warning: passing NULL to non-pointer argument 4 of ??int add_timer(t_tick, TimerFunc, int, intptr_t)?? [-Wconversion-null]
 5819 |    nd->dynamicnpc.removal_tid = add_timer( nd->dynamicnpc.last_interaction + DIFF_TICK( gettick(), nd->dynamicnpc.last_interaction ), npc_dynamicnpc_removal_timer, nd->bl.id, NULL );
      |                                                                                                                                                                                ^~~~
In file included from ../common/core.hpp:10,
                 from ../common/database.hpp:16,
                 from npc.hpp:10,
                 from npc.cpp:4:
../common/timer.hpp:54:61: note:   declared here
   54 | int add_timer(t_tick tick, TimerFunc func, int id, intptr_t data);
      |                                                    ~~~~~~~~~^~~~
npc.cpp: In function ??npc_data* npc_duplicate_npc_for_player(npc_data&, map_session_data&)??:
npc.cpp:5877:162: warning: passing NULL to non-pointer argument 4 of ??int add_timer(t_tick, TimerFunc, int, intptr_t)?? [-Wconversion-null]
 5877 |  dnd->dynamicnpc.removal_tid = add_timer( dnd->dynamicnpc.last_interaction + battle_config.feature_dynamicnpc_timeout, npc_dynamicnpc_removal_timer, dnd->bl.id, NULL );
      |                                                                                                                                                                  ^~~~
In file included from ../common/core.hpp:10,
                 from ../common/database.hpp:16,
                 from npc.hpp:10,
                 from npc.cpp:4:
../common/timer.hpp:54:61: note:   declared here
   54 | int add_timer(t_tick tick, TimerFunc func, int id, intptr_t data);
      |                                                    ~~~~~~~~~^~~~`

### Expected Result

download the latest git hash and compile it under centos. you will get compile warnings.

### How to Reproduce

download the latest git hash and compile it under centos. you will get compile warnings.

### Official Information

download the latest git hash and compile it under centos. you will get compile warnings.

**Comment by Lemongrass3110** [comment] 2023-02-01 08:33
Duplicate of #7417

**Closed by Lemongrass3110** 2023-02-01 08:33 UTC
Labels: status:duplicate
