### ISSUE TITLE
Offertorium and Magnificat do not overwrite

### ISSUE THREAD

**Issue by anelson-86** [rathena/rathena#7455] opened 2022-11-23 07:12 UTC
### rAthena Hash

df3d7d4bd10bcb0a8e14b3c9a66dd8233c00e082

### Client Date

2021-11-17

### Server Mode

Renewal

### Result

Offertorium and Magnificat do not overwrite each other instead the skill casts but shows no effect.

### Expected Result

Official servers have these skills replacing one another when cast. Causing the previous buff to be canceled.

### How to Reproduce

Cast Offertorium, then cast Magnificat

### Official Information

https://irowiki.org/wiki/Offertorium
https://irowiki.org/wiki/Magnificat

**Comment by Lemongrass3110** [comment] 2022-11-23 20:18
Duplicate of #7241

Should be fixed already. Please update your emulator.

**Closed by Lemongrass3110** 2022-11-23 20:18 UTC
Labels: type:bug
