### ISSUE TITLE
party_addmember

### ISSUE THREAD

**Issue by Zellukas** [rathena/rathena#423] opened 2015-05-07 03:55 UTC
Party_addmember isnt working on last git

**Comment by aleos89** [comment] 2015-05-13 14:06
How is it not working? Can you provide the part of the script you are using for the command.

What Git hash are you using?

**Comment by Akkarinage** [comment] 2015-05-18 12:45
@Zellukas - marking this as invalid & unable to reproduce due to a distinct lack of information from you. If the issue persists, please reopen with more information.

**Closed by Akkarinage** 2015-05-18 12:45 UTC
Labels: [ status:invalid ], [ status:unable to reproduce ]
