### ISSUE TITLE
Map server crashes

### ISSUE THREAD

**Issue by LotusRO** [rathena/rathena#5354] opened 2020-08-23 20:45 UTC
* **rAthena Hash**: 

* **Client Date**: 2020/03/01

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  Server randomly starts spewing out "delete_timer error: Function mismatch 01C3EA20(unit_walktoxy_timer) != 016D3206(skill_keep_using) and eventually crashes
  * Expected Result:  server would not spew this msg and it would not crash
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by LotusRO** [comment] 2020-08-23 20:53
Turns out that this happens when someone tries to use Rolling cutter when they are out of SP? and leads to a map-server crash?

**Comment by Daegaladh** [comment] 2020-08-23 21:18
This was already fixed in afdd8d3897a347a746bd73682999c8613be59c6b 579a01c699a406581831c0bc8666dacacef39947 and/or 2d164cb8c89268cb57e658a97658441fe8990758

Do you have your rAthena updated to the lastest revision?

**Comment by LotusRO** [comment] 2020-08-23 21:36
We update weekly from rAthena, how do i provide you with a coredump?

**Comment by Daegaladh** [comment] 2020-08-23 21:40
Here https://github.com/rathena/rathena/wiki/GDB

**Comment by LotusRO** [comment] 2020-08-23 21:44
I sadly am not sure how to use this, as i've never done it

**Comment by Daegaladh** [comment] 2020-08-23 22:20
Nope, sorry, we need the coredump data so we can trace the bug

**Comment by Masao87** [comment] 2020-08-24 10:03
We're running the server on a windows server so we can't produce a core dump with the wiki link you gave us, I can only provide this image if it helps any.

![unknown](https://user-images.githubusercontent.com/4514182/91032089-c0aadb80-e601-11ea-926a-ee22e55bfe09.png)

**Comment by ecdarreola** [comment] 2020-08-24 10:10
@Masao87 alternatively you can get crash dump via windows by compiling your server in debug mode/starting it in debug mode.

To do that, right click solution of your server "rAthena" -> go to properties and see image below.
![image](https://user-images.githubusercontent.com/48939874/91032749-0208ae80-e635-11ea-8da6-6dccdce63677.png)

Set char-server, map-server, login-server to "Start" once you successfully compile the server it will automatically start and wait for the crash signal.

**Comment by Lemongrass3110** [comment] 2020-08-24 20:41
The server does not crash because of this. So neither on linux or windows a crash dump is available.

**Comment by LotusRO** [comment] 2020-08-24 23:24
> 
> 
> The server does not crash because of this. So neither on linux or windows a crash dump is available.

With all due respect, it crashes our server whenever this happens a lot, i reverted the change that was made recently on this issue and the server crashes stopped, it might be worth looking into why this is happening instead of just dismissing it.

**Comment by Lemongrass3110** [comment] 2020-08-25 04:35
As you can see @aleos89 already looked into it.
The crashes you would encounter would not be helpful / could not be traced back to this root cause. That is why I am saying THIS does not crash your server and any crash dumps that you think are caused by this would be worthless.

**Closed** 2020-08-25 18:27 UTC
Labels: component:core, component:skill, mode:renewal, priority:medium, status:confirmed, type:bug
