### ISSUE TITLE
opt1 statuses are canceled when a status change occurs

### ISSUE THREAD

**Issue by MrGrohminet** [rathena/rathena#8128] opened 2024-02-12 09:06 UTC
### rAthena Hash

8be1f819d9997497bfab09234307c99f1ca56992

### Client Date

2018

### Server Mode

Pre-Renewal

### Result

op1 statuses are canceled when a status change occurs
[screen-capture_4.webm](https://github.com/rathena/rathena/assets/97130720/f1410237-7ede-4c24-a704-ade6401e1876)

### Expected Result

I dont know 

-> 1 : Opt1 status can be overrride (a stun can replace a freeze)
-> 2 : statuses cannot be overridden

### How to Reproduce

1/ Freeze a monster
2/ Use Lex  Divinia on it
-> The monster thaws and does not move

1/ Freeze a char (with ice cream)
2/ Use Angelus with party member
3/ You can't move (freeze cd), but you can use items

### Official Information

-

### Modifications that may affect results

src/map/status.cpp

`sc->opt1 = scdb->opt1;` will update and reset opt1 status.

Can be replaced by 

Result 1

```
	if (scdb->opt1 && !sc->opt1) {
		sc->opt1 = scdb->opt1;
	}
```

Or result 2

```
	if (scdb->opt1) {
		sc->opt1 = scdb->opt1;
	}
```

**Comment by Daraen1** [comment] 2024-02-27 01:53
With my current rathena, I have the same issue (is older than yours).
I just tried your code just for testing. 
You cannot unfreeze a character by using Angelus skill for example but status on pvp mode still the same. 
I mean, you can unfreeze player with Stun skill like Scream. 
Probably better for me to post a video to explain correctly...

**Comment by Salfer13** [comment] 2024-03-11 22:18
![image](https://github.com/rathena/rathena/assets/52106036/a12fe41e-bbb6-460b-8ab9-effc518bc6ad)
 
 if I assign opt2 status to any opt1 status, opt1's effect will be interrupted, it will work but will not be displayed (potions can still be used)
[2024-03-12_00-15-39.webm](https://github.com/rathena/rathena/assets/52106036/bbf6d005-e717-473b-8e60-26334a355c52)

**Comment by Daraen1** [comment] 2024-03-11 22:40
I can confirm for potion thingy.
With @Singe-Horizontal , we have seen in /(pre-)re/status.yml missing some status flags.
For example, freeze and sleep for stun status.
*We just check the initial problem described by the author. It could be missed other failed status for stun*

```   
- Status: Stun
    DurationLookup: NPC_STUNATTACK
    States:
      NoMove: true
      NoCast: true
      NoAttack: true
    Opt1: Stun
    Flags:
      SendOption: true
      BossResist: true
      StopAttacking: true
      StopCasting: true
    Fail:
      Refresh: true
      Inspiration: true
      Gvg_Stun: true
      Stun: true
      Freeze: true
      Sleep: true
 ```

**Comment by Salfer13** [comment] 2024-03-11 22:50
![image](https://github.com/rathena/rathena/assets/52106036/5bfc5a85-724e-463b-808a-a3263d08b74c)

chenge 
sc->opt1 = scdb->opt1;
to
sc->opt1 |= scdb->opt1;

This seems to solve the problem, but it breaks something, and I don’t understand what

**Comment by Playtester** [comment] 2024-03-15 22:12
This needs to be more concrete because it works different for every status change.

You can always only have one OPT1 status change (you can see that on Salfer13's list of constants, OPT1 is just a number counting up, not a mask, so you can always only have one OPT1 status change).

However some OPT1 status changes will block other OPT1 status changes, that's why no overwrite would happen for some.

That STUN can overwrite FREEZE is working as official. STUN only fails on already stunned targets, so it will overwrite any other OPT1 status change. So this is working as intended.

SILENCE however is a OPT2 status change and should not overwrite FREEZE. You should just be both silenced and frozen. This is a bug in rAthena.

**Comment by Playtester** [comment] 2024-03-15 22:53
Salfer13 was on the right track but the fix is incorrect.

This fixes it:
```
	if(scdb->opt1 != OPT1_NONE) sc->opt1 = scdb->opt1;
	sc->opt2 |= scdb->opt2;
	sc->opt3 |= scdb->opt3;
	sc->option |= scdb->look;
```

**Comment by Salfer13** [comment] 2024-03-16 00:15
[2024-03-16 03-10-47.webm](https://github.com/rathena/rathena/assets/52106036/a75468a9-47e9-417a-bbaa-daea55239db1)

Everything seems to be working correctly

**Closed** 2024-03-16 13:42 UTC
Labels: status:confirmed, component:core, type:bug
