### ISSUE TITLE
Monster on abyss not agresive and auto Teleport

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2572] opened 2017-11-03 18:08 UTC
Monster on abyss not agresive and auto Teleport if we normal single attack

* **rAthena Hash**: e7e9cf6

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by vstumpf** [comment] 2017-11-03 18:16
Is it all aggressive monsters? Can you try going to another dungeon and testing this?

**Comment by Jeybla** [comment] 2017-11-03 18:18
Unable to reproduce. Tested abyss_01-abyss03. Can you add more detailed informations?

**Comment by mazvi** [comment] 2017-11-03 18:24
please check my replay atachment

[abysagresivenot.zip](https://github.com/rathena/rathena/files/1442090/abysagresivenot.zip)

is this issue related with https://github.com/rathena/rathena/pull/2561?

because i using minimum value limit 0 on battle.cpp

**Comment by Jeybla** [comment] 2017-11-03 18:27
I don't think so. But you should definitely recheck the issue on a clean branch. Otherwise this is just useless guessing.

**Comment by mazvi** [comment] 2017-11-03 18:29
do you use rathena e7e9cf6? and do monsters like ferus in abys is agresive?

**Comment by Jeybla** [comment] 2017-11-03 18:35
Yes and yes:
![image](https://user-images.githubusercontent.com/6203894/32390258-fd86eb36-c0cd-11e7-86f7-13197980d1bc.png)

G++ Version 6.2.0 on a debian.

**Comment by mazvi** [comment] 2017-11-03 18:36
Update abys dungeon not agresive

the evil druid in glast heim not agresive

but on field like mantis is agresive

this is my replay

[nonagresive.zip](https://github.com/rathena/rathena/files/1442116/nonagresive.zip)

**Comment by mazvi** [comment] 2017-11-03 18:47
i was revertback battle.cpp to original but not work...

my GCC version is

gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by aleos89** [comment] 2017-11-03 19:40
I would go back through c4a364b and make sure sure all instances of `e_mode` match your base. I just tested on Windows and it works as it should.

**Comment by mazvi** [comment] 2017-11-03 19:54
are you VIP system is enabled? my VIP system is enabled

**Comment by aleos89** [comment] 2017-11-03 20:15
The VIP system doesn't change monster modes. You have something that wasn't merged properly from the update. I highly suggest you check out a clean copy, test it, see if you can replicate it. If it works fine on a clean copy of rAthena for you then you need to compare your code and see what might be wrong. I have a feeling you incorrectly merged status.cpp.

**Comment by mazvi** [comment] 2017-11-03 20:16
i was clean copy src folder and recompile but not work.... i will test using client 2015

**Comment by Akaineko-astasi** [comment] 2017-11-03 20:47
@mazvi you don't use `@monsterignore` while encountering these monsters do you?

**Comment by mazvi** [comment] 2017-11-03 20:51
no this is happen to many player, so i send this issue... 

now i revert back my rathena to 09519f3 the ferus now normaly agresive

**Comment by Questune09** [comment] 2017-11-03 22:11
same issue here 

my GCC version is

g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


i test all monsters and doesnt use @monster ignore / @battleignore or something that blocks monsters from attacking

also tested with normal character at lhz_dun_n / lhz_ dun (from low to highest lvl dungeon) gef_dun02

some dungeons working fine also check all fields

**Comment by vstumpf** [comment] 2017-11-03 22:45
Possible cause, a change in path.c(pp) prevents monsters from finding paths to the target? Since mobs are teleporting when getting attacked, it seems like they try to find a path to the target, can't, and teleport due to rude attack behavior.

Are mobs walking around or just stuck in place?

**Comment by Questune09** [comment] 2017-11-03 22:46
they just walking around

and yes your right some of monsters when you attack them they teleport

**Comment by mazvi** [comment] 2017-11-04 01:57
I have also re-cloned src including path.cpp. but still the same.

**Comment by Questune09** [comment] 2017-11-04 02:02
same like what i did before

**Comment by Questune09** [comment] 2017-11-04 07:02
any feed back to solve this please

**Comment by Questune09** [comment] 2017-11-04 07:11
now i try again a clean folder of rathena same result some monsters not attacking

gef_dun02 / glastheim / lhz_dun_n / lhz dungeons and more

**Comment by mazvi** [comment] 2017-11-04 07:33
wow clean folder? good try...

**Comment by Questune09** [comment] 2017-11-04 07:37
still not working monster is still the same -_- can help this ??

**Comment by mazvi** [comment] 2017-11-04 07:44
git pull
git reset --hard c6cc8edeb489943b5d5be2f8f71c5e606ee48ad5

will make you use time capsule before CPP Map Server Implement

**Comment by mazvi** [comment] 2017-11-04 12:21
for temporary solution i using this

`git fetch origin`
`git merge c6cc8edeb489943b5d5be2f8f71c5e606ee48ad5`

this will update rathena to c6cc8edeb489943b5d5be2f8f71c5e606ee48ad5

**Comment by Jeybla** [comment] 2017-11-04 12:38
It's hard to locate the cause, when we're unable to reproduce the issue.
Maybe it's actually a problem in older compiler versions.

**Comment by mazvi** [comment] 2017-11-04 12:59
Maybe yes my gcc is 5.3.1

**Comment by Questune09** [comment] 2017-11-04 13:03
same version now with @mazvi

**Comment by mazvi** [comment] 2017-11-04 13:14
I will try using devtoolset7 with gcc7 monday.. because my server is online now..

**Comment by mazvi** [comment] 2017-11-05 03:39
**I was Try GCC 7**

gcc (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Then i get warning**

 LD      map-server
scanner.h:208:17: warning: type of ‘libconfig_yy_scan_string’ does not match original declaration [-Wlto-type-mismatch]
scanner.c:1964:17: note: ‘libconfig_yy_scan_string’ was previously declared here
scanner.c:1964:17: note: code may be misoptimized unless -fno-strict-aliasing is used
scanner.h:202:6: warning: type of ‘libconfig_yy_delete_buffer’ does not match original declaration [-Wlto-type-mismatch]
scanner.c:1743:10: note: ‘libconfig_yy_delete_buffer’ was previously declared here
scanner.c:1743:10: note: code may be misoptimized unless -fno-strict-aliasing is used
make[1]: Meninggalkan direktori `/root/rathena/src/map'
building conf/import, conf/msg_conf/import and db/import folder...
[root@ragnarok-sg rathena]#

FINAL

the monster is also anoying, canot agresive like ferus on abys...

but monster is normal on rathena ver c6cc8edeb489943b5d5be2f8f71c5e606ee48ad5

**Comment by Questune09** [comment] 2017-11-05 04:12
well for other information not only the monsters affected also some custom NPC's are not working when you click it nothing will show

some of the skills are not working properly also

i didn't test on pets and homun i think all of them are affected

**Comment by Jeybla** [comment] 2017-11-05 10:07
> well for other information not only the monsters affected also some custom NPC's are not working when you click it nothing will show

> some of the skills are not working properly also

> i didn't test on pets and homun i think all of them are affected

Please be explicit, so we're able to reproduce it. Which NPCs are affected? Can you upload them? Which skills, pets and homunculus are affected?

**Comment by mazvi** [comment] 2017-11-05 11:36
Yes, centos 7 64bit minimal with GCC 7.2.1

gcc (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by lighta** [comment] 2017-11-05 19:50
Confirmed on Centos7_x86_64 (minimal install)
Tryed with gcc 4.8 and gcc 7.2. both manage to produce the bug when using "**./configure**"
bug did **NOT** appear when using cmake.

```
yum -y install epel-release
yum install cmake3
mkdir cbuild && cd cbuild && make ..
cd ..
mv ../*-server ./ #this is cause current cmake outpath is lettle off
```

**Comment by mazvi** [comment] 2017-11-06 01:37
So for now rathena using cmake cbuild not using ./configure && make clean && make server again?

**Comment by Questune09** [comment] 2017-11-06 01:39
what are the proper steps?

**Comment by uddevil** [comment] 2017-11-06 02:56
I have the same issues with e7e9cf6d7333345d0e11d9f0bf9f1badb6ff3cd9

![cacad bin_2017-11-06_09-54-25](https://user-images.githubusercontent.com/10105610/32423383-af90e014-c2d8-11e7-97f5-52d6f700700b.png)

Works fine on windows though..

**Comment by Questune09** [comment] 2017-11-06 03:49
forgot to mention also when you killed the monster didnt drop anything like brigan etc.

**Closed** 2017-11-06 22:00 UTC
Labels: component:core, priority:medium, status:confirmed, type:bug
