### ISSUE TITLE
[3 option] problem

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#1545] opened 2016-09-06 16:00 UTC
![image](https://cloud.githubusercontent.com/assets/11705163/18281012/d0d58fee-748d-11e6-82ec-a70a9804c0e1.png)
anyone having the same issue ?
i git pull for a month+ from july to september so i didnt know which commit done this 
Thanks if you can help :)

**Comment by secretdataz** [comment] 2016-09-07 01:01
Please provide missing info. Thanks.

**Comment by reunite-ro** [comment] 2016-09-07 04:10
git hash : https://github.com/rathena/rathena/commit/cf80d723595c6ee6ea0082a7cc819e269f429dd1
client date : 20151104
mode: renewal

**Comment by Lemongrass3110** [comment] 2016-09-07 09:22
I have had another report like this, where they had some custom changes which merged badly. So they ended up storing some of the cards in the random option fields. Maybe you should check your database(inventory table). Judging from your screenshot it looks alike, because you have 3 cards in the item and it has 3 random options sent to the client.

**Comment by secretdataz** [comment] 2016-09-07 10:45
This should be closed unless it's confirmed to be a bug.

**Closed by secretdataz** 2016-09-07 10:45 UTC
Labels: status:needs more info, status:unable to reproduce

**Comment by psyzerkski** [comment] 2016-09-26 12:52
@reunite-ro , i've fixed mine with this:

`	switch(select("Optimize Level #1","Optimize Level #2","Optimize Level #3","Optimize Level #4")){
		case 1: goto OnOptSelect0; end;
		case 2:	if (!getequiprandomoption(EQI_HAND_R,0,ROA_ID,getcharid(0))){
					mes " "; mes " ";
					mes "^FF0000You need to apply Level #1 Optimization before this.^000000";
					close;
				} goto OnOptSelect1; end;
		case 3:	if (!getequiprandomoption(EQI_HAND_R,1,ROA_ID,getcharid(0))){
					mes " "; mes " ";
					mes "^FF0000You need to apply Level #2 Optimization before this.^000000";
					close;
				} goto OnOptSelect2; end;
		case 4:	if (!getequiprandomoption(EQI_HAND_R,2,ROA_ID,getcharid(0))){
					mes " "; mes " ";
					mes "^FF0000You need to apply Level #3 Optimization before this.^000000";
					close;
				} goto OnOptSelect3; end;
	}

OnOptSelect0:
setrandomoption(EQI_HAND_R,0,RDMOPT_VAR_ATKPERCENT,10,0,getcharid(0)); end;
OnOptSelect1:
setrandomoption(EQI_HAND_R,1,RDMOPT_VAR_ATKPERCENT,10,1,getcharid(0)); end;
OnOptSelect2:
setrandomoption(EQI_HAND_R,2,RDMOPT_VAR_ATKPERCENT,10,2,getcharid(0)); end;
OnOptSelect3:
setrandomoption(EQI_HAND_R,3,RDMOPT_VAR_ATKPERCENT,10,3,getcharid(0)); end;

`

You simply need to apply the options accordingly, else it won't show the info on client side.
