### ISSUE TITLE
Free Cell Search

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#224] opened 2015-01-12 20:41 UTC
Something is clearly wrong with how monsters look for the next free cell.
And nope - no way this is official.

Enjoy this video:
http://youtu.be/urtSgP6J_F8

**Comment by cydh** [comment] 2015-01-13 03:29
nice poring line. xD

**Comment by Playtester** [comment] 2015-02-22 09:08
This is exactly how it works on our Aegis test server too.

**Comment by anacondaqq** [comment] 2015-03-12 05:48
Extra info about path looking: 
1. Try to spawn Dracula (he have 16 slaves).
2. Set these options to *2* https://github.com/rathena/rathena/blob/master/conf/battle/misc.conf#L99
3. Uncomment this one and recompile: https://github.com/rathena/rathena/blob/master/src/config/core.h#L42
4. If MVP will be somewhere like on this screenshot (blue mark) ![](https://camo.githubusercontent.com/cea4dbfd278a2d4a7bd2b8c2be7f08677caa6f1b/687474703a2f2f69362e35636d2e72752f692f4e5471762e6a7067)

When slaves will be spawned, MVP can't move outside the _|

**Comment by Playtester** [comment] 2015-03-12 07:31
Strange the cell stacking shouldn't prevent you from moving somewhere, just from staying on the cell that is occupied.

How do you move the MVP into the corner, though?

**Comment by anacondaqq** [comment] 2015-03-12 12:14
@Playtester mvp do it by itself (while server is up (no dynamic monsters)

**Comment by Playtester** [comment] 2015-03-13 08:47
So this happens only when it doesn't have any visible target?

**Comment by anacondaqq** [comment] 2015-10-26 07:10
i'm not sure...

**Comment by MrAntares** [comment] 2015-10-28 15:43
This is also the reason why we can't pick up things if there is someone standing on it's east cell....
I highly doubt this is official and even so there should be an "unofficial" fix and config for it.

**Comment by anacondaqq** [comment] 2015-10-29 00:19
yep. exactly. It's good to follow official behavior, but very weird things must be fixed.

**Comment by Playtester** [comment] 2015-10-30 14:02
I remember I already fixed the bug with picking up from a cell east of the item some months ago.

Also the official code only makes you walk to the closest free cell, it wouldn't make you get stuck.

In the example above the custom mod is used, it most likely isn't compatible with the official code, I suggest only using one of the two. Either you want any occupied cell to work like a wall (custom mod) or you want to do a path search for the closest free cell if you end up on an occupied cell (official behavior).

So my suggestion would be to comment the #define CELL_NOSTACK line.

**Comment by anacondaqq** [comment] 2015-10-30 16:38
both tried. Let me get a lot of data first, then i will post maximum details about the problem. Because there are players who know better then me official mechanic, and i'm do not understand them.
I see some difference between eAthena (2008-2009 years), and current rAthena, but i can't get them. + I do not have any test server where i can test it at official Aegis Server...

**Comment by Playtester** [comment] 2015-11-03 11:03
Well official free cell search works this way:
1. If you target a cell that is occupied you will instead target the closest free cell near the target cell. This is done by both the client and monsters. The client actually prevent you from walking on a cell that has for example a plant on it because of that. You will always walk to the cell east of the plant instead. 
2. You can "cheat" this system by placing yourself 15 cells away so your client won't know about the plant and then click on where you know the plant is. In that case you will walk on the same cell of the plant, stop moving but then start moving again one cell to the east. Monsters can also end up on an occupied cell and behave in a similar fashion because the cell might not have been occupied when they started moving, but is occupied when they finish moving.
3. Monsters put attacking and looting to a higher priority than looking for a free cell, so as long as they have something to do they won't spread out.

I implemented it the same way already on rAthena a while ago. The question is why would that cause MVPs to get stuck. Even assuming we have Dracula who has many slaves, there should still be free cells within his 15x15 search area he could target, which should cause him to actually walk to those free cells.

If I remember correctly you also reported that you keep getting the message that a monster can't walk randomly. So there might actually be a problem with the random walk routine, but I just can't find it looking at the source code:

	if(d<5) d=5;
	if(d>7) d=7;
	for(i=0;i<retrycount;i++){	// Search of a movable place
		int r=rnd();
		int x=r%(d*2+1)-d;
		int y=r/(d*2+1)%(d*2+1)-d;
		x+=md->bl.x;
		y+=md->bl.y;

		if(((x != md->bl.x) || (y != md->bl.y)) && map_getcell(md->bl.m,x,y,CELL_CHKPASS) && unit_walktoxy(&md->bl,x,y,8)){
			break;
		}
	}

In the source code a random cell in a 11x11 to 15x15 area is picked and then the monster should walk to the cell if that cell isn't the same cell as the monsters is on, the monster can actually walk to that cell (no walls blocking) and unit_walktoxy didn't return 0.

So it would be interesting to know where in the code it actually fails its movement.

That being said, the code for random walking is really unoptimized. Rather than picking a random cell and hoping that moving to it works just fine, it should just scan through all the possible cells until it finds one that works (and directly report it to the console if not a single cell could be found).

**Comment by anacondaqq** [comment] 2015-11-03 17:28
How can i help you to find a problem?

**Comment by Playtester** [comment] 2015-11-04 11:49
Hmm to find the source of the problem we would need to debug it. But that would mean you need to find a way to reproduce it on your test server. Because we can't print all the movement comment of all monsters on a real server to the console...

Maybe if we focus on Dracula only?

Problem is I don't have access to the source code anymore so I can't easily write some code snippet.

Assuming we take this part:

if(((x != md->bl.x) || (y != md->bl.y)) && map_getcell(md->bl.m,x,y,CELL_CHKPASS) && unit_walktoxy(&md->bl,x,y,8)){
    break;
}

We could change it to something like:

if(((x != md->bl.x) || (y != md->bl.y)) && map_getcell(md->bl.m,x,y,CELL_CHKPASS)) {
    if(unit_walktoxy(&md->bl,x,y,8)) {
        break;
    } else if(md->mob_id == 1389) {
        ShowDebug("Dracula can't move from (%d,%d) to (%d,%d)", md->bl.x, md->bl.y, x, y);
    }
}

That would be the first step, wait until Dracula gets stuck and then see what message you get on the console. Then check the exact coordinates on the map Dracula wants to move to and evaluate the reason why he can't move there (wall in between?).

**Comment by anacondaqq** [comment] 2015-11-04 13:06
Dear @Playtester can you release some debug for unit_walktoxy? I will apply it instantly to the live server, and we will get a lot of data to analize and find a source of the problem.

**Comment by Lemongrass3110** [comment] 2015-11-05 12:20
@Playtester could this be related to #208 ? You have a lot of debug output there.

**Comment by Playtester** [comment] 2015-11-06 07:04
Yup, that's what I was referring to earlier.

The debug output doesn't help me when I don't have a video of a monster actually being stuck in the reported locations.

Also what I'm looking for is in what part of the code unit_walktoxy returns 0 for that very case. But to debug that you'd need to do a lot of recoding, so it only outputs a very particular case (e.g. Dracula) but outputs something at every single place it could potentially return 0.

I can't really write this out of my head and especially not without sitting for too long, so I'm currently unable to do that. =/
And it doesn't help that anyone we could debug it can't reproduce the bug either. ^^;

**Comment by anacondaqq** [comment] 2015-11-06 09:33
> The debug output doesn't help me when I don't have a video of a monster actually being stuck in the reported locations (it's hard to find because the moment the error is printed to the console the mob is respawned).

The monster can't move.

**Comment by Lemongrass3110** [comment] 2016-01-31 01:13
@Playtester since my bug report is invalid. Can this one be closed or is there still something that needs to be discussed?

**Comment by Playtester** [comment] 2016-01-31 09:16
Hi, I optimized the random walk code a little here:
https://github.com/rathena/rathena/commit/78419baa76657c383112babfc7633b57c5786482

The free cell search issue originally reported is actually invalid, it works like that on official servers as well. I'll close this for now, but if more issues arise, feel free to reopen and report.

**Closed by Playtester** 2016-01-31 09:16 UTC
Labels: bug:core, priority:medium, server:map
