### ISSUE TITLE
skill_castend_nodamage_id: Unknown skill

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5851] opened 2021-04-12 06:44 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/4a8be872150844e8c1acd2e1024d3f055d5a9fe9

* **Client Date**: 2020-06-20

* **Server Mode**: RE

* **Description of Issue**: These Warning appear on the console after commit https://github.com/rathena/rathena/commit/4a8be872150844e8c1acd2e1024d3f055d5a9fe9
```
 [Warning]: skill_castend_nodamage_id: Unknown skill used:254
 
 [Warning]: skill_castend_nodamage_id: Unknown skill used:653
 ```
Unfortunately, I still don't know how to generate the warnings.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2021-04-12 08:59
CR_GRANDCROSS and NPC_EARTHQUAKE.

Any modifications or pull requests?

**Comment by Badarosk0** [comment] 2021-04-12 11:23
> CR_GRANDCROSS and NPC_EARTHQUAKE.
> 
> Any modifications or pull requests?

Yes, Bundle https://github.com/rathena/rathena/pull/5517

**Comment by Lemongrass3110** [comment] 2021-04-12 12:09
4CrAM?

**Comment by Badarosk0** [comment] 2021-04-12 12:12
> 4CrAM?

yes =D @Lemongrass3110

**Comment by vstumpf** [comment] 2021-04-12 21:08
Since we can't tell what modifications you have made, if you can show us your source modifications we can try to figure out what's going on.

**Comment by Rytech2** [comment] 2021-04-12 23:32
Your claiming that your using 4CrAM but also using rAthena commit from 6 days ago. My last rA merge was on March 30 which is close to 2 weeks. You also applied the job improvement patch. So im assuming you merged things in yourself.

Second, Grand Cross and Earthquake work fine for me and hits enemies. Tho for some reason Grand Cross isn't hitting my character and displays misses which Lemongrass also tested on rA and he too got the same issue. Other then that, they work fine and no map console errors.

Check your work to see if you made a error in your merging.

**Comment by aleos89** [comment] 2021-04-13 19:07
Unable to reproduce on a clean pull of rAthena.

**Closed by aleos89** 2021-04-13 19:07 UTC
Labels: status:invalid
