### ISSUE TITLE
character_slots column is higher than supported MAX_CHARS

### ISSUE THREAD

**Issue by fab10Carvalho** [rathena/rathena#7461] opened 2022-11-28 06:41 UTC
### rAthena Hash

46610164452ec4fe2da9c78a0aa2113f573e7239

### Client Date

20220406

### Server Mode

Renewal

### Result

Error report from charserv.bat when create vip account

![error](https://user-images.githubusercontent.com/112716645/204208463-9794c199-38dc-496a-82b0-5a63f511d59d.png)

### Relevant Log Output

```Shell
.
```

### Expected Result

Vip account should be not error

### How to Reproduce

1 `#define VIP_ENABLE`

2 create account vip type `@vip 10mn viptest`

![screenrAthena004](https://user-images.githubusercontent.com/112716645/204209249-a0f06153-955c-4b71-be1e-3720501a51fe.jpg)

3 relogin

![screenrAthena005](https://user-images.githubusercontent.com/112716645/204209433-e9b01f76-298a-41ae-a399-892f0b8c4e9b.jpg)

4 got error

![error](https://user-images.githubusercontent.com/112716645/204209561-28c73992-6715-4454-b85f-73ec237480a3.png)

### Official Information

.

### Modifications that may affect results

.

**Comment by violent01** [comment] 2022-12-01 03:31
Duplicate of #7363

**Comment by violent01** [comment] 2022-12-01 04:03
Check this PR and see if it will fix your issue #7471

**Comment by fab10Carvalho** [comment] 2022-12-01 05:10
@violent01 i try it yet, Still error (i make new database)
![1111z](https://user-images.githubusercontent.com/112716645/204970644-3820e2bb-49a4-4f96-a289-102b9e212d71.png)
![3333z](https://user-images.githubusercontent.com/112716645/204970666-f217a12a-8590-4ae7-a076-c5544987253d.png)
![2222z](https://user-images.githubusercontent.com/112716645/204970675-41d3d40b-a465-4a6e-a670-f83da29f5efd.png)
![444z](https://user-images.githubusercontent.com/112716645/204970680-3125bfd5-332a-4de4-b462-7ebc5213d6f0.png)

**Comment by violent01** [comment] 2022-12-01 05:12
Did you recompile?

**Comment by fab10Carvalho** [comment] 2022-12-01 05:14
yes,

**Comment by zdurexz** [comment] 2022-12-01 05:16
> 

Can you capture collection on character_slots

**Comment by violent01** [comment] 2022-12-01 05:20
![image](https://user-images.githubusercontent.com/30449376/204971768-831dbba9-5ec0-41e4-92b6-c58220973980.png)

Why is it showing MAX_CHARS 21 it should only show 20 if you're on the default settings? Can you revert it back to the default first.

**Comment by fab10Carvalho** [comment] 2022-12-01 05:32
i change only #define VIP_ENABLE on core.hpp

![image](https://user-images.githubusercontent.com/112716645/204972518-85540520-af58-49e1-9bb0-dfa511df6eb2.png)
![image](https://user-images.githubusercontent.com/112716645/204972563-d0708295-fb5e-4816-a674-f937f4095b1d.png)

**Comment by fab10Carvalho** [comment] 2022-12-01 05:50
> > 
> 
> Can you capture collection on character_slots

Sorry, where can i capture collection on character_slots you mean ?

**Comment by Lemongrass3110** [comment] 2022-12-18 02:34
Duplicate of #7363

**Closed by Lemongrass3110** 2022-12-18 02:34 UTC
Labels: type:bug
