### ISSUE TITLE
Random Crash Map Server after Destroyed Instance

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5920] opened 2021-05-04 16:03 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/4a8be872150844e8c1acd2e1024d3f055d5a9fe9

* **Client Date**: 2020-09-02

* **Server Mode**: RE

* **Description of Issue**: 
Crash map server randomly occurs when an instance is destroyed.

  * Result: 
Crash Debug:
```
[Info]: [Instance] Destroyed: Fall of Glast Heim (1314)

Program received signal SIGSEGV, Segmentation fault.
0x00000000005022b4 in map_addblock (bl=bl@entry=0x82ceea0) at map.cpp:405
405			bl->next = mapdata->block[pos];
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6_10.3.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-24.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64 openssl-1.0.1e-58.el6_10.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) 
[K(gdb) 
(gdb) bt full
#0  0x00000000005022b4 in map_addblock (bl=bl@entry=0x82ceea0) at map.cpp:405
        m = 1470
        y = 20
        x = 75
        pos = 89
        bl = 0x82ceea0
#1  0x00000000004b790d in clif_parse_LoadEndAck (fd=8, sd=0x82ceea0)
    at clif.cpp:11149
        guild_notice = false
        mapdata = 0x12158c0 <map+8067360>
#2  0x0000000000481873 in clif_parse (fd=8) at clif.cpp:23014
        cmd = 125
        packet_len = 2
        sd = 0x82ceea0
        pnum = 1
#3  0x000000000040e285 in do_sockets (next=<optimized out>) at socket.cpp:1422
        rfd = {fds_bits = {72338173902618496, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 19980}
        ret = <optimized out>
        i = 8
#4  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:384
No locals.
```

  * Expected Result: 

  * How to Reproduce: 

I don't know how to reproduce it yet. But this is random. Perhaps some specific player's behavior.

  
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2021-05-04 16:23
Duplicate of #4363.

**Closed by aleos89** 2021-05-04 16:23 UTC
Labels: status:duplicate
