### ISSUE TITLE
Empty Bootle New buy and sell price

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3245] opened 2018-06-24 19:23 UTC
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: the price of empty bootle sell(3) and buy(6)
  * Expected Result: the new prices sell(200) buy(400)
  * How to Reproduce: look at npc and sell and buy empty bootle
  * Official Information:https://www.divine-pride.net/database/item/713/
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment] 2018-06-25 02:48
Need to recheck on kRO.

**Comment by Lemongrass3110** [comment] 2018-06-26 22:41
Duplicate of #2770

**Closed by Lemongrass3110** 2018-06-26 22:41 UTC
Labels: status:duplicate
