### ISSUE TITLE
Debug report on SC_DANCING

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#1986] opened 2017-02-28 17:30 UTC
* **rAthena Hash**: 4270ef8
* **Client Date**: 20151104
* **Server Mode**: Pre-Renewal

* **Description of Issue**: 

Got this debug report from terminal:

[Debug]: status_change_end: SC_DANCING is missing skill unit group (val1=65847, val2=4404, val3=0, val4=2000962, timer=1401, tid=1401, char_id=3359, map=new_1-1, x=60, y=110, prev=<none>:0, from=status.c:13278). Please report this! (#3504)
[Debug]: skill_delunitgroup: group is NULL (source=status.c:11811, status_change_end_)! Please report this! (#3504)

**Comment by aleos89** [comment] 2017-02-28 18:11
Can you please explain the situation this came about? What map? PvP? GvG? Any details to help since that's just a small debug and doesn't provide a full description of the case.

**Comment by keitenai** [comment] 2017-02-28 19:00
Yeah, sadly i was not able to get ingame to check it and get more details. I see the message saying "Please report this" and so I did. :)

It is a PK mode server by the way.
According to the debug mes, the map is in @go 15 (new_1-1).

**Comment by Playtester** [comment] 2017-03-01 12:33
I think this has something to do with the messy dissonance code. Never cross songs/dances!

**Comment by Lemongrass3110** [comment] 2018-06-24 23:50
If we do not get any further input on how to reproduce this we are going to close this issue when merging #3247 to master.

**Closed** 2018-06-27 05:37 UTC
Labels: status:unable to reproduce

**Comment by blipblopblip** [comment] 2020-08-03 10:11
I'm still getting this in faadc80

`(08/03/2020 18:08:46) [ Debug ] : status_change_end: SC_DANCING is missing skill unit group (val1=655681, val2=484645, val3=169, val4=0, timer=16308, tid=-1, char_id=158206, map=alde_dun02, x=73, y=234). Please report this!`
`(08/03/2020 18:08:46) [ Debug ] : skill_delunitgroup: group is NULL (source=status.cpp:13226, status_change_end_)! Please report this! (#3504)`

**Comment by M45T3Ryu** [comment] 2020-08-30 13:27
Yeah Im getting the same error

`

- [ Debug ] : status_change_end: SC_DANCING is missing skill unit group (val1=655679, val2=2914, val3=0, val4=0, timer=5037, tid=5037, char_id=150253, map=hugel, x=95, y=146). Please report this!
- [ Debug ] : skill_delunitgroup: group is NULL (source=status.cpp:13233, status_change_end_)! Please report this! (#3504)
- [ Error ] : Skill '65535' is undefined! status.cpp:219::status_skill2sc
- [ Error ] : status_skill2sc: Unsupported skill id 65535
`
