### ISSUE TITLE
SECURE_NPCTIMEOUT bug again.

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#5100] opened 2020-06-14 08:37 UTC
* **rAthena Hash**: 5647c875d62bdf5be5429e43252e27a7c91b047f

* **Client Date**: 20181107

* **Server Mode**: Pre-re / Re

* **Description of Issue**:  i comment out the SECURE_NPCTIMEOUT to disable it but its not working anymore. this bug already reported before and fix but the bug returned.
https://rathena.org/board/tracker/issue-8330-secure-npctimeout-bug-for-those-npc-who-have-no-dialog-window/
  * Result:  you can't move you can't use skill. you will get stock.
  * Expected Result: the SECURE_NPCTIMEOUT should be disable once you comment out.
  * How to Reproduce: comment out SECURE_NPCTIMEOUT and recompile your server. then run the server and login on game. i have my warper npc enabled. when i talk to warper npc and wait for a longer time. the menu will close and you can't move or use skills. but you can warp.
  * Official Information: "in the normal way. the dialog windows of the npc will appear the close button when you idle for a very long time while talking to the npc."

* **Modifications that may affect results**:

**Comment by bgamez23** [comment] 2020-06-14 11:58
i think the bug is also related here. but this issue is already morethan 3yrs ago and still open.
https://github.com/rathena/rathena/issues/2177

**Comment by aleos89** [comment] 2020-06-14 12:15
I think this was discussed about using a NPC with no dialogue window (through npctalk or something else) but has a menu for selection and waiting too long.

**Comment by shatowolf** [comment] 2020-07-11 07:39
i can confirm this.

**Comment by aleos89** [comment] 2020-07-30 19:24
I'll close this as a duplicate of #2177. There's a possible fix in #5260.

**Closed by aleos89** 2020-07-30 19:24 UTC
Labels: status:duplicate

**Comment by bgamez23** [comment] 2020-08-02 08:12
the bug still exist specially if you have script like OnPCLoginEvent. even you disabled the #define SECURE_NPCTIMEOUT it still close the menu option.

**Comment by NeySKie** [comment] 2023-02-03 09:07
still no fix for #5260 im using 2019 trunk i already try this one https://github.com/Minara2020/rathena/commit/2e88b27b9b63db9a78cc94e7f4970d4afe60aec7

**Comment by bgamez23** [comment] 2023-02-03 13:26
> still no fix for #5260 im using 2019 trunk i already try this one [Minara2020@2e88b27](https://github.com/Minara2020/rathena/commit/2e88b27b9b63db9a78cc94e7f4970d4afe60aec7)

this issue is closed. try to post it here https://github.com/rathena/rathena/issues/2177
