### ISSUE TITLE
Soul Reaper spirit ball should not be reset when player reconnect

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#5032] opened 2020-05-31 19:51 UTC
* **rAthena Hash**: 2c1477d4c

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Soul Reaper spirit ball shouldn't be removed when the character log out
  * Expected Result: When Soul Reaper log out with spirit ball left, the spirit should be kept when the character login
  * How to Reproduce: Collect some spirit ball, logout, then log back in
  * Official Information: -

* **Modifications that may affect results**: -

**Comment by qwerty7vp** [comment] 2020-06-02 01:37
Is that a normal behavior of the skill ?
where/which server you're using as reference ?

**Comment by laziem** [comment] 2020-06-02 08:52
Yes... I should put the link above 🙏🏻

http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7076&curpage=1

**Comment by Lemongrass3110** [comment] 2020-06-02 17:58
This link only states that it was changed on Sakray.
So we still need to confirm it, but probably a valid issue.

I will leave the google translation here just in case:
```
특정 지역으로 이동 시, 재접속 시 영혼 에너지가 초기화되지 않도록 변경됩니다.

When moving to a specific area, the soul energy is not reset when reconnecting.
```

**Comment by LordWhiplash** [comment] 2020-06-02 21:43
This is actually already applied on official server, good quality of life changes for Soul Reapers, thanks for relating.

Official Information: http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7081&curpage=10

**Comment by Rytech2** [comment] 2020-06-04 07:18
> I will leave the google translation here just in case:
> 
> ```
> 특정 지역으로 이동 시, 재접속 시 영혼 에너지가 초기화되지 않도록 변경됩니다.
> 
> When moving to a specific area, the soul energy is not reset when reconnecting.
> ```

Sounds like its talking about how soul spheres were sometimes lost when crossing into another map. A thing that tends to be a issue with new status's or other special things sometimes due to how one server's load is divided by multiple map server's in official. Also the translations has that "When moving to a specific area" part which makes this more clear.

**Comment by aleos89** [comment] 2020-06-11 19:07
Confirmed that the souls to persist after relog.

**Comment by Rytech2** [comment] 2020-06-12 03:49
Seriously??? Well damn it looks like those new gravity dev's are more talented then I thought. Now if they can correct the rest of the sphere systems to do the same that would be great. Heck should rA support saving all sphere types on logout or give a config option for that?

**Comment by aleos89** [comment] 2020-06-12 14:55
We could add a config option. I could try testing other various spheres and see if they persist now too, but they may not have changed those older sphere types.

**Closed** 2020-06-29 17:49 UTC
Labels: component:skill, mode:renewal, priority:low, status:confirmed, type:bug
