### ISSUE TITLE
Clan System crashing on PRE-RE 

### ISSUE THREAD

**Issue by M45T3Ryu** [rathena/rathena#5376] opened 2020-09-04 15:28 UTC
* **rAthena Hash**: 36c629e
 

* **Client Date**:  2020-03-04 RagexeRE 

* **Server Mode**:  PRE-RENEWAL

* **Description of Issue**: 
  * Result: No warnings, just crashes when leaving a clan
  * Expected Result: Not crashing?
  * How to Reproduce: I haven't reproduced this but It apparently happens when you leave your clan somehow, I got a picture of the problem right here.
 

* Picture of the problem: 
![118801357_1356796781177132_8631858363599084194_n](https://user-images.githubusercontent.com/2993425/92256316-6ecb4680-ee88-11ea-9655-fc0c8ab278e0.png)

* **Modifications that may affect results**: 
  No source modifications, just Gepard 3.0

**Comment by blipblopblip** [comment] 2020-09-05 17:10
Hi, your crash report seems incomplete. Reproduce the crash and type `bt full` in GDB.

**Comment by Balferian** [comment] 2020-09-06 17:18
same problem
![image](https://user-images.githubusercontent.com/16213511/92331251-1a89b780-f07e-11ea-80eb-934842779afa.png)

**Comment by admkakaroto** [comment] 2020-09-09 12:05
maybe, some problem? https://github.com/rathena/rathena/issues/5390

**Comment by Balferian** [comment] 2020-09-09 13:14
I think it maybe happen when server kick inactive chars from clan after 14 days. (clan_remove_inactive_days)
When I try to reproduce it and left from clan by myself server don`t crashed.

**Comment by M45T3Ryu** [comment] 2020-09-11 12:50
> maybe, some problem? #5390

Yeah, same problem.

Players are abusing this to respawn MVP's and reset timers on some stuff, its apparently confirmed now by 3 people

**Comment by admkakaroto** [comment] 2020-09-12 15:40
@M45T3Ryu any solution man?

**Comment by Balferian** [comment] 2020-09-12 16:27
@admkakaroto you can disable clans for a time while this crash will be fixed.
Kick players from clans: **UPDATE `char` SET `clan_id` = 0;**
and disbable clan npc **npc/re/other/clans.txt**.

**Comment by reunite-ro** [comment] 2020-09-13 19:56
I have a few crashing issues a few times daily.

I think related to this issue.

**Comment by Badarosk0** [comment] 2020-09-20 09:28
I can confirm this crash. I ended up creating another issue and found this one. Would this be only in PRE or RE? I use RE and this crash also occurs with me.
https://github.com/rathena/rathena/issues/5407

Does this PR solve the problem?
https://github.com/rathena/rathena/pull/5204/files

**Comment by mazvi** [comment] 2021-04-06 16:54
Also crash on Renewal #5828

**Comment by mazvi** [comment] 2021-04-06 21:56
> @admkakaroto you can disable clans for a time while this crash will be fixed.
> Kick players from clans:
> ![image](https://user-images.githubusercontent.com/16213511/93000031-3c77b400-f52e-11ea-84a5-8c01653858ca.png)
> and disbable clan npc **npc/re/other/clans.txt**.

How about end all SC_CLAN? Because if only removed from clan the SC_CLAN still active

**Closed** 2022-09-11 18:49 UTC
Labels: status:confirmed, component:core, priority:medium, mode:renewal, mode:prerenewal, type:bug
