### ISSUE TITLE
MySQL Error 1071 : Specified key was too long; max length is 1000 bytes

### ISSUE THREAD

**Issue by tpw1314** [rathena/rathena#3093] opened 2018-04-29 07:17 UTC
* **rAthena Hash**: f9e9741d88be3be41ef765f55c200863852a807f

* **Client Date**: N/A

* **Server Mode**: N/A

* **Description of Issue**: N/A
  * Result:  MySQL Error 1071 : Specified key was too long; max key length is 1000 bytes
  * Expected Result:  N/A
  * How to Reproduce:  Create new schema, execute main.sql, hit this error when executing ipbanlist creation of table
  * Official Information: N/A
  

* **Modifications that may affect results**: None

**Comment by Rolfxx** [comment] 2018-05-01 09:51
i had this issue when configuring my test server (for windows) and it was fix by chaging the database type to Standalone MySQL Server instead of InnoDB type db

which is weird because google suggests the opposite 

i think this is just bad MySQL configs, similar issues happen when you try to configure the password

i use heidisql for management

**Comment by aleos89** [comment] 2018-05-01 13:53
InnoDB has a limit of 767 while MyISAM is 1000. The RO servers should be using MyISAM as InnoDB doesn't fit the nature of how we use SQL.

The labels I made above were for us to go back and adjust the sizes of several tables. `ipbanlist` being one since we are storing IPs in `varchar(255)` which is way too large.

**Comment by tpw1314** [comment] 2018-06-09 10:35
Just bumping this so that people will notice this thread.

**Comment by daninfuchs** [comment] 2019-07-06 01:24
Okay - found this, ran into it today trying to deploy a test server for a project we're working on. Cool, good to know, but I have been left with a few questions.

Is this a critical error?

Will this cause server failure or unexpected behavior?

Is this safe to ignore?

Is there a workaround to deploy a test server without the error; ie "just use MySQL vFoo.Bar instead" or something?

IE; I have this error but obviously people are still using the server, so I don't know what to do next. (Might want to include the answer in the wiki Installation text(s) since it seems to be a known issue, just a thought.)

**Comment by CairoLee** [comment] 2019-07-29 02:51
As a temporary solution, use utf8 encoding instead of utf8mb4. 

In the long run, the primary key of the ipbanlist table should not use a varchar type field.

**Comment by CairoLee** [comment] 2019-07-29 02:59
Because in the extreme case utf8mb4 encodes a varchar that takes 4 bytes, 256 varchars take up 1024 bytes, exceeding the 1000 limit.

In utf8 encoding, a varchar only takes 3 bytes in the extreme case, and 256 varchar only needs 768 bytes, so there is no limit beyond MySql.

**Comment by tpw1314** [comment] 2019-07-31 12:29
My solution back then was to use utf8, which is not suggested for long term. After that whenever you backup or restore on another server you would have to do the same.

**Comment by daninfuchs** [comment] 2019-08-14 07:19
It's nice to hear that there's a..."solution" for "not the long term" for now.. Next, can we assume not everyone here understands where to "use utf8" and not "utf8mb4"? I'm positive I can click around enough to break something, and pretty sure I'll figure it out eventually, but a concise "edit X line Y of main.sql" -- I dunno if anyone here has actually tried learning SQL solo with Google before, but it's a FSCKING NIGHTMARE and I'd like to be sure I did it right.

**Comment by secretdataz** [comment] 2019-08-14 13:58
Fixed in 8431410

**Closed by secretdataz** 2019-08-14 13:58 UTC
Labels: component:core, mode:prerenewal, mode:renewal, priority:low, status:confirmed, type:maintenance
