### ISSUE TITLE
Old Glast Heim : Mobs & Commander did not spawn

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#3281] opened 2018-07-04 00:00 UTC
* **rAthena Hash**: 67139f590

* **Client Date**: 2017

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 1st Commander on left room sometimes not spawn, 2nd Commander on right room spawn to quick, mobs small ammount
  * Expected Result: 1st & 2nd Commander spawn & more mobs?
  * How to Reproduce: Sometimes happen when do the instances
  * Official Information: -

* **Modifications that may affect results**: -

1. On 1st Commander room (left room), after killing all mobs, the mobs not re-spawn again. So no "Evil forces are appearing in this area" announce and no 1st commander spawn.
2. On 2nd Commander room (right room), only takes small amount of killing then the "An evil presence has teleported in this area" announce, then the 2nd spawn.
3. And on left room, mobs is very limited compared to the right room. On left room only spawn bunch of mobs on specific area.
4. One "Strange crack" that drop some treasure when clicked at the far right missing (1@gl_k,171,136)

**Comment by Lemongrass3110** [comment] 2018-07-04 04:58
Duplicate of #2861?

**Comment by Atemo** [comment] 2018-07-04 14:06
1. Duplicate of https://github.com/rathena/rathena/issues/2861 like Lemon said

2. The spawn rate of the two commanders are currently the same, 1/50. The rates are customs, datas gathered from playing on official servers. You're free to change them as you like - or to share yours datas if you play on official !

3. So far the mobs only spawn on specific area on official servers at this location.

4. There is no npc at theses coordinates on official.

**Closed by Atemo** 2018-07-04 14:06 UTC
