### ISSUE TITLE
About autobonus trigger

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#3229] opened 2018-06-20 07:37 UTC
* **rAthena Hash**: 5e9a23d

* **Client Date**: Unimportant.

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
If item_db Script have two autobonus in an item,your character can't trigger two autobonus together.
 
  * Expected Result:  
  * How to Reproduce: 
Ex. 29318,레이싱(미케닉)3Lv,레이싱(미케닉)3Lv,6,20,,10,,,,,,,,,,,,,{ autobonus3 "{ bonus bCritical,20; bonus bCritAtkRate,10; }",1000,60000,"BS_ADRENALINE"; autobonus "{ bonus2 bAddSize,Size_All,20; }",20,10000,BF_WEAPON; },{},{}
  * Official Information: https://www.divine-pride.net/database/item/29318/3lv 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2018-06-27 21:34
Duplicate of #2079

**Closed by Lemongrass3110** 2018-06-27 21:34 UTC
Labels: status:duplicate
