### ISSUE TITLE
Hair Styling / Styling Shop

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3915] opened 2019-02-03 11:03 UTC
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**:  It is lacking in Alberta, Lighthanlzen, Juno/Yuno, Rachel
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2019-02-03 11:06
Duplicate of #3037

**Closed by Lemongrass3110** 2019-02-03 11:06 UTC
