### ISSUE TITLE
Guild member disconnected when meet guild leader

### ISSUE THREAD

**Issue by Styx1592** [rathena/rathena#8676] opened 2024-09-23 13:47 UTC
### rAthena Hash

0eef678a3

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

1.when guild member meet the guild leader make random guild member disconnected .not all disconnect same time but random 1 - 3 member will disconnected.and i got this in console..
![WhatsApp Image 2024-09-23 at 19 09 01](https://github.com/user-attachments/assets/654a88bb-2380-4c69-b93f-1714c4e820f9)

#ifndef CLIF_PACKETDB_HPP
#define CLIF_PACKETDB_HPP

	#define packet(cmd,length) packetdb_addpacket(cmd,length,NULL,0)
	#define parseable_packet(cmd,length,func,...) packetdb_addpacket(cmd,length,func,__VA_ARGS__,0)

	packet(0x0064,55);
	packet(0x0065,17);
	packet(0x0066,6);
	packet(0x0067,37);
	packet(0x0068,46);
	packet(0x0069,-1);
	packet(0x006a,23);
	packet(0x006b,-1);
	packet(0x006c,3);
	packet(0x006d,108);
	packet(0x006e,3);
	packet(0x006f,2);
	packet(0x0070,6);
	packet(0x0071,28);
	parseable_packet(0x0072,19,clif_parse_WantToConnection,2,6,10,14,18);
	packet(0x0073,11);
	packet(0x0074,3);
	packet(0x0075,-1);
	packet(0x0076,9);
	packet(0x0077,5);
	packet(0x0078,54);
	packet(0x0079,53);
	packet(0x007a,58);
	packet(0x007b,60);
	packet(0x007c,41);
	parseable_packet(0x007d,2,clif_parse_LoadEndAck,0);
	parseable_packet(0x007e,6,clif_parse_TickSend,2);
	packet(0x007f,6);
	packet(0x0080,7);
	packet(0x0081,3);
	packet(0x0082,2);
	packet(0x0083,2);
	packet(0x0084,2);
	parseable_packet(0x0085,5,clif_parse_WalkToXY,2);
	packet(0x0086,16);
	packet(0x0087,12);
	packet(0x0088,10);
	parseable_packet(0x0089,7,clif_parse_ActionRequest,2,6);
	packet(0x008a,29);
	packet(0x008b,2);
	parseable_packet(0x008c,-1,clif_parse_GlobalMessage,2,4);
	packet(0x008d,-1);
	packet(0x008e,-1);
	//packet(0x008f,-1);
	parseable_packet(0x0090,7,clif_parse_NpcClicked,2,6);
	packet(0x0091,22);
	packet(0x0092,28);
	packet(0x0093,2);
	parseable_packet(0x0094,6,clif_parse_GetCharNameRequest,2);
	parseable_packet(0x0096,-1,clif_parse_WisMessage,2,4,28);
	packet(0x0097,-1);
	packet(0x0098,3);
	parseable_packet(0x0099,-1,clif_parse_Broadcast,2,4);
	packet(0x009a,-1);
	parseable_packet(0x009b,5,clif_parse_ChangeDir,2,4);
	packet(0x009c,9);
	packet( HEADER_ZC_ITEM_ENTRY, sizeof( struct PACKET_ZC_ITEM_ENTRY ) );
	packet(0x009e,17);
	parseable_packet(0x009f,6,clif_parse_TakeItem,2);
	packet(0x00a1,6);
	parseable_packet(0x00a2,6,clif_parse_DropItem,2,4);
	packet( inventorylistnormalType, -1 );
	packet( inventorylistequipType, -1 );
	packet( storageListNormalType, -1 );
	packet( storageListEquipType, -1 );
	parseable_packet(0x00a7,8,clif_parse_UseItem,2,4);
	packet( useItemAckType, sizeof( struct PACKET_ZC_USE_ITEM_ACK ) );
	parseable_packet(0x00a9,6,clif_parse_EquipItem,2,4);
	parseable_packet(0x00ab,4,clif_parse_UnequipItem,2);
	packet(0x00ac,7);
	//packet(0x00ad,-1);
	packet(0x00ae,-1);
	packet(0x00af,6);
	packet(0x00b0,8);
	packet(0x00b1,8);
	parseable_packet(0x00b2,3,clif_parse_Restart,2);
	packet(0x00b3,3);
	packet(0x00b6,6);
	packet(0x00b7,-1);
	parseable_packet(0x00b8,7,clif_parse_NpcSelectMenu,2,6);
	parseable_packet(0x00b9,6,clif_parse_NpcNextClicked,2);
	packet(0x00ba,2);
	parseable_packet(0x00bb,5,clif_parse_StatusUp,2,4);
	packet(0x00bc,6);
	packet(0x00bd,44);
	packet(0x00be,5);
	parseable_packet(0x00bf,3,clif_parse_Emotion,2);
	packet(0x00c0,7);
	parseable_packet(0x00c1,2,clif_parse_HowManyConnections,0);
	packet(0x00c2,6);
	packet(0x00c3,8);
	packet(0x00c4,6);
	parseable_packet(0x00c5,7,clif_parse_NpcBuySellSelected,2,6);
	packet(0x00c6,-1);
	packet(0x00c7,-1);
	parseable_packet(0x00c8,-1,clif_parse_NpcBuyListSend,2,4);
	parseable_packet(HEADER_CZ_PC_SELL_ITEMLIST,-1,clif_parse_NpcSellListSend,2,4);
	packet(0x00ca,3);
	packet(0x00cb,3);
	parseable_packet(0x00cc,6,clif_parse_GMKick,2);
	packet(0x00cd,3);
	parseable_packet(0x00ce,2,clif_parse_GMKickAll,0);
	parseable_packet(0x00cf,27,clif_parse_PMIgnore,2,26);
	parseable_packet(0x00d0,3,clif_parse_PMIgnoreAll,2);
	packet(0x00d1,4);
	packet(0x00d2,4);
	parseable_packet(0x00d3,2,clif_parse_PMIgnoreList,0);
	packet(0x00d4,-1);
	parseable_packet(0x00d5,-1,clif_parse_CreateChatRoom,2,4,6,7,15);
	packet(0x00d6,3);
	packet(0x00d7,-1);
	packet(0x00d8,6);
	parseable_packet(0x00d9,14,clif_parse_ChatAddMember,2,6);
	packet(0x00da,3);
	packet(0x00db,-1);
	packet(0x00dc,28);
	packet(0x00dd,29);
	parseable_packet(0x00de,-1,clif_parse_ChatRoomStatusChange,2,4,6,7,15);
	packet(0x00df,-1);
	parseable_packet(0x00e0,30,clif_parse_ChangeChatOwner,2,6);
	packet(0x00e1,30);
	parseable_packet(0x00e2,26,clif_parse_KickFromChat,2);
	parseable_packet(0x00e3,2,clif_parse_ChatLeave,0);
	parseable_packet(0x00e4,6,clif_parse_TradeRequest,2);
	packet(0x00e5,26);
	parseable_packet(0x00e6,3,clif_parse_TradeAck,2);
	packet(0x00e7,3);
	parseable_packet(0x00e8,8,clif_parse_TradeAddItem,2,4);
	packet(0x00ea,5);
	parseable_packet(0x00eb,2,clif_parse_TradeOk,0);
	packet(0x00ec,3);
	parseable_packet(0x00ed,2,clif_parse_TradeCancel,0);
	packet(0x00ee,2);
	parseable_packet(0x00ef,2,clif_parse_TradeCommit,0);
	packet(0x00f0,3);
	packet(0x00f1,2);
	packet(0x00f2,6);
	parseable_packet(0x00f3,8,clif_parse_MoveToKafra,2,4);
	parseable_packet(0x00f5,8,clif_parse_MoveFromKafra,2,4);
	packet(0x00f6,8);
	parseable_packet(0x00f7,2,clif_parse_CloseKafra,0);
	packet(0x00f8,2);
	parseable_packet(0x00f9,26,clif_parse_CreateParty,2);
	packet(0x00fb,-1);
	parseable_packet(0x00fc,6,clif_parse_PartyInvite,2);
	packet(0x00fd,27);
	parseable_packet(0x00ff,10,clif_parse_ReplyPartyInvite,2,6);
	parseable_packet(0x0100,2,clif_parse_LeaveParty,0);
	packet(0x0101,6);
	parseable_packet(0x0102,6,clif_parse_PartyChangeOption,2);
	parseable_packet(0x0103,30,clif_parse_RemovePartyMember,2,6);
	packet(0x0104,79);
	parseable_packet(0x0108,-1,clif_parse_PartyMessage,2,4);
	packet(0x0109,-1);
	packet( HEADER_ZC_MVP_GETTING_ITEM, sizeof( struct PACKET_ZC_MVP_GETTING_ITEM ) );
	packet(0x010b,6);
	packet(0x010c,6);
	packet(0x010d,2);
	packet(0x010e,11);
	packet(0x010f,-1);
	packet( HEADER_ZC_ACK_TOUSESKILL, sizeof( PACKET_ZC_ACK_TOUSESKILL ) );
	packet(0x0111,39);
	parseable_packet(0x0112,4,clif_parse_SkillUp,2);
	parseable_packet(0x0113,10,clif_parse_UseSkillToId,2,4,6);
	packet(0x0114,31);
	packet(0x0115,35);
	parseable_packet(0x0116,10,clif_parse_UseSkillToPos,2,4,6,8);
	packet(0x0117,18);
	parseable_packet(0x0118,2,clif_parse_StopAttack,0);
	packet(0x0119,13);
	packet(0x011a,15);
	parseable_packet(0x011b,20,clif_parse_UseSkillMap,2,4);
	packet(0x011c,68);
	parseable_packet(0x011d,2,clif_parse_RequestMemo,0);
	packet(0x011e,3);
	packet(0x011f,16);
	packet(0x0120,6);
	packet(0x0121,14);
	packet( cartlistequipType, -1 );
	packet( cartlistnormalType, -1 );
	packet(0x0125,8);
	parseable_packet( HEADER_CZ_MOVE_ITEM_FROM_BODY_TO_CART, sizeof( PACKET_CZ_MOVE_ITEM_FROM_BODY_TO_CART ), clif_parse_PutItemToCart, 0 );
	parseable_packet(0x0127,8,clif_parse_GetItemFromCart,2,4);
	parseable_packet(0x0128,8,clif_parse_MoveFromKafraToCart,2,4);
	parseable_packet(0x0129,8,clif_parse_MoveToKafraFromCart,2,4);
	parseable_packet(0x012a,2,clif_parse_RemoveOption,0);
	packet(0x012b,2);
	packet(0x012c,3);
	packet(0x012d,4);
	parseable_packet(0x012e,2,clif_parse_CloseVending,0);
	parseable_packet(0x012f,-1,clif_parse_OpenVending,2,4,0,84);
	parseable_packet(0x0130,6,clif_parse_VendingListReq,2);
	packet(0x0132,6);
	parseable_packet( HEADER_CZ_PC_PURCHASE_ITEMLIST_FROMMC, -1, clif_parse_PurchaseReq, 0 );
	packet(0x0135,7);
	packet(0x0137,6);
	packet(0x0138,3);
	packet(0x0139,16);
	packet(0x013a,4);
	packet(0x013b,4);
	packet(0x013c,4);
	packet(0x013d,6);
	packet(0x013e,24);
	parseable_packet(0x013f,26,clif_parse_GM_Item_Monster,2);
	parseable_packet(0x0140,22,clif_parse_MapMove,2,18,20);
	packet(0x0141,14);
	packet(0x0142,6);
	parseable_packet(0x0143,10,clif_parse_NpcAmountInput,2,6);
	packet(0x0144,23);
	packet(0x0145,19);
	parseable_packet(0x0146,6,clif_parse_NpcCloseClicked,2);
	packet(0x0147,39);
	packet(0x0148,8);
	parseable_packet(0x0149,9,clif_parse_GMReqNoChat,2,6,7);
	packet(0x014a,6);
	packet(0x014b,27);
	packet(0x014c,-1);
	parseable_packet(0x014d,2,clif_parse_GuildCheckMaster,0);
	packet(0x014e,6);
	parseable_packet(0x014f,6,clif_parse_GuildRequestInfo,2);
	packet(0x0150,110);
	parseable_packet(0x0151,6,clif_parse_GuildRequestEmblem,2);
	packet(0x0152,-1);
	parseable_packet(0x0153,-1,clif_parse_GuildChangeEmblem,2,4);
	packet(0x0154,-1);
	parseable_packet( HEADER_CZ_REQ_CHANGE_MEMBERPOS, -1, clif_parse_GuildChangeMemberPosition, 0 );
	packet(0x0156,-1);
	packet(0x0157,6);
	packet(0x0158,-1);
	parseable_packet(0x0159,54,clif_parse_GuildLeave,2,6,10,14);
	packet(0x015a,66);
	parseable_packet(0x015b,54,clif_parse_GuildExpulsion,2,6,10,14);
	packet(0x015c,90);
	parseable_packet(0x015d,42,clif_parse_GuildBreak,2);
	packet(0x015e,6);
	packet(0x015f,42);
	packet(0x0160,-1);
	parseable_packet(0x0161,-1,clif_parse_GuildChangePositionInfo,2,4);
	packet(0x0162,-1);
	packet(0x0163,-1);
	packet(0x0164,-1);
	parseable_packet(0x0165,30,clif_parse_CreateGuild,2,6);
	packet(0x0166,-1);
	packet(0x0167,3);
	parseable_packet(0x0168,14,clif_parse_GuildInvite,2,6,10);
	packet(0x0169,3);
	packet(0x016a,30);
	parseable_packet(0x016b,10,clif_parse_GuildReplyInvite,2,6);
	packet(0x016c,43);
	packet(0x016d,14);
	parseable_packet(0x016e,186,clif_parse_GuildChangeNotice,2,6,66);
	packet(0x016f,182);
	parseable_packet(0x0170,14,clif_parse_GuildRequestAlliance,2,6,10);
	packet(0x0171,30);
	parseable_packet(0x0172,10,clif_parse_GuildReplyAlliance,2,6);
	packet(0x0173,3);
	packet(0x0174,-1);
	packet(0x0175,6);
	packet(0x0176,106);
	packet(0x0177,-1);
	parseable_packet(0x0178,4,clif_parse_ItemIdentify,2);
	packet(0x0179,5);
	parseable_packet(0x017a,4,clif_parse_UseCard,2);
	packet(0x017b,-1);
	parseable_packet(0x017c,6,clif_parse_InsertCard,2,4);
	packet(0x017d,7);
	parseable_packet(0x017e,-1,clif_parse_GuildMessage,2,4);
	packet(0x017f,-1);
	parseable_packet(0x0180,6,clif_parse_GuildOpposition,2);
	packet(0x0181,3);
	packet(0x0182,106);
	parseable_packet(0x0183,10,clif_parse_GuildDelAlliance,2,6);
	packet(0x0184,10);
	packet(0x0185,34);
	//packet(0x0186,-1);
	packet(0x0187,6);
	packet(0x0188,8);
	packet(0x0189,4);
	parseable_packet(0x018a,4,clif_parse_QuitGame,2);
	packet(0x018b,4);
	packet(0x018c,29);
	packet(0x018d,-1);
	parseable_packet( HEADER_CZ_REQMAKINGITEM, sizeof( struct PACKET_CZ_REQMAKINGITEM ), clif_parse_ProduceMix, 0 );
	packet( HEADER_ZC_ACK_REQMAKINGITEM, sizeof( PACKET_ZC_ACK_REQMAKINGITEM ) );
	parseable_packet(0x0190,90,clif_parse_UseSkillToPosMoreInfo,2,4,6,8,10);
	packet( HEADER_ZC_TALKBOX_CHATCONTENTS, sizeof( struct PACKET_ZC_TALKBOX_CHATCONTENTS ) );
	packet(0x0192,24);
	parseable_packet(0x0193,6,clif_parse_SolveCharName,2);
	packet(0x0194,30);
	packet( HEADER_ZC_ACK_REQNAMEALL, sizeof( struct PACKET_ZC_ACK_REQNAMEALL ) );
	packet(0x0196,9);
	parseable_packet(0x0197,4,clif_parse_ResetChar,2);
	parseable_packet(0x0198,8,clif_parse_GMChangeMapType,2,4,6);
	packet(0x0199,4);
	packet(0x019a,14);
	packet(0x019b,10);
	parseable_packet(0x019c,-1,clif_parse_LocalBroadcast,2,4);
	parseable_packet(0x019d,6,clif_parse_GMHide,2);
	packet(0x019e,2);
	parseable_packet(0x019f,6,clif_parse_CatchPet,2);
	packet(0x01a0,3);
	parseable_packet(0x01a1,3,clif_parse_PetMenu,2);
	packet(0x01a2,35);
	packet(0x01a3,5);
	packet(0x01a4,11);
	parseable_packet(0x01a5,26,clif_parse_ChangePetName,2);
	packet(0x01a6,-1);
	parseable_packet(0x01a7,4,clif_parse_SelectEgg,2);
	packet(0x01a8,4);
	parseable_packet(0x01a9,6,clif_parse_SendEmotion,2);
	packet(0x01aa,10);
	packet(0x01ab,12);
	packet(0x01ac,6);
	packet(0x01ad,-1);
	parseable_packet( HEADER_CZ_REQ_MAKINGARROW, sizeof( PACKET_CZ_REQ_MAKINGARROW ), clif_parse_SelectArrow, 0 );
	parseable_packet(0x01af,4,clif_parse_ChangeCart,2);
	packet(0x01b0,11);
	packet(0x01b1,7);
	parseable_packet(0x01b2,-1,clif_parse_OpenVending,2,4,84,85);
	packet(0x01b3,67);
	packet(0x01b4,12);
	packet(0x01b5,18);
	packet(0x01b6,114);
	packet(0x01b7,6);
	packet(0x01b8,3);
	packet(0x01b9,6);
	parseable_packet(0x01ba,26,clif_parse_GMShift,2);
	parseable_packet(0x01bb,26,clif_parse_GMShift,2);
	parseable_packet(0x01bc,26,clif_parse_GMRecall,2);
	parseable_packet(0x01bd,26,clif_parse_GMRecall,2);
	packet(0x01be,2);
	packet(0x01bf,3);
	packet(0x01c0,2);
	packet(0x01c1,14);
	packet(0x01c2,10);
	packet(0x01c3,-1);
	packet(0x01c6,4);
	packet(0x01c7,2);
	packet(0x01c9,97);
	//packet(0x01ca,-1);
	packet(0x01cb,9);
	packet(0x01cc,9);
	packet(0x01cd,30);
	parseable_packet(0x01ce,6,clif_parse_AutoSpell,2);
	packet(0x01cf,28);
	packet(0x01d0,8);
	packet(0x01d1,14);
	packet(0x01d2,10);
	packet(0x01d4,6);
	parseable_packet(0x01d5,-1,clif_parse_NpcStringInput,2,4,8);
	packet(0x01d6,4);
	packet(0x01d7,11);
	packet(0x01d8,54);
	packet(0x01d9,53);
	packet(0x01da,60);
	packet(0x01db,2);
	packet(0x01dc,-1);
	packet(0x01dd,47);
	packet(0x01de,33);
	parseable_packet(0x01df,6,clif_parse_GMReqAccountName,2);
	packet(0x01e0,30);
	packet(0x01e1,8);
	packet(0x01e2,34);
	packet(0x01e3,14);
	packet(0x01e4,2);
	packet(0x01e5,6);
	packet(0x01e6,26);
	parseable_packet(0x01e7,2,clif_parse_NoviceDoriDori,0);
	parseable_packet(0x01e8,28,clif_parse_CreateParty2,2,26,27);
	packet(0x01ea,6);
	packet(0x01eb,10);
	packet(0x01ec,26);
	parseable_packet(0x01ed,2,clif_parse_NoviceExplosionSpirits,0);
	packet(0x01f0,-1);
	packet(0x01f1,-1);
	packet(0x01f2,20);
	packet(0x01f3,10);
	packet(0x01f4,32);
	packet(0x01f5,9);
	packet(0x01f6,34);
	parseable_packet(0x01f7,14,clif_parse_Adopt_reply,2,6,10);
	packet(0x01f8,2);
	parseable_packet(0x01f9,6,clif_parse_Adopt_request,2);
	packet(0x01fa,48);
	packet(0x01fb,56);
	packet(0x01fc,-1);
	parseable_packet( HEADER_CZ_REQ_ITEMREPAIR1, sizeof( struct PACKET_CZ_REQ_ITEMREPAIR1 ), clif_parse_RepairItem, 0 );
	packet(0x01fe,5);
	packet(0x01ff,10);
	packet(0x0200,26);
	packet(0x0201,-1);
	parseable_packet(0x0202,26,clif_parse_FriendsListAdd,2);
	parseable_packet(0x0203,10,clif_parse_FriendsListRemove,2,6);
	packet(0x0204,18);
	packet(0x0205,26);
	packet(0x0206,11);
	packet(0x0207,34);
	parseable_packet(0x0208,11,clif_parse_FriendsListReply,2,6,10);
	packet(0x0209,36);
	packet(0x020a,10);
	//packet(0x020b,-1);
	//packet(0x020c,-1);
	packet(0x020d,-1);
	packet(0x8b3,-1);

clif_pharse:receive unsupported packet (packet 0x0bb0)

### Expected Result

how to fix it make no more disconnected random guild member..

### How to Reproduce

.

### Official Information

.

**Comment by Beginerxxxxx** [comment] 2024-09-23 16:06
I have reported the problem before.
But there are idiots who keep deleting my posts and banning my ID.
Nowadays, I have encountered many problems in the game, but I can't report them because that idiot is jealous of my skill. He always bans my ID.

You guys have used good things because I am one of the people who reported the problem. And it is a real problem as I reported.

That idiot doesn't know that
I am a person who can test the server very well. Because I let people play the real server. There are people who really test playing in many things. Therefore, I found more problems than people who play alone.

But that idiot is jealous of me and always bans my ID. I feel sorry that I have encountered problems but can't report them. Many of my players have tested and reported my problems. Therefore, no one can find problems as well as me. Because there are many real players.

![Screenshot 2024-09-13 151919](https://github.com/user-attachments/assets/297626d1-7cc2-4816-b871-fc15916454c3)

**Comment by Styx1592** [comment] 2024-09-24 00:58
> I have reported the problem before. But there are idiots who keep deleting my posts and banning my ID. Nowadays, I have encountered many problems in the game, but I can't report them because that idiot is jealous of my skill. He always bans my ID.
> 
> You guys have used good things because I am one of the people who reported the problem. And it is a real problem as I reported.
> 
> That idiot doesn't know that I am a person who can test the server very well. Because I let people play the real server. There are people who really test playing in many things. Therefore, I found more problems than people who play alone.
> 
> But that idiot is jealous of me and always bans my ID. I feel sorry that I have encountered problems but can't report them. Many of my players have tested and reported my problems. Therefore, no one can find problems as well as me. Because there are many real players.
> 
> ![Screenshot 2024-09-13 151919](https://private-user-images.githubusercontent.com/182538630/369956192-297626d1-7cc2-4816-b871-fc15916454c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzk2NjAsIm5iZiI6MTcyNzEzOTM2MCwicGF0aCI6Ii8xODI1Mzg2MzAvMzY5OTU2MTkyLTI5NzYyNmQxLTdjYzItNDgxNi1iODcxLWZjMTU5MTY0NTRjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQwMDU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmM5MDc4NjQ0MjE4NDYxNDUxNDA5ZGJjNTQ0NjZiYzA0MDM5NGY2NzU0NTYxYjBhMzA3YjA4NzdhZjljOGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VndwzqYEd_pT8kYC0iaqlZ7waqRnPyiVnrdUFYzjT8Q)

oh wow ..why ?
and how to fixed ?

**Comment by Beginerxxxxx** [comment] 2024-09-25 11:06
When I report a problem, they often accuse me of having problems with my files.
From now on, I will use all files from Master so that I don't have to make excuses.

Look at this 
1- download from master
https://github.com/rathena/rathena

2- Compile
3- Run server
4- Run client from last update Kro

Guild Bug!!
https://youtu.be/gTCuNiNu5qo

**Comment by thanna** [comment] 2024-09-25 16:58
> When I report a problem, they often accuse me of having problems with my files. From now on, I will use all files from Master so that I don't have to make excuses.
> 
> Look at this 1- download from master https://github.com/rathena/rathena
> 
> 2- Compile 3- Run server 4- Run client from last update Kro
> 
> Guild Bug!! https://youtu.be/-Xvn3Cg_LSQ

if ever you encounter a problem, having a fresh copy of rathena would be a good choice to reproduce such error if you know how to reproduce it.

**Comment by Beginerxxxxx** [comment] 2024-09-26 04:35
> > When I report a problem, they often accuse me of having problems with my files. From now on, I will use all files from Master so that I don't have to make excuses.
> > Look at this 1- download from master https://github.com/rathena/rathena
> > 2- Compile 3- Run server 4- Run client from last update Kro
> > Guild Bug!! https://youtu.be/-Xvn3Cg_LSQ
> 
> if ever you encounter a problem, having a fresh copy of rathena would be a good choice to reproduce such error if you know how to reproduce it.

Repeat!!
Used Last Update From Master!!!

Look at this
1- download from master
https://github.com/rathena/rathena

2- Compile
3- Run server
4- Run client from last update Kro

Look at this!!
Guild Bug!!
https://youtu.be/-Xvn3Cg_LSQ

**Comment by thanna** [comment] 2024-09-26 04:44
> > > When I report a problem, they often accuse me of having problems with my files. From now on, I will use all files from Master so that I don't have to make excuses.
> > > Look at this 1- download from master https://github.com/rathena/rathena
> > > 2- Compile 3- Run server 4- Run client from last update Kro
> > > Guild Bug!! https://youtu.be/-Xvn3Cg_LSQ
> > 
> > 
> > if ever you encounter a problem, having a fresh copy of rathena would be a good choice to reproduce such error if you know how to reproduce it.
> 
> Repeat!! Used Last Update From Master!!!
> 
> Look at this 1- download from master https://github.com/rathena/rathena
> 
> 2- Compile 3- Run server 4- Run client from last update Kro
> 
> Look at this!! Guild Bug!! https://youtu.be/-Xvn3Cg_LSQ

Tried to reproduce your error on my emulator and I am unable to reproduce it. can I know the date of your client?

**Comment by Beginerxxxxx** [comment] 2024-09-28 08:54
Exe
2021-11-03
2023-09-06

If guild member alt+a if show guild name it will disconnect when walk pass guild master.
If guild member alt+a if guild name not show can walk pass guild master.

![Screenshot 2024-09-28 154737](https://github.com/user-attachments/assets/68600d16-cf66-419e-9fb1-4f215a3c6520)

**Comment by Aristeus09** [comment] 2024-09-29 05:58
i tried to reproduce this in my local server

and what happen is when you changed your client.exe version into latest one without updating the PACKETVER in src/config/packet.hpp the unsupported packet will happen and it will disconnect you. make sure everytime that you change client.exe version it is match in your PACKETVER in your src/config/packet.hpp

**Comment by Beginerxxxxx** [comment] 2024-09-29 13:52
> ### rAthena Hash
> 0eef678a3
> 
> ### Client Date
> 2021-11-03
> 
> ### Server Mode
> Renewal
> 

My exe 2023-09-06 same problem.

**Comment by Styx1592** [comment] 2024-09-29 23:37
Solved

Open clif_packetdb.hpp
and put

parseable_packet (0x014d, 2, clif_parse_GuildCheckMaster,0);
parseable_packet(0x0bb0,9, clif_parse_GuildCheckMaster,0);


#solved by abodi

**Comment by Beginerxxxxx** [comment] 2024-09-30 06:23
Solved.
Thank you.
Styx1592
abodi

**Comment by reunite-ro** [comment] 2024-09-30 10:08
Why did u close this then, is it still happen in latest rathena or not ?

**Comment by Beginerxxxxx** [comment] 2024-09-30 10:12
> Why did u close this then, is it still happen in latest rathena or not ?

I think this needs to be added to the master to fix the problem.

```
Open clif_packetdb.hpp
and put

parseable_packet (0x014d, 2, clif_parse_GuildCheckMaster,0);
parseable_packet(0x0bb0,9, clif_parse_GuildCheckMaster,0);
```

**Comment by Toshiro90** [comment] 2024-10-14 20:00
@Styx1592 Is 2021-11-03 really your client version or your defined `PACKETVER`? The mentioned packet `0x0BB0` didn't exist until a few months later.

**Comment by Toshiro90** [comment] 2024-10-14 20:27
> > > When I report a problem, they often accuse me of having problems with my files. From now on, I will use all files from Master so that I don't have to make excuses.
> > > Look at this 1- download from master https://github.com/rathena/rathena
> > > 2- Compile 3- Run server 4- Run client from last update Kro
> > > Guild Bug!! https://youtu.be/-Xvn3Cg_LSQ
> > 
> > 
> > if ever you encounter a problem, having a fresh copy of rathena would be a good choice to reproduce such error if you know how to reproduce it.
> 
> Repeat!! Used Last Update From Master!!!
> 
> Look at this 1- download from master https://github.com/rathena/rathena
> 
> 2- Compile 3- Run server 4- Run client from last update Kro
> 
> Look at this!! Guild Bug!! https://youtu.be/-Xvn3Cg_LSQ

You're using the default `PACKETVER` (20211103) instead of the one matching your client version, which is definitely newer.
![grafik](https://github.com/user-attachments/assets/b6812d4a-861d-4092-994c-44e9fd2dec78)



> My exe 2023-09-06 same problem.
> 
> #ifndef PACKETVER
> **/// Do NOT edit this line! To set your client version, please do this instead:**
> **/// In Windows: Add this line in your src\custom\defines_pre.hpp file: #define PACKETVER YYYYMMDD**
> /// In Linux: The same as above or run the following command: ./configure --enable-packetver=YYYYMMDD
> #define PACKETVER 20230906
> #endif

Is there also a PACKETVER define in src\custom\defines_pre.hpp that might override this (you shouldn't edit the line in packets.hpp anyways)? Check the map server output (as shown in the screenshot of your previous video) for the effective PACKETVER.

**Comment by Lemongrass3110** [comment] 2024-12-21 15:50
You claim to use client 2021-11-03, but you receive a packet which was added in 2022?
SUS.

**Closed by Lemongrass3110** 2024-12-21 15:50 UTC
Labels: status:invalid

**Comment by Fuckit-ra** [comment] 2025-03-19 07:19
> I have reported the problem before. But there are idiots who keep deleting my posts and banning my ID. Nowadays, I have encountered many problems in the game, but I can't report them because that idiot is jealous of my skill. He always bans my ID.
> 
> You guys have used good things because I am one of the people who reported the problem. And it is a real problem as I reported.
> 
> That idiot doesn't know that I am a person who can test the server very well. Because I let people play the real server. There are people who really test playing in many things. Therefore, I found more problems than people who play alone.
> 
> But that idiot is jealous of me and always bans my ID. I feel sorry that I have encountered problems but can't report them. Many of my players have tested and reported my problems. Therefore, no one can find problems as well as me. Because there are many real players.
> 
> ![Screenshot 2024-09-13 151919](https://github.com/user-attachments/assets/297626d1-7cc2-4816-b871-fc15916454c3)


Yes, I have sent the problem to ask many times and reported the problem I found because I have thousands of customers playing. It will make the system check find many parts.

When I sent the question, it blocked my ID. Sometimes it told me to ask somewhere else. This is not the place to answer questions.

Those who are admins of https://github.com/rathena are all idiots. No one is reasonable. They are all power-hungry. I am good. I am right in everything.

Even though I sent the problem to ask if you can check if you found this problem.

I did not come to ask how to fix it. I came to report the problem for inspection. If the problem was not found, it might be my problem. But I sent the problem to ask if this is a problem.

But there was an admin who blocked me and told me to go ask somewhere else. I did not ask for the solution. I came to report if this is a problem.

At https://github.com/rathena, there are only idiots and power-hungry. I said I would help donate every month and dozens of my friends wanted to support the donation.
But when I met the wicked administrator of https://github.com/rathena like this, we stopped supporting.
