### ISSUE TITLE
Warning when compiling (CentOS 7)

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#7467] opened 2022-11-30 05:00 UTC
### rAthena Hash

795414d

### Client Date

20211103

### Server Mode

Renewal

### Result

I guess nothing serious with the warning. after the compilation server still works fine and running smoothly.

### Relevant Log Output

```Shell
CXX     npc.cpp (custom rule)
npc.cpp: In function ‘int npc_dynamicnpc_removal_timer(int, t_tick, int, intptr_t)’:
npc.cpp:5783:166: warning: passing NULL to non-pointer argument 4 of ‘int add_timer(t_tick, TimerFunc, int, intptr_t)’ [-Wconversion-null]
  nd->dynamicnpc.removal_tid = add_timer( nd->dynamicnpc.last_interaction + battle_config.feature_dynamicnpc_timeout, npc_dynamicnpc_removal_timer, nd->bl.id, NULL );
                                                                                                                                                                    ^
npc.cpp:5789:181: warning: passing NULL to non-pointer argument 4 of ‘int add_timer(t_tick, TimerFunc, int, intptr_t)’ [-Wconversion-null]
 .removal_tid = add_timer( nd->dynamicnpc.last_interaction + DIFF_TICK( gettick(), nd->dynamicnpc.last_interaction ), npc_dynamicnpc_removal_timer, nd->bl.id, NULL );
                                                                                                                                                                    ^
npc.cpp: In function ‘npc_data* npc_duplicate_npc_for_player(npc_data&, map_session_data&)’:
npc.cpp:5839:167: warning: passing NULL to non-pointer argument 4 of ‘int add_timer(t_tick, TimerFunc, int, intptr_t)’ [-Wconversion-null]
 d->dynamicnpc.removal_tid = add_timer( dnd->dynamicnpc.last_interaction + battle_config.feature_dynamicnpc_timeout, npc_dynamicnpc_removal_timer, dnd->bl.id, NULL );
                                                                                                                                                                    ^
        CXX     party.cpp
```

### Expected Result

no warning messages when/after compiling.

### How to Reproduce

1. make sure youre using centos 7
2. git pull and compile

### Official Information

NA

### Modifications that may affect results

None

**Comment by Lemongrass3110** [comment] 2022-11-30 05:30
Duplicate of #7417

**Closed by Lemongrass3110** 2022-11-30 05:30 UTC
Labels: type:bug

**Comment by shatowolf** [comment] 2023-02-06 06:00
While compiling the  (Below) still....

> npc.cpp (custom rule)
npc.cpp: In function ‘int npc_dynamicnpc_removal_timer(int, t_tick, int, intptr_t)’:
npc.cpp:5783:166: warning: passing NULL to non-pointer argument 4 of ‘int add_timer(t_tick, TimerFunc, int, intptr_t)’ [-Wconversion-null]
  nd->dynamicnpc.removal_tid = add_timer( nd->dynamicnpc.last_interaction + battle_config.feature_dynamicnpc_timeout, npc_dynamicnpc_removal_timer, nd->bl.id, NULL );``
