### ISSUE TITLE
channel commands via script

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1886] opened 2017-01-16 19:27 UTC
Tested on a clean rA Revision: 06c40e6cb412cd02428d4bc326b298849c2058d7

**does not work - nothing happens**
```
prontera,156,182,3	script	Channel Leave#custom	4_M_SURA,{
	atcommand "@channel leave #main";
end;
}
```

**does not work - nothing happens**
```
prontera,158,182,3	script	CharChannel Leave#custom	4_M_SURA,{
	charcommand "#channel "+strcharinfo(0)+" leave #main";
end;
}
```

**works**
```
prontera,159,182,3	script	Channel Join#custom	4_M_SURA,{
	atcommand "@join #main";
end;
}
```

**My suggestion:**
Either give us the chance to use at least the atcommands so we can script something ourselfs.
Or even better, it would be great if the mod from Cydh could find its way into rAthena. Or some parts of it to give us some more freedom.
_As long as @cydh  is ok with it._
https://rathena.org/board/topic/107823-channel-system-expanded/#comment-310706

**Comment by vstumpf** [comment] 2017-01-16 20:04
For the second example (charcommand), when you tested it did you put the space after the character name? In the code posted above there is no space between the name and "leave".

**Comment by Everade** [comment] 2017-01-16 20:11
Thanks for pointing that out.
Just tested again, -> nothing happens.

**Comment by Tokeiburu** [comment] 2017-01-16 22:15
This is because the channel command is has the ATCMD_NOSCRIPT option. Edit your script.c file and change
`ACMD_DEFR(channel,ATCMD_NOSCRIPT),`
to
`ACMD_DEF(channel),`

There must have been a reason for this change, but... I can't think of any.

**Comment by Lemongrass3110** [comment] 2017-01-16 22:20
#1342 
369799a6c5bf6f2c4faccb4741bc81e05129af75
fbf7957d2186bb83cd0d16928f9312422c6e8cf2

**Comment by aleos89** [comment] 2017-01-31 01:10
Closing this as this is working as intended. Cydh's Channel System Expansion is in the works to getting merged into rAthena master.

**Closed by aleos89** 2017-01-31 01:10 UTC
