### ISSUE TITLE
Segmentation Fault on mob.cpp caused by imported mob on mercenary_db

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#2878] opened 2018-02-07 19:37 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/24a9e4c6d2e2c0435619ba2d9de13a28ad008618

* **Client Date**:  2015 11 04

* **Server Mode**: Renewal

* **Description of Issue**: When loading npcs the map-server halts if at least 1 mercenary monster is read from import.
  * Result: When running the map-server, if a custom mercenary monster is read, the map server halts at some point when trying to create a new monster spawn.

On a clean copy it halts at npc/quests/okolnir.txt (only modification done is adding 1 custom mercenary).
![sin titulo](https://user-images.githubusercontent.com/7315177/35935189-7d59aa74-0c1e-11e8-9d4e-6a5b128ca426.png)

gdb bt full
![sin titulo2](https://user-images.githubusercontent.com/7315177/35935370-0947618e-0c1f-11e8-83df-b8c29a59514e.png)

It also halts on a copy with modifications, but at npc/quests/quests_moscovia.txt
![sin titulo3](https://user-images.githubusercontent.com/7315177/35937415-ec08145a-0c24-11e8-8b02-39aa482d5b7b.png)
![sin titulo4](https://user-images.githubusercontent.com/7315177/35937428-f72cfe5e-0c24-11e8-9eb6-72349708d9ea.png)

On the other hand, when loading **without** the custom entry the map-server runs perfectly fine.

  * Expected Result: map-server should run normally without crashing.
  * How to Reproduce: Add a custom mercenary monster on db/import/mercenary_db.txt
  * Official Information: None.

* **Modifications that may affect results**: 
1 custom entry on mercenary_db.txt.
`2937,M_LOKI,Loki,145,1215600,1,2,1835,2279,15,89,76,66,90,55,189,22,10,12,1,7,20,100,76,384,288`

**Comment by Lemongrass3110** [comment] 2018-02-07 21:29
I am unable to reproduce your crash with your given entry.
Are you sure that this is related to this?
Both your crashes are for mob_id 1887 and 1932 - not 2937.

For me it looks like you might be running out of RAM when the vector is trying to allocate more memory.
Correct me if I'm wrong here please @Jeybla

**Comment by Darkelfen** [comment] 2018-02-08 04:40
I feel somewhat dumb, the problem was just that mmo.h MAX_MERCENARY_CLASS is 61, and the number of entries of mercenary_db is precisely 61. 

Weird was that even though maximum allowed number of entries was reached it didn't prompt a warning message until the mob data was inserted directly into db/mercenary_db.txt rather than db/import/mercenary_db.txt

**Comment by Jeybla** [comment] 2018-02-08 23:01
Thanks for the report @Darkelfen. I was able to reproduce the issue on an arch linux (gcc version 7.2.1 20180116). Anyway, the pull request provided by @Lemongrass3110 should fix it.

**Comment by Lemongrass3110** [comment] 2018-02-18 16:15
Fixed in 132feeb

**Closed by Lemongrass3110** 2018-02-18 16:15 UTC
Labels: component:core, mode:prerenewal, mode:renewal, status:confirmed, type:bug
