### ISSUE TITLE
Character move problem

### ISSUE THREAD

**Issue by Desground** [rathena/rathena#372] opened 2015-03-31 17:40 UTC
The character starts to move back if it moves monster and he out radius of the attack.
Sorry for my english.

**Comment by Playtester** [comment] 2015-03-31 20:03
Not sure what you mean with "move back". He moves back to the cell he came from? Or he just moves one cell to the east?

**Comment by Desground** [comment] 2015-03-31 21:00
here's a video http://youtu.be/kk_Q_Y012f8

**Comment by Playtester** [comment] 2015-04-01 09:49
Hmm, interesting, but how are you out of attack range? DS range is larger than your normal attack and you first use DS and then normel attack?

Do you have OFFICIAL_WALKPATH enabled?

**Comment by Desground** [comment] 2015-04-01 10:01
DS range is larger than your normal attack and you first use DS and then normel attack? - Yes
Do you have OFFICIAL_WALKPATH enabled? - happens on both
melee too exposed bug.

**Comment by anacondaqq** [comment] 2015-04-01 10:50
confirm.

**Comment by dragonis1701** [comment] 2015-05-04 19:57
Doesn't that happen with the, recently added as default, mob AI where mobs stop chasing as soon as they lose their target and then start a random walk after X amount of seconds?

**Comment by anacondaqq** [comment] 2015-10-26 07:07
@Playtester after so many monthes, this bug still exist.

# Technical Information
* pre-re / re doesnot matter
* bugs related to all revisions up to (https://github.com/rathena/rathena/commit/ea497b2938e51a526438f78aa6fc4de43af5cc23)
* OFFICIAL_WALKPATH enabled.
* other values at config & settings -> default.

# Extra Useful Information
* When you have between you, and your walking end point some texture & or trap -> your character will not avoid it, and will be stopped at this place.
* The same logic mobs have too.
* The video totally exlain what is going on, and how reproduce this bug.

**Comment by Playtester** [comment] 2015-10-26 14:44
If I remember correctly I couldn't reproduce it. Does the video have audio I need for the explanation? Otherwise a step-by-step guide would be nice so that one of the devs can reproduce it.

**Comment by Desground** [comment] 2015-10-29 04:18
1)Increase Zoom out 75% in Nemo
2)Use double strafe(because it has a higher range than conventional attacks) and Immediately сlick auto attack (Works only when the mob moving and outside the range of attack)
or
1)Need two players one melee another range
2)Range Click on mob after Immediately click melee (Works only when the mob moving)
Sorry for my english

**Comment by Playtester** [comment] 2015-10-30 14:05
Does it only happen with increase zoom mod?

**Comment by Desground** [comment] 2015-10-31 00:33
Does it only happen with increase zoom mod? - not it happen without zoom mod too. For this mob need walk for to you and outside range attack. if only range need more cell from mob. If melee char and range char then range Click on mob after Immediately click melee
And with "click auto attack" you mean Ctrl+Click? no. it's misprint.
Sorry for my english.

**Comment by Playtester** [comment] 2016-01-25 20:50
I really really cannot create this bug...

I got Vulture's Eye Level 5 so my double strafe range is as far as I can see (14 cells). I make it so Bloody Butterfly is at the edge of my visible range. I use Double Strafe on it and then Ctrl+Click. Result: My hunter uses DS then walks 1-3 cells to Bloody Butterfly and then starts auto-attacking.

**Comment by anacondaqq** [comment] 2016-01-25 21:43
Dear @Playtester you done a lot of awesome changes in walking logic, and monster logic.
Let's wait some time, maybe this bug will be available again, but for now i do not have such issues anymore. I think this issue is fixed in one of the commits before.

**Comment by Playtester** [comment] 2016-01-25 22:17
Alright, I'll close this then. Please reopen if the issue occurs again.

**Closed by Playtester** 2016-01-25 22:17 UTC
