### ISSUE TITLE
Debug SC_Dancing 

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#3032] opened 2018-04-04 01:01 UTC
* **rAthena Hash**: 
7113743

* **Client Date**: 
2015-11-04aRagexe.exe

* **Server Mode**: 

Pre-Renewal or Renewal

* **Description of Issue**: 
i got this bug :
[ Debug ] : status_change_end: SC_DANCING is missing skill unit group (val1=655681, val2=3696, val3=15, val4=0, timer=930, tid=-1, char_id=1361, map=moscovia, x=219, y=197, prev=<none>:0, from=pc.cpp:5845). Please report this! (#3504)
[ Debug ] : skill_delunitgroup: group is NULL (source=status.cpp:12062, status_change_end_)! Please report this! (#3504)
[ Debug ] : status_change_end: SC_DANCING is missing skill unit group (val1=655690, val2=619437, val3=5, val4=0, timer=2618, tid=-1, char_id=2287, map=lighthalzen, x=158, y=92, prev=<none>:0, from=unit.cpp:2851). Please report this! (#3504)

**Comment by Lemongrass3110** [comment] 2018-04-04 08:14
Duplicate of #1986

**Closed by Lemongrass3110** 2018-04-04 08:14 UTC
Labels: status:duplicate
