### ISSUE TITLE
Pincode bypass

### ISSUE THREAD

**Issue by mrpond** [rathena/rathena#8310] opened 2024-05-06 03:29 UTC
### rAthena Hash

a44d9540fb28cad1ac3da07f512fece15cbf00d8

### Client Date

20131120

### Server Mode

Pre-Renewal, Renewal

### Result

some malicious player can bypass pin code.

### Relevant Log Output

```Shell
refer to: https://github.com/rathena/rathena/issues/6595
```

### Expected Result

server should prohibit if pin code state invalid

### How to Reproduce

N/A

### Official Information

just use bot or other client(android, web client) to test it

### Modifications that may affect results

Fix
rAthena\src\char\char.hpp
```
struct char_session_data{
...
	pincode_state pincode_step;
}
```
rAthena\src\char\char_clif.cpp
```
void chclif_pincode_sendstate( int fd, struct char_session_data* sd, enum pincode_state state ){

	if (sd->pincode_step != state) {
#ifdef DEBUG
		ShowDebug("account id %d pincode state change from %d to %d\n", sd->account_id, sd->pincode_step, state);
#endif
		sd->pincode_step = state;
	}
...
}
int chclif_parse_reqtoconnect(int fd, struct char_session_data* sd,uint32 ipl){
...
		sd->auth = false; // not authed yet
		sd->pincode_step = PINCODE_ASK;
		// send back account_id
		WFIFOHEAD(fd,4);
...
int chclif_parse_charselect(int fd, struct char_session_data* sd,uint32 ipl){
...
		/* client doesn't let it get to this point if you're banned, so its a forged packet */
		if( sd->found_char[slot] == char_id && sd->unban_time[slot] > time(nullptr) ) {
			chclif_reject(fd, 0); // rejected from server
			return 1;
		}

		if (charserv_config.pincode_config.pincode_force) {
			if (sd->pincode_step != PINCODE_PASSED || sd->pincode_step != PINCODE_OK) {
				chclif_reject(fd, 0); // rejected from server
#ifdef DEBUG
				ShowDebug("account id %d pincode state != PINCODE_PASSED, PINCODE_OK\n", sd->account_id);
#endif
				return 1;
			}
		}
		/* set char as online prior to loading its data so 3rd party applications will realise the sql data is not reliable */
		char_set_char_online(-2,char_id,sd->account_id);
...
```

**Comment by Lemongrass3110** [comment] 2024-05-06 05:38
Duplicate of #6594

**Closed** 2024-05-06 05:38 UTC
Labels: status:duplicate

**Comment by mrpond** [comment] 2024-05-06 07:50
Hi, these aren't relate. this pincode bypass is character select.

**Comment by mrpond** [comment] 2024-05-06 15:47
> Should be #6595 instead.

seem so, hope someone can make pull request. I can't do it.
