### ISSUE TITLE
About skill GN_CARTCANNON problem

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#2818] opened 2018-01-19 10:12 UTC
* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The skill GN_CARTCANNON property will be change by weapon property or Elemental Converter.
  * Expected Result: The skill GN_CARTCANNON should not be change property by weapon property or Elemental Converter.And only can be change by Cannon Ball property.
  * How to Reproduce: Use skill GN_CARTCANNON and change weapon property or using Elemental Converter.
  * Official Information: http://www.inven.co.kr/board/ro/1940/316  (KRO)
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2018-01-19 15:28
Duplicate of #965.

**Closed by aleos89** 2018-01-19 15:28 UTC
Labels: status:duplicate
