### ISSUE TITLE
./configure problem

### ISSUE THREAD

**Issue by Triedge** [rathena/rathena#2153] opened 2017-05-17 14:36 UTC
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: Pre-Renewal

I am installing a new emulator, but when using the latest version of Rathena the following error appears when using ./configure.
![000](https://cloud.githubusercontent.com/assets/5862340/26159423/2a71292e-3ae4-11e7-9c3e-211b742a77c7.png)

This bug does not appear in the rathena version of 2 months ago.

**Comment by anacondaqq** [comment] 2017-05-17 14:47
Read about changes here:
https://rathena.org/board/topic/110898-rathena-now-requires-g-to-compile-on-linux/

Try to fix it with:
> yum install gcc-c++

**Comment by Jeybla** [comment] 2017-05-17 15:38
Duplicate of #2127

**Closed by Jeybla** 2017-05-17 15:38 UTC
