### ISSUE TITLE
Instance with multiple map give map crash with instance_destroy()

### ISSUE THREAD

**Issue by arby89** [rathena/rathena#3387] opened 2018-08-04 17:55 UTC
* **rAthena Hash**: 68fccf447b3c9a2aa90a3de7bdc10856400635bd

* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Instance give map server crash.
if remove instance_destroy() code, it work fine.
also, if instance using single map, also work fine, not giving map server crash.
  * Expected Result:  All char go to save point.
  * How to Reproduce:  I create instance of 3 map, move between map, then use npc with instance_destroy() command.
In my case, one party member at town, one in instance map. 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2018-08-04 18:05
Duplicate of #3386 and several other issues recently reported.

**Closed by aleos89** 2018-08-04 18:05 UTC
Labels: status:duplicate
