### ISSUE TITLE
Mapserver Crash on Horror Toy Factory Instance

### ISSUE THREAD

**Issue by darhylism** [rathena/rathena#3425] opened 2018-08-23 03:24 UTC
* **rAthena Hash**: 3d8104d

* **Client Date**: 2015-11-04

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Mapserver Crashed when 2nd player enters Horror Toy Factory Instance if there is already an active instance from another player. 
  * Expected Result: The 2nd player will be able to enter a new instance and no mapserver crash. 
  * How to Reproduce: Have Player A enter his own instance, afterwards have Player B enter his own instance, as soon as player B tries to enter his own instance the mapserver will crash
  * Official Information: https://irowiki.org/wiki/Horror_Toy_Factory

  

* **Modifications that may affect results**: NONE

**Comment by aleos89** [comment] 2018-08-23 13:43
Would you be able to provide any core dumps from MSVS/GDB? Will help to alleviate this issue we are having. Thanks.

**Comment by Atemo** [comment] 2018-08-23 20:06
Doing a quick test, I can reproduce using MSVS2017, compiled on pre-re mode, hash https://github.com/rathena/rathena/commit/2e133ed07f4ef6ac2ed4b33964caa3b05f8149e0.
No crash following his step when entering on Endless tower instance.
No crash following his step when entering on Horror Toy Factory instance, compiled in renewal mode.

**Comment by tianran0207** [comment] 2018-08-24 14:26
Mapserver Crash 
![9s5 f jd6im d2f _ ept5](https://user-images.githubusercontent.com/7557646/44589999-a2c8f700-a7ec-11e8-901d-3335a742b321.png)

**Comment by tianran0207** [comment] 2018-08-24 14:32
![qq 20180824222856](https://user-images.githubusercontent.com/7557646/44590247-4a462980-a7ed-11e8-90fb-3042fb2f74ac.png)

**Comment by tianran0207** [comment] 2018-08-24 15:41
@aleos89

**Comment by aleos89** [comment] 2018-08-26 20:09
Try #3402.

**Comment by aleos89** [comment] 2018-08-27 22:02
Duplicate of #3402.

**Closed by aleos89** 2018-08-27 22:02 UTC
Labels: status:duplicate
