### ISSUE TITLE
Clone player only take 1 damage

### ISSUE THREAD

**Issue by vietlubu** [rathena/rathena#7974] opened 2023-10-18 11:33 UTC
### rAthena Hash

1d5fdbad8

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

I already rise a same issue: https://github.com/rathena/rathena/issues/7579
Now with latest rathena version this issue is back

Using `clone` function to make a player's clone.
Clone only take 1 damage from player
Clone not using skill

![image](https://github.com/rathena/rathena/assets/9859310/bc22f35b-b438-4836-a31c-8ffa83a970d9)
![image](https://user-images.githubusercontent.com/9859310/216801061-f829e0ab-0c0d-4499-8fd3-7128406f6f69.gif)

### Expected Result

The clone should be have same original character's attributes

### How to Reproduce

Test script. [Thank ](https://github.com/rathena/rathena/issues/7579#issuecomment-1419939213)@Lemongrass3110 
```
prontera,150,150,4	script	Cloner	989,{
	clone "prontera",150,150, "Cloner::OnCloneDie", getcharid(0);
	end;

OnCloneDie:
	end;
}
```

### Official Information

None

**Comment by aleos89** [comment] 2023-10-18 12:19
Check out the fix in #7799.

**Comment by vietlubu** [comment] 2023-10-19 04:01
> Check out the fix in #7799.

Thank @aleos89 , I tested with that PR.
The clone not take 1 damage but seem differences:
- Attack speed higher than player
- Damage lower than player

https://github.com/rathena/rathena/assets/9859310/0613935b-2c3b-4bb0-b53f-cfb766c409a2

**Comment by eppc0330** [comment] 2023-10-21 10:17
![clone](https://github.com/rathena/rathena/assets/47050704/737d8499-245e-4d42-996f-518528a7985c)

@vietlubu I can't target clone monster. Have you seen this? I applied #7799 and still can't target it.

**Comment by vietlubu** [comment] 2023-10-21 13:13
> ![clone](https://user-images.githubusercontent.com/47050704/277102117-737d8499-245e-4d42-996f-518528a7985c.gif) [ ![clone](https://user-images.githubusercontent.com/47050704/277102117-737d8499-245e-4d42-996f-518528a7985c.gif) ](https://user-images.githubusercontent.com/47050704/277102117-737d8499-245e-4d42-996f-518528a7985c.gif) [ ](https://user-images.githubusercontent.com/47050704/277102117-737d8499-245e-4d42-996f-518528a7985c.gif)
> 
> @vietlubu I can't target clone monster in non-pvp map, while clone can hit me. Is this normal?

I'm not sure, but in non-pvp map you can hold shift to attack clone

**Comment by eppc0330** [comment] 2023-10-21 13:28
Clone not using skill will be fixed here #7973

**Comment by vietlubu** [comment] 2023-10-21 13:32
> Thanks. I thought it is something problem. Clone not using skill will be fixed here #7973

Nice, did you see the clone has attack speed higher than player?

**Comment by eppc0330** [comment] 2023-10-21 15:44
@vietlubu Yes I confirmed. I guess it's because difference of aspd formula between PC and MOB?
About clone damage getting weaker, the cause is in source code.

```
	status->rhw.atk2= status->dex + status->rhw.atk + status->rhw.atk2; //Max ATK
	status->rhw.atk = status->dex; //Min ATK
	if (status->lhw.atk) {
		status->lhw.atk2= status->dex + status->lhw.atk + status->lhw.atk2; //Max ATK
		status->lhw.atk = status->dex; //Min ATK
	}
```

**Comment by Kuyaraikub** [comment] 2023-10-23 17:32
https://github.com/rathena/rathena/assets/147054311/d60b5be6-d06c-4d9b-a8a3-800f2ccf8f6f

**Comment by aleos89** [comment] 2023-10-24 19:22
The differences in stats is because of like @eppc0330 stated, clones are calculated as BL_MOB types.

**Closed** 2023-10-25 12:58 UTC
Labels: status:confirmed, component:core, priority:low, mode:renewal, mode:prerenewal, type:bug
