### ISSUE TITLE
Tetra Vortex Black Bug is Back..

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1353] opened 2016-06-10 10:10 UTC
git: 
![screenandzro062](https://cloud.githubusercontent.com/assets/18629476/15961215/258709d4-2f36-11e6-87e6-649147714223.jpg)

screenshot:
![screenandzro058](https://cloud.githubusercontent.com/assets/18629476/15961214/2586db44-2f36-11e6-8bd2-51446b251e98.jpg)

client: 2015-11-04aRagexe.exe

supposed to be fix:
r16856
r17218

can also be fixed via clientside:
[data.zip](https://github.com/rathena/rathena/files/308808/data.zip)

**Comment by secretdataz** [comment] 2016-06-19 12:36
Reproducible via `Release` skill.

**Comment by spinzaku** [comment] 2016-06-19 17:13
/confused
waiting for a server side fix or just fix using clientside files

**Comment by reigneil** [comment] 2016-10-31 05:05
this is not just black image.. but also the performance of the skill.
summon fire ball caused the black image with no damage delay
but using summon stone is not reproducing black image but with damage delay.

since this reported it please close my old report here:
https://rathena.org/board/tracker/issue-8146-tetra-vortex-damage-delay/?gopid=22686#entry22686

**Comment by aleos89** [comment] 2016-11-10 01:35
Do you have the diff from NEMO applied that fixes the skill?

**Comment by reigneil** [comment] 2016-11-10 07:38
even if i apply the diff or not. it will not fix the delay of damage...

**Comment by feltenc** [comment] 2017-04-25 19:43
Confirmed. If you use Tetra vortex with summon balls it show a black effect. tested with fire ball summoned.

2017-01-25ragexeRE
mode renewall
git: https://github.com/rathena/rathena/commit/a040a52764e9f35b3037d2aa8d2d0dc24a05a93a

**Comment by aleos89** [comment] 2017-05-27 13:33
Fixed in 3e625df.

**Closed by aleos89** 2017-05-27 13:33 UTC
Labels: bug:skill, mode:renewal, priority:low, server:map, status:confirmed
