### ISSUE TITLE
'unitwarp' a NPC to a different map and OnTouch stop working

### ISSUE THREAD

**Issue by V0rr** [rathena/rathena#1777] opened 2016-12-08 17:45 UTC
When you use 'unitwarp' on a NPC to a different map, the OnTouch stop working.
I test warp's on the original map that the NPC is configured and it works fine.

Edit:
Hexed: 2015-11-04a
Git: 2016/12/07

**Comment by Stolao** [comment] 2016-12-11 14:16
I can confirm this, but the best work around is to have duplicate NPCs and disable one while enabling the other to give the illusion of warping.

Also moving an NPC doesnt move the OnTouch area at all even if on same map.

**Comment by Weskercorp** [comment] 2016-12-12 16:04
Nice, thank you Stolao

**Comment by Litro** [comment] 2019-03-01 00:37
stumble on this when making event script and because @Stolao work around isn't sitting well with the script

**Comment by Atemo** [comment] 2020-06-22 14:58
Should be fixed by https://github.com/rathena/rathena/commit/3d8c20f6b95cc1dc54aa94508a1863d450a611e7

**Closed by Atemo** 2020-06-22 14:58 UTC
Labels: component:core, status:confirmed
