### ISSUE TITLE
Map_server Crash

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3510] opened 2018-09-19 22:25 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/bfd7af34238f192b1978a9bb812306de6e2d1874
* **Client Date**: 2018-06-05
* **Server Mode**: RE
* **Description of Issue**:
the map-server is crashing, the gdb log is attached.

I know the emulator is a bit outdated and does not have the mapflag update, but it might be a recurring problem.

Anyone who has a fix for this also thank me.

Log:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004c3252 in map_delblock (bl=bl@entry=0x70851d9adddc) at map.cpp:379
379                             map[bl->m].block[pos] = bl->next;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.8.x86_64 libgcc-4.8.5-11.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt full
#0  0x00000000004c3252 in map_delblock (bl=bl@entry=0x70851d9adddc) at map.cpp:379
        pos = <optimized out>
        bl = 0x70851d9adddc
#1  0x0000000000608bbf in unit_remove_map_ (bl=bl@entry=0x70851d9adddc,
    clrtype=clrtype@entry=CLR_TELEPORT, file=file@entry=0x6d4113 "unit.cpp", line=line@entry=1241,
    func=func@entry=0x6d4562 <unit_warp(block_list*, short, short, short, clr_type)::__FUNCTION__> "unit_warp") at unit.cpp:3097
        ud = <optimized out>
        sc = 0x70851d9ae2c4
        __FUNCTION__ = "unit_remove_map_"
#2  0x0000000000609797 in unit_warp (bl=bl@entry=0x70851d9adddc, m=878, x=121, y=91,
    type=type@entry=CLR_TELEPORT) at unit.cpp:1241
        ud = 0x70851d9addfc
        __FUNCTION__ = "unit_warp"
#3  0x0000000000609a0a in unit_teleport_timer (tid=<optimized out>, tick=<optimized out>,
    id=<optimized out>, data=14) at unit.cpp:193
        msd = 0x9d6caa0
        bl = 0x70851d9adddc
#4  0x000000000060ffaa in do_timer (tick=<optimized out>) at timer.c:369
        tid = 5587
        diff = -1
        __FUNCTION__.4296 = "do_timer"
#5  0x00000000004077ac in main (argc=1, argv=0x762a8b2f7c98) at core.cpp:370
        next = <optimized out>
(gdb)
```

**Comment by aleos89** [comment] 2019-07-26 13:08
Are you still experiencing this after updating?

**Comment by admkakaroto** [comment] 2019-07-26 16:03
Oh no, sorry!

**Comment by admkakaroto** [comment] 2019-12-03 19:16
@aleos89 yes, crash using new rA:

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004d0f09 in map_addblock (bl=bl@entry=0x70c9650) at map.cpp:358
358                     bl->next = mapdata->block[pos];
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.6.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.el7_6.x86_64 libcom_err-1.42.9-13.el7.x86_64 libgcc-4.8.5-36.el7_6.2.x86_64 libselinux-2.5-14.1.el7.x86_64 libstdc++-4.8.5-36.el7_6.2.x86_64 mariadb-libs-5.5.60-1.el7_5.x86_64 openssl-libs-1.0.2k-16.el7_6.1.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt full
#0  0x00000000004d0f09 in map_addblock (bl=bl@entry=0x70c9650) at map.cpp:358
        m = 1106
        y = 133
        x = 47
        pos = 325
        bl = 0x70c9650
#1  0x00000000004a3275 in clif_parse_LoadEndAck (fd=<optimized out>, sd=0x70c9650)
    at clif.cpp:10747
        guild_notice = false
        mapdata = 0xf7af30 <map+6025488>
#2  0x000000000046b659 in clif_parse (fd=12) at clif.cpp:22289
        cmd = 125
        packet_len = 2
        sd = 0x70c9650
        pnum = 0
#3  0x000000000063030d in do_sockets (next=<optimized out>) at socket.cpp:1399
        rfd = {fds_bits = {1085440, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 19976}
        ret = 0
        i = 12
#4  0x000000000040764d in main (argc=1, argv=0x7ffd94ad0048) at core.cpp:369
        next = <optimized out>
(gdb)
```

Hash: https://github.com/rathena/rathena/commit/fb6dbc306a0e6eb13e39b594c71f62b4e6bc89b9

**Comment by Lemongrass3110** [comment] 2020-01-03 01:00
@admkakaroto your new crash is a duplicate of #4363

**Closed by Lemongrass3110** 2020-01-03 01:00 UTC
