### ISSUE TITLE
Item 18122 wrong script

### ISSUE THREAD

**Issue by SeravySensei** [rathena/rathena#4159] opened 2019-05-10 23:24 UTC
https://www.divine-pride.net/database/item/18122/gigantic-bow-1
should be bonus bHit,-50; the "-" is missing.

**Comment by aleos89** [comment] 2019-05-13 12:43
Could you try to follow the issue template. It helps with tracking. Thanks.

**Comment by SeravySensei** [comment] 2019-05-13 15:09
Whatever, this really shouldn't be that difficult to fix to be worth that much bureaucracy. I'm not going to start up the game, generate the item and equip it to prove a missing "-" sign is really not there when it's obviously not there (I checked in the latest itemdb file up here on github.) - if you like wasting time on that instead of fixing it in 3 seconds, be my guest. I'll try to restrain myself in the future and not to submit bug reports unless the issue is significant.

**Comment by aleos89** [comment] 2019-05-13 16:53
It's not a bureaucracy thing nor something to deter people from reporting issues. No matter the scope of the issue, it helps to have it fully documented. The template is there, you're just answering a couple questions. You could have just quoted the item_db script and then had the link to Divine-Pride.

**Comment by SeravySensei** [comment] 2019-05-13 18:04
I did almost exactly that though. "bonus bHit,-50; the "-" is missing."  No idea what is the problem with it, or would you prefer the whole line instead of the part that has the problem?
Normally I'd insert a GitHub link to the line but itemdb is too large so Github doesn't provide that option, only the plain text version.
The template only has questions that do not apply.  If I find a bug in the source or script without actually running it through the game, I can't honestly say "this does X but should do Y, my hash is z, I have (no) modificiations". Doing so would imply I actually tested it ingame which I did not so it would be a lie. I can only say "line x in file y has z problem" and that should be enough because anyone can tell what will or will not happen if you add/remove a "-" sign in front of a number. Filling the entire template with "not applicable" works but takes more time without providing more information so it's easier to not use it.
Anyway, good to see you care and will fix this. I'll keep reporting these problems in the future then if I find more.

**Comment by flamefury** [comment] 2019-05-13 22:37
You probably spent more time and effort explaining why you don't wanna use the template which you could've spent just using the template. As aleos89 said, it helps with organization and searching histories, and it's nothing about bureaucracy just to be annoying for people. Plenty of small issues that take 3 seconds to change follow the template.

I mean, this took me all of 5 seconds to write. It's not nearly as big of a deal as you're making.

* **rAthena Hash**: 1db461d79f7513880e67bdc8e12b6d4d7dbf526f
* **Client Date**: Doesn't matter
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: Gigantic Bow [1] is currently adding 50 HIT.
  * Expected Result: Gigantic Bow [1] should be subtracting -50 HIT.
  * How to Reproduce: Equip Gigantic Bow [1], observe HIT change.
  * Official Information: https://www.divine-pride.net/database/item/18122

* **Modifications that may affect results**: None

**Comment by SeravySensei** [comment] 2019-05-14 00:53
That kinda is what's the part impossible to understand for me. If it actually takes 3 seconds as you say why make others do it? Instead of posting "add a space here" or "follow the template" why not just edit the posted issue or pull request yourself if you prefer those changes? Takes even less time and as far as I understand this, people in charge have the ability to do that? Telling someone else to do it just increases the time wasted, and by that I not only mean you're spending your own time and the poster's time both when there is no need to, but also that you have to wait for each other to react, ultimately delaying the fix of the issue by days, weeks, months. This is inefficient. Just one of my pull requests received like 30 comments out of which only two or 3 were meaningful, the rest was about adding spaces and newline characters. If it was my project and I wanted minor changes like that on a report or pull request, I'd definitely do it myself to speed things up.
...but yeah you're right I'm wasting way too much effort on trying to understand this nonsense. I really shouldn't care. Getting lost in unimportant details is one of my weak points, I should put even more effort into not replying where there is no need to. It's not like I haven't added the "-" to my local itemdb, and as you say I probably wasted another 15-30 minutes of my life on typing this reply.

**Comment by flamefury** [comment] 2019-05-14 02:04
You realize all the maintainers are unpaid volunteers? They're already reviewing your issues and code for free, why they heck would you want to also add more work on their shoulders?

If everyone used whatever format they wanted for their issue reports, you realize 3-5 seconds per issue adds up fast for the few active individuals on this project, right? More complicated issues would require more reading, and more effort to fix it to the template.

vs. having those 3-5 seconds split up amongst reporters, which is a lot less time collectively because it's spread across more people.

The only thing that's wasting time is how adamant you are on not adhering to the rules of their free, open source, voluntary project. They give you the template automatically for crying out loud.

**Comment by SeravySensei** [comment] 2019-05-14 03:44
You're saying this as if everyone else was paid for submitting these things and making the project better.
Yes, being the project owner/administrator/whatever comes with additional responsibilities and more work to be done. That's the price of being in a higher position and having more authority. I'm also offering my work for free but if it means additional work I do not care to do comes with it, I rather reconsider and not do anything in the first place because, as you say, we don't get anything for it.
You're looking at this from the wrong premise. It's not them doing a favor to me by looking at my code or issues, it's me doing a favor by sharing what I already fixed/implemented locally. Seriously, if someone is trying to offer you something for free, telling them to "follow rules" will only make them go away. 
(Also, there are what, 5 issues posted a day when it's really busy? So that's a total of less than a minute still... While I see what you mean I don't think it applies... besides if it IS a more complicated issue where the template actually matters, I'm using the template. This wasn't one of them.)
I better hit the unsubscribe button to make sure I don't waste any more time on this.

**Comment by aleos89** [comment] 2019-05-14 12:57
Fixed in 656bcf3.

**Closed by aleos89** 2019-05-14 12:57 UTC
Labels: component:database, mode:renewal, priority:low, status:confirmed, type:bug
