### ISSUE TITLE
Refinement UI - Multiple Bugs

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6103] opened 2021-07-19 13:50 UTC
* **rAthena Hash**: 
4b339f7f6ebb01d50c7b956a8146551ad379b468

* **Client Date**: 
2021-01-07aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
**Problem 1:** 
When refining an item, reaching refinement level 10, and then trying to refine a new item, it will always fail, and display your last gear instead of the new one in the fail process. However ores and Blacksmith's Blessing are still being consumed! **This problems seems to be related to Blacksmith's Blessing usage only.**

https://user-images.githubusercontent.com/12261601/126168331-5fbafa4d-631c-45e4-a716-80379f01e343.mp4
 

**Problem 2:**
When selecting Blacksmith's Blessing, then de-selecting it again. The client will no longer display the important gear loss information regarding the selected Ore. This can be missleading and lead players into gear loss. This is most likely a client-side issue. But i figured maybe also the server needs to update the interface upon de-selection?!

https://user-images.githubusercontent.com/12261601/126168716-b1803ae5-0272-4a9f-8749-2148ee5bb2b4.mp4
 

**Problem 3:**
There are other scenarios in which the gear simply disappears from the UI. Maybe related to Problem 1.

https://user-images.githubusercontent.com/12261601/126168979-4647dbc1-d868-4eec-8e25-5ac5da76ebcd.mp4
 

**Problem 4:**
Not able to process gear, although all requirements are available (also checked zeny).
Because a gear with +8 that's being displayed in the UI, is not actualy existant in my inventory. I only have +7, +9 and +10 in my inventory, as such it cannot be processed. Most likely also connected to Problem 1, as it fall back to the last item state.

https://user-images.githubusercontent.com/12261601/126168716-b1803ae5-0272-4a9f-8749-2148ee5bb2b4.mp4
 
 
 
  * Expected Result:
  **Problem 1:** Do not fall back to last used gear, but preserve currently active data that's being applied to the UI.
  In 

  **Problem 2:** Update interface to display the missing Ore Warnings.

  **Problem 3:** Do not lose gear information but preserve it. Could be connected to Problem 1.

  **Problem 4:** Able to refine gear if all requirements are met.
  

  * How to Reproduce: 
 Videos show the process for reproduction.
 I used item id 28010 for my tests, specifically:
 @item2 28010 5 1 7 0 0 0 0 0

  * Official Information: 
  Unknown

* **Modifications that may affect results**: 
  None

**Comment by Gardosen** [comment] 2021-07-19 18:11
i have tested these issues now and can reproduce them.
i still need to check some more but what i can say so far is that problem #1 is happening when you add the item to the UI via a double click on the item and not via drag and drop.

it looks like the double click is handled client side, but not server side.

**Comment by Lemongrass3110** [comment] 2021-07-19 22:33
Some issues are clientside and can not be resolved by us serverside, the rest has been addressed in #6106

**Closed** 2021-07-22 08:21 UTC
Labels: component:core, mode:prerenewal, mode:renewal, type:bug
