### ISSUE TITLE
Unknown Map Character Selection

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#1145] opened 2016-04-07 05:36 UTC
I noticed that everytime I create my 3rd character and login then relog the map show in character selection is unknown but when i delete 1 of those 3 characters the map shows correct.

I am using pre renewal system with a 2015-05-13 ragexe client my trunk is 2 weeks older.

Any idea why this is happening?

Edit -- I've search on the internet and saw the same problem 
`https://rathena.org/board/tracker/issue-8235-character-selection-map-bug/`

and this one
`https://rathena.org/board/topic/97902-login-interface-unknown-area/`

**Comment by MrAntares** [comment] 2016-04-11 11:15
Sounds client side issue to me, but I'm just guessing :/

**Comment by Playtester** [comment] 2016-04-11 11:24
Sounds familiar, I think I had that issue too, but I don't remember if I ever found out the reason or was able to fix it. Hmm...

**Comment by RadianFord** [comment] 2016-04-11 20:40
It's happening not only on my account but same with other players.

**Comment by reigneil** [comment] 2016-04-16 09:58
i'll quote this maybe someone is interested to close this old report:
https://rathena.org/board/tracker/issue-9367-character-selection-bug/

**Comment by aleos89** [comment] 2016-04-16 13:07
I tested with 2013-08-07 (as to the reports @reigneil linked) and I have 6 characters and all show the map name just fine. I also have 2015-10-29 and the maps show as normal still.

**Comment by RadianFord** [comment] 2016-04-16 13:15
@aleos89 weird. did you try logging in then character select?

**Comment by aleos89** [comment] 2016-04-16 13:21
Correct, I logged in and out, made more characters, it all displayed just fine.

I use the default packet keys. I don't think that has any relation unless the custom packet key diffs interfere with the location of the map name.

**Comment by RadianFord** [comment] 2016-04-16 13:24
In my server packet obfuscation  is enable so the keys im using are custom.

**Comment by reigneil** [comment] 2016-04-16 18:44
this is only happen if you have 3 character created in one account. so more than 3 cannot reproduce it or less than 3 also cannot.
3char = bug
3char < no bug
3char > no bug

am i correct @RadianFord

**Comment by reigneil** [comment] 2016-04-16 19:25
since i have spare time i make screenshot of this bug.
using git: 5731eca3b04e4853fc49393e3d4963ba7f98510a
client: 2015-11-04aRagexe
making 3 character displaying you are in unknown map
![untitled](https://cloud.githubusercontent.com/assets/9740000/14583152/a02929bc-044b-11e6-8886-d2d804673d6f.JPG)
creating another character displaying correct map
![untitled1](https://cloud.githubusercontent.com/assets/9740000/14583154/b099c680-044b-11e6-939e-351fc0727cad.JPG)

**Comment by RadianFord** [comment] 2016-04-17 00:20
@reigneil confirm more than 3 characters works fine. but 3 characters will result the problem

**Comment by aleos89** [comment] 2016-04-30 18:42
I tested with 2015-10-29 and it shows just fine for me still with only 3 characters.
![chars](https://cloud.githubusercontent.com/assets/3521753/14937847/9beb13b0-0ee1-11e6-90a6-8a3451449100.png)

I logged in and out several times and it never showed unknown.

**Comment by aleos89** [comment] 2016-05-12 16:11
I went back and tested with a non-RE client. I forgot I was using RE from my testings with implementing the Summoner class.

I was able to reproduce this though with a non-RE client.

**Comment by RadianFord** [comment] 2016-05-13 00:08
@aleos89 oh so if you use a RE version of client this wont happened? xD anyway thanks for the update

**Comment by RadianFord** [comment] 2017-01-22 09:40
Any news about this?

**Comment by anacondaqq** [comment] 2017-01-22 10:49
pretty annoying bug. Confirm too

**Comment by RadianFord** [comment] 2017-07-29 00:00
Lets just wait till they fix all the main issues for rAthena... It is annoying haha

**Comment by BrOgBr** [comment] 2018-01-14 03:14
I'm having this issue too, it's very annoying, can't fix it... 
With one, two or more than three chars it's working perfectly.

**Only with three chars** the Unknow Area appears, I tried until with six and is working perfectly.

Please help us 🥇

**Comment by kukuasir1** [comment] 2018-03-05 14:03
char_clif.cpp
```
int chclif_parse_req_charlist(int fd, struct char_session_data* sd){
	if( RFIFOREST(fd) < 2 )
		return 0;
	RFIFOSKIP(fd,2);
	//chclif_mmo_send099d(fd,sd); //delete this line will fix this problem
	return 1;
}
```

**Closed** 2018-12-20 16:56 UTC
Labels: component:core, mode:prerenewal, mode:renewal, priority:low, status:confirmed
