### ISSUE TITLE
/battlechat map server crash.

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#5035] opened 2020-06-01 20:06 UTC
* rAthena Hash: https://github.com/rathena/rathena/commit/cd0937c4684304eb375869e2c80664d20750ebeb

* Client Date: 20180621

* Server Mode: Renewal

* Description of Issue: 
When a player quit game, others use /battlechat to send a message, which still causes a crash.

![註解 2020-06-01 175902](https://user-images.githubusercontent.com/54499336/83449564-6aa51c80-a486-11ea-9028-c9181a77d532.png)

**Comment by Daegaladh** [comment] 2020-06-02 14:31
Couldn't reproduce this with your description :/

**Comment by admkakaroto** [comment] 2020-06-02 22:50
> Couldn't reproduce this with your description :/

Me too.

**Comment by voyfmyuh** [comment] 2020-06-03 00:51
When a player is offline during the battle, other players use /battlechat to send a message, which will cause a crash.

**Comment by Daegaladh** [comment] 2020-06-03 00:55
I already tried that but couldn't reproduce your crash, is there anything else to be taken into account? Can you reproduce it every time?

**Comment by admkakaroto** [comment] 2020-06-05 16:25
Have you any custom mod in src?

**Comment by Lemongrass3110** [comment] 2020-06-05 16:37
@voyfmyuh do you use VS 2013?

**Comment by Daegaladh** [comment] 2020-06-05 16:42
We should change that `|| (fd = sd->fd) == 0)` to `<= 0` anyways, just in case somehow the fd is invalid like it's happening to him

**Comment by Lemongrass3110** [comment] 2020-06-05 16:45
This will just give him an error a few lines later somewhere...
Because this is freed memory access obviously.
So it will fix the issue on this line, but create an issue on another one, that we might not be able to detect or fix.

If my assumption is correct, then he is using Visual Studio 2013 and this is caused by it not being compliant somewhere again. This is why #5051exists.

**Comment by voyfmyuh** [comment] 2020-06-06 03:59
> This will just give him an error a few lines later somewhere...
> Because this is freed memory access obviously.
> So it will fix the issue on this line, but create an issue on another one, that we might not be able to detect or fix.
> 
> If my assumption is correct, then he is using Visual Studio 2013 and this is caused by it not being compliant somewhere again. This is why #5051exists.

Thank you for your reply. I am using Visual Studio 2017

**Comment by voyfmyuh** [comment] 2020-06-06 04:01
> I already tried that but couldn't reproduce your crash, is there anything else to be taken into account? Can you reproduce it every time?

thank you for your reply yes

![20200606_115543](https://user-images.githubusercontent.com/54499336/83935572-5e55f200-a7ed-11ea-805a-ebaaf636fb61.gif)

**Comment by voyfmyuh** [comment] 2020-06-06 04:02
> I already tried that but couldn't reproduce your crash, is there anything else to be taken into account? Can you reproduce it every time?

Hello, thanks for your reply

![20200606_115543](https://user-images.githubusercontent.com/54499336/83935599-9c531600-a7ed-11ea-9064-ae11665d73b9.gif)

**Comment by yashimwong** [comment] 2020-06-06 07:38
@voyfmyuh Hi. Best way is to provide us with the crash log. Please try out this guide if you use Visual Studio: https://herc.ws/wiki/MSVC_Crash_Debugging

**Comment by Lemongrass3110** [comment] 2020-08-08 22:11
Has been fixed in f997417

**Closed by Lemongrass3110** 2020-08-08 22:11 UTC
Labels: status:need user input
