### ISSUE TITLE
Soul Reaper Espa Skill soul consumption

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#4794] opened 2020-04-14 05:52 UTC
* **rAthena Hash**: 

55053e0

* **Client Date**: 

2018-09-19

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: Espa consumes soul even if its level 10
  * Expected Result: Espa will not consume soul upon reaching level 10
  * How to Reproduce: 
  * Official Information:kRO
  

* **Modifications that may affect results**: 
  
  none

**Comment by Lemongrass3110** [comment] 2020-04-14 06:40
Duplicate of #4781

**Closed by Lemongrass3110** 2020-04-14 06:40 UTC
