### ISSUE TITLE
Some problem with skill SO_STRIKING and ASPD

### ISSUE THREAD

**Issue by Rayvakarian** [rathena/rathena#6726] opened 2022-03-20 17:01 UTC
* **rAthena Hash**: latest

* **Client Date**: 2021-11-17

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: After I use Striking, my ASPD drops drastically (screenshot number 2), but as soon as I start using some other skill (for example, Lighting Bolt, screenshot number 3), it returns to normal.
I think Striking shouldn't change ASPD

* **Modifications that may affect results**: 
  
  
![image](https://user-images.githubusercontent.com/65616872/159173757-81c8bf95-d483-4f59-bc65-14b499540f8d.png)
![image](https://user-images.githubusercontent.com/65616872/159173770-1946ecc6-17e1-4ed0-9e53-9941cdb331fd.png)
![image](https://user-images.githubusercontent.com/65616872/159173783-b096d630-843d-4792-aac4-360e62b7efe8.png)

**Comment by mazvi** [comment] 2022-03-20 17:49
Same as me check https://github.com/rathena/rathena/issues/6715

**Comment by Rayvakarian** [comment] 2022-03-21 12:01
There is one more problem with Elemental Master's skill "Spell Enchanting". For example, I have S.Matk 37, after I use skill "Spell Enchanting", it's up to 57, but when I cast any other skill, this value return to 37.
I think all this problems (including ASPD, SC_ skills on healer and etc.) are caused by wrong status system. It should be fixed. 
![image](https://user-images.githubusercontent.com/65616872/159256798-3479a5b6-cd2e-4ee6-ad53-e3d99bf9433a.png)
![image](https://user-images.githubusercontent.com/65616872/159256824-0cb1176e-855f-4283-9b01-3c02094dde63.png)

**Comment by aleos89** [comment] 2022-03-22 18:40
Duplicate of #6715.

**Closed by aleos89** 2022-03-22 18:40 UTC
Labels: type:bug
