### ISSUE TITLE
Normal Attack On Ice Wall

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1407] opened 2016-06-30 15:28 UTC
This happens on latest githash. I know it happens on pre-renewal but I'm not sure if it does on renewal. I'm using 2013-08-07 but I don't think the client matters. This happens on both official ice wall and unofficial ice wall. 

When you click to normal attack an ice wall, your character will stop five cells away from the ice wall and will not walk forward to hit it no matter how many times you click it. This happens from all directions. The player has to manually walk up to Ice Wall and get within 2 cells of it to normal attack it or damage it with a melee skill.

**Comment by Playtester** [comment] 2016-07-01 12:23
Yes, attacking objects only works if you are in attack range. Pretty sure that's a client-sided issue.

**Comment by dragonis1701** [comment] 2016-07-01 13:27
Perhaps related to #1402 because it does not do this when I use my old rAthena from 2014.

**Comment by joelolopez** [comment] 2016-08-12 13:16
one more thing about ice wall, if im not mistaken attacking a wizard that is behind the ice wall should not take damage from range attacks, the ice wall should catch all the incoming arrows.. but in our current state arrows can penetrate the ice wall is this normal?

**Comment by Playtester** [comment] 2016-08-12 20:51
Ice wall is not a solid wall, you can shoot through it.

**Comment by aleos89** [comment] 2018-05-22 21:13
Duplicate of #1402.

**Closed by aleos89** 2018-05-22 21:13 UTC
Labels: status:duplicate
