### ISSUE TITLE
switch item no refresh skill tree.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#7255] opened 2022-09-07 15:32 UTC
* **rAthena Hash**: 4a43856
* **Client Date**: 2021-11-16
* **Server Mode**: Pre-renewal
* **Description of Issue**: 

![image](https://user-images.githubusercontent.com/9112684/188918355-b62f2af8-e23a-4263-a130-1b45febe7164.png)

**Comment by admkakaroto** [comment] 2022-09-07 17:09
Why not try this first?
https://github.com/rathena/rathena/pull/6529

**Comment by hnomkeng** [comment] 2022-09-07 17:30
> Why not try this first? #6529
> 
> and why not uses search buttom: #5382

pull can't fix

**Comment by hnomkeng** [comment] 2022-09-07 17:43
ok, fixed.

#5931 + #6529

**Comment by secretdataz** [comment] 2022-09-08 02:54
duplicate of #5382

**Closed by secretdataz** 2022-09-08 02:54 UTC
Labels: status:duplicate, type:bug

**Comment by raphazen** [comment] 2022-11-23 07:58
still error until this time
