### ISSUE TITLE
stuck skills

### ISSUE THREAD

**Issue by JinYuichi** [rathena/rathena#5905] opened 2021-04-28 22:35 UTC
* **rAthena Hash**: 
recently downloaded 2021-04-28

* **Client Date**: 
2020-03-04

* **Server Mode**: 
Pre-Renewall

* **Description of Issue**:  
custom item, which gives you a skill.
The thing is that I put on the item and it gives me the skill.
And when I remove the item, the skill gets stuck, I have to restart, so the skill disappears from my skill branch. 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  
![Screenshot_1](https://user-images.githubusercontent.com/74037616/116481020-07fc0280-a848-11eb-88aa-5e862c646026.png)
![Screenshot_2](https://user-images.githubusercontent.com/74037616/116481028-0a5e5c80-a848-11eb-95b0-1200872d93a5.png)
![Screenshot_3](https://user-images.githubusercontent.com/74037616/116481038-0cc0b680-a848-11eb-8820-95cb69c35e87.png)

  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2021-05-07 19:27
Duplicate of #5382.

**Closed by aleos89** 2021-05-07 19:27 UTC
Labels: status:duplicate
