### ISSUE TITLE
Monster Race console erro

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5188] opened 2020-07-07 02:03 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ff38cf70d2e6c73523f5809cbdc8fc8f71292383

* **Client Date**: 2020-04-01

* **Server Mode**: RE

* **Description of Issue**: 
Monster race script is generating console error . 
https://raw.githubusercontent.com/rathena/rathena/master/npc/other/monster_race.txt

Error:
```
[Error]: script:op_2: invalid data for operator C_ADD
[Debug]: Data: string value="1"
[Debug]: Data: string value="st"
[Debug]: Source (NPC): Runner No. 1#1 at p_track01 (30,38)
[Error]: script:op_2: invalid data for operator C_ADD
[Debug]: Data: string value="2"
[Debug]: Data: string value="nd"
[Debug]: Source (NPC): Runner No. 2#2 at p_track01 (30,36)
[Error]: script:op_2: invalid data for operator C_ADD
[Debug]: Data: string value="3"
[Debug]: Data: string value="rd"
[Debug]: Source (NPC): Runner No. 3#3 at p_track01 (30,34)
[Error]: script:op_2: invalid data for operator C_ADD
[Debug]: Data: string value="4"
[Debug]: Data: string value="th"
[Debug]: Source (NPC): Runner No. 4#4 at p_track01 (30,32)
[Error]: script:op_2: invalid data for operator C_ADD
[Debug]: Data: string value="5"
[Debug]: Data: string value="th"
[Debug]: Source (NPC): Runner No. 5#5 at p_track01 (30,30)
[Error]: script:op_2: invalid data for operator C_ADD
[Debug]: Data: string value="6"
[Debug]: Data: string value="th"
[Debug]: Source (NPC): Runner No. 6#6 at p_track01 (30,28)
```

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment] 2020-07-08 10:22
Cannot reproduce this and the debug you provide makes no sense, the script is correct.
Do you have any modifications on your server?

**Comment by Lemongrass3110** [comment] 2020-07-11 09:53
> 
> 
> Cannot reproduce this and the debug you provide makes no sense, the script is correct.
> Do you have any modifications on your server?

@Daegaladh this debug is generated by our script engine - it is not his fault.

Basically it is triggered by line 215 in npc/other/monster_race.txt:
`monster "p_track01",58,.@y,"The "+ callfunc("F_GetNumSuffix",.@n) +" Racer",.@mob[.@n],1,strnpcinfo(0)+"::OnMyMobDead";`

Or to be more precise from the function F_GetNumSuffix defined in npc/other/Global_Functions.txt

But to be honest this looks like you have a problem with your script engine. Because adding strings to each other is supported and even both of your variables are reported as string variable types. So I do not see why it would have not entered this condition  in script.cpp::op_2
`if( data_isstring(left) && data_isstring(right) )`

Please check your code for modifications and if this problem persists, feel free to post it here again. But for now I will close this.

**Closed by Lemongrass3110** 2020-07-11 09:53 UTC
Labels: status:unable to reproduce
