### ISSUE TITLE
Rebellion skill Binding trap does 1 damage when using  Flicker

### ISSUE THREAD

**Issue by shushusao** [rathena/rathena#1449] opened 2016-07-25 20:08 UTC
I think the title pretty much explains it. I'm using rAthena latest version. 

Steps to reproduce: Use binding trap, someone else steps on it, use Flicker and it does 1 HP damage. Also it slows down the caster (but i don't know if this is the correct behavior or not) and it seems like you can't cast on the same cell of someone else or yourself.

**Comment by cydh** [comment] 2016-08-03 00:41
Misplaced since ce090ce916e567444f223894d47ecd3a39dd77ef

**Comment by feltenc** [comment] 2017-04-25 19:26
I can confirm, but it was fixed on the new PR of rebellion. Thanks @cydh

**Comment by Akkarinage** [comment] 2017-04-25 19:47
@feltenc do you mean #1692 ?

**Closed** 2017-10-12 15:04 UTC
Labels: component:skill, mode:prerenewal, mode:renewal, priority:low
