### ISSUE TITLE
Spiral Pierce / Clashing spiral new formula

### ISSUE THREAD

**Issue by poporing** [rathena/rathena#5252] opened 2020-07-27 13:24 UTC
* **rAthena Hash**: 

* **Client Date**:  2018-09-19

* **Server Mode**: renewal

* **Description of Issue**: 
The update of the skill https://github.com/rathena/rathena/commit/ea8da71cdda5cddbc05cdc736683487e5c14bf08 is not complete, there is a missing part of the new formula.
iro just update spiral pierce to the new kro formula https://irowiki.org/wiki/Clashing_Spiral
Damage formula changed.
Old: (1 + (skill_lvl × 0.5)) × (floor((ATK + Weight) × 0.7) + masteryATK)
New: [(floor(statusATK x 0.9) + floor((ATK + Weight) x 0.7) + masteryATK) x floor(Base_Damage) x (BaseLvl / 100)]

* **Modifications that may affect results**: 
no modification

**Comment by qwerty7vp** [comment] 2020-07-27 13:32
you shouldn't use iRO as reference since rA follow kRO

btw according to:
https://www.divine-pride.net/forum/index.php?/topic/3453-kro-mass-skills-balance-1st-2nd-and-transcendent-classes-skills/

![image](https://user-images.githubusercontent.com/64515036/88547534-18c4e100-d048-11ea-87f0-77d63da31db2.png)

![image](https://user-images.githubusercontent.com/64515036/88547546-1d899500-d048-11ea-80fe-f9682c0db034.png)

so I think rA's formula is same as kRO already

**Comment by poporing** [comment] 2020-07-27 14:40
For information the information from the divine pride is not complete. Kro didn't put all the information on their patch note and this is not new.
iRo dosen't have source of Aegis and need to ask Gravity Korea to send already compile server. Generaly the skills are working like kro.
From what I know the only src difference is the ASPD part, and the version.

**Comment by aleos89** [comment] 2020-07-29 19:43
Duplicate of #3503.

**Closed by aleos89** 2020-07-29 19:43 UTC
