### ISSUE TITLE
typos in daily quests from phantasmagorika

### ISSUE THREAD

**Issue by Rolfxx** [rathena/rathena#3018] opened 2018-03-30 21:22 UTC
* **rAthena Hash**: c5ceda03f

* **Client Date**: 20160203

* **Server Mode**:  Renewal

* **Description of Issue**: typos in daily quests from phantasmagorika

* Result: there a few issues with npc dialogs in npc/re/quests/quests_15_1.txt  daily quests from phantasmagorika

  * with npc Commander Louis#atnd07 dialogs line 968, 979, 996, 1001, 1010 are not closing
  *  with npc Commander Arquien#e152v0 dialogs line 1185, 1200, 1207, 1237, 1249, 1263, 1276, 1282, 1325 are not closing the cutin
  *  with npc Box#e152p00 is not counting memory records as proper line 3430
  * in police officers from 	_//- Police Quests_ if you take the main quest from kesler, and then refuse to help police officers, then you go back to kesler and he doesnt let you finish the quest (not sure maybe quests 5310, 5311, 5312 and 5313 are not given properly)
  *  with npc from police quest Thicket#EP15_1D_01 has incorrect behaviour with progressbar when looking for herbs, line 4868

* Expected Result: quest should work fine
* How to Reproduce: making the daily quests from phantasmagorika
* Official Information: none

**Comment by Atemo** [comment] 2018-04-01 16:06
>with npc Commander Louis#atnd07 dialogs line 968, 979, 996, 1001, 1010 are not closing

The dialog is closed https://github.com/rathena/rathena/blob/master/npc/re/quests/quests_15_1.txt#L1012 and I can't reproduce this one.

>in police officers from //- Police Quests if you take the main quest from kesler, and then refuse to help police officers, then you go back to kesler and he doesnt let you finish the quest (not sure maybe quests 5310, 5311, 5312 and 5313 are not given properly)

I don't know if it's intended. Officially if you choose `"I have a more pressing matter at hand."` menu from Gerev request the quest is only reseted.Then the player must to re-talk to Gerev and refuse the quest.

**Comment by Rolfxx** [comment] 2018-04-01 18:33
for Police Quests, i will take Officer Gerev as example

kesler checks if 5311 is different from 0 to give reward
https://github.com/rathena/rathena/blob/333f0dddc8353663eacba0423751988c9bc38e34/npc/re/quests/quests_15_1.txt#L3943

if you say yes here to officer gerev

https://github.com/rathena/rathena/blob/333f0dddc8353663eacba0423751988c9bc38e34/npc/re/quests/quests_15_1.txt#L4326

then say yes here

https://github.com/rathena/rathena/blob/333f0dddc8353663eacba0423751988c9bc38e34/npc/re/quests/quests_15_1.txt#L4356

he gives his quest normally

https://github.com/rathena/rathena/blob/333f0dddc8353663eacba0423751988c9bc38e34/npc/re/quests/quests_15_1.txt#L4367

but the main quest (kesler request) has oportunity to refuse the quest from officers, so this behaviour will be:
return to kesler and only get the exp reward for meeting them and NOT completing any quest from them

now, if you refuse gerev quest here (after taking it), in other words, click this "i have a more pressing matter..."

https://github.com/rathena/rathena/blob/333f0dddc8353663eacba0423751988c9bc38e34/npc/re/quests/quests_15_1.txt#L4427

he NEVER gives 5311 but now you have 5306 completed

https://github.com/rathena/rathena/blob/333f0dddc8353663eacba0423751988c9bc38e34/npc/re/quests/quests_15_1.txt#L4430

so you cant remake the quest because of this

https://github.com/rathena/rathena/blob/333f0dddc8353663eacba0423751988c9bc38e34/npc/re/quests/quests_15_1.txt#L4304

so the quest stuck, you cant complete it with kesler because you dont have 5311 and you can re take it because you have 5306 completed
(sorry for spam i explain myself really bad XD)


about Commander Louis#atnd07 i will re check it, is not closing for me maybe my bad (not using fresh rA)

thank you for your work!

**Comment by Atemo** [comment] 2018-04-08 16:39
I couldn't reproduce the Gerev bug. However Gerev quest will now be marked as completed when the player refuse the quest, for script consistancy.

**Closed by Atemo** 2018-04-08 16:39 UTC
Labels: component:script, status:confirmed
