### ISSUE TITLE
Mobs doesnt despawn when killed with cart revolution

### ISSUE THREAD

**Issue by randell1993** [rathena/rathena#5599] opened 2020-12-04 01:45 UTC
* **rAthena Hash**: 

* **2020092b**: 

* **Renewal**: 

* **Description of Issue**: 
  * Result: Mobs when getting pushed back while dying e.g Cart revolution pushback, Overbrand push back, will walk towards the player character with 0 hp and unkillable. It seems like when the mob ai was trying to go back to its target since it was push back and died somewhere along that time the mob still walks without HP towards the player. Items were dropped but mobs doesnt enter death animation and gets stuck there for a long while.  Mobs tested were: Merman, Swordfish can't seem to reproduce in phens and marcs.

  * Expected Result: mobs die with death animation
  * How to Reproduce: Use skill that has push back e.g cart revolution and overbrand, I tried Jupitel and can't reproduce it there 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2020-12-04 02:33
Duplicate of #5064.

**Closed by aleos89** 2020-12-04 02:33 UTC
Labels: type:bug
