### ISSUE TITLE
Map Server crash when guild storage log was more then 360

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#5115] opened 2020-06-17 00:58 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/3598c7419135a0dca53729cfaccfeb0a3c340dc2

* **Client Date**: 2020

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Map Server crash when guild storage log was more then 360
  * Expected Result: 
  * How to Reproduce: 
1. store item more then 360 into guild storage (I store item id : 1203)
2. open guild storage log
3. map crash
[Error]: _mmalloc: 4294950912
[Error]: Server received crash signal! Attempting to save all online characters!

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by laziem** [comment] 2020-06-18 09:32
I can confirm this... opening guild log make my map server freeze

**Comment by reunite-ro** [comment] 2020-06-19 14:03
> I can confirm this... opening guild log make my map server freeze

freeze or crash ?

**Comment by laziem** [comment] 2020-06-19 14:11
> 
> 
> > I can confirm this... opening guild log make my map server freeze
> 
> freeze or crash ?

mine freeze without any error shown... but can't longer login... crash when force stop the map-server

**Comment by mazvi** [comment] 2020-06-20 05:33
I think also freeze on 2018 build

**Comment by reunite-ro** [comment] 2020-06-20 05:38
I also having issue 'hang/freeze' map server on 20180620 but I dont know which one causing it.
map server are still running, not crashing.

It doesnt happen before, I think its from around this month commits.

**Comment by mazvi** [comment] 2020-06-20 08:45
same like me :D i revert to rAthena commit 20200516 :D

**Comment by CyberDevil75** [comment] 2020-06-20 11:25
Bug tested and also **confirmed** on my server, I did a test with a guild storage with 460 items inside it, as soon as I open the logs menu the map-server freezes and I have to use the KILL command from SSH to unlock it... not it happens on guild storage with few objects.
These freezes of the map-server started when I updated rathena (like every Monday) with the version 35c3301 made on June 8, 2020, with precision that day I inserted all these updates taken from the repository:

> Clean up Summoner Power skill checks (#4999) Centralized the Summoner Power skill tree checks into one function. Fixes a couple passive skill bonuses not being recalculated when reaching 20 investment points. Thanks to @exneval and @Balferian!
Fixes Bard and Dancer Soul Link bonus (#5055) Fixes #4801. Fixes Bard and Dancer not gaining the opposite class's skills. Cleans up check to not be reliant on sketchy index checks. Thanks to @ihernandeza, @gidzdlcrz, and @Lemongrass3110!
Deprecates support for old compilers (#5051) Fixes #4646 Switches AppVeyor build worker image to Visual Studio 2015. Fixed a bug with serv.bat, since crashes would result in a negative number sometimes, the crash would not be detected and would not be reported. Thanks to @aleos89
Fixed QD Shot Not Triggerring When ASPD is 193 (#5048)
Added support for skill scale display (#5041) Fixes #4530 Thanks to @Balferian
Fix issue with mob not spawning at selected option (#4996) Co-authored-by: Atemo Atemo@users.noreply.github.com
Add Card Drops for Devil Tower Instance (#4942)
Removed account gender (#5006) Adds an upgrade script to change all existing entries to the respective gender in their account. Cleanup of a few strange design decisions in the character server code. Removed SEX_ACCOUNT. Thanks to @Daegaladh for his help.
Fixed some compiler warnings Follow up to 45cd580 Thanks to @aleos89
Fixed an issue with storages Thanks to @Daegaladh
Fixed death counter not being properly reseted with Super Novice link *Follow up to 929c30c4143dc78cb85bc70d022113e75f62d0cc
Initial support for newer packet versions (#4944) Basic support for packets up to April 2020 Changing the default packet version to 2020-04-01 Thanks to everyone involved!
Fixed death counter not updating properly Also fixes Super Novice bonus not being removed on death and a possible crash *Thanks to @aleos89
Follow up to b10caa0
Removed a sample entry in item_avail.txt This should have never been enabled by default...
Fixed instance YAML conversion handling
Fixed slave recalculation on reloadmobdb Slaves sometimes ended up with weird status calculations or insane speed, because their status got recalculated before their master and this way their speed could not be copied from the master. Thanks to @Daegaladh
Added a missing percentheal (#5033) Fixes #5031 Thanks to @Masao87
Mob and NPC Identity Update

**Comment by mazvi** [comment] 2020-06-20 16:21
Maybe staff need information about os and compiler

Iam using centos 7 with GCC 7

**Comment by mazvi** [comment] 2020-06-23 15:57
anyone have solution for this issue?

**Comment by Lemongrass3110** [comment] 2020-06-23 16:04
> anyone have solution for this issue?

Yes. Maybe later tonight

**Closed** 2020-06-24 20:36 UTC
Labels: component:core, mode:prerenewal, mode:renewal, type:bug
