### ISSUE TITLE
Taekwon Mission Monster Change Issue after @reloadmobdb ( Issue #2360 )

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#2460] opened 2017-09-28 20:50 UTC
* **rAthena Hash**: c71f10508325fdd8a97a1b07ba28b845950c51b0 and up...

* **Client Date**: 2015-09-16

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Taekwon using Taekwon Mission with only one monster: Scorpion which is the first available monster in db ( **cause of @reloadmobdb** )
  * Result: only one monster used for Taekwon Mission: Scorpion, even with change mission;
  * Expected Result: random monster from db, even with 1% chance of change monster with 0 kills;
  * How to Reproduce: create Taekwon, use skill ``Taekwon Mission``, make @reloadmobdb - you will get this problem.
  * Official Information
  

* **Modifications that may affect results**: 
  Using @reloadmobdb command;
#2360

**Comment by Jeybla** [comment] 2017-09-29 02:08
Thanks for clearing the cause!

**Comment by Jeybla** [comment] 2017-10-06 07:12
Fixed in #2469 . Already closing it, since this is a duplicate of #2360. Anyway thanks @mgksrt8 for pointing it out!

**Closed by Jeybla** 2017-10-06 07:12 UTC
Labels: status:confirmed
