### ISSUE TITLE
Max HP SP Homun wrong

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6004] opened 2021-06-06 06:12 UTC
* **rAthena Hash**: 7b1f3ff

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: Max HP SP Homun wrong check attachment
  * Result: 
  * Expected Result: 
  * How to Reproduce: Just generate first homun
  * Official Information: 
  

![gambar](https://user-images.githubusercontent.com/8316103/120914508-d721af80-c6c8-11eb-9dbf-e46a9bc0f8f4.png)

* **Modifications that may affect results**:

**Comment by RagnaWay** [comment] 2021-06-06 09:06
![image](https://user-images.githubusercontent.com/53480357/120918844-fbf83180-c68c-11eb-830d-7efdd7e6ff6b.png)

It's normal here for me. 

Hash: https://github.com/rathena/rathena/commit/7b1f3ffa442d3751c9536b1a59fa488fa0e5e80d
Client Date: 2021-01-07aRagexeRE
Server Mode: RE

**Comment by mazvi** [comment] 2021-06-06 09:21
Hmmm? This is related msgstringtabledb or packet ver?

**Comment by mazvi** [comment] 2021-06-06 10:08
ah, thx very much

**Comment by Lemongrass3110** [comment] 2021-06-08 07:27
Duplicate of #5078

**Closed by Lemongrass3110** 2021-06-08 07:27 UTC
Labels: status:duplicate, status:wontfix
