### ISSUE TITLE
hp_rate, sp_rate save wrong max_hp

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1887] opened 2017-01-16 19:37 UTC
Tested on a clean rA Revision: 06c40e6cb412cd02428d4bc326b298849c2058d7

The battle configurations
**hp_rate: X
sp_rate: X**

Do **not** affect the max_hp saved to the sql database ones logging out.
It always saves the "original" max_hp data as if the setting was 0 (although it has been set higher).
 
**Which means by setting hp_rate and sp_rate to a higher value will always save char data which results as:**

**hp > max_hp
sp > max_sp**

**Comment by aleos89** [comment] 2017-01-27 18:50
Duplicate of #1733.

**Closed by aleos89** 2017-01-27 18:50 UTC
Labels: status:duplicate
