### ISSUE TITLE
Instances system: setmapflag no work correctly 

### ISSUE THREAD

**Issue by darknessfmy** [rathena/rathena#1929] opened 2017-01-30 03:35 UTC
rAthena Hash: e8b9cf0 
Client Date: Any
Server Mode: Renewal
Description of Issue:

 if use @reloadscript and instances are started. All mapflags is removed automatic.
Example: instance no accept use skills ok? the gm use @reloadscript, now the map of instance accept skill (reloadscript remove the mapflags in maps of instances).

**No show error in map server.

---------------------
And setmapflag no apply the flag for the instance "dimensional map" or not work.
```
	setmapflag instance_mapname("ordeal_1-2"),mf_nowarpto;
	setmapflag instance_mapname("ordeal_1-2"),mf_nodrop;
	setmapflag instance_mapname("ordeal_1-2"),mf_noskill;
```

**Note:** maybe removemapflag too have this problem?

**Comment by Lemongrass3110** [comment] 2017-01-30 06:39
Duplicate of #798

**Closed by Lemongrass3110** 2017-01-30 06:39 UTC
Labels: status:duplicate
