### ISSUE TITLE
map_addinstancemap failed. map_num(1500) > map_max(1500)

### ISSUE THREAD

**Issue by tianran0207** [rathena/rathena#3551] opened 2018-10-08 13:54 UTC
* **rAthena Hash**: 129812d6a56b6dd765afd966668b4f986bf0c3b7

* **Client Date**: 2017-06-14bRagexeRE_patched.exe

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: map_addinstancemap failed. map_num(1500) > map_max(1500)
  * Expected Result: map_num will only get bigger and bigger in function "int map_addinstancemap(const char *name, unsigned short instance_id)"
  * How to Reproduce: Create and destroy instance，Always try until it happens
  * Official Information:You can try to lower  MAX_MAP_PER_SERVER 
  

* **Modifications that may affect results**: 
  
  

prontera,154,108,5	script	test	56,{
&nbsp;&nbsp;&nbsp;&nbsp;for(.@i = 0; .@i<1000; .@i++){
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;instance_create("Endless Tower");
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sleep2 4000;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;instance_destroy();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sleep2 1000;
&nbsp;&nbsp;&nbsp;&nbsp;}
}

**Comment by aleos89** [comment] 2018-10-08 16:09
Duplicate of #3517.

**Closed by aleos89** 2018-10-08 16:09 UTC
Labels: status:duplicate
