### ISSUE TITLE
Any work in progress

### ISSUE THREAD

**Issue by Lokyluminiaro** [rathena/rathena#2405] opened 2017-09-05 21:34 UTC
On only a few players and on some NPC, a bug appears. the next disappears to leave a closed place.
if you click on close or it can autoclose too and then opens the menu ...
whatever he does, the player remains blocked. He can not do anything.
A message appears next if the player wants to talk to an NPC.
He is obliged to deco reco to regain his mobility and be able to speak to a NPC.

1> git version: 470364cbe15519e2268a7f6f91668320cb622371
2> Client : 2015-11-04
3> NPC Offi (Captain Carroc > Izlude)
4> The bug appears on some players but not all, it's random.
5> It seems that the npcs that bug are those with a switch menu.
6> Version Re and Pre-re (Test on both)
7> No console error

for more information :

https://www.youtube.com/watch?v=OYebrfrLE6I

**Comment by Jeybla** [comment] 2017-09-05 21:54
Please wait for 10-20 seconds after logging in without talking to any npc. Then try to reproduce the bug.

**Comment by hurtsky** [comment] 2017-09-06 00:00
I think this relate to #2348

**Comment by poporing** [comment] 2017-09-06 08:46
I got the same issue, it's the same has #2177 
This is completly random and not happen to all players. It's happen on official script that have switch in the script from last git rathena.
I don't have any custom source and I didn't touch npc.
As you can see in the video when the script goes to the switch menu it's auto close then you are stuck
I have this problem since I start my server in october 2016
I try to disable SECURE_NPCTIMEOUT and completly remove it but I always got the problem.
There is no console error.

**Comment by Jeybla** [comment] 2017-09-06 14:19
Duplicate of #2177. Closing this issue.

**Closed by Jeybla** 2017-09-06 14:19 UTC
