### ISSUE TITLE
rAthena skill 'random' is undefined! serve\src\map\skill.c:219::skill_chk

### ISSUE THREAD

**Issue by lphz** [rathena/rathena#517] opened 2015-07-19 10:42 UTC
This server download with last Github (https://github.com/rathena/rathena/commit/23540387212193d0496b311001f09becd59505a7)

I got problem skill SIGHT BLASTER when use skill with monster or player. It’s show error rAthena skill 'random' is undefined! Server/src/map/skill.c219::skill_chk

and src and db dind’t modify anything (original src & db)

Maybe has other skill also please check it also

skill 1028 is undefined skill.c:219::skill_chk
skill 771 is undefined skill.c:219::skill_chk
skill 778 is undefined skill.c:219::skill_chk

skill 65535 status.c:95::status_skill2sc
status_skill2sc unsupported skill id 65535
status_skill2sc unsupported skill id 0

VIDEO: https://www.youtube.com/watch?v=4VNxrJWi1Vo
VIDEO: https://www.youtube.com/watch?v=4VNxrJWi1Vo
VIDEO: https://www.youtube.com/watch?v=4VNxrJWi1Vo
VIDEO: https://www.youtube.com/watch?v=4VNxrJWi1Vo

![mapbug](https://cloud.githubusercontent.com/assets/10014424/8765588/1261f5ee-2e3d-11e5-8144-c59ce8f44cd0.png)

**Comment by aleos89** [comment] 2015-07-23 19:02
I'm going to blame it on this b71ed05.

**Comment by lphz** [comment] 2015-07-27 13:23
thankz

**Comment by lphz** [comment] 2015-08-22 04:55
Please.. don't waste this problem

**Comment by anacondaqq** [comment] 2015-08-22 07:01
Are you using rAmod or rAthena? because i saw many times the same error at rAmod at any time since 2014.

**Comment by lphz** [comment] 2015-08-22 08:08
Yes, I'm using rAmod so what i do?

**Comment by anacondaqq** [comment] 2015-08-22 11:58
So, this issue related to rAmod only. Because i do not have issues with rAthena with skill 65535. Only rAmod have it. I think, this is related to some changes inside rAmod, and not to rAthena. But Please, show whole function from this line

> skill 1028 is undefined skill.c:219::skill_chk

**Comment by lphz** [comment] 2015-08-24 00:51
sry sir.... I'm use rAthena not rAmod
This rAthena Patch SVN: 13899 from https://github.com/rathena/rathena/commit/e3b3d57e163b52057d360a6a884fadc275598fcc

**Comment by lphz** [comment] 2015-10-01 11:59
please ..... help me

**Comment by aleos89** [comment] 2015-11-04 19:09
Just completed the same test you showed in the video above with c73ebec and was unable to get the warnings you show.

Try making sure you clone a clean rAthena and then see what you can reproduce. I'm assuming you have something somewhere that merged incorrectly.

**Comment by lphz** [comment] 2015-11-05 05:41
I try with https://github.com/rathena/rathena/commit/c73ebec481400ad9f26f880e64d8ac37e86a53db already, but same problem...
Please download this https://drive.google.com/file/d/0B5r4iYHUyW3YZEpKWlpUakxzcGs/view?usp=sharing to check this problem (last serv i'm test)

**Comment by aleos89** [comment] 2015-11-06 17:39
I'm sorry, but I don't have time to check the differences of your setup. I suggest you start clean since you said you haven't modified anything.

Follow this guide: https://rathena.org/wiki/GIT_Clone/Windows

It will get you setup using TortoiseGit rather than using TortoiseSVN (which I'm assuming is the source of your conflict issues).

**Closed by aleos89** 2015-11-06 17:39 UTC
Labels: status:unable to reproduce

**Comment by lphz** [comment] 2015-11-07 04:52
NVM Sir,But I try TortoiseGit (v.1.8.16.0) also same problem.
So i'm doing everything with https://rathena.org/wiki/GIT_Clone/Windows 99% and 1% edit file inter_athena.conf & mmo.h packet ver 20120410 only.

thank you every answer ^_^
