### ISSUE TITLE
Items over 300 on storage do not appear when VIP expires

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5452] opened 2020-10-14 03:17 UTC
* **rAthena Hash**: Latest

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**: Items over 300 on storage do not appear when VIP expires 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2020-10-14 14:17
Shouldn't these items become visible as players remove + relog?

**Comment by mazvi** [comment] 2020-10-14 15:49
The player has tried relogging but the item does not appear. After the player becomes VIP the item appears again. 

I don't use storage2, I only use regular storage, which defaults to 300 and becomes 600 for VIP

**Comment by blipblopblip** [comment] 2020-10-14 16:36
It's normal, the player should activate vip status again to see their storage.

**Comment by LotusRO** [comment] 2020-10-16 12:10
afaik you're supposed to be able to see them as 600/300 and only be able to remove if you used to ahve VIP.

**Comment by mazvi** [comment] 2020-10-16 13:42
Yes so the solution player is take all item first on storage to get item over 300?

**Comment by Everade** [comment] 2020-10-17 22:20
https://github.com/rathena/rathena/issues/5083

**Comment by mazvi** [comment] 2020-10-17 22:46
yes but I guess after I thought it was better like this. Items over 300 will appear after items within the 300 quota are taken. This is better because if made appear maybe it will create another new bug.

**Comment by Lemongrass3110** [comment] 2020-11-04 00:15
Duplicate of #5083

**Closed by Lemongrass3110** 2020-11-04 00:15 UTC
Labels: status:duplicate
