### ISSUE TITLE
Map server crash during WOE

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#3676] opened 2018-11-09 14:46 UTC
* **rAthena Hash**: c1b681a07

* **Client Date**: 20180621
* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Map server crash
  * Expected Result: no crash
  * How to Reproduce: 
  * Official Information: 

* **Modifications that may affect results**: 

```
Program received signal SIGSEGV, Segmentation fault.
0x080ec31a in guild_checkskill (g=0x0, id=6) at guild.cpp:113
113             return g->skill[id].lv;
(gdb) bt full
#0  0x080ec31a in guild_checkskill (g=0x0, id=6) at guild.cpp:113
No locals.
#1  0x080e7b17 in clif_parse_LoadEndAck (fd=37, sd=0x10119de8) at clif.cpp:10903
        guild_notice = false
        mapdata = 0x840c0fc <map+24732>
#2  0x080b4c37 in clif_parse (fd=37) at clif.cpp:21223
        cmd = 125
        packet_len = 2
        sd = 0x10119de8
        pnum = 0
#3  0x08051ab6 in do_sockets (next=<optimized out>) at socket.cpp:1304
        rfd = {fds_bits = {0, 32, 0 <repeats 30 times>}}
        timeout = {tv_sec = 0, tv_usec = 19609}
        ret = <optimized out>
        i = 37
        rfd = <optimized out>
        timeout = <optimized out>
        ret = <optimized out>
        i = <optimized out>
#4  main (argc=1, argv=0xbffff264) at core.cpp:368
        next = <optimized out>
```

**Comment by aleos89** [comment] 2018-11-11 19:05
Duplicate of #3591.

**Closed by aleos89** 2018-11-11 19:05 UTC
Labels: status:duplicate
