### ISSUE TITLE
'setlook' there is no correct change

### ISSUE THREAD

**Issue by Hope8888** [rathena/rathena#1779] opened 2016-12-09 09:09 UTC
hash:https://github.com/rathena/rathena/commit/d2651c45c1f69c6030ed143d1371f4ad04ff5c06
mode:re
client:20151029

(1) Equipped with weapon(id:1601)
![default](https://cloud.githubusercontent.com/assets/19237837/21043039/f871207c-be2f-11e6-87aa-2895573c5760.png)
(2) script `setlook LOOK_WEAPON,72;` or atcommand `@changelook 4 72`
(3) It still does not change the look of the weapon

--

weapon:[evil-bone-wand](http://www.divine-pride.net/database/item/1615/evil-bone-wand)

weapontable.lub
view id:`WEAPONTYPE_Bone_Wand = 72,`

It should be like this
![default](https://cloud.githubusercontent.com/assets/19237837/21043287/1cb6555a-be31-11e6-86db-cdc27da5b200.png)

--
is it client bug or rA issues?

**Comment by Lemongrass3110** [comment] 2016-12-09 09:57
Although I can confirm your issue, the client does not want the weapon type like you showed. It takes the item id, so you would have to set it to 1615 in your case.

**Comment by dastgir** [comment] 2016-12-09 10:05
@Lemongrass3110 
That's wrong, setlook for weapon sets sd->status.weapon which is weapon type, not id
Changing of weapon view is not possible from server side I believe, since client uses itemInfo to correctly determine which weapon sprite to show.

**Comment by Lemongrass3110** [comment] 2016-12-09 10:08
@dastgir
I just tried it locally... You can change it if you set it to the item id like I wrote above. Nevertheless it is currently blocked by `clif_get_weapon_view`.

**Comment by Hope8888** [comment] 2016-12-09 11:53
@Lemongrass3110 
i just want to change weapon sprite.

like this image:
![9](https://cloud.githubusercontent.com/assets/19237837/21048053/2f26e6e8-be48-11e6-87f4-4a752fd8bc42.gif)

**Comment by Hope8888** [comment] 2016-12-09 13:44
@Lemongrass3110 
I want to achieve results.

![001](https://cloud.githubusercontent.com/assets/19237837/21050567/6938cfaa-be56-11e6-9ff0-c0b873fb95b7.jpg)

Change weapon sprite on shadow weapon
![002](https://cloud.githubusercontent.com/assets/19237837/21050582/7d777d68-be56-11e6-949a-85c4e9698d3d.jpg)

--
I did a little test, but it did not succeed.
```1615,Bone_Wand,Evil Bone Wand,12,20,,700,40:110,,1,0,0x00818314,63,2,131072,3,24,1,10,{},{ setlook LOOK_WEAPON,72; },{ setlook LOOK_WEAPON,10; }```

**Comment by tony891254** [comment] 2021-06-04 17:00
same problem, @changelook 4(weapon) not works

**Comment by Akkarinage** [comment] 2022-09-02 19:07
I was in the middle of writing some script to help test this and realised that the `setlook` command only saves hair/palette data, so if you wanted the sprite to persist, you should just give the corresponding sprited weapon to the character and equip it. Since view data is client-side and this is a customisation attempt, i'm closing the issue.

**Closed by Akkarinage** 2022-09-02 19:07 UTC
Labels: status:wontfix
