### ISSUE TITLE
Char-Server Addon: Character Move

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#189] opened 2014-12-30 20:26 UTC
Character Movement System seems to be broken on 2013 clients(tested with 20130807).

A screenshot says more than 1000 words. This picture was taken after moving the character successfully.
![screenrathena002](https://cloud.githubusercontent.com/assets/3517879/5582431/d584bee8-9069-11e4-954a-23967b1e9d95.jpg)

I tried to change the packets the way hercules sends them(chclif_mmo_send099d instead of chclif_mmo_char_send) but that also does not work. I was to lazy to set up a running hercules and try if it really works with their version.

**Comment by cydh** [comment] 2015-01-01 13:46
am I the only one who don't know how make this work? /swt

**Comment by Lemongrass3110** [comment] 2015-01-01 15:09
You log in to a character and use the item Character Position Change Coupon(12786). Now you are allowed to move the character where you used the item once(or as often as you used the item) in the char select. So go back into char select menu. Now the character should have the symbol "Addons available" in the background. If you rightclick him you now have the possibility to move him. Afterwards right click on the slot where you want to move the character and thats it. Hope that helps. ;)

![screenrathena003](https://cloud.githubusercontent.com/assets/3517879/5592454/87d24586-91d0-11e4-8995-2c865023e450.jpg)
![screenrathena004](https://cloud.githubusercontent.com/assets/3517879/5592455/87d230f0-91d0-11e4-95a6-220bc2d1fb82.jpg)
![screenrathena005](https://cloud.githubusercontent.com/assets/3517879/5592456/87d3c532-91d0-11e4-8702-1c7e08f23085.jpg)

**Comment by cydh** [comment] 2015-01-02 07:47
ohhh thank you master!!

**Comment by cydh** [comment] 2015-04-01 04:27
@Lemongrass3110 I just tried it,
  1. Use item (more than once, 4 xD),
  2. to select char windo
  3. Right-click (slot 3), 'move book'
  4. Right-click on empty slot (slot 6), 'move'
  5. Char moved, looks fine
Did I miss something as ur attempt?

**Comment by aleos89** [comment] 2015-07-15 21:42
Tested with 2013-08-07 and was unable to reproduce the error as well. My characters transferred just fine!

**Closed by aleos89** 2015-07-15 21:42 UTC
Labels: bug:core, server:char, [ status:unable to reproduce ]
