### ISSUE TITLE
Map server Crash

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#5484] opened 2020-10-25 14:03 UTC
* **rAthena Hash**: lastest

* **Client Date**: 20200401

* **Server Mode**: renewal

* **Description of Issue**: after update to the lastest version and compile it, when character enter the map client always get crash.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

![image](https://user-images.githubusercontent.com/9587609/97109386-847d1f80-1705-11eb-8ecc-238c4c7bb963.png)

![image](https://user-images.githubusercontent.com/9587609/97108744-fb181e00-1701-11eb-965e-632699d62b93.png)

**Comment by aleos89** [comment] 2020-10-25 14:44
Duplicate of #5476.

**Closed by aleos89** 2020-10-25 14:44 UTC

**Comment by hendra814** [comment] 2020-10-29 11:48
Today after update my server i still have the same problem
![image](https://user-images.githubusercontent.com/9587609/97564423-26a74b00-1a17-11eb-9cbf-9f5f45a514f3.png)

What suppose i do to fix this error.

**Comment by hendra814** [comment] 2020-10-29 11:49
on map server not show any error
![image](https://user-images.githubusercontent.com/9587609/97564594-62daab80-1a17-11eb-8e4c-c3e29ca24ae8.png)

so i don't know what i suppose to do

**Comment by aleos89** [comment] 2020-10-29 12:44
You can build in debug mode and then run the [debugger](https://github.com/rathena/rathena/wiki/Visual-Studio-Debugger). It will show the crash point.

**Comment by hendra814** [comment] 2020-10-29 13:42
can't start with debuging
![image](https://user-images.githubusercontent.com/9587609/97581403-1ac38500-1a27-11eb-9d19-aa8df906418a.png)
Any idea?

**Comment by hendra814** [comment] 2020-10-29 13:53
should i make support thread at rathena forum? or i can get support at here.

**Comment by aleos89** [comment] 2020-10-29 14:04
Make a thread on the forum because now it sounds like you have some other underlying issues.

**Comment by hendra814** [comment] 2020-10-29 19:32
ok i will make new thread on forum, because change into 2018 client the character can enter the map.

**Comment by hendra814** [comment] 2020-11-01 12:37
i found the problem, the signal error appear when character enter map like izlude, payon, prontera (town map)
but when character at map like quiz_02 it's doesn't show error

![screenrAthena000](https://user-images.githubusercontent.com/9587609/97802944-61a8b900-1c79-11eb-8d5e-f747f1d591ce.jpg)

already try remove diff option about towninfo when patching the client, but it's still give the same error.

**Comment by hendra814** [comment] 2020-11-01 14:48
already make thread at rathena forum
here the link https://rathena.org/board/topic/126371-20200401-client-problem-when-entering-town-map/
