### ISSUE TITLE
Mail System

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#4555] opened 2020-01-23 16:06 UTC
* **rAthena Hash**: 930f52e31f465b574502b8037cf11ba6dc39b2ba

* **Client Date**: 2017+ Client

* **Server Mode**: Pre-renewal

* **Description of Issue**: Im getting error logs from the mail system
```
(01/20/2020 01:32:28) [ Error ] : intif_parse_Mail_delete: char not found 1244
(01/20/2020 01:32:28) [ Error ] : intif_parse_Mail_delete: char not found 1244
(01/20/2020 01:32:28) [ Error ] : intif_parse_Mail_delete: char not found 1244
(01/20/2020 01:32:28) [ Error ] : intif_parse_Mail_delete: char not found 1244
```
  * Result: 
  * Expected Result: 
  * How to Reproduce: This is a good question of how to reproduce the error, but 1 thing that im sure is i always try to delete all the non-response email i made to the players.
  * Official Information:
```
// Whether or not mail box status is displayed upon login.
// Default: 0
// 0 = No
// 1 = Yes
// 2 = Yes, when there are unread mails
mail_show_status: 0

// Amount of mails a user can send a day.
// Default: 100
// 0 = Unlimited
mail_daily_count: 100

// Fee for transferring zeny via mail (Note 2)
// NOTE: this rate is hardcoded in the client, you need to diff your client accordingly if you change this value.
// Default: 2(2%)
// 0 = No fee
mail_zeny_fee: 2

// Amount of zeny to pay for each attached item
// NOTE: this fee is hardcoded in the client, you need to diff your client accordingly if you change this value.
// Default: 2500
// 0 = No fee
mail_attachment_price: 2500

// Maximum weight in total that can be attached to a mail
// NOTE: this limit is hardcoded in the client, you need to diff your client accordingly if you change this value.
// Default: 2000
// 0 = No weight limit
mail_attachment_weight: 2000
```
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment] 2020-01-23 16:10
Yeah I also get some of these errors, not sure why. Pre-renewal, packetver 20150515

**Comment by Lemongrass3110** [comment] 2020-01-23 16:15
Duplicate of #4322

**Closed by Lemongrass3110** 2020-01-23 16:15 UTC
Labels: status:duplicate, status:wontfix
