### ISSUE TITLE
Resistence Effects Bug

### ISSUE THREAD

**Issue by tuxico** [rathena/rathena#2017] opened 2017-03-23 06:33 UTC
* **rAthena Hash**: 
- rAthena hash: da23d877d1e2d646a727cca7d12bd75cebb40a7a
- Emulator Date: 01.03.2017

* **Client Date**: 
2015

* **Server Mode**: 

Pre-Renewal

* **Description of Issue**: 
Thara Frog, bonus2 bSubRace,RC_DemiHuman,30; bonus2 bSubRace,RC_Player,30; DOENST WORKS!

* **Modifications that may affect results**: 
  After change renewal to pre-renewal...

**Comment by Playtester** [comment] 2017-03-23 08:17
Thara Frog doesn't have a bAddRace bonus. If you switch to pre-renewal you have to check pre-re/item_db.

**Comment by tuxico** [comment] 2017-03-23 08:20
Edited...

**Comment by Playtester** [comment] 2017-03-23 08:29
How do you tell that it doesn't work? You equipped a shield with Thara Frog card and got hit by a demihuman monsters and damage is not reduced compared to without shield?

**Comment by tuxico** [comment] 2017-03-23 08:32
Using @clone , Thara Frog, Custom Headger with SubRace DemiHumam & Player 80%... and nothing...
Deviling card with Asura Strike too.

**Comment by tuxico** [comment] 2017-03-23 08:35
Now i test with biolab mobs and bug continues...

**Comment by Jeybla** [comment] 2017-03-23 13:48
This bug likely is a testing or a merge mistake.

You should test this on a clean rathena clone and with a second character. Keep in mind: Damage varies often, so calculate your mean damage. If this doesn't help, please provide some screenshots. Thanks!

**Comment by tuxico** [comment] 2017-03-23 14:06
Now i tested with other clean rathena, but bug persist... look for yourself

**Comment by Jeybla** [comment] 2017-03-23 14:17
Cannot reproduce on 61ff2512e6ee075e0716e2efdc2aaa26e8ed632d .

As I said, you should check your testing. If you Tested it with Eremes or Seyren, these are not Demi-Human monsters.

**Comment by tuxico** [comment] 2017-03-23 14:29
Neither in @clone? :/

**Comment by tuxico** [comment] 2017-03-23 14:29
You are setted to pre-renewal in renewal.h?

**Comment by tuxico** [comment] 2017-03-23 14:34
Stranger... because hydra works fine in @clone...

**Comment by tuxico** [comment] 2017-03-23 14:38
And clone with deviling dont reduces asura strike or other sources neutral damage.

**Comment by Playtester** [comment] 2017-03-23 16:11
Tested and works with, even with @clone.

My script: 4058,Thara_Frog_Card,Thara Frog Card,6,20,,10,,,,,,,,32,,,,,{ bonus2 bSubRace,RC_DemiHuman,80; bonus2 bSubRace,RC_Player,80; },{},{}

Must be an error in your script. Maybe you wrote the changes into the renewal db files instead of pre-renewal.

Closing this.

**Closed by Playtester** 2017-03-23 16:11 UTC

**Comment by tuxico** [comment] 2017-03-23 16:18
You tested item in pre-renewal mode?
I use pre-re db and my custom are displaying... you are testing in renewal...

**Comment by Jeybla** [comment] 2017-03-23 16:41
Just to mention it:
I tested it on pre-re with player vs player and demi-humin-monster vs player.

**Comment by Playtester** [comment] 2017-03-23 17:08
Yes, I tested on pre-re too.

**Comment by tuxico** [comment] 2017-03-23 17:33
Wtf... what i doing wrong :(
Ok thx

**Comment by Jeybla** [comment] 2017-03-23 17:47
Test it well and think about it.
If you'll find strange behavior formulate it well and prove it with screenshots or a youtube video.

We can help you find your issues and of course our issues way better with more informations. Thanks anyway for your report, next time just provide more detailed information about it.

**Comment by tuxico** [comment] 2017-03-24 01:09
[https://ibb.co/jZfNYv
https://ibb.co/m5Vd6F](url)
35000,Elmo_Da_Valquirias,Valk Helm,4,100000,,1000,,5,,1,0xFFFFFFFE,2,2,768,,0,1,1900,{bonus bAllStats,10; bonus bMaxHPrate,10; bonus bMaxSPrate,10; bonus2 bSubRace2,RC_Player,80; bonus bUnbreakableHelm,1; bonus bNoMagicDamage,10;},{},{}

**Comment by Playtester** [comment] 2017-03-24 07:31
Let them attack you instead of you attacking them. Spawn clone and enable PVP, that makes them attack you. Then you can equip and unequip the cranial shield to see if there's a difference.

**Comment by tuxico** [comment] 2017-03-25 05:54
Really I was testing wrong, sorry ... cause damage on the clone does not work the resistance, but with another player yes ... thank you very much for the attention ..
