### ISSUE TITLE
Delete Character Bug

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2410] opened 2017-09-08 22:20 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/b275412bcc1251a1c9214b8cdafdf40323c2b0f7

* **Client Date**: 2017-03-15

* **Server Mode**: Renewal

* **Description of Issue**: It is possible for you to bypass the time block to delete the characters by doing the following, you mark to delete the character and do not close the game, change the date of the computer, then back to the game and will be able to delete the character.

**Comment by anacondaqq** [comment] 2017-09-08 22:44
I don't think this is rathena bug, gravity have many bugs like that.

**Comment by Jeybla** [comment] 2017-09-08 23:08
Well, I think the delete-mark-time is also sent to the server. So it could be re-checked on the server side.

**Comment by admkakaroto** [comment] 2017-09-08 23:27
Can not you solve this by adding the time to delete the character in the database? so you click to delete the character gets a time to be deleted right in the database, when that time runs out it can be deleted, I believe it can solve the problem.

**Comment by Lemongrass3110** [comment] 2017-09-09 16:05
Should be a duplicate of #2271 and fixed in bbd42e7

**Comment by Jeybla** [comment] 2017-09-09 17:43
@admkakaroto can you retest it?

**Comment by admkakaroto** [comment] 2017-09-09 18:04
I'm going to test again, I'm sorry for the inconvenience, I'm going to test and I'll give you a return here.

**Closed** 2017-09-13 02:01 UTC
Labels: bug:core, mode:prerenewal, mode:renewal, priority:low
