### ISSUE TITLE
Charleston Crisis

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#5352] opened 2020-08-22 20:50 UTC
* **rAthena Hash**: 88b506a

* **Client Date**: 2020-08-19

* **Server Mode**: RE

* **Description of Issue**: Missing instance of Charleston Crisis.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2020-08-23 18:54
#4840

**Comment by aleos89** [comment] 2020-08-24 14:32
Also duplicate of #1303.

**Closed by aleos89** 2020-08-24 14:32 UTC
Labels: status:duplicate
