### ISSUE TITLE
The lag after using a skill. For example Cross Impact.

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#5173] opened 2020-07-02 23:23 UTC
* **rAthena Hash**: d38d2b6

* **Client Date**:  Any (I believe)

* **Server Mode**:  RE

* **Description of Issue**: If you start moving right after using Cross Impact the character "rubberbands" or "lags" a few cells.
  * Expected Result: Character uses skill and smoothly moves without any "lag" or "rubberbanding"
  * How to Reproduce: Use Cross Impact on a dummy and the millisecond after try to move somewhere else.
  * Official Information:
  
It's a little difficult to spot on this video but if you focus yourself on the GX movement after hes using Cross Impact you'll see how fluid it is.
https://youtu.be/-IVLZMMGnlI 

This is how it looks like on rAthena:
https://www.youtube.com/watch?v=j6XSQPZraI8&

* **Modifications that may affect results**: none

**Comment by Daegaladh** [comment] 2020-07-02 23:28
Duplicate of #259

**Closed by Daegaladh** 2020-07-02 23:28 UTC

**Comment by secretdataz** [comment] 2020-07-03 05:02
The kRO video shown here isn’t really valid since it’s from the AB’s POV.
I play GX on iRO and my char rubberbands if I move right after I cast Cross Impact.

**Comment by rye305** [comment] 2020-07-03 16:52
> 
> 
> The kRO video shown here isn’t really valid since it’s from the AB’s POV.
> I play GX on iRO and my char rubberbands if I move right after I cast Cross Impact.

well, IRO is almost like a p-server lol...
here KRO footage of GX without any rubberbanding after using CI
https://youtu.be/5oFwi2m5Uro?t=171
2min 51 seconds

**Comment by secretdataz** [comment] 2020-07-03 16:54
A p-server running Aegis ;)
This new video is much better

**Comment by OptimusM** [comment] 2020-07-03 17:12
well, in the description u said "client date *Any*"
That´s incorrect, since Cross Impact has changed the animation motion from 7 hits to a single one "ON KRO"
so, that´s part of the Guillotine Cross update, but, animation motions are related to the client.

![image](https://user-images.githubusercontent.com/40366993/86488380-d18c4e80-bd2e-11ea-9c99-7e3686d52f5b.png)

**Comment by rye305** [comment] 2020-07-03 17:19
> 
> 
> well, in the description u said "client date _Any_"
> That´s incorrect, since Cross Impact has changed the animation motion from 7 hits to a single one "ON KRO"
> so, that´s part of the Guillotine Cross update, but, animation motions are related to the client.
> 
> ![image](https://user-images.githubusercontent.com/40366993/86488380-d18c4e80-bd2e-11ea-9c99-7e3686d52f5b.png)
> 
> And yes, iRO is indeed an official server, just kinda outdated, but kRo and iRO uses the same Aegis.

didn't rathena already push the GX job improvement? or does this mean it only works with 2020 clients?

**Comment by ecdarreola** [comment] 2020-07-03 17:21
It only works on 2020 client perfectly as far as testing is concerned. No position lag encountered with 100% reduce after cast delay.
