### ISSUE TITLE
@disguise duplicates visually items quantity 

### ISSUE THREAD

**Issue by Melk3000** [rathena/rathena#7097] opened 2022-07-07 22:00 UTC
* **rAthena Hash**: 

* **Client Date**: 
20180620

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
  * Result:  
`  @disguise `
  ![disguiseerror1](https://user-images.githubusercontent.com/77757689/177878371-ec95c8b6-98f7-404d-9b7f-284d6ff5239c.png)

`@undisguise`
![disguiseerror2](https://user-images.githubusercontent.com/77757689/177878420-0cd51868-08e4-44fe-b3e6-4f54c77ee8e6.png)

  * Expected Result: 
Do not duplicate visually items quantity.
  * How to Reproduce: 1.- Put items in cart, 2.-`@disguise 657`, 3.-`@undisguise`, 4.- Check items quantity (Bug is only visually)
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2022-07-20 17:17
Unable to reproduce on 78b4f44 with 2021-11-03. I don't have a 2018 client handy to test.

**Comment by Akkarinage** [comment] 2022-08-30 17:51
I can't reproduce this on the given client.

Can you provide your server's git hash and information regarding any source modifications, then a list of diff patches you applied.

**Comment by Akkarinage** [comment] 2022-09-13 12:11
As there's no update to this and no one else has been able to confirm the validity of this bug, I'll close this.

**Closed by Akkarinage** 2022-09-13 12:11 UTC
Labels: status:need user input, missing:revision, status:need more info, type:bug
