### ISSUE TITLE
Devotion and Defender bug in Pre-re (wrong calculation)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#234] opened 2015-01-17 12:41 UTC
Hi, maybe i'm wrong. But please explain to me:

First of all, i want to show skill descriptions

#### Defender: [(irowiki source)](http://irowiki.org/wiki/Defender)
> Decreases the ATK of ranged attacks against the caster by 5%+15*SkillLV%,  but also lowers ASPD by 25%-5*SkillLV% and walking speed by 1/3 while active. 
> The higher the level the lower the ASPD reduction, up to SkillLV 5 which  has no ASPD penalty; however, the walking speed reduction applies for all levels.
> Can be shared with party members when Sacrifice is cast on them, but the movement reduction will affect them too. 
> Caster must have a shield equipped.
> Level 	Long Range Reduction 	Speed Reduction
> 1 	20% 	-20% ASPD
> 2 	35% 	-15% ASPD
> 3 	50% 	-10% ASPD
> 4 	65% 	-5% ASPD
> 5 	80% 	No ASPD reduction 

#### Devotion [(irowikisource)](http://irowiki.org/wiki/Sacrifice)
> Protects a Party Member by taking all of the damage inflicted on said Party Member. 
> The Party Member must be within 10 levels of the caster. 
> The damage that the caster receives from Sacrifice is affected by the Party Member`s Defense, rather than the caster's. 
> However, if the caster activates Guard, Shield Reflect, or Defending Aura, these skills will also affect Party Members targeted by Sacrifice and will generally function as if the Sacrificed party members had them as well. 

#### Extra most important information about Devotion
> Certain abilities function through Sacrifice: Guard, Shield Reflect, and Defending Aura. Guard works as if the sacrificed target had the skill active, also inducing physical attack delay when activated. Shield Reflect only works on melee skills when applied through Sacrifice. This includes Guillotine Fist, as well as Arrow Shower cast by a monster. Defending Aura currently will slow all sacrificed targets when activated, ***but only apply a reduced damage reduction compared to the 80% reduction on the caster.***

### Rathena Pre-renewal Tests

1. Paladin all stats 1 and he have all skills he is nude, but only with equiped shield
2. Champion allstats 1 and he have all skills, he totally nude, and have only shield
3. Lord Knight, he is totally nude, without stats, and only with spiral pierce

#### Hit Spiral Pierce to Paladin without Defender (results)
From LK Spiral Pierce to Paladin with disabled Defender, Damage: **1395** (279 * 5)

#### Hit Spiral Pierce to Paladin with Enabled Defender (results)
From LK Spiral Pierce to Paladin with enabled Defender Lvl 5: **275** (55 * 5) 80% reduced (like it must) So, at this part Defender works well. It's normally decrease long range attacks.

#### Hit Spiral Pierce to Sacreficed Champion
From LK Spiral Pierce to champion under devotion without enabled Defender: **1395** (279 * 5)

#### Hit Spiral Pierce to Sacreficed Champion under Devotion (lvl 5)
From LK Spiral Pierce to Champion under devotion with enabled defender on paladin: **976** ( 195 * 5 ). 
> That mean it's only *70*%! Why it's **70%???? **

# MY QUESTION:
> Where is wrong calculation? How defender must work for sacrficed members? How much % on lvl 5 it must reduce? Thank you!

**Comment by anacondaqq** [comment] 2015-01-30 01:19
Okay, i was test on hercules, eathena, cronus, rathena, brathena, idrathena, and other different emulators. I have the same % modifider in all emulators.

So, as i understand it is not bug.
But can anyone explain to me next:

Why are only 70% long range attack reduction transfered from player under devotion with enabled on paladin defender and not 80% like in on [iROwiki](http://irowiki.org/classic/Devotion)?

**Comment by Playtester** [comment] 2015-02-06 08:42
http://irowiki.org/wiki/Sacrifice
>  Defending Aura currently will slow all sacrificed targets when activated, but only apply a reduced damage reduction compared to the 80% reduction on the caster. 

```c++
		case SC_DEFENDER:
			if (!(flag&SCSTART_NOAVOID)) {
				val2 = 5 + 15*val1; // Damage reduction
				val3 = 0; // Unused, previously speed adjustment
				val4 = 250 - 50*val1; // Aspd adjustment

				if (sd) {
					struct map_session_data *tsd;
					int i;
					for (i = 0; i < MAX_DEVOTION; i++) { // See if there are devoted characters, and pass the status to them. [Skotlex]
						if (sd->devotion[i] && (tsd = map_id2sd(sd->devotion[i])))
							status_change_start(src,&tsd->bl,type,10000,val1,5+val1*5,val3,val4,tick,SCSTART_NOAVOID);
					}
				}
			}
			break;
```
Damage reduction for self is 5% + 15%*level, damage reduction for devoted player is 5% + 5%*level.

So this is working as intended.

**Comment by anacondaqq** [comment] 2015-02-06 11:08
Dear @Playtester do not close it. I will show screenshots with damage on latest rAthena.
Give me some time to prepare it.

**Comment by anacondaqq** [comment] 2015-02-06 12:21
Okay, we have 3 characters.

1. High Priest (IGN Priest)
2. Lord Knight (Knight)
3. Paladin (Admin)

![Lord Knight Stats](http://i6.5cm.ru/i/RZpa.png) ![High Priest Stats](http://i6.5cm.ru/i/7IFg.png) ![Paladin Stats](http://i6.5cm.ru/i/Tt5I.png)

## TEST PROCESS

#### 1. LK Attacking with Spiral Pierce Paladin with and without enabled Defender status on Paladin

**Spiral Pierce to Paladin WITHOUT defender**
![Spiral Pierce to Paladin WITHOUT defender](http://i6.5cm.ru/i/q55V.png) 
**Spiral Pierce to Paladin WITH ENABLED Defender**
![Spiral Pierce to Paladin WITH ENABLED Defender](http://i6.5cm.ru/i/yNk4.png)

#### 2. LK Attacking with Spiral Pierce High Priest UNDER Devotion without Defender on Paladin.

**Spiral Pierce to devoted High Priest WITHOUT enabled Defender on Paladin**
![Attack to High Priest WITHOUT ENABLED defender](http://i6.5cm.ru/i/NJjx.png) ![Screenshot from recieved damage to Paladin](http://i6.5cm.ru/i/GNPi.png)

#### 3. LK Attacking with Spiral Pierce High Priest UNDER Devotion with enabled Defender on Paladin.

**Spiral Pierce to from Lord Knight against High Priest. When High Priest under devotion status and Paladin have enabled Defender.
![Paladin recive damage from High Priest with Enabled Defender](http://i6.5cm.ru/i/FsiX.png) ![Chat Damage](http://i6.5cm.ru/i/AVOQ.png)

# WRONG Calculation!

#### 1396 / 1995 = 69.99%, but iRowiki says it's must be 80%

But at [same time on iROwiki](http://irowiki.org/classic/Sacrifice)


![Irowiki says it's 80%](http://i6.5cm.ru/i/0C1k.png)

**Comment by anacondaqq** [comment] 2015-02-06 12:23
@Playtester take a look please.

The same result with eathena, hercules, any revision of rAthena, and i dunno why....
Help me please to understand... Is it old bug, or is am i somewhere wrong?

**Comment by Playtester** [comment] 2015-02-07 08:45
I'm not sure where you get the impression that it should be 80%.

At level 5 the reduction for devoted players should be 30% (5% + 5% x 5 = 30%). So your tests just show that it is already working perfectly.

**Comment by anacondaqq** [comment] 2015-02-07 11:29
De

**Comment by anacondaqq** [comment] 2015-02-07 11:32
Dear @Playtester sorry please for maybe stupid questions from me. 
Where can i get information about latest formula from you about devoted players
> At level 5 the reduction for devoted players should be 30% (5% + 5% x 5 = 30%)

I can't find any.
I though it's something like that:
[irowiki source](http://irowiki.org/classic/Sacrifice)
![](http://i6.5cm.ru/i/4HEv.png)

**Comment by Playtester** [comment] 2015-02-08 07:16
I think you are misreading that sentence. It just says that the normal reduction is 80%, but devoted players only get a **reduced** reduction. It doesn't actually say what the reduced reduction is. The formula I got from the source code directly, I couldn't find sources on the internet that gave the exact formula for the reduction, so I can only assume it's already correct or it need to be tested on Aegis.

**Comment by anacondaqq** [comment] 2015-02-08 12:09
Dear @Playtester ! Thank you very much for your time and your helping about these problems.  
I hope i will found the source where am i wrong about formulas, and i will found a source of the latest.


Okay, so you did help me to understand logic, and i'm was wrong. 
So close it please:)

**Comment by Playtester** [comment] 2015-02-08 12:51
Honestly I just checked on Aegis because I was curious and could not see any "reduced reduction", it still reduced damage by 80% on devoted characters, not sure if it's a renewal thing, though. But I'm actually leaning to confirming this now instead of closing it. I simply don't know where that original formula came from, probably should track that down.

**Comment by Playtester** [comment] 2015-02-08 13:16
Hah, found it:
http://code.google.com/p/eathena/source/detail?r=6384&path=/trunk/src/map/status.c

Skotlex admits himself that those values are custom, so I guess we should change it back to 80%. There is no source other than iROwiki that says there should be a reduced reduction. The speed reduction would also be interesting though, I should check that as well.

**Closed** 2015-02-08 15:28 UTC
Labels: confirmed
