### ISSUE TITLE
Sight trasher effect

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#147] opened 2014-12-02 21:52 UTC
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce: **Use the skill next to many mobs**
Description:

Sight trasher displays target in range number of overlapping effects. If you cast it without anything in range and near to 5+ monsters you can see the difference (the effect has more contrast). This excessive use of effects creates a significant client-side lag.

**Comment by MrAntares** [comment] 2015-01-19 09:03
Same with minstrel buffs. The more ppl get the buff, the louder the music gets. I think other party buffs act similarly as well.

**Comment by Akkarinage** [comment] 2015-02-11 11:22
Has this been confirmed on the test server?

**Comment by reigneil** [comment] 2015-02-19 11:26
@Akkarinage 
yes it is. Confirmed using 2014-06-13aRagexe

**Comment by Playtester** [comment] 2015-02-20 08:53
Do you mean "Confirmed that it does not happen on Aegis"?

**Comment by reigneil** [comment] 2015-02-20 17:35
I mean athena server reproduce this bug., but not on aegis server that i played... pRO Valkyrie animation only apply once even if multiple enemies are being hit by it.

**Comment by Playtester** [comment] 2015-02-21 10:48
I guess it's as I expected, we need to capture new packet data. Gravity probably uses a new damage package in renewal.

**Comment by reigneil** [comment] 2015-04-29 21:24
@playtester@Akkarinage
i think i found some interesting discovery about this issue first is using SD_ANIMATION and this dMotion but first let me tell you about the story behind this... it all started at dummy monster in prontera rAthena version, that is when you critical these monster you see white number and not displaying the highlighted one and also some skills animation that don't have animation before work on this i.e before fixing NC_BOOSTKNUCKLE that is i thought it is the feature of this monster but i doubt it is not and started to tweak this to work critical display on this until i discover dMotion but fixing this wont display animation of the said skill before on the other hand it will fix critical display. and for this SD_ANIMATION which is i first encounter with Tetra Vortex Black image and the issue behind the delay of damage which are dMotion and aMotion of it which is thank goodness i fixed applying the proper implementation. well thats all i can say... whats the lesson behind this...
1. synchronizing animation of client or server
2. correcting data to match official (dmotion,amotion etc.)
3. lack of resources/information about how things work

**Comment by MrAntares** [comment] 2015-09-01 22:44
So can we expect a solution for this, or what is the status of this issue?

**Comment by MrAntares** [comment] 2015-11-03 17:49
Client: 2012-04-10

Revision: 14739
Last Changed Author: cydh.ramdh
Last Changed Rev: 14739
Last Changed Date: 2015-10-29 06:16:10 +0100 (Thu, 29 Oct 2015)

Mode: RENEWAL

**Comment by reigneil** [comment] 2015-12-16 19:27
@MrAntares 
since @cydh implement sd_animation for sightrasher this is fixed now.

**Closed** 2016-01-12 18:45 UTC
Labels: bug:core, mode:prerenewal, mode:renewal, priority:low, status:needs official info
