### ISSUE TITLE
Guild Skill restart delay

### ISSUE THREAD

**Issue by Triedge** [rathena/rathena#5730] opened 2021-02-03 02:59 UTC
* **Server Mode**:  Pre-Renewal

* **Description of Issue**: The duration of the skill delay is reset when the guild leader dies or leaves the castle. 
  * Result: If the guild leader dies before the 5 minute delay, the delay starts over again. Causing him to be unable to use Guild's abilities again. 
  * Expected Result: Use the guild leader ability, die or leave the castle but keep the normal delay, without resetting it. 
  * How to Reproduce: Be the leader of a guild, use a guild skill, leave the castle or die. And you will see that the delay of the ability returns again to 5 minutes.

**Comment by vstumpf** [comment] 2021-02-03 04:54
This is a duplicate of #5278

**Closed by vstumpf** 2021-02-03 04:54 UTC
Labels: type:bug
