### ISSUE TITLE
Hp displayed when dead

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#758] opened 2015-11-16 20:44 UTC
Hash : e27697072317820cab4ef1e551ec50de46fc73a7

On iro/euro the client display 1 hp when you have died (on rathena -> 0 hp).

Image on left, with rathena ; offi on right
![comparaision](https://cloud.githubusercontent.com/assets/5231893/11194170/e65eacea-8caa-11e5-9678-8e678d28873c.png)

**Comment by Lemongrass3110** [comment] 2015-11-17 06:56
@RagnarokNova could you confirm this?

**Comment by RagnarokNova** [comment] 2015-11-17 08:53
http://i.imgur.com/RHCp2U6.png
Confirmed on iRO, checking kRO now.

**Comment by lordganja** [comment] 2015-11-21 19:33
due to this update. is there any work around to check if the player is dead?

**Comment by Atemo** [comment] 2015-11-22 02:05
This update only affected the hp displayed by the client. Inside server the HP of dead player is still 0.

I will update the docs but I think it will be a bit confusing, specially for those who don't read the docs.. :p We may implement a new command script or use a const to check if the player is dead Just an idea~.

**Comment by lordganja** [comment] 2015-11-22 06:04
Ohh. Alright. Didn't know that XD. So if we check the hp using a script, it will show 0 hp while we see it as 1?

And yeah a new command script to check if player is dead will really be helpful.

**Comment by kyeme** [comment] 2015-11-24 17:04
Novice too :D

![image](https://cloud.githubusercontent.com/assets/4656578/11374284/3977a542-9310-11e5-8c9a-8b759aecaa02.png)

**Comment by Atemo** [comment] 2015-11-24 17:23
Hmm yes :p

**Comment by icxbb-xx** [comment] 2015-11-25 09:18
@kyeme , you can post screen shot for  high novice and super novice when die
thank you

**Comment by icxbb-xx** [comment] 2015-11-25 15:14
Fixed in https://github.com/rathena/rathena/commit/54136ddfca421546a6cb84298d212995061829bd
Try check again , Thank you

**Closed** 2015-11-29 11:19 UTC
Labels: bug:core, mode:missing, priority:low, server:map, status:needs official info
