### ISSUE TITLE
Pre-Renewal ASPD Bug

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#6925] opened 2022-05-06 12:26 UTC
* **rAthena Hash**: 94c80a910864a84dc516536762b892b90ea0f3a4

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**: Renewal mode with disabled RENEWAL_ASPD bug
  * Result: Max aspd
  * Expected Result: Max aspd to all class even without adding stats.
  * How to Reproduce: Renewal mode with disabled RENEWAL_ASPD
  * Official Information: You won't reach max aspd without stats and cards
  

* **Modifications that may affect results**: //#define RENEWAL_ASPD

**Comment by aleos89** [comment] 2022-05-06 14:19
Duplicate of #6900.

**Closed by aleos89** 2022-05-06 14:19 UTC
Labels: status:duplicate
