### ISSUE TITLE
Map Server Crash 8218337

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5828] opened 2021-04-04 03:19 UTC
* **rAthena Hash**: 8218337

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: Map Server Crash

* **Display on Map Server**:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000499a5a in clif_send (buf=buf@entry=0x7fffffffd9aa, len=len@entry=6,
    bl=<optimized out>, type=type@entry=CLAN) at clif.cpp:703
703 

* **GDB BT Full**:

(gdb) bt full
#0  0x0000000000499a5a in clif_send (buf=buf@entry=0x7fffffffd9aa, len=len@entry=6,
    bl=<optimized out>, type=type@entry=CLAN) at clif.cpp:703
        i = 299
        sd = 0xbec0a20
        tsd = <optimized out>
        p = 0x0
        g = 0x0
        bg = std::shared_ptr (empty) 0x0
        x0 = 0
        x1 = 0
        y0 = 0
        y1 = 0
        fd = <optimized out>
        __FUNCTION__ = "clif_send"
#1  0x00000000004ab191 in clif_clan_onlinecount (clan=clan@entry=0x7fffdf8f7dac) at clif.cpp:19951
        buf = "\210\t\364\001\364\001"
        sd = <optimized out>
#2  0x00000000004740f0 in clan_member_joined (sd=sd@entry=0xbb04160) at clan.cpp:131
        clan = 0x7fffdf8f7dac
        index = <optimized out>
        sd = 0xbb04160
#3  0x000000000054cb90 in pc_reg_received (sd=0xbb04160) at pc.cpp:1925
        i = 0 '\000'
        __FUNCTION__ = "pc_reg_received"
#4  0x00000000004cfc8e in intif_parse_Registers (fd=<optimized out>) at intif.cpp:1475
        flag = 1
        sd = 0xbb04160
        account_id = <optimized out>
        char_id = <optimized out>
        node = <optimized out>
        type = <optimized out>
#5  0x00000000004d4cd5 in intif_parse (fd=fd@entry=11) at intif.cpp:3760
        packet_len = 16
        cmd = <optimized out>
---Type <return> to continue, or q <return> to quit---
#6  0x0000000000473777 in chrif_parse (fd=11) at chrif.cpp:1773
        r = <optimized out>
        cmd = 14340
        packet_len = <optimized out>
#7  0x000000000040d4a5 in do_sockets (next=<optimized out>) at socket.cpp:1024
        rfd = {fds_bits = {2048, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 18930}
        ret = <optimized out>
        i = 11
#8  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:381
No locals.
(gdb)
```

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2021-04-06 12:20
Duplicate of #5376

**Closed by Lemongrass3110** 2021-04-06 12:20 UTC
Labels: type:bug
