### ISSUE TITLE
Arm Cannon should not have animation when it is IC

### ISSUE THREAD

**Issue by Raf4h** [rathena/rathena#3045] opened 2018-04-11 12:27 UTC
* **rAthena Hash**: ae69e506263f9b183c945f49b1d88c5fc2b73a6a

* **Client Date**: 2017-06-07

* **Server Mode**: RE

* **Description of Issue**: On oficial servers, the skill of mechanic, Arm Cannon, when it's instant cast, have not any animation, similar to Acid Demo, Hells plant, Chain Lightining. The problem here in rathena, is that right now, Arm Cannon have two 2 animations, one when the cast time starts and one when it ends. Other skills such as Acid Demo and Hells plant, have just one animation, the first, when the cast starts, so if the player is Instant Cast, there is no cast, so there is no animation.
  * Result: There is an Extra Animation so even instant cast, the skill on rathena have animation.
  * Expected Result: none animation ability 
  * How to Reproduce: Pick a Meca, put DEX*2+INT= 530, Use Arm Cannon, see the caracterer do animation 
  * Official Information: Kro Arrm Cannon with cast time:
https://gfycat.com/gifs/detail/CharmingSpitefulDesertpupfish
Kro arm Cannon with no cast time:
https://gfycat.com/gifs/detail/ChiefBlueArmyant
Video on Iro testing specific that:
https://www.youtube.com/watch?v=OBNu8zM6xeE
Videos of Kro/Iro with a meca instant cast using arm cannon:
https://www.youtube.com/watch?v=c9inl9JuyOQ
https://www.youtube.com/watch?v=c9inl9JuyOQ

  

* **Modifications that may affect results**:

**Comment by erimoa1989** [comment] 2018-04-11 13:32
is an old behavior, this has been updated for more than a year.

**Comment by Raf4h** [comment] 2018-04-11 13:41
@erimoa1989 do you have the patch notes a bout that change?

**Comment by aleos89** [comment] 2018-04-11 17:44
Duplicate of #829.

**Closed by aleos89** 2018-04-11 17:44 UTC
Labels: status:duplicate
