### ISSUE TITLE
Crash with summon

### ISSUE THREAD

**Issue by van84** [rathena/rathena#182] opened 2014-12-28 07:19 UTC
REV 17004

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000055b2e2 in status_get_class.part.33.22697 (bl=0x283cf524) at status.c:6509
6509                    case BL_MOB:    return ((TBL_MOB*)bl)->vd->class_; // Class used on all code should be the view class of the mob.
#0  0x000000000055b2e2 in status_get_class.part.33.22697 (bl=0x283cf524) at status.c:6509
#1  0x000000000056ff5a in status_get_class (bl=0x283cf524) at status.c:6506
#2  0x0000000000463215 in battle_calc_cardfix.part.18.55806 (attack_type=1, src=0x283cf524, target=0x21ebdd80, nk=0, s_ele=11, s_ele_=11, damage=1034067, left=0, flag=273) at battle.c:462
#3  0x000000000047ccb5 in battle_calc_cardfix (attack_type=<optimized out>, src=<optimized out>, target=<optimized out>, nk=<optimized out>, s_ele=<optimized out>, s_ele_=<optimized out>, damage=<optimized out>, left=<optimized out>, flag=<optimized out>) at battle.c:454
#4  battle_calc_weapon_attack.56032 (src=0x283cf524, target=0x21ebdd80, skill_id=2307, skill_lv=5, wflag=0) at battle.c:4767
#5  0x000000000045b815 in battle_calc_attack (attack_type=1, bl=0x283cf524, target=0x21ebdd80, skill_id=2307, skill_lv=5, count=0) at battle.c:5917
#6  0x00000000004aa7bf in skill_attack.part.59.46386 (attack_type=1, src=0x283cf524, dsrc=0x283cf524, bl=0x21ebdd80, skill_id=2307, skill_lv=5, tick=3452416138, flag=8192) at skill.c:2669
#7  0x00000000004ef138 in skill_attack (attack_type=1, src=0x283cf524, dsrc=0x283cf524, bl=0x21ebdd80, skill_id=2307, skill_lv=5, tick=3452416138, flag=8192) at skill.c:2644
#8  0x000000000049294c in skill_attack_area.part.62.46491 (bl=0x21ebdd80, ap=0x7fffffffd8c0) at skill.c:16176
#9  0x00000000004d75c3 in skill_attack_area (bl=0x21ebdd80, ap=0x7fffffffd8c0) at skill.c:16145
#10 0x00000000005f524d in map_foreachinpath (func=0x4d7590 <skill_attack_area>, m=861, x0=115, y0=75, x1=114, y1=74, range=1024, length=10, type=603) at map.c:1207
#11 0x00000000004b6e7c in skill_castend_damage_id.part.54.46362 (src=0x283cf524, bl=0x1ce1ccb0, skill_id=2307, skill_lv=5, tick=3452416138, flag=0) at skill.c:4089
#12 0x00000000004f09ea in skill_castend_damage_id (src=0x283cf524, bl=0x1ce1ccb0, skill_id=2307, skill_lv=5, tick=3452416138, flag=0) at skill.c:3835
#13 0x00000000004f1e3e in skill_castend_id (tid=-1, tick=3452416138, id=111267707, data=0) at skill.c:10581
#14 0x0000000000446189 in unit_skilluse_id2 (src=0x283cf524, target_id=5393847, skill_id=2307, skill_lv=5, casttime=0, castcancel=0) at unit.c:1593
#15 0x000000000052fca8 in mobskill_use.part.14.34781 (md=0x283cf524, tick=3452416113, event=-1) at mob.c:3295
#16 0x000000000054aab5 in mobskill_use (md=0x283cf524, tick=3452416113, event=-1) at mob.c:3117
#17 0x00000000004476ea in unit_attack_timer_sub (src=0x283cf524, tid=97164, tick=3452416113) at unit.c:2130
#18 0x00000000004479db in unit_attack_timer.79948 (tid=97164, tick=3452416113, id=111267707, data=0) at unit.c:2184
#19 0x00000000004202a0 in do_timer (tick=3452416138) at timer.c:371
#20 0x000000000041bc95 in main (argc=1, argv=0x7fffffffe348) at core.c:375
#0  0x000000000055b2e2 in status_get_class.part.33.22697 (bl=0x283cf524) at status.c:6509
No locals.
#1  0x000000000056ff5a in status_get_class (bl=0x283cf524) at status.c:6506
No locals.
#2  0x0000000000463215 in battle_calc_cardfix.part.18.55806 (attack_type=1, src=0x283cf524, target=0x21ebdd80, nk=0, s_ele=11, s_ele_=11, damage=1034067, left=0, flag=273) at battle.c:462
        sd = 0x0
        tsd = 0x21ebdd80
        cardfix = 0
        t_class = 4061
        s_class = 2307
        s_race2 = 0
        t_race2 = 0
        sstatus = 0x903
        tstatus = 0x4eba10 <skill_get_nk+25>
        i = 569106568
#3  0x000000000047ccb5 in battle_calc_cardfix (attack_type=<optimized out>, src=<optimized out>, target=<optimized out>, nk=<optimized out>, s_ele=<optimized out>, s_ele_=<optimized out>, damage=<optimized out>, left=<optimized out>, flag=<optimized out>) at battle.c:454
No locals.
#4  battle_calc_weapon_attack.56032 (src=0x283cf524, target=0x21ebdd80, skill_id=2307, skill_lv=5, wflag=0) at battle.c:4767
        sd = 0x0
        tsd = 0x21ebdd80
        wd = {damage = 1034067, damage2 = 0, type = 0, div_ = 1, amotion = 70, dmotion = 400, blewcount = 0, flag = 273, miscflag = 0, dmg_lv = ATK_DEF}
        tstatus = 0x21ebe088
        right_element = 11
        left_element = 11
#5  0x000000000045b815 in battle_calc_attack (attack_type=1, bl=0x283cf524, target=0x21ebdd80, skill_id=2307, skill_lv=5, count=0) at battle.c:5917
        d = {damage = 28192165330945, damage2 = 6477560, type = -10736, div_ = 32767, amotion = 5701721, dmotion = 0, blewcount = 675083556, flag = 2645, miscflag = 569105792, dmg_lv = ATK_NONE}
#6  0x00000000004aa7bf in skill_attack.part.59.46386 (attack_type=1, src=0x283cf524, dsrc=0x283cf524, bl=0x21ebdd80, skill_id=2307, skill_lv=5, tick=3452416138, flag=8192) at skill.c:2669
        dmg = {damage = 543249, damage2 = 0, type = 0, div_ = 1, amotion = 70, dmotion = 400, blewcount = 0, flag = 273, miscflag = 0, dmg_lv = ATK_DEF}
        sstatus = 0x283cf7c4
        tstatus = 0x21ebe088
        tsc = 0x21ebe0e0
        sd = 0x0
        tsd = 0x21ebdd80
        rmdamage = 0 '\000'
        type = 0
        shadow_flag = 0 '\000'
        additional_effects = 0 '\000'
#7  0x00000000004ef138 in skill_attack (attack_type=1, src=0x283cf524, dsrc=0x283cf524, bl=0x21ebdd80, skill_id=2307, skill_lv=5, tick=3452416138, flag=8192) at skill.c:2644
No locals.
#8  0x000000000049294c in skill_attack_area.part.62.46491 (bl=0x21ebdd80, ap=0x7fffffffd8c0) at skill.c:16176
        src = 0x283cf524
        dsrc = 0x283cf524
        atk_type = 1
        skill_id = 2307
        skill_lv = 5
        flag = 0
        type = 131072
        tick = 3452416138
#9  0x00000000004d75c3 in skill_attack_area (bl=0x21ebdd80, ap=0x7fffffffd8c0) at skill.c:16145
No locals.
#10 0x00000000005f524d in map_foreachinpath (func=0x4d7590 <skill_attack_area>, m=861, x0=115, y0=75, x1=114, y1=74, range=1024, length=10, type=603) at map.c:1207
        returnCount = 5563853
        bl = 0x0
        bx = 15
        by = 10
        k = 0
        xi = 1840
        yi = 1200
        xu = 1840
        yu = 1200
        mx1 = 117
        my1 = 77
        ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffffffda68, reg_save_area = 0x7fffffffd930}}
#11 0x00000000004b6e7c in skill_castend_damage_id.part.54.46362 (src=0x283cf524, bl=0x1ce1ccb0, skill_id=2307, skill_lv=5, tick=3452416138, flag=0) at skill.c:4089
        sd = 0x0
        tstatus = 0x1ce1cfb8
        sc = 0x0
        tsc = 0x0
#12 0x00000000004f09ea in skill_castend_damage_id (src=0x283cf524, bl=0x1ce1ccb0, skill_id=2307, skill_lv=5, tick=3452416138, flag=0) at skill.c:3835
No locals.
#13 0x00000000004f1e3e in skill_castend_id (tid=-1, tick=3452416138, id=111267707, data=0) at skill.c:10581
        sd = 0x0
        md = 0x283cf524
        ud = 0x283cf544
        sc = 0x1ce1d010
        inf = 131072
        inf2 = 32767
        flag = 0
#14 0x0000000000446189 in unit_skilluse_id2 (src=0x283cf524, target_id=5393847, skill_id=2307, skill_lv=5, casttime=0, castcancel=0) at unit.c:1593
        ud = 0x283cf544
        tstatus = 0x1ce1cfb8
        sc = 0x0
        sd = 0x0
        tick = 3452416138
        combo = 0
        range = 11
#15 0x000000000052fca8 in mobskill_use.part.14.34781 (md=0x283cf524, tick=3452416113, event=-1) at mob.c:3295
        c2 = 0
        flag = 1
        ms = 0x7fffeea26e64
        bl = 0x283cf824
        fmd = 0x0
        i = 6
        j = 675083556
        n = 6
#16 0x000000000054aab5 in mobskill_use (md=0x283cf524, tick=3452416113, event=-1) at mob.c:3117
No locals.
#17 0x00000000004476ea in unit_attack_timer_sub (src=0x283cf524, tid=97164, tick=3452416113) at unit.c:2130
        target = 0x1ce1ccb0
        ud = 0x283cf544
        sstatus = 0x283cf7c4
        sd = 0x0
        md = 0x283cf524
        range = 2
#18 0x00000000004479db in unit_attack_timer.79948 (tid=97164, tick=3452416113, id=111267707, data=0) at unit.c:2184
        bl = 0x283cf524
#19 0x00000000004202a0 in do_timer (tick=3452416138) at timer.c:371
        tid = 97164
        diff = -25
#20 0x000000000041bc95 in main (argc=1, argv=0x7fffffffe348) at core.c:375
        next = 50
  Id   Target Id         Frame
* 1    Thread 0x7ffff7fec740 (LWP 22537) "map-server" 0x000000000055b2e2 in status_get_class.part.33.22697 (bl=0x283cf524) at status.c:6509

Thread 1 (Thread 0x7ffff7fec740 (LWP 22537)):
#0  0x000000000055b2e2 in status_get_class.part.33.22697 (bl=0x283cf524) at status.c:6509
No locals.
#1  0x000000000056ff5a in status_get_class (bl=0x283cf524) at status.c:6506
No locals.
#2  0x0000000000463215 in battle_calc_cardfix.part.18.55806 (attack_type=1, src=0x283cf524, target=0x21ebdd80, nk=0, s_ele=11, s_ele_=11, damage=1034067, left=0, flag=273) at battle.c:462
        sd = 0x0
        tsd = 0x21ebdd80
        cardfix = 0
        t_class = 4061
        s_class = 2307
        s_race2 = 0
        t_race2 = 0
        sstatus = 0x903
        tstatus = 0x4eba10 <skill_get_nk+25>
        i = 569106568
#3  0x000000000047ccb5 in battle_calc_cardfix (attack_type=<optimized out>, src=<optimized out>, target=<optimized out>, nk=<optimized out>, s_ele=<optimized out>, s_ele_=<optimized out>, damage=<optimized out>, left=<optimized out>, flag=<optimized out>) at battle.c:454
No locals.
#4  battle_calc_weapon_attack.56032 (src=0x283cf524, target=0x21ebdd80, skill_id=2307, skill_lv=5, wflag=0) at battle.c:4767
        sd = 0x0
        tsd = 0x21ebdd80
        wd = {damage = 1034067, damage2 = 0, type = 0, div_ = 1, amotion = 70, dmotion = 400, blewcount = 0, flag = 273, miscflag = 0, dmg_lv = ATK_DEF}
        tstatus = 0x21ebe088
        right_element = 11
        left_element = 11
#5  0x000000000045b815 in battle_calc_attack (attack_type=1, bl=0x283cf524, target=0x21ebdd80, skill_id=2307, skill_lv=5, count=0) at battle.c:5917
        d = {damage = 28192165330945, damage2 = 6477560, type = -10736, div_ = 32767, amotion = 5701721, dmotion = 0, blewcount = 675083556, flag = 2645, miscflag = 569105792, dmg_lv = ATK_NONE}
#6  0x00000000004aa7bf in skill_attack.part.59.46386 (attack_type=1, src=0x283cf524, dsrc=0x283cf524, bl=0x21ebdd80, skill_id=2307, skill_lv=5, tick=3452416138, flag=8192) at skill.c:2669
        dmg = {damage = 543249, damage2 = 0, type = 0, div_ = 1, amotion = 70, dmotion = 400, blewcount = 0, flag = 273, miscflag = 0, dmg_lv = ATK_DEF}
        sstatus = 0x283cf7c4
        tstatus = 0x21ebe088
        tsc = 0x21ebe0e0
        sd = 0x0
        tsd = 0x21ebdd80
        rmdamage = 0 '\000'
        type = 0
        shadow_flag = 0 '\000'
        additional_effects = 0 '\000'
#7  0x00000000004ef138 in skill_attack (attack_type=1, src=0x283cf524, dsrc=0x283cf524, bl=0x21ebdd80, skill_id=2307, skill_lv=5, tick=3452416138, flag=8192) at skill.c:2644
No locals.
#8  0x000000000049294c in skill_attack_area.part.62.46491 (bl=0x21ebdd80, ap=0x7fffffffd8c0) at skill.c:16176
        src = 0x283cf524
        dsrc = 0x283cf524
        atk_type = 1
        skill_id = 2307
        skill_lv = 5
        flag = 0
        type = 131072
        tick = 3452416138
#9  0x00000000004d75c3 in skill_attack_area (bl=0x21ebdd80, ap=0x7fffffffd8c0) at skill.c:16145
No locals.
#10 0x00000000005f524d in map_foreachinpath (func=0x4d7590 <skill_attack_area>, m=861, x0=115, y0=75, x1=114, y1=74, range=1024, length=10, type=603) at map.c:1207
        returnCount = 5563853
        bl = 0x0
        bx = 15
        by = 10
        k = 0
        xi = 1840
        yi = 1200
        xu = 1840
        yu = 1200
        mx1 = 117
        my1 = 77
        ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffffffda68, reg_save_area = 0x7fffffffd930}}
#11 0x00000000004b6e7c in skill_castend_damage_id.part.54.46362 (src=0x283cf524, bl=0x1ce1ccb0, skill_id=2307, skill_lv=5, tick=3452416138, flag=0) at skill.c:4089
        sd = 0x0
        tstatus = 0x1ce1cfb8
        sc = 0x0
        tsc = 0x0
#12 0x00000000004f09ea in skill_castend_damage_id (src=0x283cf524, bl=0x1ce1ccb0, skill_id=2307, skill_lv=5, tick=3452416138, flag=0) at skill.c:3835
No locals.
#13 0x00000000004f1e3e in skill_castend_id (tid=-1, tick=3452416138, id=111267707, data=0) at skill.c:10581
        sd = 0x0
        md = 0x283cf524
        ud = 0x283cf544
        sc = 0x1ce1d010
        inf = 131072
        inf2 = 32767
        flag = 0
#14 0x0000000000446189 in unit_skilluse_id2 (src=0x283cf524, target_id=5393847, skill_id=2307, skill_lv=5, casttime=0, castcancel=0) at unit.c:1593
        ud = 0x283cf544
        tstatus = 0x1ce1cfb8
        sc = 0x0
        sd = 0x0
        tick = 3452416138
        combo = 0
        range = 11
#15 0x000000000052fca8 in mobskill_use.part.14.34781 (md=0x283cf524, tick=3452416113, event=-1) at mob.c:3295
        c2 = 0
        flag = 1
        ms = 0x7fffeea26e64
        bl = 0x283cf824
        fmd = 0x0
        i = 6
        j = 675083556
        n = 6
#16 0x000000000054aab5 in mobskill_use (md=0x283cf524, tick=3452416113, event=-1) at mob.c:3117
No locals.
#17 0x00000000004476ea in unit_attack_timer_sub (src=0x283cf524, tid=97164, tick=3452416113) at unit.c:2130
        target = 0x1ce1ccb0
        ud = 0x283cf544
        sstatus = 0x283cf7c4
        sd = 0x0
        md = 0x283cf524
        range = 2
#18 0x00000000004479db in unit_attack_timer.79948 (tid=97164, tick=3452416113, id=111267707, data=0) at unit.c:2184
        bl = 0x283cf524
#19 0x00000000004202a0 in do_timer (tick=3452416138) at timer.c:371
        tid = 97164
        diff = -25
#20 0x000000000041bc95 in main (argc=1, argv=0x7fffffffe348) at core.c:375
        next = 50
```

**Comment by van84** [comment] 2015-01-04 14:53
it seems to be the @clone function.

i cannot reproduce it at will.

**Comment by MrAntares** [comment] 2015-01-05 09:59
I had similar issued for years now. Usually @summoning many mobs or producing many @clones will eventually crash the server (but not because of the load) in about 5 minutes. About 25+... but below 100 usually does it. On summons I usually use 100 as time and the summoned mobs usually kill other mobs when the issue appears. I always had a feeling that it might be an overflow of some kind.. maybe because of the too many actions they try to make?

**Comment by cydh** [comment] 2015-01-05 13:59
let's say, to simply test, if skill used is 2307 (LG_CANNONSPEAR), can I crash my server by cloning myself and let it attack random mobs. hmm

and ur rev is pretty old (I don't have backup for that rev, I don't have & hate to reinit dbs for that rev, and I moved on from that SVN already), just hopping I can crash my server with last rev.

**Comment by MrAntares** [comment] 2015-01-06 09:30
I did crash my server a week ago with 2014.12.17 rev. I suppose it's still a problem.

**Comment by cydh** [comment] 2015-01-06 09:54
I failed to crash my server

@MrAntares give us ur coredump

**Comment by Akkarinage** [comment] 2015-05-18 13:16
@MrAntares an update please?

**Comment by Lemongrass3110** [comment] 2015-11-05 12:11
@MrAntares are you still able to reproduce this or can we close this? If yes please state if you used renewal or pre-renewal and the git hash please. Thank you

**Comment by Lemongrass3110** [comment] 2015-12-15 22:40
Almost a year since last reply from issue creator.

**Closed by Lemongrass3110** 2015-12-15 22:40 UTC
Labels: bug:core, mode:missing, server:map, status:git hash missing, status:needs more info
