### ISSUE TITLE
@loadnpc

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#1431] opened 2016-07-17 13:14 UTC
Renewal
Last Changed Author: aleos89
Last Changed Rev: 18387
Last Changed Date: 2016-06-18 17:29:17 +0200 (Sat, 18 Jun 2016)

I have bossnia enabled. I made an npc that can @unloadnpc and @loadnpc the npc. 

So heres my problem:
@reloadscript <- works okay
@unloadnpc <- manager npc init unloads bossnia, works fine
@loadnpc <- gm loads the event by either command or manager npc, still working fine
@unloadnpc <- gm unloads the event by either command or manager npc, still working fine
@loadnpc <- gm tries to load the event by either command or manager npc, NOT WORKING ANYMORE

After this, I can't load the same npc anymore with the same command/script.

**Comment by Everade** [comment] 2016-07-17 21:17
Known issue since quite a while

simply add some random \\ inbetween and it will work.

like 

@loadnpc npc/test///npc.txt

next time add another /
next time add another /
and so on

That's my workaround for now...

**Comment by secretdataz** [comment] 2016-07-18 00:56
Duplicate of #203

**Closed by secretdataz** 2016-07-18 00:56 UTC
Labels: bug:core
