### ISSUE TITLE
2013-08-07 delay view

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#851] opened 2015-12-21 16:03 UTC
Hi folks,

Sorry if this will be a double post. This might be a source issue or client perhaps?

Linking the issue to the thread I've created.
Link: https://rathena.org/board/topic/104176-is-this-normal-see-attached-picture/#entry294766

Summary:
1. If Player A uses cloak skill and uses sonic blow to Player B. (Player B perspective view is Player A is far away from him/her)
2. If Playing B go near to player B from where he/she attack. Player B view perspective will refresh then player A will appear where player B is originally from (just a cell away)

Please view the link .

Regards!

**Comment by Lemongrass3110** [comment] 2015-12-30 20:04
According to the link which the user supplied it might be position lag issues.

Do you have OFFICIAL WALKPATH enabled or disabled?
Which git hash do you use?

**Comment by Playtester** [comment] 2015-12-31 18:55
I don't know, there should only be position lag if the Assassin was previously hit. Since position lag is caused by the flinch animation. The position of cloaked characters should still be transmitted to the client because e.g. you can see the Assassin with Maya Purple Card.

**Comment by Lemongrass3110** [comment] 2016-01-31 17:49
No answer for more than 1 month.
Closing this.

**Closed by Lemongrass3110** 2016-01-31 17:49 UTC
Labels: status:git hash missing, status:needs more info
