### ISSUE TITLE
[Server Crash] int skill_detonator

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#5011] opened 2020-05-26 04:03 UTC
* **rAthena Hash**: 7cc59c6

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: Crash Generated on int skill_detonator for line `unit->group->unit_id = UNT_USED_TRAPS;`
  * Result: Map-Server Crash
  * Expected Result: No Crash
  * How to Reproduce: Not sure how to reproduce it but the core file generated it
  * Official Information: N/A
  

* **Modifications that may affect results**: Several PR that are not related with the skill.
  
  

See attached for the full bt log. (lines may differ but the code are still the same because of PR)
[bt full skill_detonator.txt](https://github.com/rathena/rathena/files/4679833/bt.full.skill_detonator.txt)

**Comment by aleos89** [comment] 2020-06-18 02:19
Duplicate of #3268.

**Closed by aleos89** 2020-06-18 02:19 UTC
Labels: status:duplicate
