### ISSUE TITLE
Crash on Map.cpp (map_delblock)

### ISSUE THREAD

**Issue by samers1** [rathena/rathena#6994] opened 2022-05-31 04:31 UTC
I haved this map-server crash in all my servers.
I believe that problem is on rathena emulator.

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/marimms.silva/history-reborn/map-server...done.
[New LWP 12392]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000536015 in map_delblock (bl=bl@entry=0x7f280adc7ce4)
    at map.cpp:459
459                             mapdata->block[pos] = bl->next;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64                                                                                                                                                              keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-51.el7_9.x86_64 libcom_err-1.4                                                                                                                                                             2.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstd                                                                                                                                                             c++-4.8.5-44.el7.x86_64 mariadb-libs-5.5.68-1.el7.x86_64 openssl-libs-1.0.2k-25.                                                                                                                                                             el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64
(gdb) bt full
#0  0x0000000000536015 in map_delblock (bl=bl@entry=0x7f280adc7ce4)
    at map.cpp:459
        pos = <optimized out>
        bl = 0x7f280adc7ce4
#1  0x000000000072293e in unit_remove_map_ (bl=bl@entry=0x7f280adc7ce4,
    clrtype=<optimized out>, file=file@entry=0x80f803 "unit.cpp",
    line=line@entry=1325,
    func=func@entry=0x80fca8 <unit_warp(block_list*, short, short, short, clr_ty                                                                                                                                                             pe)::__FUNCTION__> "unit_warp") at unit.cpp:3281
        ud = 0x7f280adc7d04
        sc = <optimized out>
        __FUNCTION__ = "unit_remove_map_"
#2  0x00000000007231b9 in unit_warp (bl=bl@entry=0x7f280adc7ce4, m=1124,
    x=<optimized out>, y=<optimized out>, type=type@entry=CLR_TELEPORT)
    at unit.cpp:1325
        ud = 0x7f280adc7d04
        __FUNCTION__ = "unit_warp"
#3  0x00000000007235c2 in unit_teleport_timer (tid=<optimized out>,
    tick=<optimized out>, id=<optimized out>, data=14) at unit.cpp:208
        bl = 0x7f280adc7ce4
#4  0x000000000072de00 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 2510424
        diff = 0
---Type <return> to continue, or q <return> to quit---
        __FUNCTION__ = "do_timer"
#5  0x000000000040d9ce in main (argc=1, argv=0x7fff681a35d8) at core.cpp:380
        next = <optimized out>

**Comment by samers1** [comment] 2022-05-31 04:57
The same correction?
https://github.com/teenshowstep/rathena/pull/73

**Comment by aleos89** [comment] 2022-05-31 21:09
If we can find a solid way to reproduce it, it can help with debugging. There are already some security checks in place so something else is invalid at that point resulting in the crash.

**Comment by aleos89** [comment] 2022-06-02 16:24
I found an older report. I'll mark this as a duplicate of #5921.

**Closed by aleos89** 2022-06-02 16:24 UTC
Labels: status:duplicate
