### ISSUE TITLE
Thief's skill TF_DOUBLE (Double Attack) support attack effect

### ISSUE THREAD

**Issue by rAthenaCN** [rathena/rathena#3232] opened 2018-06-21 04:05 UTC
* **rAthena Hash**: 4633ab5

* **Client Date**: 20170614

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: https://forum.gamer.com.tw/Co.php?bsn=04212&sn=2782816
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2018-06-21 09:34
Duplicate of #1788?
See pull request #2982

**Closed as completed** 2018-06-21 09:35 UTC
Labels: status:duplicate
