### ISSUE TITLE
Dragon Breath bug

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#994] opened 2016-03-01 07:05 UTC
i test dragon breath skills, its not like a dragon breath before.
check the picture i think for clearly

![screenchenragnarok001](https://cloud.githubusercontent.com/assets/15665450/13420162/8e5cbeb0-dfb6-11e5-9c91-c2395f863ba8.jpg)
![screenchenragnarok002](https://cloud.githubusercontent.com/assets/15665450/13420163/8e8fb298-dfb6-11e5-938c-023f58a7471c.jpg)

**Comment by hnomkeng** [comment] 2016-03-01 07:11
out area skill ?

**Comment by reunite-ro** [comment] 2016-03-02 14:02
the area of db

**Comment by Darkelfen** [comment] 2016-03-03 04:02
Confirmed for NC_COLDSLOWER also.

Damage is casted around the caster instead of around the targeted cell.

**Comment by stealth62** [comment] 2016-03-04 05:19
Hello guys i also produced that bug and i found out the line of code might conflicting somehow.

\src\map\skill.c

case NC_COLDSLOWER:
	case NC_ARMSCANNON:
	case RK_DRAGONBREATH:
	case RK_DRAGONBREATH_WATER:
		i = skill_get_splash(skill_id,skill_lv);
		if (battle_config.skill_wall_check)
		map_foreachinshootrange(skill_area_sub,src,skill_get_splash(skill_id, skill_lv),splash_target(src),src,skill_id,skill_lv,tick,flag|BCT_ENEMY|1,skill_castend_damage_id);
		else
			map_foreachinarea(skill_area_sub,src->m,x-i,y-i,x+i,y+i,splash_target(src),src,skill_id,skill_lv,tick,flag|BCT_ENEMY|1,skill_castend_damage_id);
break;

just change to

	case NC_COLDSLOWER:
	case NC_ARMSCANNON:
	case RK_DRAGONBREATH:
	case RK_DRAGONBREATH_WATER:
		i = skill_get_splash(skill_id,skill_lv);
		//if (battle_config.skill_wall_check)
		//	map_foreachinshootrange(skill_area_sub,src,skill_get_splash(skill_id, skill_lv),splash_target(src),src,skill_id,skill_lv,tick,flag|BCT_ENEMY|1,skill_castend_damage_id);
		//else
			map_foreachinarea(skill_area_sub,src->m,x-i,y-i,x+i,y+i,splash_target(src),src,skill_id,skill_lv,tick,flag|BCT_ENEMY|1,skill_castend_damage_id);
break;

**Comment by Darkelfen** [comment] 2016-03-04 06:19
Thanks, I've tested it and indeed it worked; nevertheless, now those skills trespass walls. Do they trespass walls before?.

Psychic Wave vs Dragon Breath wall check test:

Results: 
Psy-wave damage doesn't trespass walls even if targets are within range.
Dragon Breath, Dragon Breath (Water), Cold Slower and Arms Cannon all of them are tresspassing the wall.

![screenglacierro185](https://cloud.githubusercontent.com/assets/7315177/13519441/673be6c2-e1ae-11e5-96cd-c15583b6ce67.jpg)

**Comment by Playtester** [comment] 2016-03-04 06:58
It will probably be automatically fixed once we implement the correct wall check behavior.

Though more interesting would be if Dragon Breath shouldn't be a ground skill in the first place. Does it work on LP on official servers? Need to test that first.

**Comment by stealth62** [comment] 2016-03-04 07:02
its temporary solution for now until we get fix for this im figure it out what this line do
if (battle_config.skill_wall_check)
map_foreachinshootrange(skill_area_sub,src,skill_get_splash(skill_id, skill_lv),splash_target(src),src,skill_id,skill_lv,tick,flag|BCT_ENEMY|1,skill_castend_damage_id);
its causing the dragon breath Damage is casted around the caster instead of around the targeted cell.

**Comment by stealth62** [comment] 2016-03-04 07:04
thank you sir Playtester. Im also comparing in pyschic code the wall check behavior no where to found

**Comment by Playtester** [comment] 2016-03-04 07:14
Well you need to use map_foreachinshootrange instead of map_foreachinarea, but the problem is that you need to give a block_list to it rather than coordinates. If you give "src" to it, it will be around the caster because src = caster.
Unfortunately we don't have the skill block_list in that function at all, only the coordinates.

But before we completely restructure that, we should check if Dragon Breath isn't a unit skill. If it is it should be calling unitsetting instead of map_foreach[...].

Maybe I test that when I'm at home today.

**Comment by stealth62** [comment] 2016-03-04 07:19
i see thank you sir Playtester

**Comment by stealth62** [comment] 2016-03-04 10:57
Sir playster i test dragon breath over land protector(magnetic earth) it works.

**Comment by Playtester** [comment] 2016-03-04 11:55
Okay. That means we need to create a map_foreachinshootarea or move the check to skill_attack.

**Comment by stealth62** [comment] 2016-03-05 02:06
Hello Sir playtester i add dragon breath on unit settings but my problem i dont know the unit id of dragon breath like pyschic wave (0xdf). i also add
UNT_DRAGONBREATH ,
	UNT_DRAGONBREATH_WATER , in

**Comment by Playtester** [comment] 2016-03-05 07:39
If you want to make it a unit skill then you just need to put 0x86 as unit ID. That's the dummy skill unit. Just compare to Thunder Storm.

**Comment by stealth62** [comment] 2016-03-05 08:07
2008,0x86,    ,  0, 1,1000,enemy, 0x010	//RK_DRAGONBREATH
 i tried this one but fails instead of 1hit its become 10hits maybe 0x86 was assigned to other skills. i test 0x7f dragon breath becomes firewall.

**Comment by Playtester** [comment] 2016-03-05 08:24
```2008,0x86,    ,  0, 1:1:1:2:2:2:3:3:4:4,1000,enemy, 0x010	//RK_DRAGONBREATH```
More like this.

Do you mean that it hits once per second, 10 times?
```//-- RK_DRAGONBREATH
2008,0:0:0:1000:1000:1000:1500:1500:2000:2000,2000,0,10000,0,0```
That's because duration is defined as 10000ms here.

You really shouldn't bother so much with it. XD
I will get to it eventually~

**Comment by stealth62** [comment] 2016-03-05 08:52
thank you very much sir playtester haha. im curius why its 10hits instead of one im following the structure database
Skill ID,Unit ID,Unit ID 2,Layout,Range,Interval,Target,Flag
2008,0x86,    ,  1:1:1:2:2:2:3:3:4:4, 1,1000,enemy, 0x080	//RK_DRAGONBREATH   result 10hits
2008,0x86,    ,  1:1:1:2:2:2:3:3:4:4, -1,1000,enemy, 0x080	//RK_DRAGONBREATH   result no hits
2008,0x86,    ,  1:1:1:2:2:2:3:3:4:4, 0,1000,enemy, 0x080	//RK_DRAGONBREATH   result  10hits
2008,0x86,    ,  1:1:1:2:2:2:3:3:4:4, 500,1000,enemy, 0x080	//RK_DRAGONBREATH   result  10hits
layout would be splash damage around the targeted cell., interval animation of hit,  range ??? unknown

**Comment by stealth62** [comment] 2016-03-05 09:15
i used the flag 0x018 instead of 0x080 and the result dragon breath not bypassing the wall you can watch my test here.   :)

**Comment by Playtester** [comment] 2016-03-05 09:24
The problem is with how you call skill_unitsetting.

The skill effect lasts 10 seconds right now and you set interval to 1s second, so it hits 10 times. You need to make the skill effect last only 100ms.

**Comment by stealth62** [comment] 2016-03-05 09:41
i didnt call skill_unitsetting i depent only on psychic structure inside skill.c and skill.h
 in skill.c i add
	case WM_POEMOFNETHERWORLD:
	case SO_PSYCHIC_WAVE:
	case RK_DRAGONBREATH:
	case RK_DRAGONBREATH_WATER:
and i remove
	case NC_COLDSLOWER:
	case NC_ARMSCANNON:
	//case RK_DRAGONBREATH:
//	case RK_DRAGONBREATH_WATER:
		i = skill_get_splash(skill_id,skill_lv);
		//if (battle_config.skill_wall_check)
			//map_foreachinshootrange(skill_area_sub,src,skill_get_splash(skill_id, skill_lv),splash_target(src),src,skill_id,skill_lv,tick,flag|BCT_ENEMY|1,skill_castend_damage_id);//orig code please observe
//	else
		map_foreachinarea(skill_area_sub, src->m, x - i, y - i, x + i, y + i, splash_target(src), src, skill_id, skill_lv, tick, flag | BCT_ENEMY | 1, skill_castend_damage_id);	
break;

in skill.h i add dragon breath

UNT_GLITTERING_GREED,
UNT_B_TRAP,
UNT_FIRE_RAIN,
UNT_DRAGONBREATH,
UNT_DRAGONBREATH_WATER,
	/**
	 * Guild Auras
	 **/
	UNT_GD_LEADERSHIP = 0xc1,
	UNT_GD_GLORYWOUNDS = 0xc2,
	UNT_GD_SOULCOLD = 0xc3,
	UNT_GD_HAWKEYES = 0xc4,

	UNT_MAX = 0x190

**Comment by Playtester** [comment] 2016-03-05 09:43
@stealth62 
Honestly that code doesn't make much sense.


Alright from my tests arrow shower and dragon breath behave exactly the same, but they do NOT behave like unit skills:
- Works on LP
- Check line of sight from cast center rather than caster (you can target wall and make it shoot through it like that)

**Comment by stealth62** [comment] 2016-03-05 09:49
Its only a test im new here and learning how to mod rathena source code.

**Comment by Playtester** [comment] 2016-03-05 09:52
Well if you code a unit skill and define units, you need to activate the skill by calling skill_unitsetting just like Arrow Shower does.

The code you put above would just hit stuff in an area, it would not make it deal 10 hits, it will in fact change nothing except that the damage is now from ground center and goes through walls.

**Comment by stealth62** [comment] 2016-03-05 09:53
Can you show me the screen shot of your work sir im confuse Check line of sight from cast center rather than caster (you can target wall and make it shoot through it like that)

**Comment by Playtester** [comment] 2016-03-05 09:55
Just wait for a day then I'll commit something need to work on this now.

**Comment by stealth62** [comment] 2016-03-05 09:56
hoping its like  doesn't trespass walls and around the targeted cell  :)

**Comment by stealth62** [comment] 2016-03-05 09:57
no i mean the screen shot of skill dragon breath testing on monster not the code.

**Comment by stealth62** [comment] 2016-03-05 09:59
Thank you very much sir Playtester for the time  :+1:

**Closed** 2016-03-05 17:02 UTC
Labels: bug:skill, mode:prerenewal, mode:renewal, priority:low, server:map, status:confirmed

**Comment by stealth62** [comment] 2016-03-05 17:35
Earlier i just did a fix for myself :) now dragon breath will not tresspass walls and damage applied on targeted cell

in skill.c

struct skill_unit_group *skill_unitsetting(struct block_list *src, uint16 skill_id, uint16 skill_lv, int16 x, int16 y, int flag)

case SO_ELECTRICWALK:
		limit = skill_get_time2(skill_id, skill_lv);
		break;
	case NC_COLDSLOWER:
	case NC_ARMSCANNON:
	case RK_DRAGONBREATH:
	case RK_DRAGONBREATH_WATER:
		limit=100;
		break;
	case GN_WALLOFTHORN:
		// Turns to Firewall
		if( flag&1 )
			limit = 3000;
		val3 = (x<<16)|y;
		break;

and here

int skill_castend_pos2(struct block_list* src, int x, int y, uint16 skill_id, uint16 skill_lv, unsigned int tick, int flag)

case RK_WINDCUTTER:
		clif_skill_damage(src, src, tick, status_get_amotion(src), 0, -30000, 1, skill_id, skill_lv, 6);
	case NC_COLDSLOWER:
	case NC_ARMSCANNON:
	case RK_DRAGONBREATH:
	case RK_DRAGONBREATH_WATER:
		skill_unitsetting(src, skill_id, skill_lv, x, y, 0);
	//	i = skill_get_splash(skill_id,skill_lv);
		//if (battle_config.skill_wall_check)
			//map_foreachinshootrange(skill_area_sub,src,skill_get_splash(skill_id, skill_lv),splash_target(src),src,skill_id,skill_lv,tick,flag|BCT_ENEMY|1,skill_castend_damage_id);//orig code please observe
//	else
	//	map_foreachinarea(skill_area_sub, src->m, x - i, y - i, x + i, y + i, splash_target(src), src, skill_id, skill_lv, tick, flag | BCT_ENEMY | 1, skill_castend_damage_id);	
		break;

	case SO_ARRULLO:

finally 

db\re\skill_unit_db.txt
2008,0x86,    , 1:1:1:2:2:2:3:3,1,1000,enemy, 0x018	//RK_DRAGONBREATH
5004,0x86,    , 1:1:1:2:2:2:3:3,1,1000,enemy, 0x018	//RK_DRAGONBREATH_WATER
