### ISSUE TITLE
OldGlastHeim Temporal Boots enchants

### ISSUE THREAD

**Issue by XDXDMAN** [rathena/rathena#346] opened 2015-03-16 15:07 UTC
OldGlastHeim Temporal Boots enchants NPC not exist
http://irowiki.org/wiki/Old_Glast_Heim

**Comment by Barigas** [comment] 2015-04-15 19:46
What else info is needed here? The information stated on irowiki is correct. The only thing worth to add are that the random chants have 2% to proc and are dispelled on boots switch, and that the dex temporal boots -0.5fixed cast time bonus at 120 and more base dex works before Sacramenti buff. The last change made on kro was that the 1000def bonus is changed to 200vit.

**Comment by XDXDMAN** [comment] 2015-04-16 09:48
bug:script [ status:needs more info ]
enchants NPC?

**Comment by Atemo** [comment] 2016-06-30 21:55
Duplicate of #493

**Closed by Atemo** 2016-06-30 21:55 UTC
Labels: bug:script, status:needs more info
