### ISSUE TITLE
NPC_HALLUCINATION should be just a hallucination not reality

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6790] opened 2022-04-03 14:38 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9bc1c53db443d1ceb78d74ef2c9f24d677123072

* **Client Date**: 202111103

* **Server Mode**: RE

* **Description of Issue**: NPC_HALLUCINATION making the buff self-harm, it should just be a hallucination display but what happened was reality. 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2022-04-03 22:41
I dont know what you wanted to write, but I think something was messed up with translation here.

**Comment by mazvi** [comment] 2022-04-04 00:03
Example using skill: Rampage Blast or Power Absorb if player affected by the hallucinaton effect, it will injure the player himself

**Comment by aleos89** [comment] 2022-04-22 17:24
I'm unable to reproduce this on the current master (d617d9f). Had a Bapho Jr inflict Hallucination on me -> cast Rampage Blaster -> damage dealt to targets as normal.

**Comment by Playtester** [comment] 2022-05-03 22:31
The only issue I see with this skill is that it display "Miss" when it doesn't deal any damage. When I tested on officials I noticed it even displays damage when it was blocked (for example an archer attacking into Pneuma), meaning if you are under this status change then you can't tell if the damage is really blocked or not other then by looking at your status window.

**Comment by aleos89** [comment] 2022-05-04 22:17
Fixed in 94c80a9.

**Closed** 2022-05-04 22:18 UTC
Labels: component:core, priority:low, mode:renewal, mode:prerenewal, type:bug
