### ISSUE TITLE
Moving while in Cloaking/Casting(Sage) removes bonus stats from Status Changes E.G food buffs

### ISSUE THREAD

**Issue by Relliksuriv** [rathena/rathena#6720] opened 2022-03-19 16:31 UTC
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  Cloaking Decreases bonus stat when moving
  * Expected Result:   Cloaking should increase Crit not decrease stats
  * How to Reproduce:  Use Cloak e.g. from Mysterious Muffler then move atleast 1 cell and your bonus stats will be reduced.
  * Official Information: 
  

Before Cloaking
![image](https://user-images.githubusercontent.com/97498227/159129778-99ddb177-7afe-4bf8-b1fc-cf83f7e7c658.png)

After Cloaking and moving 1 cell
![image](https://user-images.githubusercontent.com/97498227/159129795-52fe7a42-62df-4dea-bbfe-2eafd649b14f.png)

* **Modifications that may affect results**:

**Comment by Relliksuriv** [comment] 2022-03-20 03:01
So I narrowed it down further its not an exclusive issue with Cloaking but any status that lingers and active and when moving disables the bonus stats from the other Status Changes e.g food buffs.

To replicated:

Use either cloak or walk while casting (Using Elemental Master). If not using food buff no bonus stats will be decreased while when using food buffs it is being removed temporarily thus the decrease in stats as shown above.

**Comment by aleos89** [comment] 2022-03-23 12:31
Duplicate of #6715 and fixed in #6733.

**Closed by aleos89** 2022-03-23 12:31 UTC
Labels: status:duplicate
