### ISSUE TITLE
Windows compile winapi.cpp(164): warning C4800: 'BOOL'

### ISSUE THREAD

**Issue by userid0** [rathena/rathena#2718] opened 2017-12-19 07:28 UTC
* **rAthena Hash**: 
15e509f
* **Client Date**: 

 Windows Compile

* **Server Mode**: 

 Any

* **Description of Issue**: 
  winapi.cpp(164): warning C4800: 'BOOL' : forcing value to bool 'true' or 'false' (performance warning)

**Comment by Lemongrass3110** [comment] 2017-12-19 07:29
Duplicate of #2690

**Closed by Lemongrass3110** 2017-12-19 07:29 UTC
Labels: status:duplicate
