### ISSUE TITLE
Mechanics using madogear shuld recive buffs from  Cantocandidus  and  Assassin Cross of Sunset 

### ISSUE THREAD

**Issue by Raf4h** [rathena/rathena#3366] opened 2018-07-30 01:08 UTC
* **rAthena Hash**: ae69e50

* **Client Date**:  2017-06-07

* **Server Mode**: RE

* **Description of Issue**: in Rathena servers, mechanics using mado can not recive buffs from  Assassin Cross of Sunset or Cantocandidus
  * Result: 
  * Expected Result:  
  * How to Reproduce: 
  * Official Information: https://irowiki.org/wiki/Madogear
IroWiki says specifically even agi up doesn't work, cantocandidus works . And there is no limitaion for assasin, so it should works fine com mado
Limitations
Receiving skills:

When wearing madogear, the player is unable to receive certain supportive skills, such as:

Increase Agility
Heal
Adrenaline Rush
Coluseo Heal**
Renovatio
However, the player can receive Increase Agility from Cantocandidus and Tuna Belly.
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2018-07-30 02:57
Duplicate of #1564. kRO patched this differently than what iRO Wiki states.

**Closed by aleos89** 2018-07-30 02:57 UTC
Labels: status:duplicate, status:invalid

**Comment by ryomahostingph** [comment] 2022-06-19 18:15
@aleos89 having issue again in madogear not receiving buff on mado-ed players
