### ISSUE TITLE
Missing item in character, but show in shop.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#1799] opened 2016-12-15 17:32 UTC
![15380802_10154451288769093_4198188046383855887_n](https://cloud.githubusercontent.com/assets/9112684/21234826/d23961d4-c326-11e6-9f85-54f469232287.jpg)
![15589822_10154475275824093_737943850178668694_n](https://cloud.githubusercontent.com/assets/9112684/21234834/d681d6c2-c326-11e6-8f49-0c6d5a6f9324.jpg)

Character have item not show in  item box, but show in shop only.

sorry, i bad english.

Githash : 2bb92a1
Client date : 2015-09-16

**Comment by aleos89** [comment] 2017-02-07 00:57
I just tested with 4623d37 and was not able to reproduce this. Make sure you're not confusing items that can't be sold from the item_trade database. Also, make sure you merged the new storage system in properly if you're not using a clean rAthena.

**Closed** 2017-02-10 03:32 UTC
Labels: status:unable to reproduce
