### ISSUE TITLE
Memory Leak found when @mapexit

### ISSUE THREAD

**Issue by senjumina** [rathena/rathena#6964] opened 2022-05-19 11:00 UTC
* **rAthena Hash**: 
6ed0359522922308ae3279eb124a54755ab1562f

* **Client Date**: 
20180418

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
 * Memory leak issue:
 
![image](https://user-images.githubusercontent.com/79569639/169277916-dd36e875-446f-44eb-9105-c9c72bc28b7f.png)

  * How to Reproduce: 
Unknown but  pc.cpp line 2850 and 2851 are as follows 

```cpp
bool pc_addautobonus(std::vector<s_autobonus> &bonus, const char *script, short rate, unsigned int dur, uint16 flag, const char *other_script, unsigned int pos, bool onskill)
{
    if (bonus.size() == MAX_PC_BONUS) {
        ShowWarning("pc_addautobonus: Reached max (%d) number of autobonus per character!\n", MAX_PC_BONUS);
        return false;
    }

    if (!onskill) {
        if (!(flag&BF_RANGEMASK))
            flag |= BF_SHORT | BF_LONG; //No range defined? Use both.
        if (!(flag&BF_WEAPONMASK))
            flag |= BF_WEAPON; //No attack type defined? Use weapon.
        if (!(flag&BF_SKILLMASK)) {
            if (flag&(BF_MAGIC | BF_MISC))
                flag |= BF_SKILL; //These two would never trigger without BF_SKILL
            if (flag&BF_WEAPON)
                flag |= BF_NORMAL | BF_SKILL;
        }
    }

    struct s_autobonus entry = {};

    if (rate < -10000 || rate > 10000)
        ShowWarning("pc_addautobonus: Item bonus rate %d exceeds -10000~10000 range, capping.\n", rate);

    entry.rate = cap_value(rate, -10000, 10000);
    entry.duration = dur;
    entry.active = INVALID_TIMER;
    entry.atk_type = flag;
    entry.pos = pos; //--> Line 2850
    entry.bonus_script = aStrdup(script); //--> Line 2851
    entry.other_script = (other_script ? aStrdup(other_script) : NULL);

    bonus.push_back(entry);

    return true;
} 
```

**Comment by Anjuts** [comment] 2022-05-21 04:44
This is confirmed. I also reported this long time ago.

**Comment by aleos89** [comment] 2022-05-23 14:06
Duplicate of #5712.

**Closed by aleos89** 2022-05-23 14:06 UTC
Labels: status:duplicate
