### ISSUE TITLE
Secrament(AB_SECRAMENT) BUG, no have effect skill.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#736] opened 2015-11-03 12:22 UTC
see vdo test (Pre-rewenal) : https://youtu.be/9mtvzbSCAg4

Level	Description
1	Fixed Casting Time Decrease 10%
2	Fixed Casting Time Decrease 20%
3	Fixed Casting Time Decrease 30%
4	Fixed Casting Time Decrease 40%
5	Fixed Casting Time Decrease 50%

**Comment by aleos89** [comment] 2015-11-03 15:14
You're using pre-renewal? There is no fixed cast time in pre-renewal, so that skill is completely useless.

**Comment by hnomkeng** [comment] 2015-11-04 04:47
yes. i using pre-renewal and wait fixed.

**Comment by hnomkeng** [comment] 2015-11-04 04:49
yes pre-rewenal.

**Comment by Lemongrass3110** [comment] 2015-11-04 08:06
Skills and items that are designed for renewal might have no effect on pre-renewal.
If you want to change that please do so yourself.

Closing this because it is working as intended.

**Closed by Lemongrass3110** 2015-11-04 08:06 UTC
Labels: bug:skill, mode:prerenewal, server:map, status:client date missing, status:git hash missing

**Comment by hnomkeng** [comment] 2015-11-04 08:26
@Lemongrass3110  Issues such as renewal.
