### ISSUE TITLE
Rapid Smiting

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3911] opened 2019-02-02 19:23 UTC
* **rAthena Hash**: 

* **Client Date**: 2018-11-07

* **Server Mode**: Renewal

* **Description of Issue**: the ATK is not influencing the Rapid Smiting damage
  * Result: 
  * Expected Result: Damage per stroke = [((ATK + Shield Weight + (Shield Refinement × 4)) × (30% × (Lv. Rapid Smiting)) × 5
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2019-02-09 23:19
Duplicate of #535.

**Closed by aleos89** 2019-02-09 23:19 UTC
Labels: status:duplicate
