### ISSUE TITLE
General Egnigem Cenia Card HP/SP regen timer is reset when receiving buffs

### ISSUE THREAD

**Issue by Hatfun** [rathena/rathena#4150] opened 2019-05-07 00:11 UTC
* **rAthena Hash**: Latest

* **Client Date**: 2017-06-14bRagexeRE

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: When wearing General Egnigem Cenia card, HP and SP are regen every 10 seconds. However, when we receive any type of buff (self skill, support skill from someone else, or item), then the timer gets reset, and we have to wait for a full 10 seconds after the last buff has been applied to get the HP/SP regen again. Said differently, you don't have the HP/SP regen if you get any buff every 9 seconds or less.
  * Expected Result: HP/SP regen should kick in every 10 seconds, no matter what.
  * How to Reproduce: Wear General Egnigem Cenia card, and spam any of the following every less than 10 seconds. The list is non-exhaustive, so there might be other things that resets the HP/SP regen timer:
```
Self targeted skills:
- Two-Hand Quicken
- Counter-Attack
- Parrying
- Concentration
- Magnum Break
- Energy Coat
 
Have a support character spamming these skills on the GEC wearer:
- Any endow weapon from Sage/Prof
- Increase Agility
- Blessing
- Assumptio
- Magnificat
 
Using buff items:
- Concentration Potion, Awakening Potion, Berserk Potion
- Cursed Water
- Stats food
```

**Comment by aleos89** [comment] 2019-05-10 18:13
The issue arises from the bonus structure getting zeroed out every time a player's status is recalculated. This is the reason the timer just "stops" because it's wiped from memory. This applies to other item bonuses that are on a timer as well.

**Comment by NeutralDev** [comment] 2020-01-06 03:15
I'd actually like to add to this issue since I discovered the exact source of where this is occurring. As @aleos89 said, the player's status is recalculated, however, it's actually being recalculated more times than needed, it has to to with this segment in status_change_start in status.cpp:

https://github.com/rathena/rathena/blob/9993639177955cf9cd82035421e8c9a54921c13b/src/map/status.cpp#L11785-L11787

This default is no longer necessary. By removing this, the GEC effect starts working correctly again as intended.

The reason why this default is even here in the first place goes all the way back to [a mid-2014 commit ](https://github.com/rathena/rathena/commit/2732176), which was originally a Hercules commit that we merged. Hercules has since withdrawn these changes and abandoned them, as evidenced by looking at their source. You will not find this default statement or anything of the sort. That being said, this leftover reminent is forcing us to recalculate more times than necessary and is also the reason why GEC effect doesn't work when using other status changes.

**Closed** 2020-01-18 01:30 UTC
Labels: component:core, mode:prerenewal, mode:renewal, priority:low, status:confirmed, type:bug
