### ISSUE TITLE
"Check Equipment Info" with "Show Equip" Unchecked

### ISSUE THREAD

**Issue by ihernandeza** [rathena/rathena#5197] opened 2020-07-09 22:14 UTC
* **rAthena Hash**: 404e9f8

* **Client Date**: 20150513

* **Server Mode**:  Pre_renewal

* **Description of Issue**: 
  * Result: Show Equip "effect" keeps enabled after login, but Show Equip checkmark is not checked
  * Expected Result: Checkmark should appear checked OR Show equip function should be disabled on relog
  * How to Reproduce: 
- Login Two Characters (A and B) and check the option "Show Equip" on Character A
![image](https://user-images.githubusercontent.com/5288207/87095371-a1e9b480-c20e-11ea-8c7f-0125ff1039aa.png)
- Relog the character A (ESC > Character Select > Select Character Again)
- Check Equipment info of character A, is now unchecked
![image](https://user-images.githubusercontent.com/5288207/87095573-f5f49900-c20e-11ea-922c-68a4a43ed21d.png)
- Switch to Character B, do right click over Character A and select "Check name's Equipment Info"
![image](https://user-images.githubusercontent.com/5288207/87095716-40761580-c20f-11ea-8622-aba02a059c71.png)
- Equipment is visible, but "Show Equip" is unchecked.
![image](https://user-images.githubusercontent.com/5288207/87095805-67344c00-c20f-11ea-922e-556930e781df.png)

Additional notes:
- groups.conf is fine. view_equip permission is only set to level 99 accounts.
- packet_obfuscation is disabled.
- Bug happens on my two servers (with and without Gepard Shiled)
 
 
* Official Information:
  
Already using [this diff](https://github.com/rathena/rathena/commit/983d164b7da53438723b2dd078a936ddf06b60a2)

* **Modifications that may affect results**: 
  
  
none

**Comment by Daegaladh** [comment] 2020-07-10 23:47
I also experienced this, and kinda fixed it thanks to a @Lemongrass3110 suggestion, but still doesn't work 100% correct.
It's also possible that this is just a client bug tho.

**Comment by ihernandeza** [comment] 2020-07-11 00:17
I see.. For now as an temporary fix, I tried updating the show_equip value from char db to zero on player login, but with no success tho

**Comment by Lemongrass3110** [comment] 2020-07-11 11:24
Duplicate of #4284

**Closed by Lemongrass3110** 2020-07-11 11:24 UTC
Labels: status:duplicate

**Comment by shatowolf** [comment] 2020-10-20 07:43
hmm still experiencing this.
