### ISSUE TITLE
Potential Official Behaviors

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#4376] opened 2019-10-01 06:54 UTC
All of this is from the new EU RO server.

1. Songs' duration. On rAthena, if a player stands in songs from the moment it is started to the moment it ends, when the song ends, so does the status effect on the player. On EU RO, if a player stands in songs from the moment it is started to the moment it ends, the status effect lasts for the whole song's duration + 20 seconds.

2. Songs' 20 second duration after leaving songs' AoE is non-reapplying. Basically, when a player leaves the song's AoE they get a 20 second effect that will not reapply even if the player re-enters the song's AoE afterwards. Even if the player is in the AoE when the 20 second duration is over, the status effect ends and then is applied again afterwards.

3. Fly winging/teleporting away's immunity does not make players immune to status effects. If a demon pungus hits you with petrifying attack, you can fly wing/teleport away to avoid the damage but you cannot avoid the stone curse, if it succeeds. This applies to all status effects.

4. Animations are not supposed to stop attacks. In rAthena, when you are /ncing a monster and a priest casts Magnificat, your character stops attacking, does an animation, then continues attacking. On EU RO, the character continues attacking as if the animation never happened. The animation does give a slight cooldown, so no skills can be cast during the animation time but any skills currently in effect will continue through it. 

5. Assisters become aggressive and target the player who triggers their assist but their aggro is subject to change under all their criteria. It basically treats the monster as if it only turned aggressive but not with the only going to attack X player mode. So, Grand Pecos for example, change target on the way to a target. A player can trigger another Grand Peco to become aggressive and that Grand Peco can attack anybody else on the way to their assist target.

6. Assisters only trigger assist on the first attack. When an assister chases and then attacks for the first time, this is when the assist call goes out to have other species nearby come and help. Any other subsequent attack afterwards does not trigger assist. If the player runs from the assister, causing the assister to chase, the next attack "first attack that must always be a normal attack" will trigger assist call again.

If I find more, I'll post them.

**Comment by aleos89** [comment] 2019-10-01 13:15
1 and 2 are sort of useless now since the behavior of songs changed in #4072.

I believe there is already a bug report for 3. I could have sworn Playtester and Cydh were discussing something about this before.

**Comment by Akkarinage** [comment] 2024-05-14 19:53
I'm closing this issue as euRO's Prime server exhibits various localised behaviours and shouldn't be used to distinguish mechanics from kRO.

This can be re-opened at a later date if any of these can be confirmed on kRO - but in their own individual issues.

**Closed by Akkarinage** 2024-05-14 19:53 UTC
