### ISSUE TITLE
GTB vs Bloody lust

### ISSUE THREAD

**Issue by jamon18** [rathena/rathena#1906] opened 2017-01-22 16:06 UTC
https://forums.warpportal.com/index.php?/topic/131020-pvp-how-to-defend-masquerade/?p=1505572
renewal

**Comment by aleos89** [comment] 2017-01-25 15:42
It would help if you could please follow the template that shows up when you create the bug report, rather than clearing it all out.

**Comment by aleos89** [comment] 2017-01-27 19:31
Duplicate of #1721.

**Closed by aleos89** 2017-01-27 19:31 UTC
Labels: status:duplicate
