### ISSUE TITLE
Lapine upgrade items with random refine functionality should not have equal chance for every refine level

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#7238] opened 2022-09-04 02:46 UTC
* **rAthena Hash**: [3c43669](https://github.com/rathena/rathena/commit/3c4366942583f9876924a0fc83f94a29bd395ef3)
* **Client Date**: Irrelevant
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: 
As shown in the snippet below, we just use `rnd` to pick a number between min and max refine possible.
```cpp
    // Change the refine rate if needed
    if( upgrade->resultRefine > 0 ){
        // Absolute refine level change
        item->refine = max( item->refine, upgrade->resultRefine );
    }else if( upgrade->resultRefineMaximum > 0 ){
        // If a minimum is specified it can also downgrade
        if( upgrade->resultRefineMinimum ){
            item->refine = rnd_value( upgrade->resultRefineMinimum, upgrade->resultRefineMaximum );
        }else{
            // Otherwise it can only be upgraded until the maximum, but not downgraded
            item->refine = rnd_value( item->refine, upgrade->resultRefineMaximum );
        }
    }else if( upgrade->resultRefineMinimum > 0 ){
        // No maximum has been specified, so it can be anything between minimum and MAX_REFINE
        item->refine = rnd_value( upgrade->resultRefineMinimum, MAX_REFINE );
    }
```
  * Expected Result: 
Shadow_Refine_Hammer has different chances for each refine level.

| Refine Level | Chance (%) |
| -- | ----- |
1 | 4.4
2 | 8.79
3 | 17.03
4 | 35.16
5 | 17.58
6 | 8.79
7 | 4.4
8 | 2.2
9 | 1.1
10 | 0.55
  * How to Reproduce: Use Shadow_Refine_Hammer on rAthena, or just read the code.
  * Official Information: [Probability - Holgren's Refine Hammer](https://ro.gnjoy.com/news/probability/View.asp?category=6&seq=3954806&curpage=1&search=title&srhval=홀그렌의)
* **Modifications that may affect results**: N/A

**Comment by Lemongrass3110** [comment] 2022-09-04 07:24
Duplicate of #6669

**Closed by Lemongrass3110** 2022-09-04 07:24 UTC
Labels: status:confirmed, component:core, priority:low, mode:renewal, type:bug
