### ISSUE TITLE
Ripped Cabbus & Party

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#282] opened 2015-02-11 15:44 UTC
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings:

    Full Renewal
    1/1/1/1/1 rate
    PK server (not in towns, above lvl 30)
    PVP ATK/Skill modifers: 100%
    WOE ATK/Skill modifers: rA default
    Official walk path and stacking
    Exp and drop penalty table values below 100% set to 100%
    Party and attacker exp bonus: +40%
    More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce & Description:

- Create or join a Party (any setting)
- Tell the other guys in a party to go hunting for mobs
- Go to payon and find Ripped Cabbus (You need Gym Passes in your inventory)
- Start the discussion with Ripped Cabbus (for the increase weight limit misc skill)
- If someone kills a mob or mobs while you are in the middle of the discussion with Cabbus the window will go crazy, and next buttons won't appear and stuff.

**Comment by RadianFord** [comment] 2015-02-11 18:44
I tested it and nothing happens, It works 100% without any error.

**Comment by MrAntares** [comment] 2015-02-12 10:14
Well, I think my partymates were killing mobs for some kind of mob hunting mission in which party kill counts as well (probably the custom hunting mussion). I forgot this info, maybe that's the cause.

**Comment by aleos89** [comment] 2015-03-11 17:39
The custom hunting_missions is using the attachrid command. It's not the Ripped Cabbus NPC specifically but all. If you're talking to any NPC and you're party is killing monsters while talking to a NPC it will cause issues.
```
.Party = 3;             // Party options: 0 (exclude party kills), 1 (include party kills), 2 (same map only), 3 (screen area only)
```
The only option that would fix this would be 0. The rest of the options (1-3) will attach the player and then check their info. The attachrid script command immediately detaches a player from their current script (if they have one) and then attaches them to the new one.

Since this is a custom script I'm not sure where to go from here.

**Comment by aleos89** [comment] 2015-03-14 03:04
This is a duplicate of #158.

**Closed by aleos89** 2015-03-14 03:04 UTC
Labels: [ status:duplicate ]
