### ISSUE TITLE
Itemlink tag should be <ITEM></ITEM> for some 2015 clients

### ISSUE THREAD

**Issue by Leemonn** [rathena/rathena#7529] opened 2023-01-04 20:59 UTC
### rAthena Hash

64228cd18

### Client Date

2015-11-04

### Server Mode

Pre-Renewal

### Result

1. Doing shift+click on an item **works**. It uses `<ITEM></ITEM>`
2. Manually linking an item on the chat by typing `<ITEM></ITEM>` **works**.
3. Manually linking an item on the chat by typing `<ITEML></ITEML>` **doesn't work**.
4. Manually linking an item on the chat by typing `<ITEMLINK></ITEMLINK>` **doesn't work**.
5. Doing @mi and @ii uses `<ITEMLINK></ITEMLINK>` **doesn't work**

Important: **I only tested this with 2015-11-04 client, not sure which other clients need this change.**

### Expected Result

Doing @mi and @ii should use `<ITEM></ITEM>` thus linking the items in the chat.

### How to Reproduce

1. Fresh copy of rAthena. Change packetversion to 20151104 and change mode to pre renewal
2. Login
3. Do @mi orc archer
4. Do @ii knife

### Official Information

Manual testing

**Comment by Lemongrass3110** [comment] 2023-01-04 21:02
Duplicate of #7441
Feel free to comment there.

**Closed by Lemongrass3110** 2023-01-04 21:02 UTC
Labels: status:duplicate
