### ISSUE TITLE
Targeting in pvp gone wild!

### ISSUE THREAD

**Issue by GrumpyLittlePanda** [rathena/rathena#1736] opened 2016-11-21 14:28 UTC
Issue:
After attacking an enemy in pvp once, you can no longer target enemies. (client will not respond to clicking an enemy, sword cursor still shows)

Current hash: 633a642e5a37f10441477cf043c6c19e71e34297
Cause of the bug: 940c473c8824685042c28e851351541d5ee4e1f8
Client: 20151104

Can be fixed by calling `clif_map_type` with `MAPTYPE_NOPENALTY_FREEPKZONE` when pvp mode is set or just by reverting 940c473c8824685042c28e851351541d5ee4e1f8 and still sending the old packet along with `ZC_MAPPROPERTY_R2` like before.

 `clif_map_type` and `clif_map_property` seem to update the same value at least on the 20151104 client. Did a blind test and using `clif_map_property` alone still bugs targeting even if you use type instead. Need the old way or clif map type.

**Comment by Lemongrass3110** [comment] 2016-11-21 14:39
Could you give me a sample setup for one of the maps where you experience this issue?
I'd need the mapflags you have on it and if you have PK mode enabled on your server.

**Comment by GrumpyLittlePanda** [comment] 2016-11-21 14:48
no other mapflags, @pvpon. PK mode not enabled.

**Comment by Playtester** [comment] 2016-11-21 16:31
Hmm, I tried with 20151104 client in renewal compile and it works fine there.

Are using some plugins maybe? I see for example that your cursor is orange and you can see the 9 cell range. Maybe that add-on is not compatible with the new implementation.

**Comment by GrumpyLittlePanda** [comment] 2016-11-21 17:26
SRH or changing cursor sprite wont affect that. Doesnt matter if compiled renewal same stuff gets sent either way regarding map properties afaik.
but since client is indeed heavily customized I did get a clean client and fresh copy of rA, same thing. even tested both ren and preren to be safe. yes, my cursor is still orange but please dont try to blame that. sprite of the cursors doesn't matter.
http://puu.sh/spMOs/4b492073ae.mp4

Once again, reverting 940c473 or adding `clif_map_type` in a few places fixes it.

**Comment by Playtester** [comment] 2016-11-21 18:07
Frosty helped me reproduce this issue. The issue is caused by auto attacking. It only happens if you have /nc on or just press CTRL and attack.

**Comment by cydh** [comment] 2016-11-22 00:57
Ohh I thought it's only me, also happened in 2013-08-07.

**Comment by hurtsky** [comment] 2016-11-22 02:13
its also happen to me (i also thought it was only me). sometimes you will have trouble using skill (not AOE one) to target player in continuously rate (example: collect dangerous spirit > critical exp > asura > (target) collect dangerous spirit > critical exp > asura > (unable to asura at target -failed ) , moving around > asura > (target success), . 
20151104 client

**Comment by Everade** [comment] 2016-11-25 21:42
I'm having a similiar problem in **Battlegrounds**.
However it's probably not directly related to this.
The sword cursor does not appear at all i always have to hold alt to be able to attack.

_Can anyone confirm this or is it related to zephs rAmod?_
Using **2015-09-16aRagexe**

This issue persists since quite a long time already.
Wasn't able to find any fix for it as of yet.

Anyone experienced this as well?

**Comment by GrumpyLittlePanda** [comment] 2016-11-26 11:52
The BG bug is caused by issuing both BG and SIEGE property on the same map on newer clients.
It is very similiar yes, but caused by a modification.

**Comment by Everade** [comment] 2016-12-01 12:12
@GrumpyLittlePanda 
Thanks a lot for the info!
Have you found a fix for this already? Or did you simply disable Siege property then?

**Closed** 2016-12-07 22:10 UTC
Labels: bug:core, status:confirmed
