### ISSUE TITLE
Vellum Kabz should bypass Shadow Formation

### ISSUE THREAD

**Issue by alxalmora** [rathena/rathena#1915] opened 2017-01-25 23:28 UTC
* **rAthena Hash**: 
* **2015-10-29a**: 
* **Renewal**: 
* **Description of Issue**: 
  * Result - Vellum Kabz damage calculation use HP of Shadow Chaser, but damage is given to Shadow Form's target.
  * Expected Result - Damage should affect Shadow Chaser
  * How to Reproduce - PvP Shadow Chaser vs Rune Knight, and use shadow form then attack with Vellum Kabz.
  * Official Information - http://forum.ragnarokeurope.com/ro/index.php?%2Ftopic%2F79166-bypassing-shadow-formation%2F

**Comment by aleos89** [comment] 2017-01-27 19:31
Duplicate of #1721.

**Closed by aleos89** 2017-01-27 19:31 UTC
Labels: status:duplicate
