### ISSUE TITLE
Instances & Map Server Down

### ISSUE THREAD

**Issue by heimdallcodex** [rathena/rathena#3386] opened 2018-08-03 23:44 UTC
* **rAthena Hash**: [68fccf4](https://github.com/rathena/rathena/commit/68fccf447b3c9a2aa90a3de7bdc10856400635bd)

* **Client Date**: 

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Since the last update on my server (last Sunday), it has a problem with a lot of instances... When players make a team and launch an instance (for example Endless Tower or Old Glast Heim) all the walkable areas are mixed with the non-walkable areas... (we cannot walk in the walkable zone, and we could be warped on a black zone). I don't think it is a mapcache problem because when I go to the original map of the instance, I can walk normally... the problem is going when the server duplicates the map when an instance is launched... It is my first problem! After it, when the team leader breaks the team, or after the delay of the instance... the map server is down..

  

* **Modifications that may affect results**:

**Comment by teededung** [comment] 2018-08-04 00:57
@heimdallcodex You need to use ISSUE TEMPLATE to describe your issue.

**Comment by aleos89** [comment] 2018-08-04 13:57
Sounds like you didn't properly merge the map update. I had these issues while testing but it's not present on master (68fccf4 at this point in time).

**Comment by arby89** [comment] 2018-08-04 18:43
Just to add, idk related or not:
1. instance with multi map, error when use instance_destroy(), instance with single map, working great.
2. warpparty in instance with multi map just warp all other party member but not party leader, instance with single map warpparty working well.

**Comment by gustavobrigo** [comment] 2018-08-04 19:58
Well, i thinks is related with those recent "cleanups" (https://github.com/rathena/rathena/pull/2943)

I was looking back to modifications and 10 days ago there was some fix related to instance destruction rolled and seems to still exists some serious problem happening here..

**Comment by gustavobrigo** [comment] 2018-08-04 20:50
Moving on reviewing the code, seems to be related to the merge of **instance_start** and **map_num** on the same vector, BEFORE, when a instance was added, the value of **map_num** was increased, this code is for a revision before the merge of the "cleanups":
Function map_addinstancemap on map.cpp

```
	for(i = instance_start; i < MAX_MAP_PER_SERVER; i++) {
		if(!map[i].name[0])
			break;
	}
	if(i < map_num) // Destination map value overwrites another
		dst_m = i;
	else if(i < MAX_MAP_PER_SERVER) // Destination map value increments to new map
		dst_m = map_num++;
	else {
		// Out of bounds
		ShowError("map_addinstancemap failed. map_num(%d) > map_max(%d)\n",map_num, MAX_MAP_PER_SERVER);
		return -3;
	}
```

Take a look at `dst_m = map_num++;`, map_num is incremented when the instance map is created BUT instance_start is kept to the default index when the server was started, so, every time the interation try to find a "instance map" free from the last non-instanced maps.

I guess there is some mess with map indexing with this new cleanup.

**Comment by aleos89** [comment] 2018-08-05 18:24
I'll close this as it's a duplicate of the other issues (#3369).

**Closed by aleos89** 2018-08-05 18:24 UTC
Labels: status:duplicate

**Comment by heimdallcodex** [comment] 2018-08-05 21:30
Thank you @aleos89 but my problem is NOT only linked to the instance OGH... but with a lot of official instances and it is since the last upgrade. Before it, I never had this kind of problems in two years.
It seems problematic for my community and the others who cannot launch any instance, without this result (of walkable areas and map server)...

These instances have this problem.
- Endless Tower,
- Sealed Catacomb, 
- Orc's Memory, 
- Nidhoggur's 
- Nest,Culvert, 
- Wolfchev's Laboratory,
- Old Glast Heim, 
- Geffen Magic Tournament, 
- Isle of Bios

If i do @mapexit during the instance (in local) i have this message : 

> (08/05/2018 23:20:18) [ Warning ] : Memory leak detected at ERS 'instance.cpp::instance_maps_ers', 6 objects not freed.

**Comment by aleos89** [comment] 2018-08-05 22:13
You can apply #3384 and it should resolve your issues.

**Comment by heimdallcodex** [comment] 2018-08-08 06:54
It did't.

After a revert of it, [#3347](https://github.com/rathena/rathena/pull/3347), my instances are perfectly functional (no any map server down and the walkable areas are good).

Thank you for your help.
