### ISSUE TITLE
Pet Error

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#4199] opened 2019-06-02 17:28 UTC
* **rAthena Hash**: 

Latest commit 34971e5

* **Client Date**: 

2018-11-07

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: When using Incubator (Item 643) to shock the pets 'eggs, the window that opens is not closed immediately after invoking the pet, pets' eggs are also not removed from the inventory. It is necessary to exit the character and enter again so that the items are removed from the inventory every time.
Ao usar Incubadora (Item 643) para chocar os ovos de pets, a janela que abre não é fechada logo após invocar o pet, os ovos de pets também não são removidos do inventário. É nessesario sair do personagem e entrar novamenta para que os itens sejam removidos do inventário todas as vezes.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by sader1992** [comment] 2019-06-02 18:58
How to Reproduce?
please follow the template

**Comment by Lemongrass3110** [comment] 2019-07-03 21:41
Duplicate of #4190

**Closed by Lemongrass3110** 2019-07-03 21:41 UTC
Labels: status:duplicate
