### ISSUE TITLE
RE: shield chain + ELEMENTS?

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#466] opened 2015-06-15 06:37 UTC
shield chain can endow element? as far as  i know its suppose to be fix neutral..

**Comment by reigneil** [comment] 2015-06-18 16:14
Shield Chain is like Acid Demonstration behavior. Force Neutral
to test this issue you need a monster that is a Ghost Property i.e Whisper
then endow your weapon with elemental that can hit a Ghost and see what happen.
if it hits then there is something wrong...

**Comment by joelolopez** [comment] 2015-06-20 14:50
shield chain can  be endowed with element on current rathena.. anyone can fix this?

**Comment by anacondaqq** [comment] 2015-06-21 15:49
### Without enchanted element
![](http://i.imgur.com/gRehql3.png)

### With enchanted 
![](http://i.imgur.com/jzfJEtW.png)

### How reproduce:
1. Create paladin 
2. use shield chain on monster (for example phen)
3. you will see damage
4. @item 12117
5. use this converter
6. hit phen again
7. damage will be increased because of element.

### Official behavior
Proof: http://irowiki.org/classic/Rapid_Smiting
> The attack is a ranged, ALWAYS neutral attack. GR and Deviling reduces the damage considerably.

Please fix it.

**Comment by Playtester** [comment] 2015-06-25 11:53
This needs to be tested on Aegis first.
The only source that says it should always be neutral is irowiki.

Japanese wiki says non-attribute for shield charge and shield boomerang:
http://crsdr.rowiki.jp/?Crusader
It's that: 無属性 <--- Neutral

But there's no mention of this on the Paladin page:
http://crsdr.rowiki.jp/?Paladin

**Comment by anacondaqq** [comment] 2015-06-25 15:21
I was test it in Pre--re,

**Comment by Playtester** [comment] 2015-06-26 05:38
Ah ok so it needs to be fixed in pre-renewal I guess.

**Comment by MrAntares** [comment] 2015-07-07 12:44
Guys,

PLEASE don't start reverting RENEWAL behaviors now. This was tested and IS OFFICIAL RENEWAL BEHAVIOR. Shield chain, acid demo, occult impact ARE FORCED NEUTRAL, so element does increase the damage, but the final damage is neutral. Please do your work before posting and check the old infos.... You can find the whole discussion on the old bug tracker.

**Comment by anacondaqq** [comment] 2015-07-07 17:08
@MrAntares i think, you do not understand.
We are talking about **pre-re**
Not about RE

**Comment by reigneil** [comment] 2015-07-15 18:28
@anacondaqq
well maybe because the title of it is misleading.
@joelolopez
it could be better to change the title indicating if it is Renewal or Pre-Renewal

**Comment by anacondaqq** [comment] 2015-07-15 18:40
i hope, for pre-re it will be fixed. :ghost:

**Comment by MrAntares** [comment] 2015-07-20 15:00
So it is renewal? Then working as intended.

**Comment by joelolopez** [comment] 2015-07-22 15:51
but MrAntares reigneil says that in renewal behavior its suppose to be force neutral.. but in my case it can endow element RE

**Comment by aleos89** [comment] 2015-07-24 16:22
Closing this as this is how it behaves in renewal and since you opened a new issue (#521).

**Closed by aleos89** 2015-07-24 16:22 UTC
Labels: [ status:invalid ]
