### ISSUE TITLE
import folder itemdb_read_combos will overwrite entries in the db/x-re/combo dbs!!

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#1922] opened 2017-01-27 22:31 UTC
* **rAthena Hash**: 

current

* **Server Mode**: 

should apply for either

* **Description of Issue**: 

when an entry is placed in db/import/item_combo_db.txt it overwrites the first entries of db/(pre-)?re/item_combo_db.txt because of how itemdb_read_combos is coded. accidentally this means that people's custom combos are breaking default combos! oops...

see here https://github.com/rathena/rathena/blob/master/src/map/itemdb.c#L1027-L1052
to match with other readdb loads, we'd need a static combos_count variables that is added to the id->combos[idx]->id, or before parsing we use a size = uidb_size(item_combo...) and add that to id->combos[idx]->id for every entry loaded.

there may be other imported files overwriting defaults, please investigate the others!!

**Comment by Akkarinage** [comment] 2017-01-28 10:56
The import files are designed to overwrite data default, that's their purpose.

**Comment by mrjnumber1** [comment] 2017-01-28 19:57
you did not understand my report at all, please reread and re-open this.

let's say i add a brand new combo, where u have valkyrie shield (2115) + hunting spear (1422)
i put in 2115:1422 in my import/item_combo_db.txt - and now - i have just removed the first entry of db/x/item_combo_db.txt 1166:2527, however, the player's inventory will STILL report that they player has a combo equipped on them because of how the combos are added to the item db on load. but it will not properly add the bonus from 1166:2527 because it is expecting the items 2115:1422

**Comment by Canoe** [comment] 2017-01-28 20:19
I'll give a proper example. We've added several new combos to our import/item_combo_db.txt. These are non-existing combos with items that do not exist in pre-re or re as they are custom.

This is our first entry in the import/item_combo_db.txt
1420:41021,{ bonus3 bAutoSpellWhenHit,"HP_ASSUMPTIO",2,5; }

This is the first entry in pre-re/item_combo_db.txt
1166:2527,{ bonus2 bAddRace,RC_Dragon,5; }

Because of our combo in import, the 1166:2527 combo no longer works. We fixed this locally with the following changes: http://puu.sh/tEig5/95a6656fab.png

**Comment by lighta** [comment] 2017-01-28 23:08
I think the simplier will be to add an index column in that db.
Then, if you want to overwritte well you put your combo at same idx. If you want to add you put a new index. (up to the user to check the overlap).
Now in code he will have to unload properly the index when overwriting.

**Comment by aleos89** [comment] 2017-02-13 18:13
I think following @lighta's suggestion, making an index value should resolve the issue. This is the same steps we took to resolve the produce database as well.

**Comment by feltenc** [comment] 2017-02-25 22:08
Confirmed.

**Comment by Lemongrass3110** [comment] 2019-02-10 21:18
Should also be addressed when the item combo database is converted to yaml.

The problem itself is that count is resetted to zero at the beginning of the itemdb_read_combos function and therefore will partially overwrite the combos.

**Comment by Atemo** [comment] 2022-01-12 14:53
Fixed in https://github.com/rathena/rathena/commit/c8d1d1ea1e42d636d391c6fc4a70db93948ec1e5

**Closed by Atemo** 2022-01-12 14:53 UTC
Labels: component:database, component:core, mode:renewal, mode:prerenewal, type:bug, type:enhancement
