### ISSUE TITLE
Char slot issue

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#7632] opened 2023-03-09 14:51 UTC
### rAthena Hash

lastest

### Client Date

2011-11-03

### Server Mode

Pre-Renewal, Renewal

### Result

enable dan disable VIP and set #define MAX_CHAR_VIP 0
but still have 3 slot with status locked

![image](https://user-images.githubusercontent.com/9587609/224061197-16270852-c10c-4a10-a9b2-ff06bd629860.png)

### Relevant Log Output

```Shell
all slot suppose to be open
```

### Expected Result

all slot suppose to be open

### How to Reproduce

for VIP mode just enable VIP mode at \src\config\core.hpp

### Official Information

don't know

### Modifications that may affect results

enable VIP mode

**Comment by aleos89** [comment] 2023-03-09 21:55
Duplicate of #7363.

**Closed** 2023-03-09 21:55 UTC
Labels: status:duplicate, type:bug
