### ISSUE TITLE
Guild bound item retrieval deletes all guild bound items, not just selected character's

### ISSUE THREAD

**Issue by Canoe** [rathena/rathena#954] opened 2016-02-10 04:46 UTC
When attempting to retrieve guild bound items from an offline character, all guild bound items are deleted from the inventory db.

The problem line is here:
https://github.com/rathena/rathena/blob/master/src/char/int_storage.c#L338

> StringBuf_Printf(&buf, "DELETE FROM `%s` WHERE `bound` = %d",schema_config.inventory_db, BOUND_GUILD);

Since it doesn't include a check on char_id, it will delete every guild bound item instead of just that one character's.

**Comment by lighta** [comment] 2016-02-10 13:40
You partially right here.
When we first introduced we didn't check for char_id as well but already have solve the item_id that needed to be destroy, (since `inventory`.id, is the unique key for that table) see here :
https://github.com/rathena/rathena/commit/4742adac124625993086710fdde37afb1243094a
It was far from perfect but was working, so I suppose with some optimisation that 'id' resolution was broken.
I didn't understand all the current file, I need to dig into more, but hmm what I can tell you is that you can't simply add the 'char_id' in the where condition.
While it's true it will fix it, consider the scenario where the "char" have guild_item_bound from another guild. They will be removed as well. (Ok I know this is super super exentric since that whole item retrival process is suppose to happen when the guildie left a guild wheater is online or not. (in that case when is not in the current mapserver the kick was operated), but still better be prepared then fix it.)

So yeah to cap it, "where char_id=x, and guild_id=y"
And well all the item.id resolution seem kinda half useless now. (I really don't get that CHECK_REMOVE macro btw...,, line 352 to 397 should be move into a proper function, since it offer the possibility to update the char_table( char view) with an array of items.

**Comment by anacondaqq** [comment] 2016-02-10 13:46
a long time ago, I reported on the mass of bugs in this mechanism.
But @cydh was fix them all, and i was manually test different behaviors, and all was work correctly.
I think, this behavior destroyed by some update after @cydh fix commit (as i remember -> merge commit from specialized branch for guid & bounded items).

**Comment by GrumpyLittlePanda** [comment] 2016-02-10 18:13
You can also dupe items with this implementation by logging in and expelling at the same time. Also when guild storage is not loaded on the server (after restart for example) and you retrieve an item from online/offline (can't remember) you end up destroying everything that was in the storage.

**Comment by technoken** [comment] 2017-05-07 14:50
I couldn't reproduce this problem now on hash b7f3ee9772bf21debb50caf51db569fa98ac977b

**Comment by Canoe** [comment] 2017-05-07 15:03
Unfortunately based on the code, this is still an issue. Check https://github.com/rathena/rathena/blob/master/src/char/int_storage.c#L396

`// Delete bound items from player's inventory
	StringBuf_Clear(&buf);
	StringBuf_Printf(&buf, "DELETE FROM `%s` WHERE `bound` = %d",schema_config.inventory_db, BOUND_GUILD);
	if( SQL_ERROR == SqlStmt_PrepareStr(stmt, StringBuf_Value(&buf)) ||
		SQL_ERROR == SqlStmt_Execute(stmt) )
	{
		SqlStmt_ShowDebug(stmt);
		SqlStmt_Free(stmt);
		StringBuf_Destroy(&buf);
		mapif_itembound_ack(fd,account_id,guild_id);
		return true;
	}
`

The only thing this query looks for is if an item is guild bound. Every offline player will have any guild bound item permanently deleted. Online players will override this on their next save.

**Comment by aleos89** [comment] 2017-08-01 19:13
Fixed in 4c62f58.

**Closed by aleos89** 2017-08-01 19:13 UTC
Labels: bug:core, mode:prerenewal, mode:renewal, priority:medium, server:char, status:confirmed
