### ISSUE TITLE
Display Group Icon (Title)

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#5063] opened 2020-06-08 01:00 UTC
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/35c3301dda0f4f0c4628166faff24b072e0912e1

* **Client Date**: 

2020-06-03aRagexe

* **Server Mode**: 

Pre-Renewal / Renewal

* **Description of Issue**: 

Display group (title) and icon for mobs, homunculus, npc, mercenaries
For set icon in some way need get bl_id of npc, mob etc and call function:

**Set icon**

```
setunitdata(GID, UDT_GROUP, ID)
setunitdata﻿(GID, UDT_﻿GROUP, ID)
```

> Icon files stored in directory data/texture/유저인터페이스/group/group_ID.bmp

Where GID is bl id of being, ID is icon id.

Example for npc:

```
setunitdata(getnpcid(), UDT_GROUP, 3);
setunitdata(getnpcid(), UDT_GROUP, 3);
```

It will use this image:

> data/texture/유저인터페이스/group/group_3.bmp
> data/texture/유저인터페이스/group/group_3.bmp

 
**Set group**

setunittitle(GID, group_name);

Where group_name is any name what you want assign to group

Example for npc:

```
setunittitle(getnpcid(), "rAthena");
setunittitle﻿(getnpcid(), "rAthena");
```
Sample images
![image](https://user-images.githubusercontent.com/53480357/83984172-14166300-a90a-11ea-9734-946855aec661.png)
![image](https://user-images.githubusercontent.com/53480357/83984175-1973ad80-a90a-11ea-9e3f-39f395f04e95.png)
![image](https://user-images.githubusercontent.com/53480357/83984177-1d073480-a90a-11ea-84aa-38fc8c6f61c6.png)

**Comment by aleos89** [comment] 2020-06-08 01:15
Duplicate of #4529.

**Closed by aleos89** 2020-06-08 01:15 UTC
Labels: status:duplicate
