### ISSUE TITLE
When I switch skill items in Hotkey and the skill table does not disappear.

### ISSUE THREAD

**Issue by lphz** [rathena/rathena#5630] opened 2020-12-16 11:51 UTC
* **rAthena Hash**: 

 Last rAthena https://github.com/rathena/rathena

* **Client Date**: 
EXE 2020-03-04aRagnaexeRe

* **Server Mode**: 
Last rAthena (item_db.yml)
![screenWoeRO000](https://user-images.githubusercontent.com/10014424/102344828-0d5e5c00-3fcf-11eb-9758-1710d72c743a.jpg)

When I switch skill items in Hotkey and the skill table does not disappear.

**Example :**
Glove [zerom card] - 2 ea
Glove [smokie card] - 1 ea

I test on 2018 no bug
I test on 2019 - 2020 is bug

**Here a video test :**
EXE 2018-06-20eRagnaexeRe https://drive.google.com/file/d/1-s7vw5Tt1Zbf7GNAvdmRmcP18Ze2pNwF/view?usp=sharing
EXE 2020-03-04aRagnaexeRe https://drive.google.com/file/d/1Q6h_b2vPxUKjyuBm5QXwx0AwisL7kumu/view?usp=sharing

**Comment by Lemongrass3110** [comment] 2021-01-25 23:36
Duplicate of #5382

**Closed by Lemongrass3110** 2021-01-25 23:36 UTC
Labels: status:duplicate

**Comment by lphz** [comment] 2021-01-26 02:16
i'm try to fix from this but not work https://github.com/rathena/rathena/commit/351f0db1914532924cdf678010c6aa3b209ca311
