### ISSUE TITLE
bIntravision is not working on disguised hidden player

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#2361] opened 2017-08-22 03:01 UTC
* **rAthena Hash**: 1fc0ed6

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Other player's can't detect player's that are disguised as monster's using disguise script for example is a Poring while using Cloaking/Chase Walk/Hiding Skill but when the user which is disguised as monster uses  Cloaking/Chase Walk/Hiding Skill while having Maya Purple Card the user is detected by himself but other player's can't detect him.
  * Expected Result: It should be detected by both user and other player's.

**Comment by secretdataz** [comment] 2017-08-22 03:32
Duplicate of #1370

**Closed by secretdataz** 2017-08-22 03:32 UTC
