### ISSUE TITLE
loadnpc/unloadnpcfile

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#1217] opened 2016-04-27 14:35 UTC
These commands work fine for a single time usage, but they stop working if you're playing with more than one script. For example:

```
@loadnpc npc/custom/test3.txt
@loadnpc npc/custom/test4.txt
```

Using `@unloadnpcfile npc/custom/test4.txt` will not work (file not found). Using `@unloadnpcfile npc/custom/test3.txt` will unload both files at the same time. You will also no longer be able to load test4.txt afterwards (unless you use `@reloadscript`).

Git version: 62271358da41cfc3f6239d73af964ce79b5a909b

test3.txt:
```
prontera,150,150,0	script	TestNPC1	4_ALIZA,{
	end;
}
```

test4.txt:
```
prontera,151,150,0	script	TestNPC2	4_ALIZA,{
	end;
}
```

**Comment by benching** [comment] 2016-04-27 16:30
use double slash when giving a file directory.
"@unloadnpcfile npc//custom//test4.txt"

i usually unload the npc via "@unloadnpc" and "@unloadnpcfile"

**Comment by Tokeiburu** [comment] 2016-04-27 20:19
That solution above is sketchy and most likely will cause a ton of issues if it's used repeatedly. Anyway, the main part of the issue is from the npc_parsename method in npc.c.

The npc_last_path's pointer is being assigned to filepath, but the pointer of filepath is always the same when using `@loadnpc` (it's the pointer of `message` from atcommand.c). All new scripts loaded are then considered being in the same file.

Changing the condition in that method from 
`if( npc_last_path != filepath ) {`
to
`if( npc_last_path != filepath || strncmp(npc_last_path, npc_last_ref, 255) != 0) {`
would solve most of it (could probably be done more cleanly).

The reference count of the last unloaded NPC is also never removed. In `npc_unload`, 
```
	if( single && nd->path ) {
		struct npc_path_data* npd = NULL;
		if( nd->path && nd->path != npc_last_ref ) {
			npd = (struct npc_path_data*)strdb_get(npc_path_db, nd->path);
		}
```
should be changed to:
```
	if( single && nd->path ) {
		struct npc_path_data* npd = NULL;
		if( nd->path && nd->path != npc_last_ref ) {
			npd = (struct npc_path_data*)strdb_get(npc_path_db, nd->path);
		}
		else {
			npd = npc_last_npd;
		}
```

Applying these changes fixed all the isues I had with it. While we're on that subject, in `npc_unloadfile`, changing
```
npc_delsrcfile(path);
```
to
```
if (npc_delsrcfile(path)) // with the appropriate changes in npc_delsrcfile of course
    found = true;
```
would help out a lot when you're unloading 'mapless' NPCs. Otherwise there's no way to know for sure if the NPC has been unloaded or not and it will display ingame as "File not found" while it has actually removed the file.

**Comment by aleos89** [comment] 2016-04-27 23:57
Duplicate of #203.

**Closed** 2016-05-24 10:24 UTC
Labels: status:duplicate
