### ISSUE TITLE
SC_ODINS_POWER status.c MATK

### ISSUE THREAD

**Issue by sanny1128** [rathena/rathena#2120] opened 2017-05-05 09:36 UTC
the skill ODINS_POWER before use it and ATK +70or100 (SHOW IN STATUS
BUT MATK +70OR100(**NOT**SHOW IN STATUS

**Comment by anacondaqq** [comment] 2017-05-05 12:44
hi @sanny1128 can you please use a template when you create an issue? Why? Because for developers it's pretty hard to understand what they should to do, and how to reproduce the error. For example, your issue has been fixed in latest commits by rolling-back changes related to a status window. 

If you provided your git hash, I could say with certainty what to do, but right now can just suggest "upgrade emulator to latest revision". 

Se commits: 9ba2513ff4ea85a05722151bea4bdda49582ab04 and 4bb6aa13a057d20159028634e65ef0219e9a6472

**Comment by aleos89** [comment] 2017-05-05 13:37
Related to #2118.

As @anacondaqq said, giving more information helps resolving issues by following the template. He also gave the two commit hashes that resolve this issue.

**Closed by aleos89** 2017-05-05 13:37 UTC
Labels: status:duplicate
