### ISSUE TITLE
Can't pick items on floor

### ISSUE THREAD

**Issue by iraciz** [rathena/rathena#4853] opened 2020-04-27 07:15 UTC
* **rAthena Hash**: 05ebde0

* **Client Date**: 

<20180621>

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Attempts to pick items on floor stuck your char sometimes.
  * Expected Result: Move to the item and grab it from your current cell, without forcing you to refresh or move to other cell.
  * How to Reproduce: <Drop 10 or more items in the ground and try to pick one by one, just click on the item at floor whitout moving you char from your current cell, and voila! at certain point the character stop moving  towards the item to pick it. You still clicking the item on floor but It just keep stuck at the cell without moving. This forces you to move to another cell or use @refresh in order to update your position and be able to pick the item.>

 * Official Information: The click must respong to everything, from picking items to chasing monster with the skills without stucking you in your current cell.

* **Modifications that may affect results**: 
  Nope, I'm using a clean latest rAthena emulator.

**Comment by iraciz** [comment] 2020-04-27 11:40
This problem also occurs when chasing and targeting with a skill a monster example cart termination, bash,  the char sometimes stop in a cell, and don't follow the movement after the skill is casted, you have to refresh or move to an adjacent cell in order to continue with the attack,

**Comment by Daegaladh** [comment] 2020-04-27 19:10
I've tested this and cannot reproduce it, maybe your client exe is damaged, or you configured the PACKETVER wrong?

**Comment by Latiosu** [comment] 2020-04-28 06:18
Hmm, I actively experience this issue on my server. I thought it was normal behaviour but I guess it  probably isn't.
I can try to reproduce issue later today and see if I can define more cases where it does and doesn't occur.

**Comment by iraciz** [comment] 2020-04-28 08:14
> I've tested this and cannot reproduce it, maybe your client exe is damaged, or you configured the PACKETVER wrong?

Sir, I tried diferent clients, also toggled change  wak to delay diff, also skipt packet obfuscation and this persist, I think this is not related to client, the problem here is that at certain direction,  the char stop responding at clicks that aims items or targets, and get stuck in his own cell forcing you to move again.

**Comment by Latiosu** [comment] 2020-04-28 09:44
@Daegaladh I've reproduced the issue and simplified the reproduction steps. Video demonstrating the bug with new steps: https://youtu.be/pFrsc_uRGow

**Reproduction Steps**
1. Drop an item
2. Very quickly click away from the item and click back onto the item (<0.5 secs).

**Expected Result**
Player walks to item and picks it up

**Actual Result**
Nothing happens

---
**Futher Details**
* **rAthena Hash:** 05ebde0
* **Client Date:** 20180620
* **Server Mode:** Renewal

**Comment by vstumpf** [comment] 2020-04-28 16:00
Do you have CIRCULAR_AREA defined?

**Comment by Latiosu** [comment] 2020-04-28 16:31
It isn't defined in my case:
![image](https://user-images.githubusercontent.com/7020503/80512835-7605b380-89c1-11ea-802a-8b0284342376.png)

**Comment by Latiosu** [comment] 2020-04-29 06:23
I suspect this issue may be related to #1402.

**Comment by iraciz** [comment] 2020-04-30 17:23
> I suspect this issue may be related to #1402.

4 years experiencing this, any idea where to revert?

**Comment by Daegaladh** [comment] 2020-04-30 17:48
Works fine with 2015-05-13aRagexe, so maybe a missing packet? or a client-server desync with newer clients?

**Comment by alisonrag** [comment] 2020-04-30 18:33
this issue also happens when use openkore, i dont have the video now, but i can try to make a one.
so the issue is not related to client

**Comment by iraciz** [comment] 2020-05-02 19:11
> this issue also happens when use openkore, i dont have the video now, but i can try to make a one.
> so the issue is not related to client

share please

**Comment by alisonrag** [comment] 2020-05-03 22:56
I'm sorry to have bad news, but after some tests using openkore and the ragnarok client I could see that this behavior is related to the client.
As you can see in the following video, openkore console is showing the packets that client send to server, after drop a item and walk to far and try to pick the item to fast, for some reason the ragnarok client dont send the pick item packet

[![](http://img.youtube.com/vi/dvpnV9vq1Fo/0.jpg)](http://www.youtube.com/watch?v=dvpnV9vq1Fo "")

**Comment by alisonrag** [comment] 2020-05-03 23:00
this can be some kind of bug position i will try to reproduce in official server

**Comment by iraciz** [comment] 2020-05-05 21:25
how to fix in 20180621?

**Comment by iraciz** [comment] 2020-05-12 08:40
This also affect monsters, they stuck at picking items.
![poring machines](https://user-images.githubusercontent.com/15825408/81661807-4368ab80-9402-11ea-8036-42784bcb779d.png)

**Comment by violent01** [comment] 2020-05-13 00:57
tested it on my live server using 20180621 client for 2 hours and i cannot reproduce this issue @iraciz.

**Comment by iraciz** [comment] 2020-05-13 07:11
> tested it on my live server using 20180621 client for 2 hours and i cannot reproduce this issue @iraciz.

Any server side mood? Diff? Source edit?

**Comment by violent01** [comment] 2020-05-13 14:47
@iraciz  try to get the client via nemo here's the link! http://nemo.herc.ws/downloads/

**Comment by iraciz** [comment] 2020-05-13 17:29
Where is 20180621aRagexe**RE**
![poring machines](https://user-images.githubusercontent.com/15825408/81844663-07723b00-9515-11ea-8627-103ac2f15f21.png)

**Comment by iraciz** [comment] 2020-05-13 18:05
well, it has been determined that ragexeRe clients seems to have this missing packet issue, I tried diferent Re clients from a to d for the dates 20180620 and 20180621 respectively, also an user using RagexeRE_2018_04_18a experience the same, 

since this is a client related issue and not a rathena, I'm closing it.

**Comment by poporing** [comment] 2020-05-16 03:02
I experience this with 2018-08-01cRagexe.exe that is not a RagexeRE, what client do you use to fix this @iraciz ?

**Comment by violent01** [comment] 2020-05-16 05:19
@iraciz  I’ve replied to the topic in the forums with my client and patch list. Try it if it will work on you.

**Comment by iraciz** [comment] 2020-05-16 05:23
Not working, clean emulator, your client and diff, is all the same, can´t pick the items and the mosnters stuck in their cells, something real bad is happening here.

**Comment by violent01** [comment] 2020-05-16 05:24
That’s really weird on your part. Have you tried any modifications on your side? Cause I can’t really reproduce your issue.

**Comment by iraciz** [comment] 2020-05-16 05:28
> That’s really weird on your part. Have you tried any modifications on your side? Cause I can’t really reproduce your issue.

Drop an item
Very quickly click away from the item and click back onto the item (<0.5 secs).

This also affect monsters, try to reproduce doing this steps:
make 10 diferent items example @item sandals 10
now drop em all @dropall
now summon 10 tatachos, 9 of them will get stuck with out even noticing your presence.

**Comment by iraciz** [comment] 2020-05-16 05:33
I wonder what check was talking about @Playtester in this thread?, maybe this is the possible cause of this issue.

![¿Õ°ü¾Þ¹«](https://user-images.githubusercontent.com/15825408/82111720-baf15000-970c-11ea-963a-def72426cfd3.jpg)

**Comment by qwerty7vp** [comment] 2020-05-23 15:37
I can reproduce this but need to timing it right to make it happen

Video : https://youtu.be/olf-gvUPfbs

**Comment by gidzdlcrz** [comment] 2020-05-23 15:56
tried reproducing it like @qwerty7vp does. It works fine on my end. Using 2015 client

**Comment by acelabini** [comment] 2020-09-02 03:37
I reproduced it using 2015 client.

**Comment by hnomkeng** [comment] 2021-02-12 13:33
same issue hard pick item on floor, using 2020 client

**Comment by Akkarinage** [comment] 2022-09-04 20:47
I can't reproduce this on a 20201104 client.

If it's still on-going can someone please provide more information on some up-to-date testing? The problem with Issues being open this long is that there's no guarantee that it hasn't already been resolved. When testing, please provide client date and video footage/gif if possible to prove this is still an issue, otherwise we'll close it.

**Comment by Lemongrass3110** [comment] 2023-01-23 18:02
No user comments for almost 2 years.

**Closed by Lemongrass3110** 2023-01-23 18:02 UTC
Labels: status:unable to reproduce
