### ISSUE TITLE
Izlude Mapcache For Pre-Renewal

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5902] opened 2021-04-27 16:56 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/2677d2f688f13ea90a2273f899920c129d7d7252

* **Client Date**: Not related.

* **Server Mode**: Pre-Renewal.

* **Description of Issue**: Right now rAthena are using new izlude mapcache, but the warp portal for example are using pre-re (old) izlude map.
  * Result: If using pre-re (old) izlude map, the warp portal are correct but having issue on moving/walk because of mapcache. 
  * Expected Result: Since warp portal used are in pre-re mode, I think mapcache also should use old izlude mapcache.
Also might be good to update mapcache for pvp map izlude too if needed.

**Comment by aleos89** [comment] 2021-04-27 17:07
Duplicate of #5349.

**Closed by aleos89** 2021-04-27 17:07 UTC
Labels: status:duplicate
