### ISSUE TITLE
mob trace problem

### ISSUE THREAD

**Issue by hotspicy945** [rathena/rathena#4184] opened 2019-05-19 19:32 UTC
rAthena Hash: [339e6c6](https://github.com/rathena/rathena/commit/339e6c67182e5cb344fcd614329f2b7fb048d8bf)
Client Date: 20180620
Server Mode: Renewal

Description of Issue: server lag
Result: all player feel lag
Expected Result: no lag
How to Reproduce:  Aggregated about 150 monsters, that monster trace the player

I found some player maliciously aggregated the monsters﻿, it let my server all player lag.

When about 150 monster trace a player

Server will be very lag,   all map player feel  lag ,  not only that map.

But only trace will be lag,  if monster around the player and attack , it will not lag.

My test computer
computer-1  : Intel(R) Core(TM)i7-8700  3.20GHz  3.19GHz      ram 16G   64bit
computer-2  : intel(R) Xeon(R) CPU X5650 2.67GHz 2.67GHz    ram 32G   64bit﻿

but if I used old rathnea about 2018-03 version (I forgot hash)
In the same computer, even I aggregated about 1000 monsters, it not be lag
Only new Rathena have this problem

I also try to download the newest Rathena 2019-05-17   hash version [40cc613](https://github.com/rathena/rathena/commit/40cc613418f71ec520ee49452467f869bef6e843)

no any modify , no any custom script, but still happened

And I found other user have this problem either
[why so LAG when 30 mobs moving to trace?](https://rathena.org/board/topic/117999-why-so-lag-when-30-mobs-moving-to-trace/)

Thank you!

**Comment by aleos89** [comment] 2019-05-22 14:08
There were some issues with mob spawns around July of last year from the mapflag and map changes. Those issues should have been resolved by August.

**Comment by hotspicy945** [comment] 2019-05-23 00:38
@aleos89  Thank you for reply
So how can I do to fix this problem?
I use 2019-05-17 Rathena have this problem.
Shoud I change to use about 2018-08 Rathena?

Thank you!!!

**Comment by cydh** [comment] 2019-06-20 03:08
still can be reproduced using 34971e57 (20190611)

**Comment by Playtester** [comment] 2019-06-20 09:05
Would be interesting to know what introduced this issue. 

Sounds a bit like the path finding code got really slow due to some change. The latest change in the path class is https://github.com/rathena/rathena/commit/2ab298076c4eeb506aef156e24c835c31d417490 from 2018-08-10. Does the problem occur here already?

**Comment by cydh** [comment] 2019-06-20 09:23
before the patch 48ae1a1e05db440263ac2a4fe0d887d1528151f3 (1 commit before @Playtester mentioned) is even worse

**Comment by Playtester** [comment] 2019-06-20 09:28
Thanks for testing @cydh 

Can you try: https://github.com/rathena/rathena/commit/a05ed6e814268f881d192a36b89d9ba49d9ca7a8

And: https://github.com/rathena/rathena/commit/584fcac43a13381d74374cf8835b2d2b077913b6

**Comment by cydh** [comment] 2019-06-20 09:49
well, here's the reason why I tested using bbe552d1d3f9e75bcf79f55d1186fedaf4ffff26 (Jul 19, 2018)
* (Jul 19, 2018) it's 1 commit before a942853d55dd0e96ff98e6c352e2c2a9e000ea86 which updates some maps elements into std::map
* (Jul 26, 2018) then 584fcac43a13381d74374cf8835b2d2b077913b6 is another cleanup to get rid fixed array into std::map, and later we found it's terrible
* (Aug 11, 2018) and because of that 48ae1a1e05db440263ac2a4fe0d887d1528151f3 commited to revert std::map for map list back into array

I found back then, after 48ae1a1e05db440263ac2a4fe0d887d1528151f3 the performance is better than 584fcac43a13381d74374cf8835b2d2b077913b6 but is still not good as before the mapflag set to STL at a942853d55dd0e96ff98e6c352e2c2a9e000ea86

**Comment by Playtester** [comment] 2019-06-20 10:37
Ah okay so we know what's causing the issue.

**Closed** 2022-09-17 03:58 UTC
