### ISSUE TITLE
Map server crash

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#5390] opened 2020-09-09 11:48 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/0dd400c136e1176b1342f634bd7171df3cca7a36
* **Client Date**: 20200401
* **Server Mode**: RE
* **Description of Issue**: Map_server crashing.
  * How to Reproduce: Unfortunately I don't know how to reproduce.
* **Modifications in SRC**: https://github.com/rathena/rathena/pull/5081 

Code Dump:

```
[New LWP 667]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000470e1a in clif_send (buf=buf@entry=0x7ffc1055d52a, len=len@entry=6,
    bl=<optimized out>, type=type@entry=CLAN) at clif.cpp:748
748                                     if( ( sd = clan->members[i] ) == nullptr || !session_isActive( fd = sd->fd ) ){
Missing separate debuginfos, use: debuginfo-install glibc-2.17-307.el7.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-46.el7.x86_64 libcom_err-1.42.9-17.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 mariadb-libs-5.5.65-1.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt full
#0  0x0000000000470e1a in clif_send (buf=buf@entry=0x7ffc1055d52a, len=len@entry=6,
    bl=<optimized out>, type=type@entry=CLAN) at clif.cpp:748
        i = 398
        sd = 0x8ff50c0
        tsd = <optimized out>
        p = 0x0
        g = 0x0
        bg = 0x0
        x0 = 0
        x1 = 0
        y0 = 0
        y1 = 0
        fd = <optimized out>
        iter = <optimized out>
        __FUNCTION__ = "clif_send"
#1  0x0000000000495141 in clif_clan_onlinecount (clan=clan@entry=0x7f781bd45034) at clif.cpp:20046
        buf = "\210\t\364\001\364\001"
        sd = <optimized out>
#2  0x000000000046ba80 in clan_member_joined (sd=sd@entry=0x8533710) at clan.cpp:131
        clan = 0x7f781bd45034
        index = <optimized out>
        sd = 0x8533710
#3  0x000000000052a3c0 in pc_reg_received (sd=0x8533710) at pc.cpp:1800
        i = 0 '\000'
        __FUNCTION__ = "pc_reg_received"
#4  0x00000000004c8fde in intif_parse_Registers (fd=<optimized out>) at intif.cpp:1475
        flag = 1
        sd = 0x8533710
        account_id = <optimized out>
        char_id = <optimized out>
        node = <optimized out>
        type = <optimized out>
#5  0x00000000004ce035 in intif_parse (fd=fd@entry=7) at intif.cpp:3756
        packet_len = 16
---Type <return> to continue, or q <return> to quit---
        cmd = <optimized out>
#6  0x000000000046b2ff in chrif_parse (fd=7) at chrif.cpp:1791
        r = <optimized out>
        cmd = 14340
        packet_len = <optimized out>
#7  0x000000000040bc15 in do_sockets (next=<optimized out>) at socket.cpp:1411
        rfd = {fds_bits = {128, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 19997}
        ret = <optimized out>
        i = 7
#8  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:381
No locals.
(gdb)
```

**Comment by admkakaroto** [comment] 2020-09-12 15:55
Maybe this PR its a fix for this issue? https://github.com/rathena/rathena/pull/5204

**Comment by aleos89** [comment] 2020-09-14 12:14
Duplicate of #5376.

**Closed by aleos89** 2020-09-14 12:14 UTC
Labels: status:duplicate
