### ISSUE TITLE
Green MVP

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#5186] opened 2020-07-06 22:05 UTC
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: With recently Ra support 2020 client, I really hope Ra can implement green MVP feature, I think 99% of us including ra developers already know what is green MVP. Kro now the max base level is 200, and a lot of equipment has been updated. RA needs to make MVP stronger in order to balance the server.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:https://www.divine-pride.net/forum/index.php?/topic/3318-kro-mvp-bosses-adjustment/
  

* **Modifications that may affect results**:

**Comment by OptimusM** [comment] 2020-07-06 23:23
Actually, there is a Pull about this on rA https://github.com/rathena/rathena/pull/4231

But, to be honest, doing MVP´s more resistant, it´s the same that add more HP, what it really makes the MVP stronger now on kRO are the new monster skills, not the aura itself.

Actually rA are mising alot, and i really mean it, *ALOT* of monster skills and new boss skills.
that´s will actually do a real balance to boss fights.

**Comment by Surefirer** [comment] 2020-07-06 23:54
@OptimusM Thanks for your replay. RA dev team works really hard to keep RA alive. I really appreciate every single pull request or commit they made. By adding this feature without double MVP's HP, at least we are one more step close to Kro's official behavior. I respect the RA dev team's decision to not implement this feature for a reason. I still want to make an effort to open this ticket.  I just want to knock the door again:)

**Comment by Daegaladh** [comment] 2020-07-08 11:47
Duplicate of #3324

**Closed by Daegaladh** 2020-07-08 11:47 UTC
