### ISSUE TITLE
Itemshop not work

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5154] opened 2020-06-27 16:11 UTC
* **rAthena Hash**: 005a2c4

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**: Itemshop not work
  * Result: Itemshop not work
  * Expected Result: Itemshop work
  * How to Reproduce:  create npc Itemshop then test to buy it
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment] 2020-06-29 01:35
Cannot reproduce this, I tried itemshop and pointshop and both worked fine.

**Comment by mazvi** [comment] 2020-06-29 07:55
@Daegaladh are you try using client 20180620? :)

**Comment by Daegaladh** [comment] 2020-06-29 13:33
Ah no, sorry, I used 2018-06-21aRagexe

**Comment by aleos89** [comment] 2020-06-29 15:16
![image](https://user-images.githubusercontent.com/3521753/86023716-03817600-b9fa-11ea-9c63-862efe8f9d38.png)
Unable to reproduce on 2018-06-20.

**Comment by mazvi** [comment] 2020-06-29 22:45
Can you test it with custom item number 64214? Iam using that id but can buy on itemshop

Or this is posible? Becasue my compiler? 

Bellow my server configuration:

Operating System: CentOS Linux release 7.8.2003 (Core)
Compiler: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
MySQL: mysql Ver 15.1 Distrib 10.1.45-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by Daegaladh** [comment] 2020-06-29 22:50
Have you tried with normal items? Or a lower id?

**Comment by sader1992** [comment] 2020-06-29 22:54
a screenshot and more info could help , "not work" could mean anything.

**Comment by mazvi** [comment] 2020-06-29 22:55
Okay i will test and provide screenshot

**Comment by mazvi** [comment] 2020-06-30 13:23
UPDATE!  work with lower item ID like 909 but dont work using custom item, my item id is 64214

please test / reproduce issue using high item id like 64214 :)

![gambar](https://user-images.githubusercontent.com/8316103/86131190-847e6180-bb0f-11ea-810d-83e22fc951ab.png)

**Comment by Daegaladh** [comment] 2020-06-30 13:27
Maybe related to #5141?

**Comment by mazvi** [comment] 2020-06-30 13:33
i dont know but this is work on rAthena may 7004fe3 

may be this bug is related 79feae3

**Comment by Badarosk0** [comment] 2020-07-01 14:02
> * Itemshop

Confirmed the BUG.

Example to reproduce:

```
prontera,165,174,3	itemshop	Event Shop	877,7828,12209:1,12211:2
```

In kRO there are some stores with this image model:
https://ibb.co/D7d8CCn

There may be some new requirements needed on the emulator to work.

**Comment by Badarosk0** [comment] 2020-07-01 23:41
I did the test again and it is working, Sorry.

Client: 2020-04-01.

![screenrAthena000](https://user-images.githubusercontent.com/13624462/86301091-48b0ce00-bbdb-11ea-85a1-47e163d9e352.jpg)

**Comment by Daegaladh** [comment] 2020-07-02 01:58
I'm going to close this for now, because nobody from the staff or other users have been able to reproduce it.
If in the future you could provide a way we can reproduce it I'll be glad to reopen the issue.

**Closed by Daegaladh** 2020-07-02 01:58 UTC
Labels: status:unable to reproduce

**Comment by mazvi** [comment] 2020-07-02 06:26
Please open again and read my comment

This bug is on 20180620 and only custom item/high item id

I test using item 909 is work but i test using 64214 is not work

**Comment by secretdataz** [comment] 2020-07-02 06:29
Do you have the 32bit item id patch applied?

**Comment by mazvi** [comment] 2020-07-02 06:32
@secretdataz no sir.. but in rAthena may is working normally

@Badarosk0 read your poin its zero amd please using custom item and high item id 64214

**Comment by mazvi** [comment] 2020-07-02 06:36
The custom item using id 64214 its work without 32bit item id but this item cannot use for buy on itemshop

I think itemshop not read the custom item id
