### ISSUE TITLE
Speed command affect ASPD

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#6722] opened 2022-03-20 06:53 UTC
* **rAthena Hash**: 242983f0d

* **Client Date**: 20211103

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Command `@speed 1` changed ASPD.
  * Expected Result: Command `@speed 1` should not changed ASPD.
  * How to Reproduce: Create new character -> Enter game -> see status panel -> `@speed 1`.
  * Official Information: -

* **Modifications that may affect results**: -

Test on my PC

https://user-images.githubusercontent.com/9493525/159170550-d04e4f0a-903a-480e-9845-ba0e275b5089.mp4

Test on live server

https://user-images.githubusercontent.com/9493525/159151695-ff4eeaf8-b28a-4ae5-906c-d76b74666f96.mp4

**Comment by aleos89** [comment] 2022-03-22 18:40
Duplicate of #6715.

**Closed by aleos89** 2022-03-22 18:40 UTC
Labels: status:duplicate
