### ISSUE TITLE
[Error]: status_skill2sc: Unsupported skill id 65535

### ISSUE THREAD

**Issue by tkporreta** [rathena/rathena#4638] opened 2020-02-13 20:30 UTC
* **rAthena Hash**: b68133952953caec69a7ee520e1d46826f3acf4b
* **Client Date**: 2018-09-19aRagexe or 2018-06-21aRagexeRE
* **Server Mode**: Pre-Renewal
* **Description of Issue**: 
When you have two bards using skills and one leaves the field, the emulator starts to make these errors.
[https://www.youtube.com/watch?v=6z_uP752mVs](url)
[Error]: Skill '65535' is undefined! m:\rAthena\src\map\status.cpp:219::status_skill2sc
[Error]: status_skill2sc: Unsupported skill id 65535

**Comment by sader1992** [comment] 2020-02-13 20:42
https://github.com/rathena/rathena/issues/1341

**Comment by secretdataz** [comment] 2020-02-14 03:13
duplicate of #1341

**Closed by secretdataz** 2020-02-14 03:13 UTC
Labels: status:duplicate
