### ISSUE TITLE
Strength/Dexterity weapon atk bonus from Buffs, Foods and Runes does not apply

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#578] opened 2015-08-15 00:23 UTC
as we know rAthena designed it so that weapon atk bonus from status are visible , problem is none of atk bonus (weapon atk) from stats ( buffs/foods/runes ) apply in the status window i don't know if this intended or a bug but im gonna report it anyway. ^^

![screenjamro073](https://cloud.githubusercontent.com/assets/8035101/9286463/bd7488b8-4326-11e5-9aa9-a7f849bd9de7.jpg)

**Comment by anacondaqq** [comment] 2015-10-26 07:02
Is this still exist?

**Comment by RagnarokNova** [comment] 2015-10-26 07:17
I'm not sure, but I am also aware that most MATK buffs are invisible to the status window, and I'm also not sure if this is intended or not. I get constant reports of MATK boosting skills "not working" because the status window does not show them on my server.

**Comment by Paoly28** [comment] 2015-10-29 17:22
i tested this on high weapon atk ( pilebunker ) and Poring of course with weapon maximize and weapon perfection
used +20 str foods and only dealt additional 42 damage ( status atk is doubled during calculation )  whereas i should actually get 85+ using high weapon atk.

I dunno where i get the extra 2 dmg must be factors outside the test

![screenjamro079](https://cloud.githubusercontent.com/assets/8035101/10826361/6752c062-7ea4-11e5-9c5e-97ea3ccc3dc0.jpg)

![screenjamro078](https://cloud.githubusercontent.com/assets/8035101/10826362/675d54b4-7ea4-11e5-9c6b-f7140b34d136.jpg)

**Comment by Paoly28** [comment] 2015-10-29 17:35
@RagnarokNova this is different from racial bonuses as rA's design is to show atk bonus from STR at the status window, hence why your weaponatk/eqatk increases when you pump str or equip str increasing equipment.

**Comment by Lemongrass3110** [comment] 2015-11-03 21:43
Possible duplicate of #554 ?

**Comment by Paoly28** [comment] 2015-11-13 05:59
@Lemongrass3110  it's different.

#554 is about status window showing the str bonus for weapon atk, this report however is about str from buffs not giving the respected weapon atk bonus from str/dex.

**Comment by Playtester** [comment] 2015-11-13 08:47
Yeah, well, we probably should decide for either show everything (easier to understand, less players complain about boosts not working) or show nothing (official) or even better, make a config for it. Right now I think it's a weird mix of both depending on which developer has coded it.

**Comment by Paoly28** [comment] 2015-11-14 05:24
bug isn't about the str bonus not showing up, it's about not giving str atk bonus from buffs not working at all.

**Closed** 2020-12-20 23:52 UTC
Labels: component:core, missing:clientdate, missing:revision, mode:renewal, status:confirmed, type:bug
