### ISSUE TITLE
Mysql 8 error 1071 max key length is 1000 bytes

### ISSUE THREAD

**Issue by fuzzyfreak** [rathena/rathena#3430] opened 2018-08-25 07:28 UTC
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
When importing main.sql the error occurs.  The engine is MyISAM

**Comment by aleos89** [comment] 2018-08-26 19:56
Duplicate of #3093.

**Closed by aleos89** 2018-08-26 19:56 UTC
Labels: status:duplicate
