### ISSUE TITLE
map server crash 

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#5740] opened 2021-02-14 03:19 UTC
* **rAthena Hash**: 1e43c6c
* **Client Date**: 2020-05-20b
* **Server Mode**:  Pre-renewal

* **Description of Issue**: 
#0  0x00000000004ef97a in map_addblock (bl=0x39e23310) at map.cpp:404
404                     bl->next = mapdata->block[pos];
(gdb) bt full
#0  0x00000000004ef97a in map_addblock (bl=0x39e23310) at map.cpp:404
        m = 1098
        y = 64
        x = 37
        pos = 308
        mapdata = 0x1233820 <map+10523232>
#1  map_addblock (bl=bl@entry=0x39e23310) at map.cpp:366
No locals.
#2  0x00000000004bcb66 in clif_parse_LoadEndAck (fd=<optimized out>,
    sd=0x39e23310) at clif.cpp:10796
        guild_notice = false
        mapdata = 0x1233820 <map+10523232>
#3  0x0000000000485f06 in clif_parse (fd=967) at clif.cpp:22646
        cmd = 125
        packet_len = 2
        sd = 0x39e23310
        pnum = 0
#4  0x00000000006b0f9d in do_sockets (next=next@entry=20) at socket.cpp:1411
        rfd = {fds_bits = {0, 64, 0 <repeats 13 times>, 128, 140737488355328,
            0 <repeats 143 times>}}
        timeout = {tv_sec = 0, tv_usec = 18646}
        ret = <optimized out>
        i = 967
#5  0x000000000041b827 in main (argc=<optimized out>, argv=<optimized out>)
    at core.cpp:382
        next = 20

**Comment by aleos89** [comment] 2021-02-17 12:44
Duplicate of #4363.

**Closed by aleos89** 2021-02-17 12:44 UTC
Labels: status:duplicate
