### ISSUE TITLE
Marketshop - fix sell list

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#4419] opened 2019-10-23 19:11 UTC
* **rAthena Hash**: d9e0409

* **Client Date**: -

* **Server Mode**: Pre/RE

* **Description of Issue**: 
  * Result: if limited item were sold from 'marketshop' they are remove from list.
  * Expected Result: when limited item sold it shouldn`t remove from sell list and you can`t buy it.
  * How to Reproduce: buy all item from 'marketshop'.
  * Official Information: Tested on kRo (2019-10-23).
https://youtu.be/mcT3YyQAArM
* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2019-12-20 19:08
Is this a duplicate of #4113?

**Comment by aleos89** [comment] 2019-12-20 19:45
From the description it does seem like a duplicate.

**Comment by Balferian** [comment] 2019-12-23 09:59
It's not the same problem.
I mean that sold items must be showed in the shop, but players can't buy it.
![image](https://user-images.githubusercontent.com/16213511/71350802-2df20280-2583-11ea-9819-e6b877ca1adb.png)
![image](https://user-images.githubusercontent.com/16213511/71350812-38140100-2583-11ea-8e78-1eb351dd5199.png)
You can see this on video or check on kRo server.
When we try to buy an item that is sold we have error in the chat.
![image](https://user-images.githubusercontent.com/16213511/71351050-d738f880-2583-11ea-8333-b68a25804912.png)

**Comment by Lemongrass3110** [comment] 2019-12-23 11:11
The thing you showed is unlimited stock i think

**Comment by Balferian** [comment] 2019-12-23 11:48
I thought so too.
But these things cannot be bought.

**Comment by Balferian** [comment] 2019-12-23 12:48
![image](https://user-images.githubusercontent.com/16213511/71358867-8634fe80-259b-11ea-80c4-d99fd74d9970.png)
For now shop is updated and i can buy Coagulated Spell
and cant buy Temporal Crystall because it is sold.

**Comment by Lemongrass3110** [comment] 2019-12-23 23:22
This is simply either a late 2018 or 2019 client feature.
I have run this on rAthena with a 2019 client and it works just like you showed it.

**Comment by Lemongrass3110** [comment] 2020-06-03 14:36
Fixed in 45cd580

**Closed by Lemongrass3110** 2020-06-03 14:36 UTC
Labels: component:core, mode:renewal, priority:low, status:confirmed, type:bug
