### ISSUE TITLE
[Crash] clif_send - WFIFOHEAD(fd,len);

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#5194] opened 2020-07-09 01:07 UTC
* **rAthena Hash**: 7457e32

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: Crash upon clif_send for clan
  * Result: map-server down
  * Expected Result: No crash
  * How to Reproduce: Not sure how this happens. See bt full of core file.
  * Official Information:
  

* **Modifications that may affect results**: None except for available PR which are 2billion ItemID, quest objectives PR, Blocking Play PR.

gdb dump:
[bt_full clif_send - clan.txt](https://github.com/rathena/rathena/files/4893936/bt_full.clif_send.-.clan.txt)

Additional Info: Happens frequently on newer client. Old client doesn't seem to have any issue.

**Comment by ecdarreola** [comment] 2020-07-09 12:45
Here's another gdb dump 
[bt_full-reproduce.txt](https://github.com/rathena/rathena/files/4896819/bt_full-reproduce.txt)

**Comment by Lemongrass3110** [comment] 2020-07-11 09:40
Duplicate of #5196

**Closed by Lemongrass3110** 2020-07-11 09:40 UTC
Labels: status:duplicate
