### ISSUE TITLE
After updating from Dec 5, 2022 up to today 

### ISSUE THREAD

**Issue by rAthenaServer** [rathena/rathena#7509] opened 2022-12-23 20:36 UTC
### rAthena Hash

https://github.com/rathena/rathena/commits/master

### Client Date

20220406

### Server Mode

Renewal

### Result

Various systems are broken and all functions are working well.
1 - Game Roulette Can play in a row below a single row. (Now i can fix it)
2 - Class 4 Expanded Can not us skill.
3 - Class 4 and Class 4 Expanded Skill icon not showing up.
- Spirit Handler
- Hyper Novice
- Night Watch
- Shiranui
- Shinkiro
- Soul Ascetic
- Sky Emperor
- Meister

==============================================

### Relevant Log Output

```Shell
Roulette  (Now i can fix it)
https://user-images.githubusercontent.com/121316776/209402910-73804216-44e4-472f-8aa5-83185c27af4f.mp4

==============================================
![Hyper Novice](https://user-images.githubusercontent.com/121316776/209402773-4795a0b7-0ddb-4998-9b54-1a502879f39a.png)

![Meister](https://user-images.githubusercontent.com/121316776/209402778-4f50d943-96d4-4eca-8460-6f5a9aa9bc83.png)

![Night Watch](https://user-images.githubusercontent.com/121316776/209402781-f0a0b28c-cf76-4d68-a4b9-3de1216f629d.png)

![Shinkiro](https://user-images.githubusercontent.com/121316776/209402782-65d18d81-6b9c-4c9a-aaac-a9168bded6f5.png)

![Shiranui](https://user-images.githubusercontent.com/121316776/209402783-49056b48-cc57-4fe9-b15d-4dba94640223.png)

![Sky Emperor](https://user-images.githubusercontent.com/121316776/209402785-375afe5c-48c0-4c43-b23c-12fda907ec25.png)

![Soul Ascetic](https://user-images.githubusercontent.com/121316776/209402788-ffcf9771-0245-45cf-8cf3-471663dde972.png)

![Spirit Handler](https://user-images.githubusercontent.com/121316776/209402790-99573c00-f598-4851-a8ce-377179edb712.png)
```

### Expected Result

Please check, not arguing. I encountered many problems before anyone else, but I couldn't post because I was blocked. Do you understand the word likely to be a problem?
Still, it's good to have someone check it out.

Looking at the topic written to ask each other, it's stupid to ask because it's because I made a mistake. I still see it to post normally.

I know how to fix some things and I can't post them. It's good that I won't tell you how to solve it.

### How to Reproduce

Please check, not arguing. I encountered many problems before anyone else, but I couldn't post because I was blocked. Do you understand the word likely to be a problem?
Still, it's good to have someone check it out.

Looking at the topic written to ask each other, it's stupid to ask because it's because I made a mistake. I still see it to post normally.

I know how to fix some things and I can't post them. It's good that I won't tell you how to solve it.

### Official Information

-

### Modifications that may affect results

I update from this https://github.com/rathena/rathena/commits/master
Dec 5, 2022 up to today.

**Comment by Lemongrass3110** [comment] 2022-12-23 21:01
The only valid part of your report is a duplicate of #7506.

Enjoy your next ban until you finally learn to use Discord and ask there. And the only question you can ask is „What did I break during merging xxx?“. If you would know how to fix stuff, you would not have angered us that much that we already had to ban many of your accounts for ban evasion.

**Closed by Lemongrass3110** 2022-12-23 21:01 UTC
Labels: type:bug
