### ISSUE TITLE
skill_damage_db.txt no effect / no changes on skill damage happen.

### ISSUE THREAD

**Issue by jofvgaming** [rathena/rathena#6897] opened 2022-04-27 08:22 UTC
* **rAthena Hash**: Latest 

* **Client Date**:  20180621

* **Server Mode**:  Pre-Renewal, not yet tested on Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

db/[skill_damage_db.txt](https://github.com/rathena/rathena/blob/master/db/skill_damage_db.txt)
db/import/skill_damage_db.txt

Not take effect, no changes on skill damage output, not working,  already used @reloadskilldb @reloadskilldamgedb, rathena restart
* **Modifications that may affect results**: 
  
  
No modification

**Comment by aleos89** [comment] 2022-04-27 12:29
Duplicate of #6896.

**Closed by aleos89** 2022-04-27 12:29 UTC
Labels: status:duplicate
