### ISSUE TITLE
[Missing Feature] Inventory Expansion

### ISSUE THREAD

**Issue by xEasycore** [rathena/rathena#6237] opened 2021-09-06 22:07 UTC
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/cb83cb8fa4eebf333f1ffd7e9b3fc0ccd0473d43

* **Client Date**: 
2018-10-31

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Missing Feature: Inventory Expansion
Gravity has implemented the feature of expand your inventory size years ago.
  * Official Information:
http://imgc1.gnjoy.com/ufile/ro/2018/11/21/QK3O60RA1MGOMU301NUO.gif
![image](https://i.imgur.com/2IX9sxn.gif)
  * Additional Information:
HerculesWS Team has implemented this feature:
[https://github.com/HerculesWS/Hercules/pull/2324/files](https://github.com/HerculesWS/Hercules/pull/2324/files)

**Comment by Lemongrass3110** [comment] 2021-09-07 07:37
Duplicate of #5218

**Closed by Lemongrass3110** 2021-09-07 07:37 UTC
Labels: type:bug
