### ISSUE TITLE
[Suggestion] Implement Dual Dagger Double Attack Critical Guillotine Cross

### ISSUE THREAD

**Issue by reymarbc** [rathena/rathena#2652] opened 2017-11-29 05:45 UTC
In this GX Guide [LimitRO GX Guide](https://www.limitro.com/forums/topic/4567-mvp-guillotine-cross-dual-dagger-da-critical-build/) the OP said that since 2016 kRO implemented this already, 
I just thought that implementing this to our GX makes a huge impact in this class
Thank you for the devs specially @aleos89

**Comment by admkakaroto** [comment] 2017-11-29 11:24
NovaRO has already implemented that too.

**Comment by Atemo** [comment] 2017-11-29 14:00
Duplicate of https://github.com/rathena/rathena/issues/1788

**Closed by Atemo** 2017-11-29 14:00 UTC
