### ISSUE TITLE
gettick() in channel.cpp always return an integer larger than 0

### ISSUE THREAD

**Issue by syracuase** [rathena/rathena#3017] opened 2018-03-30 19:10 UTC
**Client Date:**
2017-06-14

**Server Mode:**
Renewal

**Description of Issue:**
I keep getting talking too fast messages when using the chat channel system. Tried different configuration to no avail. [Reducing cooldown from the default to 100 or any non zero would cause the error] The chat seems to be in perpetual cool down.

Pulled and re-compiled on windows it works. Pull on live server, compile in centos doesnt work.

**Expected Result:** 
Chat cooldown follow the configuration.

**How to Reproduce:** 
Compile a fresh rAthena, pull to a live server [the same directory]. Compile on centos7, didnt work.

**Official Information:**

**Modifications that may affect results:**
Gepard, iRO ASPD, Pet Evolution, RefineUI but none of these touches the channel.cpp

**Comment by vstumpf** [comment] 2018-03-31 00:25
Please use the issue template.

**Comment by sader1992** [comment] 2018-03-31 00:59
i do confirm that the `channel chat delay` have issue >> however don't have info about it/and can't reproduce it and didn't look more into it
if you follow the template (as @vstumpf mention) and you know (How to Reproduce) it would save a lot of time
with my tests (clean rathena) the issue does not happen (when you open the server)
and it just appear from no where (when ppl report me for this issue i just remove the channel chat delay)

**Comment by vstumpf** [comment] 2018-03-31 01:52
The only thing I can think of is that `gettick()` is so big, the subtraction underflows. Maybe casting as 64 bit integers is the way to go.

**Comment by Sirique** [comment] 2018-04-29 19:32
Anyone found a working solution?

**Comment by sader1992** [comment] 2018-04-29 20:45
@Sirique if you have the issue and how to Reproduce it , it will get fix faster
if not i suggest you put the channel delay to 0 until it get a fix

**Comment by Sirique** [comment] 2018-05-06 19:31
To anyone who had the same issue, which is having the message You're talking to fast when using the channel system you have to use ./configure --enable64bit and then recompile your server. Make sure thaat whatever platform you use that it can handle 64bit. So if you use a linux droplet make sure to choose one with 64bit.

**Comment by RadianFord** [comment] 2018-05-06 22:33
I did that too, enabling 64bit but issue is randomly happening

**Comment by aleos89** [comment] 2018-10-19 17:19
This is strictly an issue with how tick is defined, not how the server is compiled or anything else. Having a 64bit server will not change the results of this.

**Comment by vBrenth** [comment] 2018-11-05 10:34
@aleos89  any update to this bug? our #channel is getting messy.

**Comment by aleos89** [comment] 2018-11-05 14:20
Lemon and I had originally started something for this some time ago but it got left behind for other things. I don't remember where it's left off at aside from the client issues I described in my other comment. Maybe @Lemongrass3110 remembers.

**Comment by vBrenth** [comment] 2018-11-06 05:05
@Lemongrass3110 Hello, If you have semi-fix for this please share 💯

**Comment by vBrenth** [comment] 2018-11-08 12:09
I used 64bit Debian 8, Still nothing even if i restarted the Server/Host still delay is bug.

**Comment by RadianFord** [comment] 2018-11-09 03:48
@Lemongrass3110 Yes. restarts makes the channel system works again.

**Closed** 2018-12-20 23:02 UTC
Labels: component:core, mode:prerenewal, mode:renewal, priority:low, type:bug
