### ISSUE TITLE
C++ Waring on CSAVE_INVENTORY

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#1985] opened 2017-02-28 08:32 UTC
rAthena Hash: Latest ( 4270ef8 )

* **Client Date**:  any
* **Server Mode**:  any

* **Description of Issue**: 

Getting incompatible error on VisualC++ 2010

![capture](https://cloud.githubusercontent.com/assets/11855571/23397420/4f85f8c2-fd4d-11e6-849b-cd795ea7e343.JPG)

**Comment by reigneil** [comment] 2017-02-28 12:20
i'm also using visual c++ 2010 but how will i reproduce that kind of error?

**Comment by aleos89** [comment] 2017-02-28 14:03
As it states, make sure `CSAVE_INVENTORY` is not an integer (which can't be a mask type):
```c
enum e_chrif_save_opt {
	CSAVE_NORMAL = 0x00,		/// Normal
	CSAVE_QUIT = 0x01,				/// Character quitting
	CSAVE_CHANGE_MAPSERV = 0x02,	/// Character changing map server
	CSAVE_AUTOTRADE = 0x04,		/// Character entering autotrade state
	CSAVE_INVENTORY = 0x08,		/// Inventory data changed
	CSAVE_CART = 0x10,				/// Cart data changed
	CSAVE_QUITTING = CSAVE_QUIT|CSAVE_CHANGE_MAPSERV|CSAVE_AUTOTRADE,
};
```

**Comment by keitenai** [comment] 2017-02-28 19:06
All i did was to open the fresh rathena git on VS2010 to compare and trace a bug on my modified trunk. Then i just happen to see a red underlining mark on it.

**Comment by aleos89** [comment] 2017-03-01 14:35
It seems to be an intellisense issue and it doesn't like the fact that there's no value for `CSAVE_INVENTORY` and `CSAVE_CART` like the `CSAVE_QUITTING` value. AppVeyor does not show any compile errors or warnings though, so it's possible you're missing some SDK. ([2010 Renewal](https://ci.appveyor.com/project/rAthenaAPI/rathena/build/master-980/job/h7xal3o0uuya5tuc) / [2010 Pre-renewal](https://ci.appveyor.com/project/rAthenaAPI/rathena/build/master-980/job/yv1p7qrap4ohg9a0))

My suggestion would be to possibly look into moving to a newer compiler. We will be ending support for older versions soon so I'd suggest you look into MSVS 2015 or MSVS 2017.

**Comment by keitenai** [comment] 2017-03-05 05:04
I see, thanks for the heads up.
Guess its time to get myself used to newer version compilers.

**Comment by secretdataz** [comment] 2017-05-02 06:02
No longer valid since VS2010 is no longer supported.

**Closed by secretdataz** 2017-05-02 06:02 UTC
