### ISSUE TITLE
Suggestion : script command "itemshop" renewal

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5716] opened 2021-01-25 12:00 UTC
**Is your request related to a missing feature?** Yes

**Describe the solution you'd like** 

Now Rathena uses Cash shop UI when "itemshop" command used.

Official KRo uses new UI for itemshop, with several differences.
![Raitemshop](https://user-images.githubusercontent.com/47050704/105702361-096b1580-5f4f-11eb-80f6-7a951c38216e.png)
![KROitemshop](https://user-images.githubusercontent.com/47050704/105702382-0f60f680-5f4f-11eb-9f83-43bb77734537.png)

Above is from Rathena. Below is from official KRO.

First, new itemshop ui shows icon of cost item.

Second, look of ui is different, like red square in Rathena screenshot above. Also, new ui can be closed with 'esc' key.

![mutiple itemshop](https://user-images.githubusercontent.com/47050704/105703238-45eb4100-5f50-11eb-9d83-780666bab8c7.png)

Finally, mutiple cost item, also with zeny, is possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by Balferian** [comment] 2021-01-25 12:06
duplicate of #5062

**Closed** 2021-01-25 13:18 UTC
Labels: status:duplicate
