### ISSUE TITLE
Client crash when click get all items in RodEx service [2020-03-18bRagexe]

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#5091] opened 2020-06-12 23:52 UTC
* **rAthena Hash**: 5cc04d963741c27b7ba641547d83ff481c86d4e6

* **Client Date**:  2020-03-18bRagexe

* **Server Mode**: Re

* **Description of Issue**:  click get all mail attachments button, you do not get all item, you have to log out, then log in, but when you click again, client crash
  * Result: 
  * Expected Result: 
  * How to Reproduce: diff 2020-03-18bRagexe, then send 3 or more items, try to use get all button, your client will crash.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2020-06-12 23:58
Duplicate of #5061.

**Closed by aleos89** 2020-06-12 23:58 UTC
Labels: status:duplicate

**Comment by voyfmyuh** [comment] 2020-07-13 16:19
May I ask when this problem can be corrected, I have tested that Hercules does not have this problem, thank you
