### ISSUE TITLE
Error std::min

### ISSUE THREAD

**Issue by Beginerxx** [rathena/rathena#8400] opened 2024-06-04 11:09 UTC
### rAthena Hash

https://github.com/rathena/rathena/commit/48b4623f3eb28c2ce1baee6bcd8e811063ea1106

### Client Date

2023-09-06

### Server Mode

Renewal

### Result

Hi i found error std::min after update from 
https://github.com/rathena/rathena/commit/48b4623f3eb28c2ce1baee6bcd8e811063ea1106
Or i miss some function Thank you.

![Screenshot 2024-06-04 180310](https://github.com/rathena/rathena/assets/169546524/16592830-3852-43a2-8eba-b211dc39efdd)

### Relevant Log Output

```Shell
none
```

### Expected Result

none

### How to Reproduce

none

### Official Information

none

### Modifications that may affect results

none

**Comment by Lemongrass3110** [comment] 2024-06-04 11:50
Has to be a merge error on your side.
All the Continous Integration tests are compiling fine and I can also not reproduce it locally in MSVS (not in x86 and not in x64).
What version of MSVS are you using?

**Comment by Beginerxx** [comment] 2024-06-04 12:07
> Has to be a merge error on your side. All the Continous Integration tests are compiling fine and I can also not reproduce it locally in MSVS (not in x86 and not in x64). What version of MSVS are you using?

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.7.3

**Comment by Daegaladh** [comment] 2024-06-04 16:42
> > Has to be a merge error on your side. All the Continous Integration tests are compiling fine and I can also not reproduce it locally in MSVS (not in x86 and not in x64). What version of MSVS are you using?
> 
> Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.7.3

Try updating your MSVS version, I don't have any issues in v17.10.0

**Comment by Beginerxx** [comment] 2024-06-05 01:40
> > > Has to be a merge error on your side. All the Continous Integration tests are compiling fine and I can also not reproduce it locally in MSVS (not in x86 and not in x64). What version of MSVS are you using?
> > 
> > 
> > Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.7.3
> 
> Try updating your MSVS version, I don't have any issues in v17.10.0

Thank you it's not working.

**Comment by Playtester** [comment] 2024-06-05 06:17
Can you try to add
`#include <algorithm>`
At the top of the npc.cpp file?

**Comment by Beginerxx** [comment] 2024-06-05 06:59
> Can you try to add `#include <algorithm>` At the top of the npc.cpp file?

Thank you very much for trying to help. But it's still not working.

![Screenshot 2024-06-05 135740](https://github.com/rathena/rathena/assets/169546524/2a00da8f-b904-41aa-9ddb-c809e5a52094)

**Comment by Lemongrass3110** [comment] 2024-06-11 17:01
Closing this as we are unable to reproduce this.
If you still have this problem, feel free to send me a direct message on Discord.

**Closed by Lemongrass3110** 2024-06-11 17:01 UTC
Labels: status:unable to reproduce

**Comment by Beginerxx** [comment] 2024-06-12 04:11
> Closing this as we are unable to reproduce this. If you still have this problem, feel free to send me a direct message on Discord.

Thank you very much.
