### ISSUE TITLE
Cash Shop Sale Limited

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8348] opened 2024-05-20 12:49 UTC
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

Implement in rAthena the Cash Shop Sale Limited for Clients 2019-07-24 above.

**Comment by aleos89** [comment] 2024-05-20 13:31
Might need @Lemongrass3110's input, but I think this was due to removal in newer clients.

**Comment by datawulf** [comment] 2024-05-20 16:43
iirc the ui/date-format had a little update last year

**Comment by Lemongrass3110** [comment] 2024-05-20 17:38
Duplicate of #7512

**Closed by Lemongrass3110** 2024-05-20 17:38 UTC
Labels: type:enhancement
