### ISSUE TITLE
crash in func map_addblock() on map.cpp

### ISSUE THREAD

**Issue by samers1** [rathena/rathena#4477] opened 2019-12-11 21:14 UTC
That gdb error:

```
#0  0x00000000004c7254 in map_addblock (bl=bl@entry=0xfe1d210) at map.cpp:360
360                     bl->next = mapdata->block[pos];
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.el7_7.2.x86_64 libcom_err-1.42.9-16.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libselinux-2.5-14.1.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 mariadb-libs-5.5.64-1.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt full
#0  0x00000000004c7254 in map_addblock (bl=bl@entry=0xfe1d210) at map.cpp:360
        m = 1079
        y = 281
        x = 150
        pos = 1348
        bl = 0xfe1d210
#1  0x00000000004a11e3 in clif_parse_LoadEndAck (fd=<optimized out>, sd=0xfe1d210) at clif.cpp:10552
        guild_notice = false
        mapdata = 0xf0f3a0 <map+5904288>
#2  0x000000000046ca10 in clif_parse (fd=149) at clif.cpp:21750
        cmd = <optimized out>
        packet_len = 2
        sd = 0xfe1d210
        pnum = 0
#3  0x000000000040b815 in do_sockets (next=<optimized out>) at socket.cpp:1407
        rfd = {fds_bits = {0, 16384, 9007233616576512, 0 <repeats 13 times>}}
        timeout = {tv_sec = 0, tv_usec = 19730}
        ret = <optimized out>
        i = 149
#4  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:369
```

Map.cpp func  map_addblock():

```
int map_addblock(struct block_list* bl)
{
	int16 m, x, y;
	int pos;

	nullpo_ret(bl);

	if (bl->prev != NULL) {
		ShowError("map_addblock: bl->prev != NULL\n");
		return 1;
	}

	m = bl->m;
	x = bl->x;
	y = bl->y;

	if( m < 0 )
	{
		ShowError("map_addblock: invalid map id (%d), only %d are loaded.\n", m, map_num);
		return 1;
	}

	struct map_data *mapdata = map_getmapdata(m);

	if( x < 0 || x >= mapdata->xs || y < 0 || y >= mapdata->ys )
	{
		ShowError("map_addblock: out-of-bounds coordinates (\"%s\",%d,%d), map is %dx%d\n", mapdata->name, x, y, mapdata->xs, mapdata->ys);
		return 1;
	}

	pos = x/BLOCK_SIZE+(y/BLOCK_SIZE)*mapdata->bxs;

	if (bl->type == BL_MOB) {
		bl->next = mapdata->block_mob[pos];
		bl->prev = &bl_head;
		if (bl->next) bl->next->prev = bl;
		mapdata->block_mob[pos] = bl;
	} else {
		bl->next = mapdata->block[pos];
		bl->prev = &bl_head;
		if (bl->next) bl->next->prev = bl;
		mapdata->block[pos] = bl;
	}

#ifdef CELL_NOSTACK
	map_addblcell(bl);
#endif

	return 0;
}
```

clif.cpp call func:

```
	if(map_addblock(&sd->bl))
		return;
```

**Comment by yashimwong** [comment] 2019-12-12 10:44
How to trigger this crash?

**Comment by Lemongrass3110** [comment] 2020-01-02 23:43
Duplicate of #4363

**Closed by Lemongrass3110** 2020-01-02 23:43 UTC
