### ISSUE TITLE
@clone Recieved Only 1 Damage

### ISSUE THREAD

**Issue by krispaul27** [rathena/rathena#7667] opened 2023-03-27 17:02 UTC
### rAthena Hash

198566204

### Client Date

20151104

### Server Mode

Pre-Renewal

### Result

clone Recieved Only 1 Damage From Player by Normal Attacks And Skills

### Expected Result

To Fix Clone Damage Recieved

### How to Reproduce

To Fix Clone Damage Recieved

### Official Information

To Fix Clone Damage Recieved

**Comment by aleos89** [comment] 2023-03-27 21:14
Duplicate of #7579.

**Closed** 2023-03-27 21:14 UTC
Labels: status:duplicate
