### ISSUE TITLE
Eden Group Market Vendors Messed Up

### ISSUE THREAD

**Issue by NordGate** [rathena/rathena#6418] opened 2021-12-21 10:56 UTC
* **rAthena Hash**: 

* **Client Date**: 2018-06-20e

* **Server Mode**: renewal

* **Description of Issue**: In Eden Group Market (paramk), the NPCs selling does not remove the purchased item, they remove it from the top of their sale list. 

Also adding an item back from the buy list won't bring back the item that got removed, only adds to the one currently on top of the list. 
  * Result: 
  * Expected Result: 
  * How to Reproduce: Most clear on NPCs with a buying limit of just one, but also happens with other NPCs that have higher purchase limit, the amount on the topmost gets reduced, not the one that actually was purchased.
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2021-12-21 11:44
Duplicate of #3267

**Closed by Lemongrass3110** 2021-12-21 11:44 UTC
Labels: type:bug

**Comment by NordGate** [comment] 2021-12-21 11:57
still not fixed. the bug is valid, on "supported" client. or wait, is the client supported only on the features you guys know how to make / fix?
