### ISSUE TITLE
Loading map cause the client stop running

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#2411] opened 2017-09-09 08:39 UTC
* **Client Date**: 2017-06-14

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: if change map fastly,client will probability stop running. After back to character field then loadint map, the client will probability stop running,too.
  * Expected Result: It should not to stop running.
  * How to Reproduce: Use 2017-06-14 client and @warp "anymap" quickly.It will reproduce.
  * Official Information: N / A
  

* **Modifications that may affect results**: N / A

**Comment by admkakaroto** [comment] 2017-09-09 10:45
Client 2017-05-31, I can not reproduce this.

**Comment by redlightliu** [comment] 2017-09-09 10:58
... I use Client 2017-06-14

**Comment by sader1992** [comment] 2017-09-09 11:17
normally windows get to programs stuck in loading so if you did rush on the program while it's on loading mode in window mode it will stop working
Usually full screen mode would fix this but no one use full screen in ragnarok :P 

i did test that and i can't reproduce your problem with 2017/6/14

**Comment by redlightliu** [comment] 2017-09-09 11:52
https://www.youtube.com/watch?v=XqpW36-NLLA&feature=youtu.be
reproduce the problem

**Comment by redlightliu** [comment] 2017-09-09 12:23
This problem is about on mine hardware.
Really Thank you

**Comment by Akkarinage** [comment] 2017-09-09 16:13
Marked as invalid and closing as this is client related.

**Closed by Akkarinage** 2017-09-09 16:13 UTC
Labels: status:invalid
