### ISSUE TITLE
Marketshop Purchase Ack Bug

### ISSUE THREAD

**Issue by akiyamamio16** [rathena/rathena#5696] opened 2021-01-17 12:48 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/a33887b59f2b601665d313a0e260d826fced4b0c

* **Client Date**: 20180620

* **Server Mode**: Pre-Renewal

* **Description of Issue**: It changed the amount of the other items in the list instead of the dragged item. dragging the same item will result in more amount but will give error.
  * Result: doesn't reduce the amount from the shop list once dragged, it also happens wherein the item which is not dragged is the one reduced. 
  * Expected Result: Once dragged to purchase cart, should reduce the amount of the dragged item on the list 
  * How to Reproduce: create a marketshop and purchase things 
  

* **Modifications that may affect results**:  none
  
  
  
  Video proof : https://streamable.com/sfqxdz

**Comment by Lemongrass3110** [comment] 2021-01-17 23:13
Duplicate of #4419

This is a client problem. Upgrade to a newer one.

**Closed by Lemongrass3110** 2021-01-17 23:13 UTC
Labels: status:duplicate
