### ISSUE TITLE
Bullet (Id: 13200) wrong db info

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3494] opened 2018-09-15 22:30 UTC
* **rAthena Hash**: 3cd771732

* **Client Date**: 2018-06-21a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The item 13200 have wrong attack it 10 and wrong weight 0,2
  * Expected Result: The item should have attack 25 and weight 0,1
  * How to Reproduce: Look at db rathena renewal
  * Official Information:
Look at kro version NOT iro version : https://www.divine-pride.net/database/item/13200
And you can look at Korean Ragnarok Online\System\itemInfo_true.lub id: 13200

금속을 주재료로 하였으며 관통력으로 살상 및 파괴효과를 낸다.
계열 : 총알 공격 : 25
무게 : 0.1 속성 : 무 

> 

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2018-09-17 17:05
Duplicate of #2745.

**Closed by aleos89** 2018-09-17 17:05 UTC
Labels: status:duplicate
