### ISSUE TITLE
Issue With Dynamic NPC when Server Compile

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7460] opened 2022-11-26 21:38 UTC
### rAthena Hash

bc4934373db20935f1ab36a1df71e33463987cb8

### Client Date

20211103

### Server Mode

Renewal

### Result

![gambar](https://user-images.githubusercontent.com/8316103/204109846-ad4f0341-1e80-49bb-8800-f7e3bccf46a8.png)

### Expected Result

Normal

### How to Reproduce

OS: Centos 7
GCC: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

this is my compile bash

```
scl enable devtoolset-7 bash
which gcc
gcc --version

ulimit -c unlimited
./configure --enable-debug=gdb --enable-packetver=20211103 --enable-64bit --with-MYSQL_LIBS=/usr/lib64/libmysqlclient.so
make clean
make server
```

### Official Information

N/A

**Comment by mazvi** [comment] 2022-11-26 21:41
Maybe another related issue https://github.com/rathena/rathena/issues/7419

**Comment by vstumpf** [comment] 2022-11-26 21:53
duplicate of #7417

**Closed by vstumpf** 2022-11-26 21:53 UTC
Labels: type:bug
