### ISSUE TITLE
Warnings compiling on gcc 7.2.0

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#2787] opened 2018-01-08 01:25 UTC
* **rAthena Hash**: a65e7dbf4697b64f835965d1e96b9502d1b7369e

* **Client Date**: not relevant

* **Server Mode**: both

* **Description of Issue**: 
  * Result: It seems GCC 7.2.0 became more strict:
```
int_mail.cpp: In function ‘void mapif_Mail_return(int, uint32, int)’:
int_mail.cpp:475:6: warning: ‘%s’ directive output may be truncated writing up to 39 bytes into a region of size 37 [-Wformat-truncation=]
 void mapif_Mail_return(int fd, uint32 char_id, int mail_id)
      ^~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../common/../../3rdparty/libconfig/libconfig.h:48,
                 from ../common/showmsg.h:11,
                 from int_mail.cpp:10:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 43 bytes into a destination of size 40
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
```
```
mob.cpp: In function ‘int mobskill_use(mob_data*, unsigned int, int)’:
mob.cpp:3551:5: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 253 [-Wformat-truncation=]
 int mobskill_use(struct mob_data *md, unsigned int tick, int event)
     ^~~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6349,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/stdexcept:39,
                 from /usr/include/c++/7/array:39,
                 from /usr/include/c++/7/tuple:39,
                 from /usr/include/c++/7/bits/stl_map.h:63,
                 from /usr/include/c++/7/map:61,
                 from mob.cpp:7:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output 4 or more bytes (assuming 259) into a destination of size 256
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
```
```
npc_chat.cpp: In function ‘int npc_chat_sub(block_list*, __va_list_tag*)’:
npc_chat.cpp:342:5: warning: ‘%i’ directive output may be truncated writing between 1 and 10 bytes into a region of size 3 [-Wformat-truncation=]
 int npc_chat_sub(struct block_list* bl, va_list ap)
     ^~~~~~~~~~~~
npc_chat.cpp:342:5: note: directive argument in the range [0, 2147483647]
In file included from /usr/include/stdio.h:862:0,
                 from ../common/../../3rdparty/libconfig/libconfig.h:48,
                 from ../common/showmsg.h:11,
                 from npc_chat.cpp:12:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 6 and 15 bytes into a destination of size 6
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
```
```
npc.cpp: In function ‘int npc_duplicate4instance(npc_data*, int16)’:
npc.cpp:3254:5: warning: ‘%s’ directive output may be truncated writing up to 50 bytes into a region of size 40 [-Wformat-truncation=]
 int npc_duplicate4instance(struct npc_data *snd, int16 m) {
     ^~~~~~~~~~~~~~~~~~~~~~
npc.cpp:3315:11: note: ‘snprintf’ output between 12 and 62 bytes into a destination of size 50
   snprintf(w2, sizeof(w2), "duplicate(%s)", snd->exname);
   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
npc.cpp:3254:5: warning: ‘::’ directive output may be truncated writing 2 bytes into a region of size between 0 and 50 [-Wformat-truncation=]
 int npc_duplicate4instance(struct npc_data *snd, int16 m) {
     ^~~~~~~~~~~~~~~~~~~~~~
npc.cpp:3316:11: note: ‘snprintf’ output 3 or more bytes (assuming 53) into a destination of size 50
   snprintf(w3, sizeof(w3), "%s::%s", snd->name, newname);
   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
scanner.h:208:17: warning: type of ‘libconfig_yy_scan_string’ does not match original declaration [-Wlto-type-mismatch]
scanner.c:1964:17: note: ‘libconfig_yy_scan_string’ was previously declared here
scanner.c:1964:17: note: code may be misoptimized unless -fno-strict-aliasing is used
scanner.h:202:6: warning: type of ‘libconfig_yy_delete_buffer’ does not match original declaration [-Wlto-type-mismatch]
scanner.c:1743:10: note: ‘libconfig_yy_delete_buffer’ was previously declared here
scanner.c:1743:10: note: code may be misoptimized unless -fno-strict-aliasing is used
```
  * Expected Result: No warnings
  * How to Reproduce: Compiled on Ubuntu 17.10 GCC 7.2.0
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2018-01-08 07:40
The general approach seems to be to disable this warning(format-truncation).
Those usages are intended. I do not really understand why GCC is issuing a warning in these situation, since that is what snprintf is used for...

The scanner things were on older systems already as well. At least I think I remember those.
But I guess we will not bother fixing them anymore, since we are going to remove libconfig sooner or later anyway.

**Comment by Lemongrass3110** [comment] 2018-01-29 23:22
Going to change this to confirmed anyway, since #2852 will list those warnings when it is merged to master.
See https://travis-ci.org/rathena/rathena/jobs/334932920#L836 for confirmation.

**Closed** 2018-09-28 17:57 UTC
Labels: component:core, mode:prerenewal, mode:renewal, priority:low, status:confirmed, type:maintenance
