### ISSUE TITLE
Unknown packets on 2015-10-29

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1049] opened 2016-03-13 01:35 UTC
Hello good evening, the client 2015-10-29 is giving desconect the players randomly, but this only occurs if it is performing some task, whether walking, talking or anything like that, if the same stand there it does not take dc.

**Comment by Darkelfen** [comment] 2016-03-13 04:02
I'm using the same client and we got ""massive"" random disconnections (30 ppl or so at the same time). Nevertheless, I dunno whether it is my hosting provider or my internet connection or a buggy OnTimer from custom script or the client itself.

**Comment by Lemongrass3110** [comment] 2016-03-13 12:00
This could be due to some packet's we do not have yet. That is why this client is not yet marked as stable.
If you can pinpoint when those disconnects happen we can look into it further and try to get a hold of the newer packet(s) or the structure changes of old ones we do not have yet.

**Comment by Darkelfen** [comment] 2016-03-13 22:27
As soon as I can isolate any factor, I will post it here.

**Comment by Lemongrass3110** [comment] 2016-03-13 23:03
@RagnarokNova any input from your server on this?

**Comment by admkakaroto** [comment] 2016-03-14 02:29
Console: http://i.imgur.com/qzoVTTg.png

**Comment by Lemongrass3110** [comment] 2016-03-14 07:24
@admkakaroto could you monitor this and ask your users what they do, before they get kicked by the server? But I think we are on the right track already.

**Comment by admkakaroto** [comment] 2016-03-14 14:50
@Lemongrass3110, I was talking to them, and no one knows for sure, the problem occurs in very different situations, one thing is quite certain, if the player is idle without performing any action, he has no problem with that.

**Comment by Lemongrass3110** [comment] 2016-03-14 15:03
Could you uncomment this line, so that we at least get to know which data is sent:
https://github.com/rathena/rathena/blob/master/src/map/clif.c#L58
Through this you should get the data which is sent from the client to the server on your console. :-)

**Comment by Darkelfen** [comment] 2016-03-15 03:19
Also packet 0x037b is causing disconnections.
I'm trying to pinpoint it cause.

![asdasd](https://cloud.githubusercontent.com/assets/7315177/13766649/2e630c92-ea3a-11e5-8927-69c802799906.png)

**Comment by Lemongrass3110** [comment] 2016-03-16 14:05
Which clients do both of you use?
The Ragexe or the RagexeRE?
If you use the Ragexe: Have you customized your packet keys?

**Comment by Darkelfen** [comment] 2016-03-16 16:21
I'm using: 
"2015-10-29aRagexeRE"

I will copy the packet_db for ver 54 I'm using.

```
//2015-10-29Ragexe
packet_ver: 54
packet_keys: ..., ..., ... //I don't want any of my players reading this get intel on those.
0x0369,7,actionrequest,2:6
0x083C,10,useskilltoid,2:4:6
0x0437,5,walktoxy,2
0x035F,6,ticksend,2
0x0202,5,changedir,2:4
0x07E4,6,takeitem,2
0x0362,6,dropitem,2:4
0x07EC,8,movetokafra,2:4
0x0364,8,movefromkafra,2:4
0x0438,10,useskilltopos,2:4:6:8
0x0366,90,useskilltoposinfo,2:4:6:8:10
0x096A,6,getcharnamerequest,2
0x0368,6,solvecharname,2
0x0838,12,searchstoreinfolistitemclick,2:6:10
0x0835,2,searchstoreinfonextpage,0
0x0819,-1,searchstoreinfo,2:4:5:9:13:14:15
0x0811,-1,reqtradebuyingstore,2:4:8:12
0x0360,6,reqclickbuyingstore,2
0x0817,2,reqclosebuyingstore,0
0x0815,-1,reqopenbuyingstore,2:4:8:9:89
0x0365,18,bookingregreq,2:4:6
// 0x094F,8 CZ_JOIN_BATTLE_FIELD
0x0281,-1, itemlistwindowselected,2:4:8:12
0x022D,19,wanttoconnection,2:6:10:14:18
0x0802,26,partyinvite2,2
// 0x0938,4 CZ_GANGSI_RANK
0x023B,26,friendslistadd,2
0x0361,5,hommenu,2:4
0x0860,36,storagepassword,2:4:20
```

**Comment by admkakaroto** [comment] 2016-03-16 18:39
I use the standard package emulator, to the client 2015-10-29.

Client 2015-10-29aRagexeRE or 2015-10-29aRagexe both with the same problem.

**Comment by Darkelfen** [comment] 2016-03-16 19:21
@admkakaroto Have you received reports about disconnections while chatting, storing or selling using drag and drop method?

**Comment by admkakaroto** [comment] 2016-03-16 23:20
@Darkelfen, yes, players have long claimed were talking and being disconnected, or are performing some instance or simply dropping items.

**Comment by Darkelfen** [comment] 2016-03-17 01:05
I will update the information on the packets which caused disconnections. 

So far we have been monitoring the server for nearly 18 hours by now, and we got a myriad of disconnections.

**Comment by secretdataz** [comment] 2016-03-18 07:53
Spamming `@go` doesn't disconnect me on 718e478 with 2015-10-29aRagexe.

**Comment by admkakaroto** [comment] 2016-03-18 12:05
I have no problems with @go spamming, my biggest problem is even with instances, or when several players together and talking ... or even interacting, as in pvp, but especially in instances, so far no time was because of commands.

**Comment by Darkelfen** [comment] 2016-03-18 14:23
I've monitoring for nearly 48 hours by now, and I couldn't get a hold on 0x036b.

Regarding the atcommand go, it was only caused in my PC w/win8; I've tried on a PC w/win-xp and I was unable to reproduce it. So maybe it is a problem related with win8 rather than the client itself.

Regarding 1:1 whispers, I couldn't reproduce them, but I was disconnected while chatting and doing nothing else, so 1:1 whispers are triggering the disconnections but I couldn't isolate why or how yet.

**Comment by admkakaroto** [comment] 2016-03-21 16:37
@Darkelfen, @Lemongrass3110, @secretdataz,  any solution?

**Comment by Darkelfen** [comment] 2016-03-21 18:59
I've monitored for nearly a week the unsupported/unknown packets errors in the console. As it's so time demanding, I've decided to stop monitoring. 

I got a massive amount of data which I'm unable to analyse nor isolate any factor causing the disconnections.

In my post above I've updated the packets I was able to identify but 0x036b never appeared.

**Comment by reunite-ro** [comment] 2016-03-22 19:24
having dc issue also using ragexe not ragexeRE

**Comment by secretdataz** [comment] 2016-03-23 12:03
[Warning]: clif_parse: Received unsupported packet (packet 0x5597, 42 bytes received), disconnecting session #11.

**Comment by secretdataz** [comment] 2016-03-27 04:08
(03/27/2016 10:27:57) [ Warning ] : clif_parse: Received unsupported packet (packet 0x41de, 105 bytes received), disconnecting session #18.
    (03/27/2016 10:41:19) [ Warning ] : clif_parse: Received unsupported packet (packet 0x6b90, 72 bytes received), disconnecting session #18.
    (03/27/2016 10:43:00) [ Warning ] : clif_parse: Received unsupported packet (packet 0x6022, 275 bytes received), disconnecting session #18.
    (03/27/2016 10:44:47) [ Warning ] : clif_parse: Received unsupported packet (packet 0x6b90, 117 bytes received), disconnecting session #18.
    (03/27/2016 10:49:45) [ Warning ] : clif_parse: Received unsupported packet (packet 0x39b9, 990 bytes received), disconnecting session #17.
    (03/27/2016 10:51:28) [ Warning ] : clif_parse: Received unsupported packet (packet 0x6b90, 9 bytes received), disconnecting session #17.

**Comment by admkakaroto** [comment] 2016-03-28 01:31
[Warning]: clif_parse: Received unsupported packet (packet 0x04a1, 5 bytes received), disconnecting session #34.

**Comment by Lemongrass3110** [comment] 2016-03-29 07:08
Please try to add those two commits to your server:
https://github.com/rathena/rathena/commits/test/issue1049
Travis says that they compile just fine(I just did them online on github without testing them locally) so please just tell me if something does not work as intended.

What do these changes do?
First of all it differentiates between already authenticated players or "players" that try to login with an unknown packet(these can also be portscanners or other similar programs).
The second one gives us the possibility to debug what happens in the packet obfuscation. It stores the value of the sessions crypt key and packet value before the decryption happens and shows them in a debug message when it is an unknown packet after the decryption progress.

**Comment by admkakaroto** [comment] 2016-03-30 16:58
I compiled yet received these errors on the console:
http://i.imgur.com/rdAnNU5.png

I'll try to do some tests.

**Comment by secretdataz** [comment] 2016-03-30 17:10
@admkakaroto Merge the updated test/issue1049 branch. It should compile now.

**Comment by reunite-ro** [comment] 2016-03-31 13:03
This is the list of packet that occur for about 3-4 days in server. Can you check this out?
`packet 0x099e
packet 0x0372
packet 0x03f9
packet 0x037b
packet 0x039a
packet 0x039e
packet 0x0393
packet 0x0059
packet 0x03a6
packet 0x037a
packet 0x03d1
packet 0x03c7
packet 0x984e
packet 0x0385
packet 0x03a3
packet 0x03d9
packet 0x03eb
packet 0x04fd
packet 0xbb58
packet 0x5cf7
packet 0x0379
packet 0x03f0
packet 0x0029 // when agit2 start
packet 0x03f2 // when agit2 start
packet 0x03bc // when agit2 start
packet 0x7a0a // when agit2 start
packet 0x03c7 // when agit2 start
packet 0x03b5
packet 0x036b
packet 0x03b4
packet 0x043b
packet 0x0373
packet 0x03d9
packet 0x32ba // maybe related to Hunting Mission NPC
packet 0x70c4 // maybe related to Hunting Mission NPC
packet 0x03ce
packet 0xbecd //maybe because of instance endless tower created
packet 0x050b
packet 0x3877
packet 0x038f
packet 0x09a3
packet 0x3056
packet 0x09c6
packet 0xafd5
packet 0x0021
packet 0x0376
packet 0x0394 // maybe because of incorrect use of 'close' commands
packet 0x03b5
packet 0x03de
packet 0x0374
packet 0xb44a
packet 0x03a3
packet 0x091b
packet 0x9a7e
packet 0x2418
packet 0x04dc
packet 0x4ff7
packet 0x6aa2
packet 0x03da
packet 0x03f2
packet 0x0bf2
packet 0x036e
packet 0x03d0
packet 0x0986
packet 0x002f
packet 0x0392 //maybe Hunting Mission NPC
packet 0x1b4e //maybe Hunting Mission NPC
packet 0x03b6 //maybe Hunting Mission NPC
packet 0x5c62 //maybe Hunting Mission NPC
packet 0x03bb // when character server lost
packet 0x03c2
packet 0x03bd
packet 0x0043
packet 0x03c3
packet 0x690a
packet 0x049c
`

**Comment by Badarosk0** [comment] 2016-04-06 22:43
When using flood of characters in chat generates the warning below:

[Warning]: clif_parse: Received unsupported packet (packet 0x8480, 55 bytes received), disconnecting session #8.

Example:
d
d
f
rwetg
rw
wf
wf
w
w
...

**Comment by Darkelfen** [comment] 2016-04-07 01:02
I've started to monitor with the test commits added:
```
//Disconnections While Chatting (Guild Chat):
[Warning]: clif_parse: Received unsupported packet (packet 0x03a3, 6 bytes received) from character <char name>(AID: 2000001, CID: 8), disconnecting session #8.
[Warning]: clif_parse: Received unsupported packet (packet 0x0393, 6 bytes received) from character <char name>(AID: 2000001, CID: 8), disconnecting session #22.

//Unknown Reason:
[Warning]: clif_parse: Received unsupported packet (packet 0x5d8e, 13 bytes received) from character <char name>(AID: 2000886, CID: 3254), disconnecting session #22.
```

@Badarosk0 I've tried to flood my chat and I couldn't replicate. As far as I know, chatting does cause disconnections.

**Comment by aleos89** [comment] 2016-04-08 17:28
We added support for 2015-11-04 in 5e58149. You can grab the client from the [2015 Client Support topic](https://rathena.org/board/topic/104205-2015-client-support/). This will end up being an issue we can't resolve because it's specifically related to the October clients.

**Comment by hendra814** [comment] 2016-04-14 05:35
2015-10-29 have this error

**Comment by Darkelfen** [comment] 2016-04-14 06:17
Move to 2015-11-04, this issue can't be helped.

**Comment by admkakaroto** [comment] 2016-04-17 12:52
With the new client players do not take more random dc, but when they talk very fast in general chat or be interacting with various NPC's by clicking one after the other they still take dc, see:

`[Warning]: clif_parse: Received unsupported packet (packet 0x2d2e, 24 bytes received), disconnecting session # 9.`

**Comment by Playtester** [comment] 2016-04-17 13:41
Almost sounds like some integrated spam protection.

**Comment by Darkelfen** [comment] 2016-04-17 17:03
I've also get a few disconnections with 2015-11-04 but considerably less than before.
````
clif_parse: Received unsupported packet
packet 0x0395, 5 bytes received
packet 0x05ce, 46 bytes received
packet 0x0845, 6 bytes received
packet 0x08b8, 12 bytes received
packet 0x08df, 6 bytes received
packet 0x1d28, 3 bytes received
packet 0x5d6f, 2 bytes received
packet 0x62a2, 11 bytes received
packet 0x78b1, 40 bytes received
````

**Closed** 2016-04-17 20:31 UTC
Labels: bug:core, mode:prerenewal, mode:renewal, server:map, status:needs more info

**Comment by M45T3Ryu** [comment] 2016-05-14 23:42
we should re-open this because the commit was reversed

**Comment by admkakaroto** [comment] 2016-05-15 00:14
really

**Comment by aleos89** [comment] 2016-05-15 00:23
There's no need. #1223 is open and is related to this.

**Comment by M45T3Ryu** [comment] 2016-05-15 00:42
@aleos89 but there is no "bug" there the problem is here, here you have all the list of errors and btw that bug #1223 doesnt happen to me. And I tried all the 2015 10+ clients

**Comment by aleos89** [comment] 2016-05-15 21:02
The issues are related. Both are at fault with the messaging system, now that we know what is causing the random crashes. Not just normal chat is at fault though which is why there are those random crashes though `@commands`, log system, and other things that send messages to the client.

The packets above listed in this issue are just fine and serve no purpose into resolving this issue. It has been worked on and just needs testing now. It will be pushed to master soon!
