### ISSUE TITLE
Skill Auto Guard when proc by Clock Guard should NOT be removed when unequip armor

### ISSUE THREAD

**Issue by Tydus1** [rathena/rathena#5909] opened 2021-04-29 00:54 UTC
* **rAthena Hash**:  Latest

* **Client Date**: 20200401

* **Server Mode**: Pre-Renewal (not sure if Renewal had its behavior as well so...)

* **Description of Issue**: 
  * Result: Skill Auto Guard when proc by Clock Card gets removed when unequipping armor;
  * Expected Result: The buff should NOT be removed when armor is removed;
  * How to Reproduce: Create a character and equip any armor with clock card. I recommend creating a knight, summoning 5~10 porings and provoke them. It will proc Auto Guard pretty fast. When the skill pops up, just unequip the armor and the buff will be removed as well;
  * Official Information: The profs provided here were obtained from a discursion on OriginRO discord (Thanks to Xellie). The information come from a supposedly test on Aegis. (Would be nice if anyone with Aegis access could confirm).
  * Note: Seems like this behavior occurs to toggle skills but other skills were not mentioned. Skills like sight when used by equiping a item with Horong Card should have its effect removed when unequipping the equipment, since its not a toggle (on/off) skill.
  

* **Modifications that may affect results**: None

**Comment by mrjnumber1** [comment] 2021-04-29 01:18
https://github.com/rathena/rathena/pull/5817

**Comment by aleos89** [comment] 2021-04-29 18:16
Duplicate of #5766.

**Closed by aleos89** 2021-04-29 18:16 UTC
Labels: status:duplicate
