### ISSUE TITLE
Bug in buying

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#818] opened 2015-12-06 13:28 UTC
Hello good day, after the commit https://github.com/rathena/rathena/commit/0212d44bb4cac01a4fb1dc8e7e21443eadee13f3

the NPC's shop are selling the items for free, without checking the requirements, to reproduce the problem do the following.

Take this npc: https://eathena.ws/forum/topic/40-euphys-quest-shop/

place one or more items to be caught, and ready, talk to the NPC and choose buy item and you will receive without having to give any of the required items.

**Comment by Dark8008** [comment] 2015-12-07 02:19
I hate the same problem, pre-renewal, huhu, my server got down have to roll back :((((

**Comment by aleos89** [comment] 2015-12-07 16:30
Sorry, I was not able to reproduce this. I tried buying things from normal shops and Euphy's Quest Shop.

Everything worked as it should have.

**Comment by admkakaroto** [comment] 2015-12-07 16:43
Really? Please see the video:

https://www.youtube.com/watch?v=dGnvdf3ZEjk&feature=youtu.be

**Comment by Dark8008** [comment] 2015-12-07 16:51
This is really bug, i have the same problem like him !

**Comment by aleos89** [comment] 2015-12-07 19:13
I did the exact same thing. I made sure I had the quest items and even when I didn't have the quest items I was unable to get the item for free.

**Comment by Dark8008** [comment] 2015-12-08 06:50
You should try this script -> http://pastebin.com/raw.php?i=YftccqDs

**Comment by Dark8008** [comment] 2015-12-11 04:06
Any solution ??

**Comment by admkakaroto** [comment] 2015-12-11 17:48
Yes: https://github.com/rathena/rathena/commit/0c9bd301d84c0a596710333c50739d2d5b576f6d

**Comment by Dark8008** [comment] 2015-12-12 00:53
@aleos89 , sir, please update for git too !

**Comment by CairoLee** [comment] 2015-12-12 01:34
@admkakaroto @Dark8008

Sorry, that is not an Perfect solution, it is only effective for the clientversion is greater than or equal to 20131223.

**Comment by CairoLee** [comment] 2015-12-12 08:33
https://github.com/rathena/rathena/pull/832
@admkakaroto @Dark8008 Please check this.

**Comment by admkakaroto** [comment] 2015-12-16 23:17
@CairoLee I use client 20150513 and worked perfectly.

**Comment by CairoLee** [comment] 2015-12-17 04:27
Thank you @admkakaroto XD

**Comment by aleos89** [comment] 2016-01-15 14:52
Fixed in 01ba54c. Thanks everyone!

**Closed by aleos89** 2016-01-15 14:52 UTC
