### ISSUE TITLE
Memory leaks pc.cpp

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#4393] opened 2019-10-04 15:47 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/df6385fd4a3846417c4a96b02c9f17087ee18338
* **Server Mode**: RE
* **Description of Issue**: Memory leak found after trying to turn off the emulator.
  * How to Reproduce: Unfortunately I do not know how to play, just turned on the emulator, tested some skills, when I went off, appeared in map_server.

I will try to reproduce this today.

```
Memory manager: Memory leaks found at 2019/10/03 23h18m04s (Unknown version).
0001 : pc.cpp line 2562 size 31 address 0x0x7f389cd0de4c
0002 : pc.cpp line 2562 size 31 address 0x0x7f389cd112cc
0003 : pc.cpp line 2563 size 49 address 0x0x7f3897c48bac
0004 : pc.cpp line 2563 size 49 address 0x0x7f3897c4950c
```

Line 2562: https://github.com/rathena/rathena/blob/master/src/map/pc.cpp#L2562
Line 2563: https://github.com/rathena/rathena/blob/master/src/map/pc.cpp#L2563

**Comment by Lemongrass3110** [comment] 2019-10-04 15:55
Duplicate of #4334

**Closed by Lemongrass3110** 2019-10-04 15:55 UTC
