### ISSUE TITLE
Bard Skill

### ISSUE THREAD

**Issue by Aristeus09** [rathena/rathena#7259] opened 2022-09-11 13:31 UTC
rAthena Hash :  15a5bcb2cf6ef30d9322d04ee7c30d96c5eca7a3

Client Date: 2017-11-17

Server Mode: Pre-Renewal

Description of Issue:
  * Result: When 2 clown cast poem of bragi in same area and cause a dissonance it will spam a error.  i do not have custom skills or modification in skills.
  * How to Reproduce:  Create 2 Clown in a different account then cast poem of bragi in same area. then after casting bragi with same area try to walk both of your character it will spam a error in terminal.

![Untitled](https://user-images.githubusercontent.com/34960872/189529946-39e1be24-51ed-491e-814b-0fb62d3ecb3f.png)
![screenLumiere003](https://user-images.githubusercontent.com/34960872/189530772-b0a796a4-80e6-4c44-b7b4-f2f7ca68e9b9.jpg)
![screenLumiere004](https://user-images.githubusercontent.com/34960872/189530774-45b69914-e425-4099-9413-dcb4dca3098e.jpg)

**Comment by Daegaladh** [comment] 2022-09-11 16:41
Duplicate of #1341

**Closed by Daegaladh** 2022-09-11 16:41 UTC
Labels: type:bug
