### ISSUE TITLE
Missing some NPC skills.

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8372] opened 2024-05-27 00:47 UTC
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

Most of this list of skills are used in Illusion MOBs, and another in event MVPs.

NPC_EARTHQUAKE_K - https://www.divine-pride.net/database/skill/750
NPC_ACIDBREATH2 - https://www.divine-pride.net/database/skill/766
NPC_EVILLAND2 - https://www.divine-pride.net/database/skill/767
NPC_ASSASSINCROSS - https://www.divine-pride.net/database/skill/2539
NPC_UGLYDANCE - https://www.divine-pride.net/database/skill/2541

**Comment by Lemongrass3110** [comment] 2024-05-28 22:43
Please comment the missing ones (some are already included) in #1525

**Comment by Lemongrass3110** [comment] 2024-05-28 22:43
Duplicate of #1525

**Closed by Lemongrass3110** 2024-05-28 22:43 UTC
Labels: type:enhancement
