### ISSUE TITLE
[BUG] ATK keep increasing

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#3730] opened 2018-12-06 06:00 UTC
* **rAthena Hash**: 08a45f5e8

* **Client Date**: 2018-06-21

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Attack become larger and larger
  * Expected Result: Normal
  * How to Reproduce: Equip any weapon, then start attacking,ATK will increase by it self while attacking. Changing weapon multiple times will increase the ATK too.
  * Official Information: -

* **Modifications that may affect results**: -

![atk_error](https://user-images.githubusercontent.com/31171415/49564498-5d24da00-f956-11e8-980b-1489d7902f9d.png)

**Comment by Lemongrass3110** [comment] 2018-12-06 06:10
Duplicate of #3725

**Closed by Lemongrass3110** 2018-12-06 06:10 UTC
