### ISSUE TITLE
BOSS Monster Behavior

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1697] opened 2016-11-07 16:24 UTC
Git Hash: cbc365d0f2f02ebceece4b6de7d58c8fe487f88f
Mode: Pre-Renewal
Core Bug (?)
Issue:
According to the [https://github.com/rathena/rathena/commit/78d9e2a245f245ce800f37b6f2ebfda1c5ef84b7](Slave aggro (fixes #1676)) all BOSS monster after being traped or stacked change their AI to unknown stance, not even to MSS_IDLE where they should still using skills, like heal, teleport and other. They should keep their AI of "chase" or "angry", but due to unreachable target ( for example, high ASPD sniper, or traps + Ice Walls ) they becomes stupied monsters.

Asking for check this, please. Thank you!

**Comment by Playtester** [comment] 2016-11-07 19:01
My change only affects the slave targets and has no effect on the boss monster AI, so I'd be surprised if that broke boss behavior, but I'll check.

**Comment by Playtester** [comment] 2016-11-07 19:11
Nope can't confirm this at all. The moment I trap a boss monster it will start spaming its idle skills.

Can you tell me which boss you mean in particular and what you expect him to use?

**Comment by mgksrt8** [comment] 2016-11-07 19:30
Your fix for summons works, but a little bit different: summons continue attack until you in the trapped monster view range. I opened this issue, because range attacks makes monsters stupid. The same with boss monsters:
Thanatos, Gloom, Ifrit, Atroce and other not "easy" bosses like Edgga.

When you trap boss monster and you are a range attacker ( Hunter, Sniper ), monsters loosing their target and don't use skills properly. Melee attacks works fine ( but some doubts have place ).

It's looks like view side range of monsters. I creating this issues, because ( my Lord... ) my medium server is a hole of all Russian bug users and cheaters, but I also have a good players from official raggame and one Game Master from it.

I understand, that it totally different, but... Check please this Boss monsters, with pre-renewal Sniper. Put them into traps and choose the largest distance and try with any range skills ( for example: Double Strife, that have 20+ range in rA... ), and you will see, that boss do nothing. Thank you!

**Comment by Playtester** [comment] 2016-11-07 20:04
Yeah, but this is official behavior. If you trap a boss it will turn idle and only use idle skills and it also can't use skills exceeding its own range. A few boss monsters have counters against this by having idle ranged attack skills. Like Seyren has Spear Boomerang. He spams it once trapped.

**Comment by mgksrt8** [comment] 2016-11-07 20:23
I mean, that they don't use IDLE skills at all. Looks like they shocked that some range attackers can hit them. In IDLE without any attack ( for example change AI of monsters and BOSS in battle config from 0 to 5 minutes - they will use skills if there are no players on the map ). But after being attacked and moved from chase / angry to IDLE they forget their skills at all.

**Comment by Playtester** [comment] 2016-11-07 21:36
Definitely can't confirm this one. Knight of the Abyss for example summons his slaves when I trap him. Amon Ra (which behaves like a permanently trapped mob) summons his minions when I attack him from range.

**Comment by cydh** [comment] 2016-11-08 00:53
> with any range skills ( for example: Double Strife, that have 20+ range in rA... ), and you will see, that boss do nothing.

I believe, if bosses has teleport skill when attacked from out-of-range, bosses will teleport.

**Comment by mgksrt8** [comment] 2016-11-08 01:00
> I believe, if bosses has teleport skill when attacked from out-of-range, bosses will teleport. maybe this one that need to be checked first
I believed until I checked it myself like other 500+ different people. Rude attack - yes, but not ranged.

**Comment by Playtester** [comment] 2016-11-08 09:34
Ankle Snare prevents teleport so bosses won't rude attack teleport as long as they are trapped by it. They'd use ALLHEAL as rudeattack skill though. 

You can't really be 20 cells away and attack a monster as the visible area is only 14 cells in each direction.

**Comment by mgksrt8** [comment] 2016-11-08 20:34
Not all bosses has heal with rude attack, only teleport.

**Comment by Playtester** [comment] 2016-11-09 09:29
That's right and continuously trapping them to prevent them from escaping is an official tactic. On official servers you can even just cast icewall on a boss to make its AI break, but that's disabled on rAthena (there's a config for it in monster.conf).

**Comment by mgksrt8** [comment] 2016-11-09 14:45
And what about iRO, where icewall totally disabled? Btw, you right, but partially, because Boss monster somehow and sometime don't use their MSS_IDLE stance at all, making them studied. All monsters, especially Boss should use their skill on the map even if there are no players on the map or in the range view. It's consume more resources, but... stop host RO on 5$ hosting...

**Comment by anacondaqq** [comment] 2016-11-09 15:14
@mgksrt8 looks like you don't even know about what are you talking about. I was young and stupid like you, and i remember all issues about which are you talking here. But everything works correctly here, i can't say about 100% mechanic, but i can say that current mechanic looks like official one and tested on aegis and official servers, and confirmed several times in different periods of time. 

### About skill usage on map when there are no players.
When i have said about "you have no clue about current issue", i mean this thing. At rA by default you have enabled dynamic_mobs on, this unload mobs from the memory if nobody comes in 300 seconds to the map (or something like that, do not remember values or 100% true description about this mechanic behavior), but if you will turn it off, all of your mobs will walk at map ALWAYS and always will do what you said above (even if nobody will be at the map, they will use skills). 

But let me explain other issues related to turning OFF dynamic mobs at rAthena:
* all of your players will cry a lot, really a lot about situation which will be happened.
* all mobs with transformation will be transformed, and all classic mobs on maps will be unable to find by players, and in result all of your players will make bugreports that they can't finding a mob at specific map, but to be clear, this mob already at map, but it will be transformed.
* You will receive million of bugreports from players which will cry a lot about very fast selfhealing MVP's

This is just few issues which i can remember for now. So as you see it's works like you said, but you should to turn off dynamic mobs first.

**Comment by mgksrt8** [comment] 2016-11-09 15:26
@anacondaqq 
First of all, thank you for your reply.
Second: yes, I'm not a programmer or uber tester, I just telling you and other dev. members about issues, that confirmed by most of players and game masters from closed official russian ragnarok online server.
Third: this is my hobby after U.S. Army, and when you writing
> I was young and stupid like you
to the Sergant, who was in the combat... never write it again, because at least you wrong, in total - you looks like the sentence that you addressed to me.
Forth: thank you, I will try to turn off dynamic mobs.

**Comment by Playtester** [comment] 2016-11-14 09:13
As I can't find anything wrong with the behavior, I'm closing this now. If you think a specific behavior is different from official servers, feel free to post the exact steps to reproduce the behavior difference.

Yes, it's true iRO blocked casting icewall on maps with MVPs, feel free to do so too, the corresponding mapflag should already exist, you just need to add the corresponding maps to it. By default rAthena follows kRO however.

**Closed by Playtester** 2016-11-14 09:13 UTC
