### ISSUE TITLE
Items errors with the latest rAthena: dbe5ba748

### ISSUE THREAD

**Issue by amaurymn** [rathena/rathena#5320] opened 2020-08-12 17:15 UTC
* **rAthena Hash**: [dbe5ba748](https://github.com/rathena/rathena/commit/dbe5ba748)
* **Client Date**: 2020-04-01bRagexe
* **Server Mode**: Renewal
* **Database Mode**: SQL

* **Description of Issue**: 
After fresh download and launch of the last rAthena server, i got some errors due to missing items in database or wrong names in these different files:

- db/re/produce_db.txt
- db/re/spellbook_db.yml
- db/re/quest_db.yml

Here the errors:
```
[Error]: skill_parse_row_producedb: Invalid item 100231.
[Error]: sv_readdb: Could not process contents of line 659 of "db/re/produce_db.txt".
[Error]: skill_parse_row_producedb: Invalid item 100232.
[Error]: sv_readdb: Could not process contents of line 661 of "db/re/produce_db.txt".
[Error]: skill_parse_row_producedb: Invalid item 100233.
[Error]: sv_readdb: Could not process contents of line 663 of "db/re/produce_db.txt".
[Error]: skill_parse_row_producedb: Invalid item 1100003.
[Error]: sv_readdb: Could not process contents of line 665 of "db/re/produce_db.txt".
[Error]: skill_parse_row_producedb: Invalid item 1100004.
[Error]: sv_readdb: Could not process contents of line 667 of "db/re/produce_db.txt".
[Error]: skill_parse_row_producedb: Invalid item 1100005.
[Error]: sv_readdb: Could not process contents of line 669 of "db/re/produce_db.txt".
```
```
[Error]: Book item WL_MB_MS does not exist.
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 36 and column 10.
WL_MB_MS
[Error]: Book item WL_MB_LOV does not exist./spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 39 and column 10.
WL_MB_LOV
[Error]: Book item WL_MB_SG does not exist.e/spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 42 and column 10.
WL_MB_SG
[Error]: Book item WL_MB_JF does not exist.e/spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 45 and column 10.
WL_MB_JF
[Error]: Book item WL_MB_DL does not exist.e/spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 48 and column 10.
WL_MB_DL
[Error]: Book item WL_MB_CR does not exist.e/spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 51 and column 10.
WL_MB_CR
[Error]: Book item WL_MB_CM does not exist.e/spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 54 and column 10.
WL_MB_CM
[Error]: Book item WL_MB_CL does not exist.e/spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 57 and column 10.
WL_MB_CL
[Error]: Book item WL_MB_ES does not exist.e/spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 60 and column 10.
WL_MB_ES
[Error]: Book item WL_MB_TV does not exist.e/spellbook_db.yml'
[Error]: Occurred in file 'db/re/spellbook_db.yml' on line 63 and column 10.
WL_MB_TV
```
```
[Error]: Item Power_Control_Device does not exist, skipping.ml'
[Error]: Occurred in file 'db/re/quest_db.yml' on line 4089 and column 14.
Power_Control_Device
[Error]: Item Power_Control_Device does not exist, skipping.
[Error]: Occurred in file 'db/re/quest_db.yml' on line 4092 and column 14.
Power_Control_Device
[Error]: Item Power_Control_Device does not exist, skipping.
[Error]: Occurred in file 'db/re/quest_db.yml' on line 4095 and column 14.
Power_Control_Device
```

  * How to Reproduce:
Clone latest rAthena, compile, import `main, logs, item_cash_db, item_cash_db2, item_db_re, item_db2_re, mob_db_re, mob_db2_re,  mob_skill_db_re, mob_skill_db2_re, roulette_default_data.`

**Comment by echomokona** [comment] 2020-08-12 17:37
Same error observed without usage of SQL itemdb as well.
Steps to reproduce: Clone latest rA, compile, run.
Quest DB is calling for Power Control Device, while itemdb still calls it Operation Control Device.

**Comment by Lemongrass3110** [comment] 2020-08-12 21:49
Duplicate of #5311

**Closed by Lemongrass3110** 2020-08-12 21:49 UTC
