### ISSUE TITLE
ITEMLINK BUG!

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1873] opened 2017-01-12 22:23 UTC
ITEMLINK BUG!
In the game which directly enter the props link code, will lead to the client crash!
E.g
＜ITEM＞0000y1f+%g7'1a0'1a0＜／ITEM＞
http://i.imgur.com/7wdbvQd.png

Can modify the source code, prohibit the importation of ＜ITEM＞ at the beginning of the characters?
Client version 20151104

**Comment by aleos89** [comment] 2017-01-12 22:38
Duplicate of #1236.

**Closed by aleos89** 2017-01-12 22:38 UTC

**Comment by LingLingYang** [comment] 2017-01-13 01:08
@aleos89  It's not the same ,I think he was trying to say that strange code will  crashed other players clients include himself.

**Comment by aleos89** [comment] 2017-01-13 01:32
Even then, there's nothing rAthena can do. This is solely a client feature that doesn't interact with rAthena at all.

I think it has been reported on the forum multiple times as well as being broken. It was something Gravity did that broke the feature.

**Comment by whupdo** [comment] 2017-01-13 06:36
@aleos89 can not modify the source code by the way, if the importation of strange code will not be able to send normal ITEMLINK not affected
I use other versions of rathena For example https://rathena.cn/changelog This is to prevent changes.
http://i.imgur.com/Rg92BV9.jpg
Thank!

**Comment by Akkarinage** [comment] 2017-01-13 12:31
Aleos has already stated this is a client issue. The itemlink code is handled by the client, not rAthena.
Using other "versions" of rAthena to prevent changes is quite ridiculous.

**Comment by aleos89** [comment] 2017-01-13 15:28
The only solution I can think of without changing clients is you will have to parse the message in `clif_process_message`. If it contains `<ITEM%` then just return back false to prevent the message from being sent. This isn't really a practical solution as it will put strain on the server since you will have to parse every message a player sends.

**Comment by PsyOps23** [comment] 2020-10-26 17:59
> The only solution I can think of without changing clients is you will have to parse the message in `clif_process_message`. If it contains `<ITEM%` then just return back false to prevent the message from being sent. This isn't really a practical solution as it will put strain on the server since you will have to parse every message a player sends.

also having this trouble atm. How do i go about on parsing the message in 'clif_process_message'?
