### ISSUE TITLE
Program received signal SIGSEGV on mapexit

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7561] opened 2023-01-21 22:35 UTC
### rAthena Hash

b40469f

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

```
[Status]: Terminating...
[Error]: delete_timer error : function mismatch 0x7435e0(connect_check_clear) != 0x585a68(npc_dynamicnpc_removal_timer)
[Error]: delete_timer error : function mismatch 0x7435e0(connect_check_clear) != 0x585a68(npc_dynamicnpc_removal_timer)
[Status]: Cleaned up 1181 maps.
[Error]: delete_timer error : function mismatch 0x7435e0(connect_check_clear) != 0x585a68(npc_dynamicnpc_removal_timer)

Program received signal SIGSEGV, Segmentation fault.
_mfree (ptr=0xfdfdfdfdfdfdfdfd, file=0x7dadc8 "script.cpp", line=2978,
    func=0x808320 <script_free_array_db(DBKey, DBData*, __va_list_tag*)::__FUNCTION__> "script_free_array_db") at malloc.cpp:388
388             if(head->size == 0) {
Missing separate debuginfos, use: debuginfo-install MariaDB-shared-10.2.44-1.el7.centos.x86_64 glibc-2.17-326.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-55.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 openssl-libs-1.0.2k-25.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64
(gdb)
```
bt full
```
#0  _mfree (ptr=0xfdfdfdfdfdfdfdfd, file=0x7dadc8 "script.cpp", line=2978,
    func=0x808320 <script_free_array_db(DBKey, DBData*, __va_list_tag*)::__FUNCTION__> "script_free_array_db") at malloc.cpp:388
        head = 0xfdfdfdfdfdfdfde5
#1  0x00000000005f83d4 in script_free_array_db (key=..., data=data@entry=0x11cf9948,
    ap=ap@entry=0x7fffffffdb08) at script.cpp:2978
        sa = 0x4521030
        __FUNCTION__ = "script_free_array_db"
#2  0x0000000000748728 in db_obj_vclear(DBMap *, DBApply, typedef __va_list_tag __va_list_tag *) (
    self=0x1630d448, func=0x5f83b0 <script_free_array_db(DBKey, DBData*, __va_list_tag*)>,
    args=0x7fffffffdb98) at db.cpp:2137
        argscopy = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdc70,
            reg_save_area = 0x7fffffffdbb0}}
        db = 0x1630d448
        sum = 0
        i = <optimized out>
        node = <optimized out>
        parent = <optimized out>
#3  0x0000000000749051 in db_obj_vdestroy(DBMap *, DBApply, typedef __va_list_tag __va_list_tag *)
    (self=0x1630d448, func=0x5f83b0 <script_free_array_db(DBKey, DBData*, __va_list_tag*)>,
    args=0x7fffffffdb98) at db.cpp:2234
        db = 0x1630d448
        sum = <optimized out>
        args = 0x7fffffffdb98
        func = 0x5f83b0 <script_free_array_db(DBKey, DBData*, __va_list_tag*)>
        self = 0x1630d448
        db = 0x1630d448
#4  0x000000000074753c in db_obj_destroy (self=<optimized out>, func=<optimized out>)
    at db.cpp:2269
        args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdc70,
            reg_save_area = 0x7fffffffdbb0}}
#5  0x00000000004e9b90 in instance_destroy (instance_id=52) at instance.cpp:1029
        idata = std::shared_ptr (count 2, weak 0) 0x12e74480
        sd = 0x7fffffffe116
---Type <return> to continue, or q <return> to quit---
---Type <return> to continue, or q <return> to quit---
        pd = <optimized out>
        gd = <optimized out>
        cd = <optimized out>
        mode = IM_PARTY
        type = IN_DESTROY_USER_REQUEST
#6  0x00000000004ea3f8 in do_final_instance () at instance.cpp:1311
        it = <optimized out>
#7  0x000000000053a182 in rathena::server_map::MapServer::finalize (this=<optimized out>)
    at map.cpp:4868
        iter = <optimized out>
        __FUNCTION__ = "finalize"
#8  0x000000000074333d in rathena::server_core::Core::start (this=this@entry=0x7fffffffdd90,
    argc=1, argv=0x7fffffffde98) at core.cpp:398
No locals.
#9  0x000000000040acfa in main_core<rathena::server_map::MapServer> (argv=<optimized out>,
    argc=<optimized out>) at ../common/core.hpp:102
        server = {<rathena::server_core::Core> = {
            _vptr.Core = 0x7c9010 <vtable for rathena::server_map::MapServer+16>,
            m_status = rathena::server_core::SERVER_FINALIZING,
            m_type = rathena::server_core::MAP, m_run_once = false,
            m_crashed = false}, <No data fields>}
#10 main (argc=<optimized out>, argv=<optimized out>) at map.cpp:5270
No locals.
(gdb)
```

### Expected Result

no Program received signal SIGSEGV

### How to Reproduce

just use command kickall and then mapexit

### Official Information

na

**Comment by Lemongrass3110** [comment] 2023-01-23 17:50
Duplicate of #6642

**Closed by Lemongrass3110** 2023-01-23 17:51 UTC
Labels: status:duplicate
