### ISSUE TITLE
Mail Not Sending Zeny

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6100] opened 2021-07-19 01:55 UTC
* **rAthena Hash**: 4b339f7

* **Client Date**: 20200401

* **Server Mode**: Mail Not Sending Zeny

* **Description of Issue**: 
  * Result:  On the receiver of the mail, the zeny of the mail is 0, but the sender's money disappeared according to what was sent for example 1,000,000
  * Expected Result:  Zeny same on sender and receiver
  * How to Reproduce:  Send zeny using mail to another account character example 1,000,000 zeny
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Gardosen** [comment] 2021-07-19 07:40
tested this with the latest rathena + a 20210107 ragexeRE client. it works as expected.

the receiver receives the money and the money also gets deducted from the senders zeny amount

**Comment by ijped27** [comment] 2021-07-19 08:14
@Gardosen I tested it in latest and it's bugged 20200401

**Comment by RagnaWay** [comment] 2021-07-19 08:27
Working for me! lasted rA in 20210107 ragexeRE client.
![image](https://user-images.githubusercontent.com/53480357/126127783-eadbce7c-38a1-40cc-83fc-c3171ffea1b3.png)
![image](https://user-images.githubusercontent.com/53480357/126127887-a13638c9-0129-468f-b2c9-94f1a857cf4c.png)

![image](https://user-images.githubusercontent.com/53480357/126127994-b2c43bb3-fd59-442b-a001-89374d0ef1f5.png)
![image](https://user-images.githubusercontent.com/53480357/126128041-7fa0a83c-64eb-4a3a-9ddc-ff8af148c16f.png)
![image](https://user-images.githubusercontent.com/53480357/126128114-13ac5d68-eb37-444c-98b2-eb4195771b50.png)

**Comment by Gardosen** [comment] 2021-07-19 09:00
> @Gardosen I tested it in latest and it's bugged 20200401

you are right, apparently the packet which is send from the server to the client, is not well formed for the client.
i traced the logic down to clif_Mail_read in clif.cpp

my first guess without deeper investigation would be that we need a special #if case for this client version

**Comment by Lemongrass3110** [comment] 2021-07-22 23:32
I am unable to reproduce this issue on 2020-04-01bRagexe

**Comment by mazvi** [comment] 2021-07-23 02:50
> I am unable to reproduce this issue on 2020-04-01bRagexe

Did you tes compile using gcc? Because i compile using gcc and centos..

**Comment by Akkarinage** [comment] 2022-08-30 20:32
This issue has been sat on "Unable to Reproduce" for over a year with no further updates, so I'm going to close this issue.

**Closed by Akkarinage** 2022-08-30 20:32 UTC
Labels: status:unable to reproduce
