### ISSUE TITLE
Sage skill cause map crash

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#6228] opened 2021-08-29 10:30 UTC
* **rAthena Hash**:  fe7cb5a

* **Client Date**:  

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  Cast violet gale will be fine on the first cast but after 2nd cast map crash will happen, Same with other skills.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by kaninhot004** [comment] 2021-08-29 12:42
I thought they are already fix the problems, please wait for merge. https://github.com/rathena/rathena/pull/6226

**Comment by Miraakol** [comment] 2021-08-29 13:34
same. i can confirm this.

**Comment by Daegaladh** [comment] 2021-08-29 15:13
Have you tested this on PR #6226?

**Comment by AsurielRO** [comment] 2021-08-29 16:17
Not yet but i will try now thank you.

**Comment by AsurielRO** [comment] 2021-08-29 16:43
Fixed using this commit thank you. #6226

**Comment by Daegaladh** [comment] 2021-08-29 16:54
Duplicate of #6224

**Closed by Daegaladh** 2021-08-29 16:54 UTC
Labels: status:duplicate, type:bug
