### ISSUE TITLE
Crash Map server

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5407] opened 2020-09-20 09:21 UTC
* **rAthena Hash**: https://github.com/rathena/rathena/commit/36c629e84141a54a27dbdab69bd2daaac554b043

* **Client Date**: 2020-04-01

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000047800a in clif_send (buf=buf@entry=0x7fffffffd96a, 
    len=len@entry=6, bl=<optimized out>, type=type@entry=CLAN) at clif.cpp:785
785					if( ( sd = clan->members[i] ) == nullptr || !session_isActive( fd = sd->fd ) ){
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6_10.3.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-24.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64 openssl-1.0.1e-58.el6_10.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) 
(gdb) bt full
#0  0x000000000047800a in clif_send (buf=buf@entry=0x7fffffffd96a, 
    len=len@entry=6, bl=<optimized out>, type=type@entry=CLAN) at clif.cpp:785
        i = 285
        sd = 0xd3840c0
        tsd = <optimized out>
        p = 0x0
        g = 0x0
        bg = 0x0
        x0 = 0
        x1 = 0
        y0 = 0
        y1 = 0
        fd = <optimized out>
        iter = <optimized out>
        __FUNCTION__ = "clif_send"
#1  0x000000000049bac1 in clif_clan_onlinecount (
    clan=clan@entry=0x7fffe029643c) at clif.cpp:19997
        buf = "\210\t\263\001\364\001"
        sd = <optimized out>
#2  0x0000000000472810 in clan_member_joined (sd=sd@entry=0xcd7ccd0)
    at clan.cpp:132
        clan = 0x7fffe029643c
        index = <optimized out>
        sd = 0xcd7ccd0
#3  0x0000000000533470 in pc_reg_received (sd=0xcd7ccd0) at pc.cpp:1796
        i = 0 '\000'
        __FUNCTION__ = "pc_reg_received"
#4  0x00000000004cfdde in intif_parse_Registers (fd=<optimized out>)
    at intif.cpp:1473
        flag = 1
        sd = 0xcd7ccd0
        account_id = <optimized out>
        char_id = <optimized out>
        node = <optimized out>
        type = <optimized out>
#5  0x00000000004d4e35 in intif_parse (fd=fd@entry=7) at intif.cpp:3754
        packet_len = 16
        cmd = <optimized out>
#6  0x000000000047208f in chrif_parse (fd=7) at chrif.cpp:1789
        r = <optimized out>
        cmd = 14340
        packet_len = <optimized out>
#7  0x000000000040d005 in do_sockets (next=<optimized out>) at socket.cpp:1411
        rfd = {fds_bits = {128, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 19990}
        ret = <optimized out>
        i = 7
#8  main (argc=<optimized out>, argv=<optimized out>) at core.cpp:381
No locals.
```
This crash is occurring even after this change:
https://github.com/rathena/rathena/pull/5202/files
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment] 2020-09-20 18:24
Duplicate of #5376

**Closed by Lemongrass3110** 2020-09-20 18:24 UTC
Labels: status:duplicate
