### ISSUE TITLE
OnNPCKillEvent doesn't work on spawned monsters with event label

### ISSUE THREAD

**Issue by technoken** [rathena/rathena#1949] opened 2017-02-07 10:43 UTC
* **rAthena Hash**: 
c7709909738592d6b5cac3f1ef4df70e1cd0a02b

* **Client Date**: 
2013-12-23

* **Server Mode**: 
Pre-renewal

* **Modifications that may affect results**: 
No modification

* **Description of Issue**: 
OnNPCKillEvent doesn't work on spawned monsters with event label
I tried it using this script
```
prontera,153,178,4	script	monstertest	52,{
	monster "prontera",155,178,"--ja--",1002,1,"monstertest::OnKill";
	end;

OnKill:
end;

OnNPCKillEvent:
	dispbottom killedrid;
	end;
}
```
After killing the monster, no dispbottom appears. but if I use this, the OnNPCKillEvent is triggered.
 `monster "prontera",155,178,"--ja--",1002,1;`

Is it really working like this or no?

**Comment by Jeybla** [comment] 2017-02-07 13:24
Afaik this is intentionally behavior.

But I changed it in our fork, too. In mob.c:
```diff
2907c2924,2926
< 		} else if( mvp_sd && !md->state.npc_killmonster ) {
---
> 		}
> 		
> 		if( mvp_sd && !md->state.npc_killmonster ) {

```

**Comment by technoken** [comment] 2017-02-08 05:22
@Jeybla Thanks for that. But I also wanna know why they did that on purpose. perhaps for some reason?

**Comment by Jeybla** [comment] 2017-02-08 13:03
I'm pretty sure this decision has been taken long time ago. The last change on this line is 4 years ago: https://github.com/rathena/rathena/commit/a2bdc47dafb32f6d18ed350d8bbe79b8f679a049

So it's hard to tell why it is adjusted to this behavior since this is a minor difference. Just change it yourself :)

Personally I'd recommend to avoid the use of OnNPCKillEvent due to performance issues.

**Comment by Akkarinage** [comment] 2017-02-08 16:09
Related:
1c9ed48 and b19fbe5

**Comment by aleos89** [comment] 2017-02-08 18:36
From my point of view, if you're going to give a spawned monster a unique label, why would you need the global mob death label then?

**Comment by Jeybla** [comment] 2017-02-09 05:08
It can be easier in some cases.

In example if you have a global mobkillcounter in an OnNPCKillEvent.
Currently monsters with an unique Kill-Label wouldn't increase the mobkillcounter. So you'd need to increase it in every unique Kill-Label.

Beside the fact, that this change is hard work and hard to maintain; it's not a good style to mix the unique code with the global stuff.

**Comment by aleos89** [comment] 2017-02-09 14:40
@Jeybla: Right, there can be times when that will be needed, but can easily be resolved by having a function that increases your global kill counter and just call that function from both labels. This way there's no duplicate code and the labels stay separated.

As for the issue itself. I'm leaning towards keeping how it is because we don't want multiple labels called at once.

**Comment by Jeybla** [comment] 2017-02-09 15:02
```
[jey@localhost npc]$ egrep -r "monster\s.*(::On|,\.@label)" | wc -l
4256
[jey@localhost npc]$ egrep -lr "monster\s.*(::On|,\.@label)" | wc -l
96
```
You'd need to insert this function like 4000 times in like 100 files for rathenas current unique labels.

But I totally understand your concern. Just wanted to clarify this.

**Comment by aleos89** [comment] 2017-02-14 15:10
I'll continue under the notion that this is working as intended. :)

**Closed by aleos89** 2017-02-14 15:10 UTC
