### ISSUE TITLE
HP / SP Homunculos showing wrong values

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5165] opened 2020-07-01 13:42 UTC
* **rAthena Hash**:  https://github.com/rathena/rathena/commit/a3125e6e95bbae25eda416e0435c3c2acf0964c3

* **Client Date**: 2020-04-01

* **Server Mode**: RE

* **Description of Issue**: Homunculus HP / SP bar is showing incorrect values.
  * Result: 
  * Expected Result: It should show the correct HP / SP. The Hp and SP values look correct, only the look is wrong.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

Image:
https://ibb.co/QC2FnMJ

**Comment by Lemongrass3110** [comment] 2020-07-01 13:43
Duplicate of #5078

**Closed by Lemongrass3110** 2020-07-01 13:43 UTC
Labels: status:duplicate
