### ISSUE TITLE
changesex not working

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1197] opened 2016-04-23 11:47 UTC
Latest GIT download and used on live server.

after talking to gender changer npc. The person automatically gets logged out.. but when he comes back in. he is still the same gender and all equipments are sent to kafra storage on the "misc" section.

i used two different scripts to test this and both had same issues.

script#1
```
prontera,150,150,5 script Gender Bender 99,{
 
mes "Good-day,";
mes "I can help you with what most others can't, change your gender.";
mes "Want to do it? You'll feel like a whole new person!";
if(select("Yes:No")&2) close;
next;
mes "Alright, great, now I just need 5 Medusa heads.";
mes "Continue?";
if(select("Yes:No")&2 || countitem(1148)<5) close;
next;
mes "Just one second now.";
next;
mes "*Feel a person sticking a needle into you..";
next;
mes "Starting to wake up again..";
delitem 1148,5;
changesex;
end;
}
```

script #2 

```
-	script	Andy Belo#01::boyle	878,{

//////////////////////////////////////////
//Customize the npc!! //
set @CDname$,"[Andy Belo]"; //Set NPCs name
// Remember to set script header name as well!!//
set @CDzeny,5000; //Set amount of zeny it costs
set @CDsymbol$,"@"; //Set the atcommand(gm command) symbol you use
//////////////////////////////////////////

mes @CDname$;
mes "FABULOUS!!!!!!!";
mes "Hello, how do you do!";
mes "Do you want something diffren..";
next;
mes @CDname$;
mes "I can change your sex";
mes "Do you want it?";
mes "I know you want it";
next;
mes @CDname$;
mes "What do you think?";
mes "That would be great, right?!";
next;
menu "Sure, I want!",CD_sexchange,"of course no!",CD_uhno;

CD_sexchange:
mes @CDname$;
mes "FABULOUS!!!FANTASTIC!!!OUTSTANDING!!!WONDERFUL!!!SUPER!!!";
mes "This operation requires 5000 zeny and 10 jelopy.. hehe!";
mes "And I'll do it now";
next;
menu "Do it doctor!",CD_blastoff,"I am afraid doctor!",CD_uhno;

CD_blastoff:
mes @CDname$;
mes "BLAST OFF!!!";
mes "OK we began operations!";
next;
if(countitem(909)<10 || Zeny < @CDzeny) goto CD_zeny;
delitem 909,10;
set Zeny, Zeny - @CDzeny;
atcommand @CDsymbol$ + "changesex ";
mes @CDname$;
mes "Ok the surgery will begin, you will log off and please relog in again.";
end;

CD_zeny:
mes @CDname$;
mes "Mama mia you have not got a requirement.";
mes "Complete the requirements!";
mes "I'll be waiting!";
close;

CD_uhno:
mes @CDname$;
mes "Ok fine, please think again.";
mes "If you've prepared your heart .";
mes "I'll be waiting.";
close;

}

//lhz_in02.gat,286,85,4	duplicate(beyle)	Dokter Boyle#02	878
prontera,133,189,5	duplicate(beyle)	Andy Belo#03	617
```

**Comment by Lemongrass3110** [comment] 2016-04-24 10:18
I just tried it in RENEWAL mode with PACKETVER 20151104 and it worked just fine.

Could you tell us which git hash you actually use? Latest is not valid in this case.
Also at least please tell us your client version.

Thank you

**Comment by icxbb-xx** [comment] 2016-04-24 10:38
the client 2014 04 10 or high use changecharsex not changesex

**Comment by Lemongrass3110** [comment] 2016-04-24 18:46
@icxbb-xx changesex still works and changes the default sex of the account and all existing characters to the opposite gender. So his script is okay. It even worked when I tested it.

**Comment by spinzaku** [comment] 2016-04-24 20:46
I just changed to linux server and got the latest git. still same problem for me, character doesn't change gender. i can provide video or screenshot if you want

Client Version: 20151104
How to check git version? i edited some src. like removed renewal drop, blocked summoner class, etc.

**Comment by majimboo** [comment] 2016-04-25 21:55
see [`changesex()`](https://github.com/rathena/rathena/blob/62271358da41cfc3f6239d73af964ce79b5a909b/src/map/atcommand.c#L6828) which has a comment:
```
 * @changesex 
 * => Changes one's account sex. Switch from male to female or visversa
```

see [`changecharsex()`](https://github.com/rathena/rathena/blob/62271358da41cfc3f6239d73af964ce79b5a909b/src/map/atcommand.c#L6849) which has a comment:
```
 * @changecharsex
 * => Changes one's character sex. Switch from male to female or visversa.
```

The following codes should be self explanatory:

    changesex()
    chrif_changesex(sd, true);

    changecharsex()
    chrif_changesex(sd, false);

Now if you check the code that actually does the changing:

```
int chrif_changesex(struct map_session_data *sd, bool change_account) {
	(...omitted)
	WFIFOW(char_fd,30) = (change_account ? CHRIF_OP_LOGIN_CHANGESEX : CHRIF_OP_CHANGECHARSEX);
	if (!change_account)
		WFIFOB(char_fd,32) = sd->status.sex == SEX_MALE ? SEX_FEMALE : SEX_MALE;
    (...omitted)
}
```

**Comment by spinzaku** [comment] 2016-04-25 22:08
Thank you @majimboo 
i have fixed my issue, i just changed changesex to changecharsex to my NPC scripts
and it worked!

**Comment by Lemongrass3110** [comment] 2016-04-25 22:12
Closing this since everything was working as intended

**Closed by Lemongrass3110** 2016-04-25 22:12 UTC
Labels: bug:core, mode:missing, server:char, server:map, status:client date missing, status:git hash missing

**Comment by spinzaku** [comment] 2016-04-25 22:16
@Lemongrass3110 
Changesex doesn't change character gender only account.. 

i just tested now. so what you commented about is not correct. You can close if you want.
