### ISSUE TITLE
Emergencycall re cooldown skill every change map/warp

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#6182] opened 2021-08-12 06:41 UTC
* **rAthena Hash**: 9d48c5a
* **Client Date**: 2020-05-20b
* **Server Mode**: Pre-renewal
* **Description of Issue**: emergencycall re cooldown(guild_skill_relog_delay) skill every change map/warp(same map)

Example : 
 1. alde_gld -> aldeg_cas01 (change map)
 2. aldeg_cas01,122,62 -> aldeg_cas01,62,191 (change warp)

**Comment by aleos89** [comment] 2021-08-12 12:40
Duplicate of #5278.

**Closed by aleos89** 2021-08-12 12:40 UTC
Labels: status:duplicate
