### ISSUE TITLE
 Gentle Touch - Cure  can heal Emperium or Barricades

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#1290] opened 2016-05-21 02:21 UTC
i want to ask, as i know, Emperium its plant type and can't healed.
but in game, my player can heal emperium use Gentle touch Cure (Sura) / Silent Breeze (Homun S Eira)
it is bug need to fixed or not?

**Comment by secretdataz** [comment] 2016-05-21 04:16
Issue with Gentle Touch - Cure is fixed on 63e7729.
Probably want to check Eira skill.

**Comment by secretdataz** [comment] 2016-05-21 05:31
Can't reproduce on latest Git.

**Closed by secretdataz** 2016-05-21 05:31 UTC
Labels: bug:skill, mode:missing, server:map, status:git hash missing
