### ISSUE TITLE
bDefRatioAtkClass reduces damage instead of increasing it

### ISSUE THREAD

**Issue by M45T3Ryu** [rathena/rathena#2595] opened 2017-11-10 06:34 UTC
Server Mode: Pre-re

Description of Issue:
Memory of Thanatos Card is behaving weird reducing damage output instead of increasing it

Result: So my players found out that the card was behaving very weird, I tested on various mobs with high defense but the damage was still lowering I had different results over different weapons

Try testing a normal Main Gauche [4] then add Memory of Thanatos Card then it will do less damage

**Comment by Jeybla** [comment] 2017-11-10 10:39
Please be more explicit. Which monsters did you test? What is the actual difference? Which rathena version are you using?
Detailed informations helps us to understand and reproduce issues.

**Comment by uddevil** [comment] 2017-11-10 15:53
@M45T3Ryu :
What is your rAthena hash?
I don't really know, but it might be related to 6decf6c6d05d016e10eabddd025775e68f2ad1d7 
Before that, somehow skills does not check nk_ignore_flee / nk_ignore_def (tested using Dragon Breath missed against mob with high flee, and Tiger Cannon's damage is small vs mobs with high vit).

My suggestion is, try to update ur server at least until the commit i've mentioned above. :)

**Comment by Jeybla** [comment] 2017-11-10 18:24
Good catch @uddevil. Related issue: #2577

**Comment by M45T3Ryu** [comment] 2017-11-11 04:19
I don't have the Github app installed so I can't check the git hash(I downloaded it as zip)
The date I downloaded it was..  03/11/2017 so this was the exact Hash

**Comment by M45T3Ryu** [comment] 2017-11-11 04:21
Im going to check again, with a the newest revision.

**Comment by M45T3Ryu** [comment] 2017-11-11 04:32
I tested again its the same with the latest revision

Without Card
![screenrathena000](https://user-images.githubusercontent.com/2993425/32686222-1912ab32-c656-11e7-9a78-73bb04d826b8.jpg)

With Card
![screenrathena001](https://user-images.githubusercontent.com/2993425/32686223-19359656-c656-11e7-9ce8-253b1dd47614.jpg)

**Comment by M45T3Ryu** [comment] 2017-11-15 17:18
@Jeybla  is it enough?

**Comment by Jeybla** [comment] 2017-11-15 21:17
@M45T3Ryu yes, although I'm unable to reproduce it on 9766ec94890c36cb242eb0cf13761d9f413c16a7

Without thanatos card:
![image](https://user-images.githubusercontent.com/6203894/32860683-a8ad689a-ca52-11e7-99d8-5ee55d738b48.png)
With thanatos card:
![2017-11-15-22-15-52_tp](https://user-images.githubusercontent.com/6203894/32860692-b0b93050-ca52-11e7-8e92-f68e5d14822a.png)

**Comment by Paoly28** [comment] 2017-11-17 02:24
that because the damage scales with target Def and Vit. 1 vit meant he'd take only 1% of intended damage for example.

**Comment by M45T3Ryu** [comment] 2017-11-19 09:53
Try with an Ice Pick the damage increases by a lot

**Comment by Playtester** [comment] 2017-11-20 18:23
In pre-renewal, piercing damage means that damage is multiplied with [VIT_DEF+DEF]%, so if VIT_DEF+DEF is lower than 100, it will deal less damage.

In renewal the formula is completely different. In fact, it hardly has any effect on the damage anymore (but it also doesn't reduce it ever).

**Comment by Jeybla** [comment] 2017-11-20 18:45
Thanks for the clarification. Closing the issue, since it's working as intended.

**Closed by Jeybla** 2017-11-20 18:45 UTC
Labels: status:invalid
