### ISSUE TITLE
Crash when mob cast skill

### ISSUE THREAD

**Issue by mrpond** [rathena/rathena#8319] opened 2024-05-09 11:21 UTC
### rAthena Hash

13bc3e2bb765f64266ba56dc0cc06a1b99c09fc5

### Client Date

20131120

### Server Mode

Pre-Renewal

### Result

![image](https://github.com/rathena/rathena/assets/18654771/80fb10bf-3bd7-4911-81c4-6dafee4f80d5)

this is my temp fix
```
static int8 skill_castend_id_check(struct block_list *src, struct block_list *target, uint16 skill_id, uint16 skill_lv) {
	std::shared_ptr<s_skill_db> skill = skill_db.find(skill_id);

#ifdef 1
	if (nullptr == skill) // invalid skill id
		return USESKILL_FAIL_MAX;
#endif
	...
```

### Relevant Log Output

```Shell
See picture above
```

### Expected Result

It should not crash

### How to Reproduce

When mob cast character lock-on skill, map will crash
maybe unit.cpp line 2857 cause this.

### Official Information

N/A

### Modifications that may affect results

#define RENEWAL_CAST

**Comment by aleos89** [comment] 2024-05-09 17:48
Do you have something custom calling this? You have `skill_lv=3` and `skill_id=0` being passed to this function.

Somehow you are either clearing `ud->skill_id` or not properly accounting for something from `skill_castend_id`. We could add nullptr checks here but technically you shouldn't be failing to look up skills in these locations. If you are the crash is valid and it's a result of a problem somewhere else.

**Comment by mrpond** [comment] 2024-05-10 04:18
nothing, the bug happens after https://github.com/rathena/rathena/pull/8302.

 I think this is https://github.com/rathena/rathena/commit/ffe40def4ab753b428f4425cdd946a56c7ae947a#diff-7aa01f32243f325129ff31983fd8166d61e578b8e7855fa7c8684f5c346b5167R2857 the problem

**Comment by Lemongrass3110** [comment] 2024-05-10 07:35
You clearly have modifications in your file:

Line [13348 of skill.cpp](https://github.com/rathena/rathena/blob/13bc3e2bb765f64266ba56dc0cc06a1b99c09fc5/src/map/skill.cpp#L13348) is:
```cpp
						case TR_METALIC_FURY: // Don't know the official increase. For now lets do up to 50% increase.
```

Nevertheless I think you are right.

**Comment by Playtester** [comment] 2024-05-10 09:16
Any idea which monster skill is causing this?

skill_id gets cleared when a monster does a normal attack, it shouldn't happen while a skill is currently being processed, but above looks like it's some kind of skill that creates a timer and then expects the skill_id to still be set at the end of the timer.

**Comment by rotloso** [comment] 2024-05-10 10:53
@Playtester here skill.cpp
[skill.zip](https://github.com/rathena/rathena/files/15274069/skill.zip)

**Comment by Playtester** [comment] 2024-05-10 13:45
> @Playtester here skill.cpp [skill.zip](https://github.com/rathena/rathena/files/15274069/skill.zip)

That file also doesn't contain a skill_castend_id_check call in line 13348.

But I assume it's the section I quoted.

Would still need to know what skill causes this. Can you reproduce it with a certain skill?

**Comment by Playtester** [comment] 2024-05-10 14:28
The issue can be reproduced when a player has the "Freecast" ability, but not sure how it happens with monsters. Still should be fixed so that we don't set it to 0 when a skilltimer exists.

**Comment by Playtester** [comment] 2024-05-10 14:51
Can you check if the linked PR fixes the issue for you?

**Comment by mrpond** [comment] 2024-05-10 15:05
> Can you check if the linked PR fixes the issue for you?

yes, we'll test it on production server (1800 Players) for you.

**Comment by mrpond** [comment] 2024-05-10 15:28
@Playtester if you had time, https://github.com/rathena/rathena/issues/8310
kindly look into this and make PR. I add some fix about bot/custom client can bypass pin code system.

**Closed** 2024-05-10 16:19 UTC
Labels: component:core, mode:renewal, mode:prerenewal, type:bug
