### ISSUE TITLE
Npc cashheadgear_dye.txt is not working

### ISSUE THREAD

**Issue by tiagofm94** [rathena/rathena#7147] opened 2022-07-31 15:25 UTC
* **rAthena Hash**:  Latest

* **Client Date**:  2021-11-17_Ragexe

* **Server Mode**:  Renewal
* **Description of Issue**:  I tested the npc with Rathena limp and it's not working.
  * Result: Not dyeing the hats
  * Expected Result:  Should dye the hats using the dye
  * How to Reproduce: Use current Rathena and try to dye any hat
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment] 2022-08-02 18:46
Tested using a clean build from [498c4fe](https://github.com/rathena/rathena/commit/498c4fe2b347b93eac88bff0adf1608703cd9118), worked for me. What variation of hat/color are you using? Please provide more information as to what combo is failing.

**Comment by Akkarinage** [comment] 2022-09-04 20:36
No additional user input after 4 weeks of waiting. As the script runs as intended out-of-the-box, I'm closing this Issue.

This Issue can be re-opened at a later date when the user provides more information.

**Closed by Akkarinage** 2022-09-04 20:36 UTC
Labels: status:need user input, status:unable to reproduce
