### ISSUE TITLE
item combo not working ingame

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#2386] opened 2017-08-30 09:08 UTC
* **rAthena Hash**: 

 item_combo_db.txt

* **Client Date**: 

 2015/04/05

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  item combo for item id 13034 and 13035 not working in game but the item script combo is available at item_combo_db.txt
  * Expected Result:  this item should give the combo as the item said in descriptions
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by vstumpf** [comment] 2017-08-30 20:06
I can't reproduce this in either pre-renewal or renewal on `3e51f6`.

**Comment by Jeybla** [comment] 2017-08-31 14:30
Works fine for me, too. Tested on c9ce29c00e4c440e15fcecadf314b85ad65e8c2b

**Comment by Questune09** [comment] 2017-09-01 08:32
im on renewal base

**Comment by Jeybla** [comment] 2017-09-01 10:39
Please try tro reproduce the issue on a clean rathena and tell us exactly the steps on how to reproduce it.

**Comment by Jeybla** [comment] 2017-10-06 06:46
No further input. Closing the issue.

**Closed by Jeybla** 2017-10-06 06:46 UTC
Labels: component:database, missing:revision, mode:prerenewal, mode:renewal, priority:low, status:need user input, status:unable to reproduce
